### ISSUE TITLE
Error when using S3 client to call localstack

### ISSUE THREAD

**Issue by wolfgangmeyers** [aws/aws-sdk-net#1014]
## Expected Behavior

No exception should be thrown when calling PutBucketAsync

## Current Behavior

When calling AmazonS3Client.PutBucketAsync, an error is thrown.

This is the error that is printed out when unit tests are run with `dotnet test`:

```
Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:00.9935780]     TestS3Client.UnitTest1.Test1 [FAIL]
Failed   TestS3Client.UnitTest1.Test1
Error Message:
 System.AggregateException : One or more errors occurred. (Device not configured)
---- System.Net.Http.HttpRequestException : Device not configured
-------- System.Net.Sockets.SocketException : Device not configured
Stack Trace:
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at TestS3Client.UnitTest1.Test1() in /Users/wolfgangmeyers/code/rns_dotnet_core/TestS3Client/UnitTest1.cs:line 18
----- Inner Stack Trace -----
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_mobile\HttpRequestMessageFactory.cs:line 428
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:line 175
   at Amazon.Runtime.Internal.RedirectHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CredentialsRetriever.cs:line 98
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\RetryHandler\RetryHandler.cs:line 137
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
----- Inner Stack Trace -----
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
```

## Steps to Reproduce (for bugs)

UnitTest1.cs:

```
using System;
using Xunit;
using Amazon;
using Amazon.S3;

namespace TestS3Client
{
    public class UnitTest1
    {
        [Fact]
        public void Test1()
        {
            var client = new AmazonS3Client("foobar", "foobar", new AmazonS3Config{
                RegionEndpoint=RegionEndpoint.USEast1,
                ServiceURL = "http://localhost:4572",
                UseHttp = true,
            });
            client.PutBucketAsync("testbucket").Wait();
            var t = client.ListBucketsAsync();
            t.Wait();
            Assert.Equal("testbucket", t.Result.Buckets[0].BucketName);
        }
    }
}

```

## Your Environment

* AWSSDK.Core version used: 
Not sure, but I am using AWSSDK.S3 version 3.3.20. I tried several previous versions, which didn't change the outcome.
* Service assembly and version used: 
* Operating System and version: 
Mac OSX 10.13.6
* Visual Studio version: 
Visual Studio Code 1.25.1 (but I am launching from command line)
* Targeted .NET platform: 
netcoreapp2.1

## .NET Core Info

* .NET Core version used for development: 
2.1.302
* .NET Core version installed in the environment where application runs: 
Still in development
* Output of `dotnet --info`: 

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.302/

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.104 [/usr/local/share/dotnet/sdk]
  2.1.302 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

* Contents of project.json/project.csproj: 
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="3.3.20" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.7.0" />
    <PackageReference Include="xunit" Version="2.3.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.1" />
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.1" />
  </ItemGroup>

</Project>
```

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by gokarnm** [comment]
Hi @wolfgangmeyers, a search for _System.Net.Sockets.SocketException : Device not configured_ pointed me to this [CoreFx issue](https://github.com/dotnet/corefx/issues/13309) as per which there may an issue with resolving localhost on MacOS. Could you try the following, I'd like to verify if you are hitting the same issue

- Use `ServiceURL = "http://127.0.0.1:4572"`, does that work?
- Check if you can repro the error with this [code](https://github.com/dotnet/corefx/issues/13309#issuecomment-279568600)

**Comment by wolfgangmeyers** [comment]
This only seems to happen when hitting localstack. It happens in unit tests and if I implement as a console application. However, if I call AWS directly, the error doesn't occur and the S3 bucket is created as expected.
```
using System;
using Amazon;
using Amazon.S3;

namespace TestS3Client2
{
    class Program
    {
        static void Main(string[] args)
        {
            var client = new AmazonS3Client(new AmazonS3Config{
                RegionEndpoint=RegionEndpoint.USEast1,
            });
            client.PutBucketAsync("co.donuts.testbucket").Wait();
            var t = client.ListBucketsAsync();
            t.Wait();
        }
    }
}
```

**Comment by wolfgangmeyers** [comment]
@gokarnm I tried again with the host being 127.0.0.1, and I see the same problem still.

**Comment by wolfgangmeyers** [comment]
@gokarnm I tried running the code you linked to, and see my hostname output:
```
$ dotnet run
KRKLTM103.local
10.0.0.223
```

**Comment by wolfgangmeyers** [comment]
Some more info that may be relevant:

I can hit S3 service in localstack directly using curl:
```
$ curl http://localhost:4572
<ListAllMyBucketsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01"><Owner><ID>bcaf1ffd86f41161ca5fb16fd081034f</ID><DisplayName>webfile</DisplayName></Owner><Buckets></Buckets></ListAllMyBucketsResult>
```

I also have no problem using the DynamoDB client with localstack. Everything works as expected.
Trying any hostname or ip address with this code seems to yield the same error "Device not configured":
```
using System;
using Amazon;
using Amazon.S3;
using System.Net;

namespace TestS3Client2
{
    class Program
    {
        static void Main(string[] args)
        {
            var client = new AmazonS3Client("foobar", "foobar", new AmazonS3Config{
                RegionEndpoint=RegionEndpoint.USEast1,
                ServiceURL = "http://1.2.3.4:4572",
                UseHttp = true,
            });
            client.PutBucketAsync("testbucket").Wait();
            var t = client.ListBucketsAsync();
            t.Wait();
        }
    }
}
```

**Comment by wolfgangmeyers** [comment]
@gokarnm this is also happening when I run the .net core process inside of docker, although the error message is slightly different. I will provide a repository to reproduce it, since the setup is more complicated.

**Comment by wolfgangmeyers** [comment]
@gokarnm please see https://github.com/wolfgangmeyers/aws-sdk-net-1014 for detailed instructions on how to reproduce the issue

**Comment by wolfgangmeyers** [comment]
Ok... so I managed to figure this out by running the project through visual studio, with the full source code of the sdk to debug through. It turns out I forgot an important parameter in the S3 config that isn't required for DynamoDB to work:
`ForcePathStyle = true,`
Without this, the S3 client tries to use a hostname that is specific to the bucket, and it doesn't resolve. After I added this to the config, the problem was resolved. Hopefully this helps anyone else who searches for the same error.

**Comment by chorinator** [comment]
> Ok... so I managed to figure this out by running the project through visual studio, with the full source code of the sdk to debug through. It turns out I forgot an important parameter in the S3 config that isn't required for DynamoDB to work: `ForcePathStyle = true,` Without this, the S3 client tries to use a hostname that is specific to the bucket, and it doesn't resolve. After I added this to the config, the problem was resolved. Hopefully this helps anyone else who searches for the same error.

6 years after I'm facing the same problem.
Thank you for your answer
