### ISSUE TITLE
Aws tool kit installation issue on VS 2017

### ISSUE THREAD

**Issue by SubhaKVinod** [aws/aws-sdk-net#1034]
I am using  Visual studio 2017 professional and trying to install the  tool kit from https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.AWSToolkitforVisualStudio2017#qna

But i have  the error message saying that "This extension is not installable on any currently installed products."

Below is the error log text.

8/14/2018 4:30:26 PM - Microsoft VSIX Installer
8/14/2018 4:30:26 PM - -------------------------------------------
8/14/2018 4:30:26 PM - vsixinstaller.exe version:
8/14/2018 4:30:26 PM - 15.0.26403.7 built by: D15SVC
8/14/2018 4:30:26 PM - -------------------------------------------
8/14/2018 4:30:26 PM - Command line parameters:
8/14/2018 4:30:26 PM - C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VSIXInstaller.exe,C:\Users\m1013467\Downloads\AWSToolkitPackage (2).vsix
8/14/2018 4:30:26 PM - -------------------------------------------
8/14/2018 4:30:26 PM - Microsoft VSIX Installer
8/14/2018 4:30:26 PM - -------------------------------------------
8/14/2018 4:30:26 PM - Failed to initialize settings for Isolated Shell C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\ssms.exe: Unable to find an entry point named '?' in DLL 'PkgdefMgmt.dll'.
8/14/2018 4:30:26 PM - Failed to create LocationBasedSKU: System.Runtime.InteropServices.COMException (0x80070490): Element not found. (Exception from HRESULT: 0x80070490)
   at Microsoft.VisualStudio.Setup.Configuration.ISetupInstance2.GetPackages()
   at VSIXInstaller.LocationBasedSKU.GetEdition(ISetupInstance2 instance)
   at VSIXInstaller.LocationBasedSKU..ctor(ISetupInstance2 instance)
   at VSIXInstaller.SupportedSKUs.<>c.<AddInstalledLocationBasedSKUs>b__12_0(ISetupInstance2 instance)
   at VSIXInstaller.SupportedSKUs.EnumerateIsolatedInstalls(Action`1 callback)
8/14/2018 4:30:26 PM - Initializing Install...
8/14/2018 4:30:26 PM - Extension Details...
8/14/2018 4:30:26 PM - 	Identifier         : 12ed248b-6d4a-47eb-be9e-8eabea0ff119
8/14/2018 4:30:26 PM - 	Name               : AWS Toolkit for Visual Studio 2017
8/14/2018 4:30:26 PM - 	Author             : Amazon Web Services LLC
8/14/2018 4:30:26 PM - 	Version            : 1.14.4.0
8/14/2018 4:30:26 PM - 	Description        : The AWS Toolkit for Visual Studio 2017 is an extension for Microsoft Visual Studio 2017 on Microsoft Windows that makes it easier for developers to develop, debug, and deploy .NET and .NET Core applications using Amazon Web Services. With the AWS Toolkit you'll be able to get started faster and be more productive when building AWS applications.
8/14/2018 4:30:26 PM - 	Locale             : en-US
8/14/2018 4:30:26 PM - 	MoreInfoURL        : https://aws.amazon.com/sdkfornet
8/14/2018 4:30:26 PM - 	InstalledByMSI     : False
8/14/2018 4:30:26 PM - 	SupportedFrameworkVersionRange : [4.6,)
8/14/2018 4:30:26 PM - 
8/14/2018 4:30:29 PM - 	SignatureState     : ValidSignature
8/14/2018 4:30:29 PM - 	SignedBy           : Amazon.com, Inc.
8/14/2018 4:30:29 PM - 	Certificate Info   : 
8/14/2018 4:30:29 PM - 		-------------------------------------------------------
8/14/2018 4:30:29 PM - 		[Subject]       : CN="Amazon.com, Inc.", O="Amazon.com, Inc.", L=Seattle, S=Washington, C=US
8/14/2018 4:30:29 PM - 		[Issuer]        : CN=Symantec Class 3 SHA256 Code Signing CA - G2, OU=Symantec Trust Network, O=Symantec Corporation, C=US
8/14/2018 4:30:29 PM - 		[Serial Number] : 2B778385004F4CA691C07F3590C07B7F
8/14/2018 4:30:29 PM - 		[Not Before]    : 7/10/2017 5:30:00 AM
8/14/2018 4:30:29 PM - 		[Not After]     : 7/11/2020 5:29:59 AM
8/14/2018 4:30:29 PM - 		[Thumbprint]    : D2038C3D2E59604D9AD05674B21B53EA40ACE63F
8/14/2018 4:30:29 PM - 
8/14/2018 4:30:29 PM - 	Supported Products : 
8/14/2018 4:30:29 PM - 		Microsoft.VisualStudio.Community
8/14/2018 4:30:29 PM - 			Version : [15.0,)
8/14/2018 4:30:29 PM - 
8/14/2018 4:30:29 PM - 	References         : 
8/14/2018 4:30:29 PM - 		-------------------------------------------------------
8/14/2018 4:30:29 PM - 		Identifier   : Microsoft.VisualStudio.MPF.15.0
8/14/2018 4:30:29 PM - 		Name         : Visual Studio MPF 15.0
8/14/2018 4:30:29 PM - 		Version      : [15.0,16.0)
8/14/2018 4:30:29 PM - 		MoreInfoURL  : 
8/14/2018 4:30:29 PM - 		Nested       : No
8/14/2018 4:30:29 PM - 
8/14/2018 4:30:29 PM - 	Prerequisites      : 
8/14/2018 4:30:29 PM - 		-------------------------------------------------------
8/14/2018 4:30:29 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
8/14/2018 4:30:29 PM - 		Name         : Visual Studio core editor
8/14/2018 4:30:29 PM - 		Version      : [15.0,)
8/14/2018 4:30:29 PM - 
8/14/2018 4:30:29 PM - Signature Details...
8/14/2018 4:30:29 PM - 	Extension is signed with a valid signature.
8/14/2018 4:30:29 PM - 
8/14/2018 4:30:29 PM - Searching for applicable products...
8/14/2018 4:30:29 PM - Found installed product - Microsoft Visual Studio Premium 2013 
8/14/2018 4:30:29 PM - Found installed product - Microsoft Visual Studio Professional 2013
8/14/2018 4:30:29 PM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
8/14/2018 4:30:29 PM - Found installed product - Microsoft Visual Studio Enterprise 2015
8/14/2018 4:30:29 PM - Found installed product - Microsoft Visual Studio Professional 2015
8/14/2018 4:30:29 PM - Found installed product - Microsoft Visual Studio Community 2015
8/14/2018 4:30:29 PM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
8/14/2018 4:30:29 PM - Found installed product - Global Location
8/14/2018 4:30:29 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by steveataws** [comment]
Based on this version data `15.0.26403.7 built by: D15SVC` on entry to the log it appears that the correct version of vsixinstaller.exe is being run (it's part of your VS install, not something we distribute) but the tail of the log doesn't show it picking up your installed version of 2017 which is what's triggering the error - the vsix file we distribute to the gallery only supports VS2017. 

How did you start the install? Did you download the vsix file and then launch it locally? In previous cases like this we've found that that approach can either start the wrong version of vsixinstaller.exe or based on the environment setup, it completely fails to identify an installed edition of VS2017. 

What I'd recommend is that you instead start the install from within Visual Studio. Open `Extensions and Updates` from the `Tools` menu and in the online category, search for AWS. That will locate the marketplace entry which you can then select to install (which will happen when you restart the IDE).

Let us know if this does, or does not, fix the issue? Thanks.
