### ISSUE TITLE
Amazon.Runtime.AmazonUnmarshallingException occured with .NET Amazon Simple Storage Service (Amazon S3) v3.3.18.2

### ISSUE THREAD

**Issue by KalpeshRajai** [aws/aws-sdk-net#1047]
Amazon.Runtime.AmazonUnmarshallingException occured with .NET Amazon Simple Storage Service (Amazon S3) v3.3.18.2

I am trying check the existence of the directory on the AWS S3 with the AWS .NET SDK.
I am using the **S3DirectoryInfo** class and it's **Exists** property.

Occasionally it throws the error:
Amazon.Runtime.AmazonUnmarshallingException: Error unmarshalling response back from AWS. Response Body: **confidential**, HTTP Status Code: 200 OK ---> System.IO.IOException: Unable to read data from the transport connection: The connection was closed.
   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at Amazon.Runtime.Internal.Util.CachingWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer(Char[] userBuffer, Int32 userOffset, Int32 desiredChars, Boolean& readToUserBuffer)
   at System.IO.StreamReader.Read(Char[] buffer, Int32 index, Int32 count)
   at System.Xml.XmlTextReaderImpl.ReadData()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at Amazon.Runtime.Internal.Transform.XmlUnmarshallerContext.Read()
   at Amazon.S3.Model.Internal.MarshallTransformations.S3UnmarshallerContext.Read()
   at Amazon.S3.Model.Internal.MarshallTransformations.ListObjectsResponseUnmarshaller.UnmarshallResult(XmlUnmarshallerContext context, ListObjectsResponse response)
   at Amazon.S3.Model.Internal.MarshallTransformations.ListObjectsResponseUnmarshaller.Unmarshall(XmlUnmarshallerContext context)
   at Amazon.Runtime.Internal.Transform.XmlResponseUnmarshaller.Unmarshall(UnmarshallerContext input)
   at Amazon.S3.Model.Internal.MarshallTransformations.S3ReponseUnmarshaller.Unmarshall(UnmarshallerContext input)
   at Amazon.Runtime.Internal.Transform.ResponseUnmarshaller.UnmarshallResponse(UnmarshallerContext context)
   at Amazon.Runtime.Internal.Unmarshaller.UnmarshallResponse(UnmarshallerContext context, IRequestContext requestContext)
   at Amazon.Runtime.Internal.Unmarshaller.Unmarshall(IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.Unmarshaller.Unmarshall(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.AmazonServiceClient.Invoke[TRequest,TResponse](TRequest request, IMarshaller`2 marshaller, ResponseUnmarshaller unmarshaller)
   at Amazon.S3.AmazonS3Client.ListObjects(ListObjectsRequest request)
   at Amazon.S3.IO.S3DirectoryInfo.ExistsWithBucketCheck(Boolean& bucketExists)

## Your Environment

* AWSSDK.Core version used: 3.3.22.1
* Service assembly and version used: 
* Operating System and version: Windows 2008
* Visual Studio version: Microsoft Visual Studio Professional 2017
* Targeted .NET platform: 4.6.2

**Comment by sstevenkang** [comment]
This looks like the connection was abruptly closed and not due to an issue in unmashallling logic: `System.IO.IOException: Unable to read data from the transport connection: The connection was closed.`

**Comment by KalpeshRajai** [comment]
@sstevenkang

**Comment by KalpeshRajai** [comment]
@sstevenkang Thank you for the help.
Sorry to disturb you but I does not understand in which part the problem is exist ?
Is this problem in the AWS or in the .NET SDK or in the our tool (Code) ?

Is there any way to solve this problem ?
	Like: Do I need to retry the same logic to get the expected output or something else ?
