### ISSUE TITLE
How to add device to cognito user?

### ISSUE THREAD

**Issue by dmitriy-proskurin** [aws/aws-sdk-net#1055]
I want to add device to my cognito user. If i set CognitoDevice to cognito user and call RememberThisDeviceAsync on CognitoDevice, i got exception:

> Amazon.CognitoIdentityProvider.Model.ResourceNotFoundException: Device does not exist. ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type \'Amazon.Runtime.Internal.HttpErrorResponseException\' was thrown.

## Expected Behavior
Device must be added to user's devices?

## Current Behavior
Exception with following stack trace:

>  at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
>    at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
>    at Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---

## Steps to Reproduce (for bugs)
Try this code
```C#
var currentUser = m_cognitoUserPool.GetUser("user_email");
var authRequest = new InitiateSrpAuthRequest {
    Password = password
};

var authResponse = await CurrentUser.StartWithSrpAuthAsync(authRequest);

CurrentUser.Device = new CognitoDevice("win_234124", new Dictionary<string, string>(), DateTime.Now, DateTime.Now, DateTime.Now, CurrentUser);
await CurrentUser.Device.RememberThisDeviceAsync();
```

## Your Environment

* AWSSDK.Core: 3.3.24.4
* AWSSDK.Extensions.CognitoAuthentication: 0.9.4
* Operating System and version: Windows 10 17134.165
* Visual Studio version: Community 2017 15.7.6
* Targeted .NET platform: Microsoft.NETCore.UniversalWindowsPlatform 5.4.0

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by niraj-bpsoftware** [comment]
I have same question. How do we use Cognito Extension to enable device tracking feature?

**Comment by dmitriy-proskurin** [comment]
@niraj-bpsoftware 
I've work on that feature in our project, but now it planned for next days. As i can see, when user Authentificate throught StartWithSrpAuthAsync, afterf success authentification(with empty device key), in auth response you receive NewDeviceMetadata(not empty). And as i can see, you can use DeviceKey and DeviceGroupKey for call ConfirmDeviceAsync(AmazonCognitoIdentityProviderClien). After that Cognito  remember this device. Also, this method required DeviceSecretVerifierConfigType with Salt and  PasswordVerifier. How to generate it, you can see in another sdk sources.
