### ISSUE TITLE
The type initializer for 'Amazon.AWSConfigs' threw an exception

### ISSUE THREAD

**Issue by swath24** [aws/aws-sdk-net#1079]
Hi all,

I am trying to connect to amazon dynamodb through .net. and ended up in this error.

<Error>
<Message>An error has occurred.</Message>
<ExceptionMessage>
The type initializer for 'Amazon.AWSConfigs' threw an exception.
</ExceptionMessage>

I am attaching  my code and config file.

Any help would be greatly appreciated.

> <configSections>
    
    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
    <section name="aws" type="Amazon.AWSSection , AWSSDK.Core" />
  
 > </configSections>
  <aws profileName="default" profilesLocation="C:/Users/SwathiG/.aws/credentials" region="us-west-2">
    ><dynamoDB
    conversionSchema="V1 | V2">
      <dynamoDBContext
        tableNamePrefix="string value">
        <tableAliases>
          <alias
            fromTable="string value"
            toTable="string value" />
        </tableAliases>
        <map
          type="NameSpace.Class, Assembly"
          targetTable="string value">
          <property
            name="string value"
            attribute="string value"
            ignore="true | false"
            version="true | false"
            converter="NameSpace.Class, Assembly" />
        </map>
      </dynamoDBContext>
    </dynamoDB>
  </aws>

`

 AWSCredentials credentials = new StoredProfileAWSCredentials("default");
            using (AmazonDynamoDBClient client = new AmazonDynamoDBClient(credentials, RegionEndpoint.APSoutheast1))
            {
                string tableName = "ProductCatalog";

                var request = new CreateTableRequest
                {
                    TableName = tableName,
                    AttributeDefinitions = new List<AttributeDefinition>()
                  {
                    new AttributeDefinition
                    {
                      AttributeName = "Id",
                      AttributeType = "N"
                    }
                  },
                    KeySchema = new List<KeySchemaElement>()
                  {
                    new KeySchemaElement
                    {
                      AttributeName = "Id",
                      KeyType = "HASH"  //Partition key
                    }
                  },
                    ProvisionedThroughput = new ProvisionedThroughput
                    {
                        ReadCapacityUnits = 10,
                        WriteCapacityUnits = 5
                    }
                };

                var response = client.CreateTable(request);
            }
`

**Comment by klaytaybai** [comment]
Hi @swath24, thank you for letting us know you have a problem.  Are you able to provide an InnerException for this or any other details?

**Comment by jayd16** [comment]
I'm seeing a similar issue with the static constructor for Awsconfigs.

`NullReferenceException: Object reference not set to an instance of an object
Amazon.CSMSection.get_CSMEnabled ()
Amazon.Util.CSMConfig.Configure (Amazon.CSMSection section)
Amazon.Util.Internal.RootConfig..ctor ()
Amazon.AWSConfigs..cctor ()`

**Comment by bvgwi** [comment]
I'm getting a similar error, but related to Amazon Pinpoint.  Using .NET Core 2.1, Framework 4.7.1, on a Windows 2016 server.   Does anyone know of a solution to fix this for Windows Server? 

`Details
--------------------------------------------------
Error Message: Exception has been thrown by the target of an invocation.
Source: mscorlib
Stack Trace:   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Amazon.Extensions.NETCore.Setup.ClientFactory.CreateConfig(Type serviceInterfaceType, AWSOptions options)
   at Amazon.Extensions.NETCore.Setup.ClientFactory.CreateServiceClient(ILogger logger, Type serviceInterfaceType, AWSOptions options)
   at Amazon.Extensions.NETCore.Setup.AWSOptions.CreateServiceClient[T]()
   at [XXXXXXXX].VerifyPhoneNumber(String phoneNumber)
--- Inner Exception ---
Error Message: The type initializer for 'Amazon.AWSConfigs' threw an exception.
Source: AWSSDK.Core
Stack Trace:   at Amazon.AWSConfigs.get_LoggingConfig()
   at Amazon.Runtime.ClientConfig..ctor()
   at Amazon.Pinpoint.AmazonPinpointConfig..ctor()
--- Inner Exception ---
Error Message: Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
Source: mscorlib
Stack Trace:   at System.Security.Policy.PEFileEvidenceFactory.GetLocationEvidence(SafePEFileHandle peFile, SecurityZone& zone, StringHandleOnStack retUrl)
   at System.Security.Policy.PEFileEvidenceFactory.GenerateLocationEvidence()
   at System.Security.Policy.PEFileEvidenceFactory.GenerateEvidence(Type evidenceType)
   at System.Security.Policy.AssemblyEvidenceFactory.GenerateEvidence(Type evidenceType)
   at System.Security.Policy.Evidence.GenerateHostEvidence(Type type, Boolean hostCanGenerate)
   at System.Security.Policy.Evidence.GetHostEvidenceNoLock(Type type)
   at System.Security.Policy.Evidence.GetHostEvidence(Type type, Boolean markDelayEvaluatedEvidenceUsed)
   at System.Security.Policy.AppDomainEvidenceFactory.GenerateEvidence(Type evidenceType)
   at System.Security.Policy.Evidence.GenerateHostEvidence(Type type, Boolean hostCanGenerate)
   at System.Security.Policy.Evidence.GetHostEvidenceNoLock(Type type)
   at System.Security.Policy.Evidence.RawEvidenceEnumerator.MoveNext()
   at System.Security.Policy.Evidence.EvidenceEnumerator.MoveNext()
   at System.Configuration.ClientConfigPaths.GetEvidenceInfo(AppDomain appDomain, String exePath, String& typeName)
   at System.Configuration.ClientConfigPaths.GetTypeAndHashSuffix(AppDomain appDomain, String exePath)
   at System.Configuration.ClientConfigPaths..ctor(String exePath, Boolean includeUserConfig)
   at System.Configuration.ClientConfigPaths.GetPaths(String exePath, Boolean includeUserConfig)
   at System.Configuration.ClientConfigurationHost.RequireCompleteInit(IInternalConfigRecord record)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at Amazon.AWSConfigs.GetSection[T](String sectionName)
   at Amazon.Util.Internal.RootConfig..ctor()
   at Amazon.AWSConfigs..cctor()
`

**Comment by aqiao** [comment]
Hi @klaytaybai ,noted this issue closed, may i know if it's fixed, if so, could you share the details
