### ISSUE TITLE
Amazon.Runtime.AmazonUnmarshallingException

### ISSUE THREAD

**Issue by devlin3004** [aws/aws-sdk-net#1110]
Getting an error while polling message from SQS

## Current Behavior
Getting error,

Exception Info: System.Xml.XmlException
   at System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at Amazon.Runtime.Internal.Transform.XmlUnmarshallerContext.Read()
   at Amazon.Runtime.Internal.Transform.ErrorResponseUnmarshaller.Unmarshall(Amazon.Runtime.Internal.Transform.XmlUnmarshallerContext)
   at Amazon.SQS.Model.Internal.MarshallTransformations.GetQueueAttributesResponseUnmarshaller.UnmarshallException(Amazon.Runtime.Internal.Transform.XmlUnmarshallerContext, System.Exception, System.Net.HttpStatusCode)
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(Amazon.Runtime.IExecutionContext, Amazon.Runtime.Internal.HttpErrorResponseException)

## Your Environment
AWSSDK.Core version: 3.3.14.0
AWSSDK.SQS version: 3.3.0.0

## .NET Core Info
SDK Language and Version: .NET SDK 3

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
Hi @devlin3004, This sounds bad.  Are you able to reproduce? Do you know what data it is trying to read?  If not, let's try capturing your network traffic.  If running on Windows, could you please use Fiddler to try to get the response data that is failing.  If you aren't, please try Wireshark.

**Comment by klaytaybai** [comment]
Also, if you reply with your network traffic or response data, please make sure all sensitive information is removed.  Thanks

**Comment by klaytaybai** [comment]
Closing due to inactivity
