### ISSUE TITLE
DynamoDBContext.LoadAsyn: System.InvalidOperationException: Cannot instantiate type System.String[]

### ISSUE THREAD

**Issue by salomari** [aws/aws-sdk-net#1121]
I am trying to retrieve from DynamoDB table, this was working fine last week.
 when I call LoadAsync I receive System.InvalidOperationException: Cannot instantiate type System.String[].  Please see the sample code and the exception below.

## Code Sample:
    public class DataContext<T> : DynamoDBContext
    {
        private DynamoDBOperationConfig _config;
        private IAmazonDynamoDB _client;

        public DynamoDbContext(IAmazonDynamoDB client, string tableName): base(client)
        {
            _config = new DynamoDBOperationConfig()
            {
                OverrideTableName = tableName,
            };
            _client = client;
        }

        public async Task<T> GetByIdAsync(string id)
        {
            return await base.LoadAsync<T>(id, _config);
        }
    }

Table Structure:

    public class Item
    {
        [DynamoDBHashKey]
        public string Id { get; set; }

        [DynamoDBProperty]
        public string[] Tags { get; set; }

        [DynamoDBProperty]
        public string[] SearchKeys { get; set; }
    }

Sample Item:

    {
      "Id": {
        "S": "880bd759-99b3-4bf3-af05-029ef1c3999e"
      },
      "SearchKeys": {
        "SS": [
          "key1",
          "key2"
        ]
      },
      "Tags": {
        "SS": [
          "tag1",
          "tag2"
        ]
      }
    }

## Current Behavior
{System.InvalidOperationException: Cannot instantiate type System.String[]
   at Amazon.DynamoDBv2.DataModel.Utils.InstantiateHelper(Type objectType, ITypeInfo[][] validConstructorInputs, Object[] optionalInput) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DataModel\Utils.cs:line 260
   at Amazon.DynamoDBv2.DataModel.Utils.ItemsToCollection(Type targetType, IEnumerable`1 items, Object& result) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DataModel\Utils.cs:line 129
   at Amazon.DynamoDBv2.Converter.TryFromEntry(DynamoDBEntry entry, Type targetType, Object& value) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\Conversion\DynamoDBEntryConversion.cs:line 532
   at Amazon.DynamoDBv2.Converter.FromEntry(DynamoDBEntry entry, Type targetType) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\Conversion\DynamoDBEntryConversion.cs:line 508
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.FromDynamoDBEntry(SimplePropertyStorage propertyStorage, DynamoDBEntry entry, DynamoDBFlatConfig flatConfig) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DataModel\ContextInternal.cs:line 335
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.PopulateInstance(ItemStorage storage, Object instance, DynamoDBFlatConfig flatConfig) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DataModel\ContextInternal.cs:line 248
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.DocumentToObject(Type objectType, ItemStorage storage, DynamoDBFlatConfig flatConfig) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DataModel\ContextInternal.cs:line 229
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.DocumentToObject[T](ItemStorage storage, DynamoDBFlatConfig flatConfig) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DataModel\ContextInternal.cs:line 218
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.LoadHelperAsync[T](Key key, DynamoDBFlatConfig flatConfig, ItemStorageConfig storageConfig, CancellationToken cancellationToken)

## .NET Core Info
Output of `dotnet --version`: 
2.1.403

Output of `dotnet --info`: 
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.403\

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  1.0.0-preview2-003131 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by salomari** [comment]
BTW, I changed string[] to List<string> and it worked.  Not sure what changed but I have used string[] before and it was working until a recent update.

**Comment by klaytaybai** [comment]
What version of the AWS SDK are you currently using and what were you using before?

**Comment by klaytaybai** [comment]
Are you still hoping to get support on this?

**Comment by salomari** [comment]
It will be nice if I don't have to change every string[] to List<string>.

It's a breaking change and I believe it will be useful to fix it.

**Comment by klaytaybai** [comment]
@salomari and @napalmdaz I haven't been able to identify when string[] might have been accepted, so I will be closing out this issue after a few days.  Other team members were confused about this too because the relevant code hasn't had changes for a while.  If you can identify the version of the SDK that you think was working, please let us know.  

You should be able to use lists and sets.

**Comment by klaytaybai** [comment]
I'm closing this for now.  Please reopen or comment if you can find an example version where string[] was working.
