### ISSUE TITLE
Cannot install AWS Tools for VS 2017 without internet

### ISSUE THREAD

**Issue by dburtsev** [aws/aws-sdk-net#1126]
## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by dburtsev** [comment]
ES2 Windows Server 2016 instance. Microsoft SQL Server Data Tools for Visual Studio 2017. Private network 10.x.x.x. No internet connection. I am trying to install AWSToolkitPackage.vsix
Log:
11/15/2018 2:26:01 PM - Certificate is invalid: AWSToolkitPackage.vsix
11/15/2018 2:26:02 PM - Skipping Install of '12ed248b-6d4a-47eb-be9e-8eabea0ff119,version=1.14.4.1' since downloading it failed.
11/15/2018 2:26:02 PM - Skipping cache of package '12ed248b-6d4a-47eb-be9e-8eabea0ff119,version=1.14.4.1' since the package or a parent package had a vital failure.
11/15/2018 2:26:02 PM - Skipping cache of package 'Component.12ed248b-6d4a-47eb-be9e-8eabea0ff119,version=1.14.4.1' since the package or a parent package had a vital failure.
11/15/2018 2:26:11 PM - Install Error : Microsoft.VisualStudio.Setup.PackageFailureException: Package '12ed248b-6d4a-47eb-be9e-8eabea0ff119' failed to download
   at Microsoft.VisualStudio.Setup.InstallOperation.Run(CancellationToken token)
   at Microsoft.VisualStudio.Setup.Engine.RunOperation(InstallOperation installOperation, CancellationToken token, ExecuteAction action, ITelemetryOperation telemetryOperation)
   at Microsoft.VisualStudio.Setup.Engine.RunCoreOperation(InstallOperation coreOperation, ExecuteAction action, ITelemetryOperation telemetryOperation, CancellationToken token)
   at Microsoft.VisualStudio.Setup.Engine.Install(Product product, String destination, CancellationToken token)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

**Comment by dburtsev** [comment]
Closed. It was a proxy issue.
