### ISSUE TITLE
AmazonSimpleEmailServiceClient throws HttpRequestException 'no route to host' on .NET Core

### ISSUE THREAD

**Issue by ghost** [aws/aws-sdk-net#1142]
My setup:

- ASP.NET Core
- Linux Mint
- Visual Studio Code
- Credentials in ~/.aws/credentials
- Domains verified in RegionEndpoint.EUWest1 (Ireland)
- Profile in eu-central-1 (does it matter if they are different? eu-central-1 does not provide e-mail services).

I am following the instructions at: https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-using-sdk-net.html. SendEmail(...) doesn't seem to exist, but SendEmailAsync(...) does. Using that instead.

The following code fails:

```
    async Task testasync(IAmazonSimpleEmailService client)
    {
        var sendRequest = new SendEmailRequest
        {
            Source = "foo@foo.com",
            Destination = new Destination
            {
                ToAddresses = new List<string> { "foo2@foo.com" }
            },
            Message = new Message
            {
                Subject = new Content("subject"),
                Body = new Body
                {
                    Text = new Content
                    {
                        Charset = "UTF-8",
                        Data = "Hello, world!"
                    }
                }
            },
            //ConfigurationSetName = Don't want to use a configuration set as it has no relevance. Applies to Amazon CloudWatch and Amazon Kinesis Firehose as far as I could understand.
        };
        try
        {
            Console.WriteLine("Sending email using Amazon SES...");
            var response = await client.SendEmailAsync(sendRequest);
            Console.WriteLine("The email was sent successfully.");
        }
        catch (Exception ex)
        {
            Console.WriteLine("The email was not sent.");
            Console.WriteLine("Error message: " + ex.Message);
        }
    }
```

It throws:

`HttpRequestException -- no route to host`

Stack trace:

```
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
   at Amazon.Runtime.Internal.Util.AsyncHelpers.<>c__DisplayClass1_1`1.<<RunSync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Amazon.Runtime.Internal.Util.AsyncHelpers.ExclusiveSynchronizationContext.BeginMessageLoop() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\Util\_mobile\AsyncHelpers.cs:line 142
   at Amazon.Runtime.Internal.Util.AsyncHelpers.RunSync[T](Func`1 task) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\Util\_mobile\AsyncHelpers.cs:line 87
   at Amazon.Util.AWSSDKUtils.DownloadStringContent(Uri uri, TimeSpan timeout, IWebProxy proxy) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Util\AWSSDKUtils.cs:line 1000
   at Amazon.Util.EC2InstanceMetadata.GetItems(String relativeOrAbsolutePath, Int32 tries, Boolean slurp) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Util\_bcl+coreclr\EC2InstanceMetadata.cs:line 513
   at Amazon.Util.EC2InstanceMetadata.get_IAMSecurityCredentials() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Util\_bcl+coreclr\EC2InstanceMetadata.cs:line 311
   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.FetchCredentials() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Credentials\_bcl+coreclr\DefaultInstanceProfileAWSCredentials.cs:line 142
   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentials() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Credentials\_bcl+coreclr\DefaultInstanceProfileAWSCredentials.cs:line 88
   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentialsAsync() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Credentials\_bcl+coreclr\DefaultInstanceProfileAWSCredentials.cs:line 106
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CredentialsRetriever.cs:line 90
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\RetryHandler\RetryHandler.cs:line 137
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
```

My credentials file looks like this:

```
[foo]
aws_access_key_id = xxx
aws_secret_access_key = xxx
```

My appSettings.Development.json looks like this:

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  },
  "AWS": {
    "Profile": "foo",
    "Region": "eu-central-1"
  }
}
```

In Startup.cs I have this (not sure if it's relevant):

```
services.AddDefaultAWSOptions(Configuration.GetAWSOptions());
services.AddAWSService<IAmazonSimpleEmailService>();
```

Not sure what no route to host indicates. Is it my credentials? Is my configuration wrong?

**Comment by emilmuller** [comment]
I would also like to point out that dependency injection is not a good idea with IAmazonSimpleEmailService. IAmazonSimpleEmailService seems to use whatever AWS_REGION is set to. However, as in my case, eu-central-1 does *NOT* support SES, and as such, I had to go for Ireland:

`new AmazonSimpleEmailServiceClient(RegionEndpoint.EUWest1)`

https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-netcore.html

appsettings.json should maybe have an SESRegion in there?

**Comment by emilmuller** [comment]
Ended up doing this:

```
        // THIS DOES NOT WORK:
        // -------------------

        services.AddDefaultAWSOptions(Configuration.GetAWSOptions());

        // THIS FIXES IT
        // -------------

        var awsOptions = Configuration.GetAWSOptions();
        var chain = new CredentialProfileStoreChain(awsOptions.ProfilesLocation);

        if (chain.TryGetAWSCredentials(awsOptions.Profile, out AWSCredentials result))
        {
            var credentials = result.GetCredentials();
            
            Environment.SetEnvironmentVariable("AWS_ACCESS_KEY_ID", credentials.AccessKey);
            Environment.SetEnvironmentVariable("AWS_SECRET_ACCESS_KEY", credentials.SecretKey);
        }

        else throw new Exception("Could not get Amazon credentials");

        Environment.SetEnvironmentVariable("AWS_REGION", awsOptions.Region.SystemName);
```

**Comment by klaytaybai** [comment]
Hi @emilmuller, I'm sorry to hear you had some issues with this, but I'm glad to see that you found a workaround. I'm not yet sure why the first solution didn't work.  Which method did you use to set up your client?

**Comment by emilmuller** [comment]
Here is my Startup.cs file (if this is what you were asking :) ):

```
using Amazon;
using Amazon.Extensions.NETCore.Setup;
using Amazon.Runtime;
using Amazon.Runtime.CredentialManagement;
using Amazon.S3;
using Amazon.SimpleEmail;

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.HttpsPolicy;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

using Foo.Hubs;
using Foo.Models.Database;

namespace Foo
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });

            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
            services.AddDbContext<FooDbContext>(options => options.UseSqlite(Configuration.GetConnectionString("Sqlite")));


            // AWS configuration
            // -----------------

            // THIS DOES NOT WORK:
            // -------------------

            services.AddDefaultAWSOptions(Configuration.GetAWSOptions());

            // THIS FIXES IT
            // -------------

            var awsOptions = Configuration.GetAWSOptions();

            if (new CredentialProfileStoreChain(awsOptions.ProfilesLocation).TryGetAWSCredentials(awsOptions.Profile, out AWSCredentials result))
            {
                var credentials = result.GetCredentials();
                
                Environment.SetEnvironmentVariable("AWS_ACCESS_KEY_ID", credentials.AccessKey);
                Environment.SetEnvironmentVariable("AWS_SECRET_ACCESS_KEY", credentials.SecretKey);
            }

            else throw new Exception("Could not get Amazon credentials");

            Environment.SetEnvironmentVariable("AWS_REGION", awsOptions.Region.SystemName);

            // END OF FIX

            services.AddAWSService<IAmazonS3>(); // Singleton
            services.AddAWSService<IAmazonSimpleEmailService>(new AWSOptions() { Region = RegionEndpoint.EUWest1 }); // Singleton
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            Program.Services = app.ApplicationServices;

            Cache.Initialize();

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();
            //app.UseCookiePolicy(); We don't use cookies


            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{*url}",
                    defaults: new { controller = "Spa", action = "Index" });
            });
        }
    }
}
```

**Comment by emilmuller** [comment]
appsettings.json:

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Warning"
    }
  },
  "AllowedHosts": "*",
  "ConnectionStrings": {
    "Sqlite": "Data Source=Sqlite.db"
  }
}
```

appsettings.Development.json:

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  },
  "AWS": {
    "Profile": "foo",
    "Region": "eu-central-1"
  }
}
```

And in ~/.aws/credentials:

```
[foo]
aws_access_key_id = xxx
aws_secret_access_key = xxx
```

It's not working when debugging. Haven't tested release yet.

**Comment by future81** [comment]
ok for new comers here's how you get AWS service to use your appsettings.json
In Startup.cs
`services.AddDefaultAWSOptions(Configuration.GetAWSOptions());
            services.AddAWSService<IAmazonSimpleEmailService>();`
Surely add AWS configuration to appsettings
`"AWS": {
    "Profile": "profileName",
    "Region": "us-east-1"
  }`

Lastly in order to use above configuration in your AWS service you have to add the service with Dependency Injection to your class and use it
for Example to send emails with SimpleEmailService in the EmailSender class:
` public class EmailSender : IEmailSender
   {
        IAmazonSimpleEmailService _SES;
        public EmailSender(IAmazonSimpleEmailService SES)
        {
            _SES= SES;
        }
      `
and then call it in your function and dont use AmazonSimpleEmailServiceClient
`_SES.SendEmailAsync(sendRequest);`

**Comment by emilmuller** [comment]
@future81 Not sure if you were just giving general advice, or have spotted something that I did wrong? I can't see it. My setup works on Windows, but not on Linux.
