### ISSUE TITLE
Download object throw TypeInitializationException

### ISSUE THREAD

**Issue by vickyrathee** [aws/aws-sdk-net#1188]
## Expected Behavior
Object should be downloaded to given directory.

## Current Behavior
I have a service which download the objects in EC2 from S3 process them > upload result back to S3. But in version 3.3.31.11 of S3 the object is downloaded only when user is logged in to windows server 2016 but throw error after logged out and services is running via scheduler while the download folder has full permission to read/write/modify. 

```
<package id="AWSSDK.Core" version="3.3.31.3" targetFramework="net461" />
<package id="AWSSDK.S3" version="3.3.31.11" targetFramework="net461" />
```

## Code

```
public async Task<HttpStatusCode> DownloadObjectAsync(string s3Bucket, string s3Path, string s3Region, string filePath)
	{
		try
		{
			var region = Amazon.RegionEndpoint.GetBySystemName(s3Region);
			using (IAmazonS3 client = new AmazonS3Client(awsAccessKey, awsSecretKey, region))
			{
				using (TransferUtility transferUtility = new TransferUtility(client))
				{

					await transferUtility.DownloadAsync(filePath, s3Bucket, s3Path);
					return HttpStatusCode.OK;

				}
			}
		}
		catch (AmazonS3Exception s3Exception)
		{
			return s3Exception.StatusCode;
		}
		catch (Exception)
		{
			// Escalate to admin
		}
		return HttpStatusCode.InternalServerError;
	}
```

## Errror

```
2019-01-24 04:02:46.6725	FATAL	System.TypeInitializationException: The type initializer for 'Amazon.AWSConfigs' threw an exception. ---> System.Runtime.InteropServices.COMException: Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
   at System.Security.Policy.PEFileEvidenceFactory.GetLocationEvidence(SafePEFileHandle peFile, SecurityZone& zone, StringHandleOnStack retUrl)
   at System.Security.Policy.PEFileEvidenceFactory.GenerateLocationEvidence()
   at System.Security.Policy.PEFileEvidenceFactory.GenerateEvidence(Type evidenceType)
   at System.Security.Policy.AssemblyEvidenceFactory.GenerateEvidence(Type evidenceType)
   at System.Security.Policy.Evidence.GetHostEvidenceNoLock(Type type)
   at System.Security.Policy.Evidence.GetHostEvidence(Type type, Boolean markDelayEvaluatedEvidenceUsed)
   at System.Security.Policy.AppDomainEvidenceFactory.GenerateEvidence(Type evidenceType)
   at System.Security.Policy.Evidence.GetHostEvidenceNoLock(Type type)
   at System.Security.Policy.Evidence.OnSerializing(StreamingContext context)


   at System.AppDomain.get_Evidence()
   at System.AppDomain.get_Evidence()
   at System.Configuration.ClientConfigPaths.GetEvidenceInfo(AppDomain appDomain, String exePath, String& typeName)
   at System.Configuration.ClientConfigPaths.GetTypeAndHashSuffix(AppDomain appDomain, String exePath)
   at System.Configuration.ClientConfigPaths..ctor(String exePath, Boolean includeUserConfig)
   at System.Configuration.ClientConfigPaths.GetPaths(String exePath, Boolean includeUserConfig)
   at System.Configuration.ClientConfigurationHost.RequireCompleteInit(IInternalConfigRecord record)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at Amazon.AWSConfigs.GetSection[T](String sectionName) in d:\Jenkins\jobs\build-sdk-v2\workspace\sdk\src\AWSSDK_DotNet35\AWSConfigs.bcl.cs:line 56
   at Amazon.Util.RootConfig..ctor() in d:\Jenkins\jobs\build-sdk-v2\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Util\AWSConfigs.Models.cs:line 74
   at Amazon.AWSConfigs..cctor() in d:\Jenkins\jobs\build-sdk-v2\workspace\sdk\src\AWSSDK_DotNet35\AWSConfigs.cs:line 92
   --- End of inner exception stack trace ---
   at Amazon.Runtime.ClientConfig.GetDefaultRegionEndpoint() in d:\Jenkins\jobs\build-sdk-v2\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\ClientConfig.bcl.cs:line 42
   at Amazon.Runtime.ClientConfig..ctor() in d:\Jenkins\jobs\build-sdk-v2\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\ClientConfig.bcl.cs:line 38
   at Amazon.S3.AmazonS3Config..ctor() in d:\Jenkins\jobs\build-sdk-v2\workspace\sdk\src\AWSSDK_DotNet35\Amazon.S3\AmazonS3Config.cs:line 34
   at Amazon.S3.AmazonS3Client..ctor(String awsAccessKeyId, String awsSecretAccessKey, RegionEndpoint region) in d:\Jenkins\jobs\build-sdk-v2\workspace\sdk\src\AWSSDK_DotNet45\Amazon.S3\AmazonS3Client.cs:line 147
   at AwsClient.DownloadObject(String fromPath, String toPath) in MyApp.exe:line 677
   at ProcessFile.<T>d__5.MoveNext() in MyApp.exe:line 202
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at <Main>d__3.MoveNext() in MyApp.exe:line 88System.TypeInitializationException: The type initializer for 'Amazon.AWSConfigs' threw an exception. ---> System.Runtime.InteropServices.COMException: Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
   at System.Security.Policy.PEFileEvidenceFactory.GetLocationEvidence(SafePEFileHandle peFile, SecurityZone& zone, StringHandleOnStack retUrl)
   at System.Security.Policy.PEFileEvidenceFactory.GenerateLocationEvidence()
   at System.Security.Policy.PEFileEvidenceFactory.GenerateEvidence(Type evidenceType)
   at System.Security.Policy.AssemblyEvidenceFactory.GenerateEvidence(Type evidenceType)
   at System.Security.Policy.Evidence.GetHostEvidenceNoLock(Type type)
   at System.Security.Policy.Evidence.GetHostEvidence(Type type, Boolean markDelayEvaluatedEvidenceUsed)
   at System.Security.Policy.AppDomainEvidenceFactory.GenerateEvidence(Type evidenceType)
   at System.Security.Policy.Evidence.GetHostEvidenceNoLock(Type type)
   at System.Security.Policy.Evidence.OnSerializing(StreamingContext context)


   at System.AppDomain.get_Evidence()
   at System.AppDomain.get_Evidence()
   at System.Configuration.ClientConfigPaths.GetEvidenceInfo(AppDomain appDomain, String exePath, String& typeName)
   at System.Configuration.ClientConfigPaths.GetTypeAndHashSuffix(AppDomain appDomain, String exePath)
   at System.Configuration.ClientConfigPaths..ctor(String exePath, Boolean includeUserConfig)
   at System.Configuration.ClientConfigPaths.GetPaths(String exePath, Boolean includeUserConfig)
   at System.Configuration.ClientConfigurationHost.RequireCompleteInit(IInternalConfigRecord record)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at Amazon.AWSConfigs.GetSection[T](String sectionName) in d:\Jenkins\jobs\build-sdk-v2\workspace\sdk\src\AWSSDK_DotNet35\AWSConfigs.bcl.cs:line 56
   at Amazon.Util.RootConfig..ctor() in d:\Jenkins\jobs\build-sdk-v2\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Util\AWSConfigs.Models.cs:line 74
   at Amazon.AWSConfigs..cctor() in d:\Jenkins\jobs\build-sdk-v2\workspace\sdk\src\AWSSDK_DotNet35\AWSConfigs.cs:line 92
   --- End of inner exception stack trace ---
   at Amazon.Runtime.ClientConfig.GetDefaultRegionEndpoint() in d:\Jenkins\jobs\build-sdk-v2\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\ClientConfig.bcl.cs:line 42
   at Amazon.Runtime.ClientConfig..ctor() in d:\Jenkins\jobs\build-sdk-v2\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\ClientConfig.bcl.cs:line 38
   at Amazon.S3.AmazonS3Config..ctor() in d:\Jenkins\jobs\build-sdk-v2\workspace\sdk\src\AWSSDK_DotNet35\Amazon.S3\AmazonS3Config.cs:line 34
   at Amazon.S3.AmazonS3Client..ctor(String awsAccessKeyId, String awsSecretAccessKey, RegionEndpoint region) in d:\Jenkins\jobs\build-sdk-v2\workspace\sdk\src\AWSSDK_DotNet45\Amazon.S3\AmazonS3Client.cs:line 147
   at AwsClient.DownloadObject(String fromPath, String toPath) in C:\Users\Administrator\MyApp.exe:line 677
   at <ProcessFile>d__5.MoveNext() in MyApp.exe:line 202
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at <Main>d__3.MoveNext() 
```

## Steps to Reproduce (for bugs)
Create an app > install on windows 2016 server > run every minute using scheduler (non-administrator) > Log out

**Comment by klaytaybai** [comment]
Do you have anything in your AWS configuration that would be specific to the user, such as the AWSProfilesLocation?

**Comment by vickyrathee** [comment]
@klaytaybai No, i use the credentials in string as given below. After investigation i found this error throws in Windows Server 2016 only and when logged in as System account(Non-administrator account), because my application was running using Task Scheduler or using command line as `Process.Start`

```
static readonly string awsAccessKey = "****";
static readonly string awsSecretKey = "******************";
```

I guess the AWS SDK is checking the config file somewhere on system directory and Windows is disallowing to access that location (or may be Windows defender not letting the SDK to access the file) when running the exe using [Process.Start](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.start?view=netframework-4.7.2) with Task Scheduler as non-administrator.

Anyway, this is easy to re-produce!

**Comment by sstevenkang** [comment]
This looks like a permission issue in your particular environment, not the issue with the SDK.  The exception is triggered by `System.Security.Policy.PEFileEvidenceFactory.GetLocationEvidence()` which is Microsoft's API.  I don't see how this is an issue with the SDK.

**Comment by vickyrathee** [comment]
Couple of questions :

1 - Why the sdk is looking for configuration file, while the credentials
are provided as string. So no configuration exists or should be checked in
run time.

2 - What directory folder it’s looking for to find the configuration. if I
can grant access (or ask customers) to make that folder public to let sdk
read that.

3 - The AMI I’m using is standard windows 2016 by AWS. So nothing
customised and expected the script using this sdk should run without any
problem in non-administrator account using task scheduler as it was running
in windows 2008 r2 successfully.

**Comment by ashishdhingra** [comment]
Hi @vickyrathee,

Please try using the latest version of SDK and confirm if the issue is fixed. 

Thanks,
Ashish
