### ISSUE TITLE
Visual Studio 2017 crashes when opening the Lambda Function View

### ISSUE THREAD

**Issue by rabejens** [aws/aws-sdk-net#1202]
Whenever I try to publish a Lambda function to AWS, VS 2017 crashes with "Visual Studio 2017 Community has stopped working".

## Expected Behavior

The function should publish and the Test Function panel should open

## Current Behavior

The function publishes, the test view appears and then VS 2017 crashes with "Visual Studio 2017 has stopped working".

VS 2017 also crashes when I open the Lambda Function View directly.

### Followup

This is accompanied by the following two events in Windows Event Viewer:

#### First one:
```
Faulting application name: devenv.exe, version: 15.9.28307.222, time stamp: 0x5c0aff10
Faulting module name: KERNELBASE.dll, version: 10.0.17763.134, time stamp: 0xc30ded87
Exception code: 0xe0434352
Fault offset: 0x0011ab32
Faulting process id: 0x7d4
Faulting application start time: 0x01d4bbd030d51d06
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: e81d4c62-d726-4094-b314-b0835e188814
Faulting package full name: 
Faulting package-relative application ID: 
```

#### Second one

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Amazon.AWSToolkit.Lambda.View.Components.DLQSelectionControl.SetAvailableDLQTargets(System.Collections.Generic.IList`1<System.String>, System.Collections.Generic.IList`1<System.String>, System.String)
   at Amazon.AWSToolkit.Lambda.Controller.ViewFunctionController+<>c__DisplayClass27_0.<OnDLQTargetsAvailable>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

### Method 1:

1. Create and register a profile in AWS Explorer that can upload to AWS Lambda
2. Create a new, basic, empty Lambda Function
3. Right-Click the project, select "Publish to AWS Lambda"
4. Add the missing information and let it upload
5. Wait until the Function View appears

### Method 2:

1. Publish any Lambda function
2. Register a profile in AWS explorer for the region the function is in
3. Open the AWS Lambda Tree and double-click the function

## Your Environment

* AWSSDK.Core version used: 

Amazon.Lambda.Core 1.0.0

* Service assembly and version used: 

?

* Operating System and version: 

Windows 10 Pro 64 Bit, Version 1809

* Visual Studio version: 

Visual Studio Community 2017, Version 15.9.4

* Targeted .NET platform: 

.net Core 2.1 as well as 2.0

## .NET Core Info

* .NET Core version used for development: 

.net core 2.1.502

* .NET Core version installed in the environment where application runs: 

.net Core 2.1.502

* Output of `dotnet --info`: 

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.502
 Commit:    c74ce8f29f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.502\

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

* Contents of project.json/project.csproj: 

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Function.fs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="aws-lambda-tools-defaults.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="1.0.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.Json" Version="1.4.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="aws-lambda-tools-defaults.json" />
    <None Include="Readme.md" />
  </ItemGroup>


</Project>
```

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
@rabejens thanks for following up and giving us your feedback.  I believe some work to prevent crashes like this is in progress.  Which version of the Toolkit are you using?
