### ISSUE TITLE
CodeCommit - NullReferenceException for previously-working credentials in VS2017

### ISSUE THREAD

**Issue by RickyAppSe** [aws/aws-sdk-net#1238]
## Expected Behavior

Open Visual Studio 2017. In Team Explorer, have the projects ready to be opened and worked on under AWS CodeCommit.

## Current Behavior

Where "AWS CodeCommit" should be in Team Explorer, the title is instead: "Error".

Where the projects should be is the following exception stack trace:

```
System.TypeInitializationException: The type initializer for 'Amazon.AWSToolkit.VisualStudio.TeamExplorer.CredentialManagement.TeamExplorerConnection' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Amazon.AWSToolkit.VisualStudio.TeamExplorer.CredentialManagement.TeamExplorerConnection..cctor()
   --- End of inner exception stack trace ---
   at Amazon.AWSToolkit.VisualStudio.TeamExplorer.CredentialManagement.TeamExplorerConnection.add_OnTeamExplorerBindingChanged(TeamExplorerBindingChanged value)
   at Amazon.AWSToolkit.VisualStudio.TeamExplorer.CodeCommit.Model.ConnectSectionViewModel..ctor()
   at Amazon.AWSToolkit.VisualStudio.TeamExplorer.CodeCommit.Connect.ConnectionSection.CreateViewModel(SectionInitializeEventArgs e)
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.TeamExplorerSectionBase.Initialize(Object sender, SectionInitializeEventArgs e)
   at Amazon.AWSToolkit.VisualStudio.TeamExplorer.CodeCommit.Connect.ConnectionSection.Initialize(Object sender, SectionInitializeEventArgs e)
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Initialize(Object context)
```

## Possible Solution
I have no idea. I haven't changed anything - I was on a recent version of VS 2017, and AWS Toolkit for VS 2017 & 2019 was on the latest version, and previously this setup has been working since I began using it about 5 months ago.

I tried updating VS2017 to the latest version (it was less than a month our of date). No luck, error message still the same.

I also tried completely uninstalling and re-installing the AWS Toolkit for VS2017 extension. No luck, error message still the same. And no, it didn't even ask me to enter any credentials again or anything, it's just immediately presenting me with that error.

## Steps to Reproduce (for bugs)

1. Have working credentials and be connected to projects successfully for 5 months.

2. One day, have AWS CodeCommit crash?

Maybe this was a Windows Update issue?

Please help.

## Context

This is how I connect to my client's codebase. With this out, it will severely hamper my ability to do work as a contractor.

## Your Environment

VS2017 Professional, v15.9.10.

Windows 10 Pro, 64-bit version.

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by RickyAppSe** [comment]
![image](https://user-images.githubusercontent.com/49116830/55287474-ca8ec780-5398-11e9-85c9-2c825dbe8b4c.png)

This probably won't help much, but this is a screenshot of the part of the Team Explorer pane where AWS CodeCommit normally is.

**Comment by normj** [comment]
I want to confirm was this issue happening with the version before the recent 1.15.0.0 version of the toolkit that added VS 2019 support as well as the new latest version? Or is it only happening with the latest version that added support for VS 2019?

As an experiment could you try rename the following directory to see if that changes the behavior. You will need to have Visual Studio shutdown to rename this directory and then you should see the AWS Toolkit reset itself back the original settings. 

C:\Users\<user-id>\appdata\Local\AWSToolkit

Once you have done the experienment you can delete the new AWSToolkit directory that will be created when you launch Visual Studio and rename this directory back to the original name so you don't lose any of your settings.

**Comment by ryanriv** [comment]
I was experiencing a similar issue. Renaming the folder and adding back in my credentials seems to have fixed it for me. It started after updating the toolkit to the latest version with VS 2019 support. I am using VS 2017.

**Comment by RickyAppSe** [comment]
Unfortunately, this did not fix my issue.

I renamed the old folder to AWSToolkit-Old, started VS 2017, and a new AWSToolkit folder was automatically created. But I'm still just seeing that error in the Team Explorer pane.

As for version, I'm on 1.15.0. I have these kinds of VS extensions set to auto-update so I don't need to worry about them, and it was working for me as early as last Friday (29th March), so maybe it updated to this version when I shut down VS for the day/week at the end of Friday and it's this update which is causing the issue?

Is there a place I can download previous versions so I can uninstall this one, re-install the older one, and see if that helps?

**Comment by normj** [comment]
I'm have been unsuccessful in reproducing the problem. Looking at the code indicating by the stack trace it looks like this could happen if the AWS Toolkit had an error during its main initialization and then when Team explorer opened up it threw this error trying to access an uninitialized instance of the toolkit.

Can either of you check the toolkit logs for any errors that might have happen before this error. The toolkit's logs can be found at C:\Users\<user-id>\AppData\Local\AWSToolkit\logs\visualstudio.

Also can you confirm if the AWS Explorer windows is open when you go into Team explorer. If it is not can you open the AWS Explorer window to see if that component works. You shouldn't need the AWS Explorer open I'm just trying to figure out if that is also broken in your installs.

**Comment by RickyAppSe** [comment]
[log.txt](https://github.com/aws/aws-sdk-net/files/3036222/log.txt)

Attached: Log from yesterday (in the newly created folder from the previous experiment).

Also, I'm not entirely sure what you're referring to by seeing if the AWS Explorer windows are open, but if I go to Team Explorer pane --> Manage Connections --> Connect to AWS CodeCommit, then I get (basically) the same error. E.g:

![image](https://user-images.githubusercontent.com/49116830/55442406-fd55dd00-559d-11e9-9b50-2edcae2527f4.png)

**Comment by normj** [comment]
I was able to reproduce the issue and it is a timing issue. If you have pined the AWS Explorer which can opened via View -> Explorer then restart Visual Studio the toolkit will be loaded before Team Explorer attempts to access it and you won't get the error.

![image](https://user-images.githubusercontent.com/1653751/55443708-936f1080-5568-11e9-87bd-8355d618e779.png)

I'm working on a fix now and we keep you all updated.

**Comment by RickyAppSe** [comment]
I can confirm that this workaround (pinning the AWS Explorer window and then restarting VS 2017) works on my side too.
Thank you for looking into this for me. Looking forward to hearing more about the fix making its way to a new version to update to, so I don't need to continue to keep the AWS Explorer window open and pinned. :)

**Comment by normj** [comment]
I have a fix for VS2017 but VS2019 is being challenging. I'm assuming the users that are running into this issue are using VS2017 so I'm going to focus on getting the release out for just VS2017 and then come back to VS2019. Thanks for your patience.
