### ISSUE TITLE
Lambda publishing to SNS (Authentication failed ... remote party has closed the transport stream)

### ISSUE THREAD

**Issue by IndikaUdagedara** [aws/aws-sdk-net#1306]
I have a .NET Core 2.1 Lambda publishing messages to an SNS topic in eu-west-2 region. It throws the following exception

```
One or more errors occurred. (Authentication failed because the remote party has closed the transport stream.): AggregateException
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at lambda_method(Closure , Stream , Stream , LambdaContextInternal )

at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
```

This application works fine in ap-southeast-2 region. It is deployed using Cloudformation and the only difference between the two deployments is the region. I suspect it has something to do with regional SNS endpoints and TLS versions. 

## Expected Behavior
Lambda should be able to publish messages to SNS.

## Current Behavior
Lambda fails to publish to SNS with the above error. Using the same Lambda role locally and using VS2019, the application is able to publish to SNS. Publishing works in `ap-southeast-2` as well.

## Steps to Reproduce (for bugs)
```
public async Task FunctionHandler(ILambdaContext context)
{	
  var snsClient = scope.ServiceProvider.GetRequiredService<IAmazonSimpleNotificationService>();
  var request = new PublishRequest("<topic arn>", JsonConvert.SerializeObject(new
  {
    hello = "world"
  }, Formatting.None));

  try
  {
    var response = await snsClient.PublishAsync(request);
  }
  catch (Exception e)
  {
    Console.WriteLine(e)
  }
}
```
## Context
This is affecting our `eu-west-2` production deployment

### .csproj
```
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
    <ApplicationIcon />
    <OutputType>Exe</OutputType>
    <StartupObject />
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="1.1.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.Json" Version="1.5.0" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.3.6" />
    <PackageReference Include="AWSSDK.SecurityToken" Version="3.3.101.10" />
    <PackageReference Include="AWSSDK.SimpleNotificationService" Version="3.3.101.17" />
    ....
  <ItemGroup>
```
### Lambda build/package
```
> dotnet lambda package --framework netcoreapp2.1 -o ... -pl ...

> dotnet lambda version
Amazon Lambda Tools for .NET Core applications (3.2.3)

> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.203
 Commit:    e5bab63eca

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.203\

Host (useful for support):
  Version: 2.2.4
  Commit:  f95848e524

.NET Core SDKs installed:
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.2.203 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

```
[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
If you are using a VPC, is it configured to reach eu-west-2 SNS?

**Comment by IndikaUdagedara** [comment]
Spot on! We have an egress firewall which had sns.eu-west-2 blocked. "Authorization failed" in the exception threw me off. Thanks!

I'm now considering using a SNS VPC endpoint. After creating the endpoint though I got a `Task Cancelled` exception indicating possibly a timeout. Since SNS endpoint is of type `Interface`, do I have to do anything special in  `IAmazonSimpleNotificationService` configuration e.g. specifying the endpoint url?

**Comment by IndikaUdagedara** [comment]
My mistake again.. no special configuration needed. Security Group for endpoint needs to allow VPC traffic.

Surprised how that works though - I'd hope that the endpoint url needs to be specified. Otherwise how does the routing figure out to use the VPC endpoint instead of default route? (because endpoint of type `Interface` doesn't modify VPC route table unlike type `Gateway`)

**Comment by klaytaybai** [comment]
Hi @IndikaUdagedara, maybe this will provide more information:  [VPC_Route_Tables](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Route_Tables.html) and [VPCs with Lambda](https://docs.aws.amazon.com/lambda/latest/dg/vpc.html).

Is this good to close now?

**Comment by IndikaUdagedara** [comment]
Yes.
