### ISSUE TITLE
Error sending SNS message through SNSClient

### ISSUE THREAD

**Issue by grungondola** [aws/aws-sdk-net#1350]
## Expected Behavior
I use the following code to send a message to SNS:

```
using (var snsClient = new AmazonSimpleNotificationServiceClient())
{
  Logger.LogInstance.Debug("Beginning SNS message transfer");
  snsClient.PublishAsync(new PublishRequest
  {
    Subject = "My-Status",
    Message = snsMessage,
    MessageAttributes = messageAttributes,
    TopicArn = Configuration["TopicArn"]
  }).Wait();
  Logger.LogInstance.Debug("Finished SNS message transfer");
}
```

## Current Behavior
I receive the Debug log message stating "Beginning SNS message transfer"
I then receive the following error:
```
Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
```

## Context
This error occurs occasionally when attempting to send a message from a Lambda function to an SNS topic, but it seems to happen in groups. I had 4 failed messages within a 15-minute window, and then the 5th message succeeded.

## Your Environment

* AWSSDK.Core version used: 3.3.103.10
* Service assembly and version used: AWSSDK.SimpleNotificationService 3.3.101.35 (happened in multiple versions)
* Operating System and version: AWS Lambda on API Gateway
* Visual Studio version: Visual Studio 2017
* Targeted .NET platform: .Net Core 2.1

## .NET Core Info

* .NET Core version used for development: 2.1
* .NET Core version installed in the environment where application runs: 2.1
* Contents of project.json/project.csproj: 
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
    <Configurations>Debug;Release;Test;Training;Pre-Prod</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.APIGatewayEvents" Version="1.2.0" />
    <PackageReference Include="Amazon.Lambda.Core" Version="1.1.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.Json" Version="1.5.0" />
    <PackageReference Include="AWSSDK.SimpleNotificationService" Version="3.3.101.35" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="5.2.7" />
    <PackageReference Include="System.Data.SqlClient" Version="4.6.1" />
    <PackageReference Include="THLogging" Version="1.2.2" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
```

**Comment by klaytaybai** [comment]
Are you able to provide any more details about the exceptions?

**Comment by grungondola** [comment]
I have given all of the details about the error. The exception is:

`Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.`

The Stack Trace is:

```
Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
```

I am getting no additional information from AWS on this error. I have checked CloudWatch, and there are no success or failure messages written by the SNS Topic at the time of the error, so something is stopping it in the snsClient.PublishAsync function for some reason, but I'm not sure what that could be.

**Comment by grungondola** [comment]
This error was caused by a blank Message Attribute value. I was grabbing just the inner-most exception and ignoring the outer exception:

The message attribute 'SENDER' must contain non-empty message attribute value for message attribute type 'String'.
