### ISSUE TITLE
Mono.Cecil.ResolutionException: Failed to resolve Amazon.S3.Transfer.TransferUtilityDownloadDirectoryRequest

### ISSUE THREAD

**Issue by cjkarande** [aws/aws-sdk-net#1360]
I am getting following Assembly linker issue whenever i reference to S3 DownloadXXXXX APIs & their objects in my code. For ex.
TransferUtilityDownloadRequest
TransferUtilityDownloadDirectoryRequest
DownloadAsync
DownloadDirectoryAsync

For some reason the linker is scoping the AWSSDK.S3 to version 3.3.0.0 though my .NET Shared Project refers to AWSSDK.S3 version 3.3.103.4
However i dont face this issue for any references to the UploadXXXX APIs & their objects like
TransferUtilityUploadRequest
UploadAsync

This is a bit wierd....Appreciate a quick support from Xamarin Team
//////////////////////////////////////////////////////////////////////////////////////////////
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "LinkAssemblies" task failed unexpectedly.
Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: **Could not resolve reference to 'Amazon.S3.Transfer.TransferUtilityDownloadDirectoryRequest' (defined in assembly 'TipssyAutomation, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null') with scope 'AWSSDK.S3, Version=3.3.0.0,** Culture=neutral, PublicKeyToken=885c28607f98e604'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve Amazon.S3.Transfer.TransferUtilityDownloadDirectoryRequest
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkField(FieldReference reference)
   at Mono.Linker.Steps.MarkStep.MarkFields(TypeDefinition type, Boolean includeStatic, Boolean markBackingFieldsOnlyIfPropertyMarked)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.InitializeType(TypeDefinition type)
   at Mono.Linker.Steps.MarkStep.InitializeType(TypeDefinition type)
   at Mono.Linker.Steps.MarkStep.InitializeType(TypeDefinition type)
   at Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.MarkStep.Initialize()
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   --- End of inner exception stack trace ---
   at Java.Interop.Tools.Diagnostics.Diagnostic.Error(Int32 code, Exception innerException, String message, Object[] args)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	TipssyAutomation.Android	
//////////////////////////////////////////////////////////////////////////////////////////////

**Comment by klaytaybai** [comment]
Hi @cjkarande, I suspect that this issue isn't caused by the AWS .NET SDK but rather version dependency conflicts caused by your code or third parties.  There seem to be a lot of resources about this type of error online.  Could you please look over some of them and see if making some changes to your .csproj files resolves your issue?  Here's an example of a resource that might help:  [StackOverflow:  Can't build my app in release mode](https://stackoverflow.com/questions/42611187/cant-build-my-app-in-release-mode). 

If you come across something that you think we need to take action on to fix your problem, please let us know.
