### ISSUE TITLE
System.IO.IOException: Unable to read data from the transport connection While executing an AWS lambda function

### ISSUE THREAD

**Issue by 1ds14te050manoj** [aws/aws-sdk-net#1424]
Hi @gokarnm I have created a solutiion to retrieve the secret but i am facing an exception. No sure what's the cause. Could you help me me here? And also how can i resolve this exception?

here's the exception:

+		InnerException	{	: An error occurred while sending the request. ---> System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine. ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
   at Amazon.Runtime.Internal.Util.AsyncHelpers.<>c__DisplayClass1_1`1.<<RunSync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Amazon.Runtime.Internal.Util.AsyncHelpers.ExclusiveSynchronizationContext.BeginMessageLoop() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\Util\_mobile\AsyncHelpers.cs:line 142
   at Amazon.Runtime.Internal.Util.AsyncHelpers.RunSync[T](Func`1 task) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\Util\_mobile\AsyncHelpers.cs:line 87
   at Amazon.Util.AWSSDKUtils.DownloadStringContent(Uri uri, TimeSpan timeout, IWebProxy proxy) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Util\AWSSDKUtils.cs:line 1138
   at Amazon.Util.EC2InstanceMetadata.GetItems(String relativeOrAbsolutePath, Int32 tries, Boolean slurp) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Util\_bcl+netstandard\EC2InstanceMetadata.cs:line 513
   at Amazon.Util.EC2InstanceMetadata.get_IAMSecurityCredentials() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Util\_bcl+netstandard\EC2InstanceMetadata.cs:line 311
   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.FetchCredentials() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Credentials\_bcl+netstandard\DefaultInstanceProfileAWSCredentials.cs:line 142
   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentials() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Credentials\_bcl+netstandard\DefaultInstanceProfileAWSCredentials.cs:line 88
   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentialsAsync() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Credentials\_bcl+netstandard\DefaultInstanceProfileAWSCredentials.cs:line 106
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CredentialsRetriever.cs:line 90
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\RetryHandler\RetryHandler.cs:line 137
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)}	System.Exception {System.Net.Http.HttpRequestException}

**Comment by 1ds14te050manoj** [comment]
Also attaching the code i am using. 
Here's the code:

using System;
using Amazon.Lambda.Core;
using Amazon;
using Amazon.SecretsManager;
using Amazon.SecretsManager.Model;
using System.IO;
using Newtonsoft.Json;
using MySql.Data.MySqlClient;
using System.Net.Http;
using System.Threading.Tasks;

// Assembly attribute to enable the Lambda function's JSON input to be converted into a .NET class.
[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.Json.JsonSerializer))]

namespace SecretManager
{
    /// <summary>
    /// Class for SecretManagerValue
    /// </summary>
    /// 

    public class SecretManagerValue
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Engine { get; set; }
        public string Host { get; set; }
        public string Port { get; set; }
        public string DbClusterIdentifier { get; set; }
    }
    public class Function
    {

        /// <summary>
        /// A simple function that takes a string and does a ToUpper
        /// </summary>
        /// <param name="input"></param>
        /// <param name="context"></param>
        /// <returns></returns>
        /// 

        public string FunctionHandler(String input, ILambdaContext context)
        {
            var result = JsonConvert.DeserializeObject<SecretManagerValue>(GetSecret());
            LambdaLogger.Log("Generating Configuration....");
            var connString = GenerateConfiguration(result);
            LambdaLogger.Log("Check Connection....");
            var connectToDB = CheckConnectionMySQL(connString);
            if (connectToDB) { LambdaLogger.Log("Connection was succesfull."); }
            else { LambdaLogger.Log("Connection was unsuccesfull."); }
            return connString;
        }

        /// <summary>
        /// Generate ConnectionString
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static string GenerateConfiguration(SecretManagerValue value)
        {
            var configString = "Server={ServerName};Port=3306;Database={databaseName};Uid={UserName};Pwd={Password};Convert Zero Datetime=True;default command timeout=0;";

            var connectionString = configString.Replace("{ServerName}", value.Host)
                                                .Replace("{databaseName}", "MY-DB")
                                                .Replace("{UserName}", value.UserName)
                                                .Replace("{Password}", value.Password);


            return connectionString;
        }

        public static bool CheckConnectionMySQL(string connString)
        {
            using (var conn = new MySqlConnection(connString))
            {
                try
                {
                    conn.Open();
                    return true;
                }
                catch (Exception ex)
                {
                    LambdaLogger.Log(ex.Message);
                    return false;
                }
            }
        }

        /// <summary>
        /// Get Secret from AWS secret manager
        /// </summary>
        /// <returns></returns>
        public static string GetSecret()
        {
            
            string secretName = "MY-Lambda";
            string region = "us-east-1";
            string secret = "";
            Console.WriteLine(region);
            MemoryStream memoryStream = new MemoryStream();


            //IAmazonSecretsManager client = new AmazonSecretsManagerClient(RegionEndpoint.GetBySystemName(region));

            AmazonSecretsManagerConfig smConfig = new AmazonSecretsManagerConfig
            {


                //RegionEndpoint = RegionEndpoint.USEast1,
                AuthenticationRegion = RegionEndpoint.USEast1.SystemName,
                //ServiceURL = "https://vpce-0eebfe484da95a7c1-s82syo9o.secretsmanager.us-east-1.vpce.amazonaws.com/"
                ServiceURL = "https://vpce-09c6a1210945be04e-obyrsarv.secretsmanager.us-east-1.vpce.amazonaws.com/"
            };
            IAmazonSecretsManager client = new AmazonSecretsManagerClient(smConfig);
          
            Console.WriteLine("Service URL: " + client.Config.ServiceURL);
            Console.WriteLine("Determined Service URL: " + client.Config.DetermineServiceURL());
            Console.WriteLine("Authentication Region: " + client.Config.AuthenticationRegion);

            GetSecretValueRequest request = new GetSecretValueRequest();
            request.SecretId = secretName;
            request.VersionStage = "AWSCURRENT"; // VersionStage defaults to AWSCURRENT if unspecified.

            GetSecretValueResponse response = null;

            // In this sample we only handle the specific exceptions for the 'GetSecretValue' API.
            // See https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_GetSecretValue.html   
            // We rethrow the exception by default.

            try
            {
                response = client.GetSecretValueAsync(request).Result;

                

            }
            catch (DecryptionFailureException e)
            {
                // Secrets Manager can't decrypt the protected secret text using the provided KMS key.
                // Deal with the exception here, and/or rethrow at your discretion.
                Console.WriteLine("DecryptionFailureException");
                Console.WriteLine(e.Message);
                throw;
            }
            catch (InternalServiceErrorException e)
            {
                // An error occurred on the server side.
                // Deal with the exception here, and/or rethrow at your discretion.
                Console.WriteLine("InternalServiceErrorException");
                Console.WriteLine(e.Message);
                throw;
            }
            catch (InvalidParameterException e)
            {
                // You provided an invalid value for a parameter.
                // Deal with the exception here, and/or rethrow at your discretion
                Console.WriteLine("InvalidParameterException");
                Console.WriteLine(e.Message);
                throw;
            }
            catch (InvalidRequestException e)
            {
                // You provided a parameter value that is not valid for the current state of the resource.
                // Deal with the exception here, and/or rethrow at your discretion.
                Console.WriteLine("InvalidRequestException");
                Console.WriteLine(e.Message);
                throw;
            }
            catch (ResourceNotFoundException e)
            {
                // We can't find the resource that you asked for.
                // Deal with the exception here, and/or rethrow at your discretion.
                Console.WriteLine("ResourceNotFoundException");
                Console.WriteLine(e.Message);
                throw;
            }
            catch (System.AggregateException ae)
            {
                // More than one of the above exceptions were triggered.
                // Deal with the exception here, and/or rethrow at your discretion.
                Console.WriteLine("AggregateException");
                Console.WriteLine(ae.Message);
                throw;
            }

            // Decrypts secret using the associated KMS CMK.
            // Depending on whether the secret is a string or binary, one of these fields will be populated.
            if (response.SecretString != null)
            {
                secret = response.SecretString;

                dynamic jsonSecret = JsonConvert.DeserializeObject(secret);
                LambdaLogger.Log("User Name: " + Convert.ToString(jsonSecret.username).Substring(0, 3) + "*****");
                LambdaLogger.Log("Password: " + Convert.ToString(jsonSecret.password).Substring(0, 3) + "*****");
            }
            else
            {
                memoryStream = response.SecretBinary;
                StreamReader reader = new StreamReader(memoryStream);
                string decodedBinarySecret = System.Text.Encoding.UTF8.GetString(Convert.FromBase64String(reader.ReadToEnd()));

                dynamic jsonSecret = JsonConvert.DeserializeObject(decodedBinarySecret);
                Console.WriteLine("User Name (decodedBinarySecret): " + Convert.ToString(jsonSecret.username).Substring(0, 3) + "*****");
                Console.WriteLine("Password (decodedBinarySecret): " + Convert.ToString(jsonSecret.password).Substring(0, 3) + "*****");
            }

            return secret;

            // Your code goes here.
        }
    }
}

**Comment by klaytaybai** [comment]
Hi @1ds14te050manoj, please follow my advice about async programming in your previous issue.  If you don't, you will continue to see errors.  You may also want to confirm that you are using the correct VPC Endpoint with the appropriate policies set up.  I see your code has two (one commented out).

**Comment by 1ds14te050manoj** [comment]
Thank you @klaytaybai . I will try this and get back to you once resolved.

**Comment by cidthecoatrack** [comment]
The referenced issue is #1423
