### ISSUE TITLE
AWSConfigs.EndpointDefinition null reference exception

### ISSUE THREAD

**Issue by mgkeen** [aws/aws-sdk-net#1460]
## Context
I'm trying to alter the endpoint definitions so i can run my app locally using `localstack`. I followed the documentation here (https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html#config-setting-awsendpointdefinition). But i'm getting a null reference exception.

## Expected Behavior
Set AWSConfigs.EndpointDefinition to the json file as provided here: https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/endpoints.json
It should load up the endpoint definitions

## Current Behavior
Get a null reference exception with the following stack trace:
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
    at Amazon.Internal.RegionEndpointProviderV2.RegionEndpoint.ReadEndpointFile(Stream stream)
    at Amazon.Internal.RegionEndpointProviderV2.RegionEndpoint.LoadEndpointDefinitionFromFilePath(String path)
    at Amazon.Internal.RegionEndpointProviderV2.RegionEndpoint.LoadEndpointDefinitions(String endpointsPath)
    at Amazon.Internal.RegionEndpointProviderV2.RegionEndpoint.LoadEndpointDefinitions()
    at Amazon.Internal.RegionEndpointProviderV2.RegionEndpoint.GetBySystemName(String systemName)
    at Amazon.Internal.RegionEndpointProviderV2.GetRegionEndpoint(String regionName)
    at Amazon.RegionEndpoint.get_InternedRegionEndpoint()
    at Amazon.RegionEndpoint.GetEndpointForService(String serviceName, Boolean dualStack)
    at Amazon.Runtime.ClientConfig.GetUrl(RegionEndpoint regionEndpoint, String regionEndpointServiceName, Boolean useHttp, Boolean useDualStack)
    at Amazon.Runtime.ClientConfig.DetermineServiceURL()
    at Amazon.Runtime.Internal.DefaultRetryPolicy..ctor(IClientConfig config)
    at Amazon.Runtime.AmazonServiceClient.BuildRuntimePipeline()
    at Amazon.Runtime.AmazonServiceClient..ctor(AWSCredentials credentials, ClientConfig config)
    at Amazon.S3.AmazonS3Client..ctor(RegionEndpoint region)
```

## Possible Solution
I had a look through the code that is in the call stack. It appears that if `EndpointDefintion` is specified then it assumes the file is v2 and uses `RegionEndpointProviderV2`. As seen here:
https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/RegionEndpoint/RegionEndpoint.cs#L218
Looking at `RegionEndpointProviderV2` and `RegionEndpointProviderV3` it appears as though the example file that is provided in the documentation is in V3 format, as it has a `providers` object at the root and not an `endpoints` one?

## Steps to Reproduce (for bugs)
```
    class Program
    {
        static void Main(string[] args)
        {
            AWSConfigs.EndpointDefinition = "endpoints.json";
            var s3Client = new AmazonS3Client(RegionEndpoint.APSoutheast2);
        }
    }
```
With the referenced example file copied into the output directory.

**Comment by klaytaybai** [comment]
Hi @mgkeen, can you please try using the ServiceURL property?  I think this should help you to use localstack.

**Comment by mgkeen** [comment]
@klaytaybai just to clarify, is that the ServiceURL on the AmazonS3Config? Thanks for pointing me towards it. That should unblock me, but it isn't ideal. 
I didn't want to have to change my production code (in this case introduce configuration) purely to serve the purpose of running locally. The `EndpointsDefinition` was ideal because it meant no code change in my production context.
