### ISSUE TITLE
Ec2 instance automation with boto3 lambda function 

### ISSUE THREAD

**Issue by prasadsai528** [aws/aws-sdk-net#1512]
Log output
START RequestId: c12b67de-618c-4682-a5bd-268d53989066 Version: $LATEST
[ERROR] NameError: name 'us' is not defined
Traceback (most recent call last):
  File "/var/lang/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/var/lang/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/lambda_function.py", line 4, in <module>
    ec2 = boto3.client('ec2', region_name=us-west-2)
END RequestId: c12b67de-618c-4682-a5bd-268d53989066
REPORT RequestId: c12b67de-618c-4682-a5bd-268d53989066	Duration: 3003.19 ms	Billed Duration: 3000 ms	Memory Size: 128 MB	Max Memory Used: 29 MB	
2020-01-29T11:49:30.760Z c12b67de-618c-4682-a5bd-268d53989066 Task timed out after 3.00 seconds


11:40:14
[ERROR] NameError: name 'us' is not defined Traceback (most recent call last):   File "/var/lang/lib/python3.7/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/lib/python3.7/imp.py", line 171, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 696, in _load   File "<frozen importlib._bootstrap>", line 677, in _load_u

11:40:15
START RequestId: 19e33008-ed05-4e10-a8bc-e758d194e8a8 Version: $LATEST

11:40:18
END RequestId: 19e33008-ed05-4e10-a8bc-e758d194e8a8

11:40:18
REPORT RequestId: 19e33008-ed05-4e10-a8bc-e758d194e8a8 Duration: 3003.17 ms Billed Duration: 3000 ms Memory Size: 128 MB Max Memory Used: 29 MB

11:40:18
2020-01-29T11:40:18.354Z 19e33008-ed05-4e10-a8bc-e758d194e8a8 Task timed out after 3.00 seconds

11:40:18
[ERROR] NameError: name 'us' is not defined Traceback (most recent call last):   File "/var/lang/lib/python3.7/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/lib/python3.7/imp.py", line 171, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 696, in _load   File "<frozen importlib._bootstrap>", line 677, in _load_u

11:41:15
START RequestId: 5a137b6e-72df-4df7-80ee-5ecf22c013be Version: $LATEST

11:41:18
[ERROR] NameError: name 'us' is not defined Traceback (most recent call last):   File "/var/lang/lib/python3.7/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/lib/python3.7/imp.py", line 171, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 696, in _load   File "<frozen importlib._bootstrap>", line 677, in _load_u

11:41:18
END RequestId: 5a137b6e-72df-4df7-80ee-5ecf22c013be

11:41:18
REPORT RequestId: 5a137b6e-72df-4df7-80ee-5ecf22c013be Duration: 3003.21 ms Billed Duration: 3000 ms Memory Size: 128 MB Max Memory Used: 29 MB

11:41:18
2020-01-29T11:41:18.426Z 5a137b6e-72df-4df7-80ee-5ecf22c013be Task timed out after 3.00 seconds

11:41:19
[ERROR] NameError: name 'us' is not defined Traceback (most recent call last):   File "/var/lang/lib/python3.7/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/lib/python3.7/imp.py", line 171, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 696, in _load   File "<frozen importlib._bootstrap>", line 677, in _load_u

11:41:29
START RequestId: eb68a1dd-0e32-4d3e-8d03-f9c45714e619 Version: $LATEST

11:41:32
[ERROR] NameError: name 'us' is not defined Traceback (most recent call last):   File "/var/lang/lib/python3.7/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/lib/python3.7/imp.py", line 171, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 696, in _load   File "<frozen importlib._bootstrap>", line 677, in _load_u

11:41:32
END RequestId: eb68a1dd-0e32-4d3e-8d03-f9c45714e619

11:41:32
REPORT RequestId: eb68a1dd-0e32-4d3e-8d03-f9c45714e619 Duration: 3003.14 ms Billed Duration: 3000 ms Memory Size: 128 MB Max Memory Used: 29 MB

11:41:32
2020-01-29T11:41:32.859Z eb68a1dd-0e32-4d3e-8d03-f9c45714e619 Task timed out after 3.00 seconds

11:41:33
[ERROR] NameError: name 'us' is not defined Traceback (most recent call last):   File "/var/lang/lib/python3.7/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/lib/python3.7/imp.py", line 171, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 696, in _load   File "<frozen importlib._bootstrap>", line 677, in _load_u

11:43:24
START RequestId: 5a137b6e-72df-4df7-80ee-5ecf22c013be Version: $LATEST

11:43:27
[ERROR] NameError: name 'us' is not defined Traceback (most recent call last):   File "/var/lang/lib/python3.7/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/lib/python3.7/imp.py", line 171, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 696, in _load   File "<frozen importlib._bootstrap>", line 677, in _load_u

11:43:27
END RequestId: 5a137b6e-72df-4df7-80ee-5ecf22c013be

11:43:27
REPORT RequestId: 5a137b6e-72df-4df7-80ee-5ecf22c013be Duration: 3003.21 ms Billed Duration: 3000 ms Memory Size: 128 MB Max Memory Used: 28 MB

11:43:27
2020-01-29T11:43:27.600Z 5a137b6e-72df-4df7-80ee-5ecf22c013be Task timed out after 3.00 seconds

11:43:27
[ERROR] NameError: name 'us' is not defined Traceback (most recent call last):   File "/var/lang/lib/python3.7/imp.py", line 234, in

**Comment by prasadsai528** [comment]
Resolved
