### ISSUE TITLE
STS Request ("/latest/api/token") gives 403 response when running .Net Core 3.0 or higher on EC2 instance with instance role

### ISSUE THREAD

**Issue by Andy-DFN** [aws/aws-sdk-net#1518]
Hi There,

We are trying to access secrets manager using AWS SDK for get secret value on a known valid ARN.

When running a very basic .Net Core 3.0 console application on a EC2 instance that has an iam role associated with it's instance, I get a 403 from the request to /latest/api/token when attempting to get credentials with which to perform request to secrets manager.

When I downgrade to .Net Core 2.2 and change nothing else about the application, it resolves fine and allows access the secrets.

When debugging locally, .Net Core 3.0 works correctly and allows access to secrets. The issue only presents itself when placed on an EC2 Instance with an associated instance role. No credentials are stored in/on the instance itself.

## Expected Behavior
When running the provided console application on the EC2 instance, the following output is expected. This output is also the output that is correctly shown when running the version of the console app built targetting .Net Core 2.2. (resources values have been redacted for security):

```
dotnet ConsoleApp3.0Test.dll
Hello World!
Attempting to connect to arn: {redacted}
Constructing secrets manager configuration options...
Constructing secrets manager provider ...
Loading secrets...
Getting {redacted} secret...
{redacted} is {expected value}
```

## Current Behavior
When running the provided console application on the EC2 instance, targetting .Net Core 3.0 or higher, the following exception is provided:

```
dotnet ConsoleApp3.0Test.dll
Hello World!
Attempting to connect to arn: {redacted}
Constructing secrets manager configuration options...
Constructing secrets manager provider ...
Loading secrets...
Unhandled exception. Amazon.Runtime.AmazonServiceException: Unable to get IAM se
curity credentials from EC2 Instance Metadata Service.
   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.FetchCredentials()
   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentials()
   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentialsAsync()
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionCont
ext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext exec
utionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext exec
utionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext e
xecutionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext e
xecutionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionCont
ext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext ex
ecutionContext)
   at ConsoleApp3._0Test.SecretsManagerConfigurationProvider.LoadAsync() in {user directory}\ConsoleApp3.0Test\Program.cs:line 111
   at ConsoleApp3._0Test.SecretsManagerConfigurationProvider.Load() in {user directory}\ConsoleApp3.0Test\Program.cs:line 107
   at ConsoleApp3._0Test.Program.Main(String[] args) in {user directory}\ConsoleApp3.0Test\Program.cs:line 36
```

When debugging through the AWS SDK, I found the issue was originating from the first call to /latest/api/token was returning with a HTTP status code of '403'. This results in the EnsureStatusCode method failing and then bubbles up to the exception you see above.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
1. Create EC2 instance with instance role which has permissions to peform "Get Secret Value" on the arn for a valid secret.
2. Run the provided .Net Core 3.0 console application on the EC2 instance.
[ConsoleApp3.0Test.zip](https://github.com/aws/aws-sdk-net/files/4147857/ConsoleApp3.0Test.zip)

## Context
This prevents us providing a new software release version which contains the update from .Net Core 2.2 to 3.0 and is a major show stopper for us.

## Your Environment
* AWSSDK.Core version used: 3.3.104.21
* AWSSDK.SecretsManager version used: 3.3.101.78
* Service assembly and version used: 
* Operating System and version: Microsoft Windows Server 2012 R2 Standard 6.3.9600 N/A Build 9600
* Visual Studio version: Microsoft Visual Studio Professional 2019 Version 16.4.3
* Targeted .NET platform: .Net Core 3.0

## .NET Core Info
* .NET Core version used for development: 3.1.101
* .NET Core version installed in the environment where application runs: 3.1.1
* Output of `dotnet --info`: 
```
dotnet --info
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c
.NET Core SDKs installed:
  No SDKs were found.
.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.All]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.App]
  Microsoft.AspNetCore.App 3.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.
App]
  Microsoft.NETCore.App 3.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.
App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.
App]

```
* Contents of project.json/project.csproj: 
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <RootNamespace>ConsoleApp3._0Test</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.SecretsManager" Version="3.3.101.78" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="3.1.1" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
  </ItemGroup>

</Project>

```

## Additional Notes

When running PowerShell for AWS and executing the command for Get Secret Value on the EC2 instance we get the values back correctly, so there is no issue with the permission with the role for the EC2 instance.

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
Thanks for reporting this.  I'm looking into reproducing it.

**Comment by klaytaybai** [comment]
I assume that you are just relying on the default credential chain to provide the instance role credentials for both your application code and the Powershell command, correct?

There is a chance that you don't have access to your metadata enabled.  If that were true, however, you shouldn't be able to use the Powershell command without specifying credentials.  You can read up more on [configuring your EC2 Instance Metadata here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html).

**Comment by klaytaybai** [comment]
I haven't been able to reproduce this yet with working metadata access and a role with a valid policy.

**Comment by AdamWillden** [comment]
@klaytaybai I am a colleague of @Andy-DFN 

Yes we are using the default credential chain.

My understanding is that we can do the following:

- run the same app compiled for 2.2 (on the same box) and it works
- run the equivalent code in powershell (on the same box) and it works

**Comment by klaytaybai** [comment]
Thanks for the confirmation.  Both should work.  

We're curious if maybe you have a firewall restriction that is limiting 3.0 executables?

**Comment by AdamWillden** [comment]
@klaytaybai certainly not knowingly. I did recall that something about configuring proxies changed in aspnetcore 3.0, so maybe there's something there. Will see if there's anything we can do to verify your suggestion (e.g. temporarily disable firewall)...

Thank you for looking into it. The fact you can't replicate does suggest a environmental issue but we don't get why 2.2 works but 3.0/3.1 doesn't.

We'll be back in touch. Thanks again

**Comment by Andy-DFN** [comment]
Just as a follow on to what @AdamWillden has said, @klaytaybai We will be looking into this further at the beginning of next week in which we will create a new environment with as few restrictions as possible to see if the issue persists on a more open instance.

If we still experience the issue we will get back to you with as much further information as we can. 

Many Thanks

**Comment by klaytaybai** [comment]
Closing due to inactivity.  Please reopen if you are still experiencing the issue

**Comment by AdamWillden** [comment]
@klaytaybai we have the same issue now in two of our environments which are configured up similarly.

I don't know why it wasn't checked before by those involved (seemed an obvious thing to check) but the 403 is being returned from our proxy. The question then is **why** is the request being proxied when we have set set `no_proxy` for `169.254.169.254 (metadata)` in both the WinHTTP and WinINet/IE stacks.

As I said previously, I'm aware that since aspnetcore 3.0 (https://github.com/dotnet/corefx/pull/37238) it now respects the the environment variables if they are set (but they are set correctly) only then if not set falling back on WinINet/IE style configuration.

In case it is relevant, which seems to me likely, please also see this change in aspnetcore 3.0: https://github.com/dotnet/corefx/pull/37333

We're actively trying to resolve this again now. Any thoughts/contributions would be appreciated.

**Comment by AdamWillden** [comment]
I should add I also tried this (https://github.com/dotnet/runtime/issues/1191#issuecomment-569300147) to unset the environment variables in code. This should have made it fall back on WinINet which I beklieve aspnetcore2.1 was using. But that seemed to make no difference.

**Comment by AdamWillden** [comment]
@klaytaybai, it appears as though @Andy-DFN can't reopen this.

**Comment by AdamWillden** [comment]
Okay, given the information I knew above (i.e. it's proxy related) I was already looking into how to configure the client to use the correct proxy info.

I have just made the following change to the code shared and made a non-proxied successful(!) request:

```c#
            var config = new AmazonSecretsManagerConfig()
            {
                RegionEndpoint = options.SecretsManagerRegionEndpoint,
            };

            // this fixed it ::
            config.SetWebProxy(HttpClient.DefaultProxy); 
            // this fixed it ^^

            _secretsManager = new AmazonSecretsManagerClient(config);
```

While I now have a way forward the question stands why did I need to make this change? When did this behaviour change?

**Comment by AdamWillden** [comment]
To follow up again, we got this change into our real IIS hosted web apps (not the console sample attached above). This changed the error but seemed the environment variables were then not being respected. We enabled loading the user profile (i.e https://github.com/dotnet/aspnetcore/issues/2057#issuecomment-310727908) which caused the system to function correctly by respecting the proxy environment variables.

**Comment by AdamWillden** [comment]
We also had another issue which would have only affected netcoreapp3.0 due to it's use of environment variables. Our `NO_PROXY` environment variable  was set to `169.254.169.254;local` which has now been changed to just `169.254.169.254` to not proxy the metadata endpoint. I believe I read that the values should be comma separated but our ops team had used a semi-colon.

I then re-ran the deployment without the code change above... and the requests now work.

There's something still a little strange I can't put my finger on but I think it's best to let sleeping dogs lie at this point!

**Comment by AdamWillden** [comment]
Please leave this closed.
