### ISSUE TITLE
Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead.

### ISSUE THREAD

**Issue by NinoFloris** [aws/aws-sdk-net#1534]
Aws sdk is doing synchronous reads on async calls

Full stack trace:
```
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.InvalidOperationException: Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.Read(Span`1 buffer)
   at Amazon.Runtime.Internal.Util.WrapperStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Amazon.Runtime.Internal.Util.PartialReadOnlyWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Amazon.Runtime.Internal.Util.WrapperStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Amazon.Runtime.Internal.Util.HashStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Amazon.Runtime.Internal.Util.ChunkedUploadWrapperStream.FillInputBuffer()
   at Amazon.Runtime.Internal.Util.ChunkedUploadWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Amazon.Runtime.Internal.Util.WrapperStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.<>c.<BeginReadInternal>b__43_0(Object <p0>)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at System.IO.Stream.CopyToAsyncInternal(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.StreamToStreamCopy.<CopyAsync>g__DisposeSourceAsync|0_0(Task copyTask, Stream source)
   at System.Net.Http.HttpContent.CopyToAsyncCore(ValueTask copyTask)
   at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendRequestContentWithExpect100ContinueAsync(HttpRequestMessage request, Task`1 allowExpect100ToContinueTask, HttpContentWriteStream stream, Timer expect100Timer, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RedirectHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)

```

Repro (configure `_client` first):
```cs
public class Foo {
    private class File
    {
       public long? Filesize { get;set; }   
    }
    
    AmazonS3Client _client;

    public async Task Upload(File file, Stream stream)
    {
        long effectiveLength = 0;
        if (file.Filesize != null) 
        {
            if (!stream.CanSeek)
                throw new ArgumentException("Unseekable streams have to pass in a file size"); 
            effectiveLength = stream.Length - stream.Position;
        }
        else 
        {
            effectiveLength = file.Filesize.Value;
        }

        var request = 
            new PutObjectRequest(
                AutoResetStreamPosition = stream.CanSeek,
                Key = getFullKey(file),
                BucketName = options.Bucket,
                ContentType = file.MediaType,
                InputStream = stream
            )
        request.Headers.ContentLength = effectiveLength;
        
        await _client.PutObjectAsync(request)
    }
}
```
Call `Upload` with a `Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream` e.g. by uploading a file via http to a controller action that will call `Upload`, anything from AspNetCore 3.0 and up will do. 

This is happening because none of the streams in `Amazon.Runtime.Internal.Util` actually override any of the Async methods (ReadAsync, BeginRead); those will call the sync versions by default.

Related https://github.com/aws/aws-sdk-net/issues/675

**Comment by NinoFloris** [comment]
@normj if you're serious about what's in your bio this should get some prio.

**Comment by normj** [comment]
@NinoFloris we are aware of the issue. This is also critical to get done for WASM Blazor support which is single threaded. We are working on a PR to update all of stream implementations to have an async implementation. I hope to give you an update on a release status soon.

**Comment by btecu** [comment]
Is there an update here? It looks like #1416 was adding `ReadAsync`, which is needed.

**Comment by oliverjanik** [comment]
How's this tracking? `Stream.ReadAsync` has existed since .NET 4.5 (released 8 years ago) and async is very much the norm these days. In fact I'd happily forgo sync versions if you only gave me async.

I'd really appreciate if you could elevate this library to be compatible with modern dotnet 👍

**Comment by Kralizek** [comment]
@ashishdhingra can we keep this one open?

**Comment by JordanBrobyn** [comment]
2 years later. Is there any plan to implement a proper fix for this or should we expect this to continue to be ignored?

**Comment by JordanBrobyn** [comment]
@normj Has any progress been made here to resolve the synchronous IO operations being perform in an async method?

**Comment by normj** [comment]
We are in the design stage of some pretty large fundamental low level SDK changes that would address reading the stream async. Hope to get designs out for public consumption soon.

In this case even in when the SDK switches to async read I still don't think you are going to be able to pass in the `Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream` directly. The SDK needs the stream to be seekable because we have to read the stream first to compute the AWS Signature for authentication and then reset the stream back to the initial position for upload.

**Comment by samueldjack** [comment]
Any further news on this? I've just run into the same problem mentioned above.

> In this case even in when the SDK switches to async read I still don't think you are going to be able to pass in the `Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream` directly. The SDK needs the stream to be seekable because we have to read the stream first to compute the AWS Signature for authentication and then reset the stream back to the initial position for upload.

There's a straightforward way to avoid the problem you mention here, which is to call HttpContext.Request.EnableBuffering(). This wraps the stream and makes it seekable.

**Comment by peterrsongg** [comment]
I haven't tried with the aspnet core kestrel stream that you were using, but I did try with a blazor app, using .NET 8.0, which uses a BrowserFileStream (nonseekable) and instead of using the low-level s3 client I used the `TransferUtility`, which we added support for nonseekable stream uploads. [This is the release](https://www.nuget.org/packages/AWSSDK.S3/3.7.308.6) with the new support + a bug fix. The upload works and I checked that it was calling the `ReadAsync` method [here](https://github.com/aws/aws-sdk-net/blob/e7884ca9be71b710c93a50307049d1c434c1752d/sdk/src/Core/Amazon.Runtime/Internal/Util/WrapperStream.cs#L352).

We can't fix this in the low-level s3 client because as Norm said, we need the stream to be seekable because we have to read the stream first to compute the AWS Signature for authentication and then reset the stream back to the initial position for upload. However since we buffer the stream if it is nonseekable in the Transfer Utility and use a multi-part upload your use case works when using the Transfer Utility. Do you mind trying to use the Transfer Utility instead.?

**Comment by oliverjanik** [comment]
Can we kill the bot on this fundamental issue? Will it keep taking this issue for closure every 5 days?

**Comment by normj** [comment]
Resolving as because the SDK does use implement `ReadAsync` in it's wrapper streams and the http request logic is using `ReadAsync`.
