### ISSUE TITLE
Exception on BatchWrite<T>.AddPutItems

### ISSUE THREAD

**Issue by nicollaas94** [aws/aws-sdk-net#1543]
tracker being released is not the latest one. make sure to release child trackers before releasing parent.

## Expected Behavior
Add the items

## Current Behavior
```
> Tracker being released is not the latest one. Make sure to release child trackers before releasing parent.

>    at Amazon.Util.CircularReferenceTracking.PopTracker(Tracker tracker)
   at Amazon.Util.CircularReferenceTracking.Tracker.Dispose(Boolean disposing)
   at Amazon.Util.CircularReferenceTracking.Tracker.Dispose()
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.PopulateItemStorage(Object toStore, ItemStorage storage, DynamoDBFlatConfig flatConfig, Boolean keysOnly, Boolean ignoreNullValues)
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.ObjectToItemStorageHelper(Object toStore, ItemStorageConfig config, DynamoDBFlatConfig flatConfig, Boolean keysOnly, Boolean ignoreNullValues)
   at Amazon.DynamoDBv2.DataModel.BatchWrite`1.AddPutItem(T item)
   at Amazon.DynamoDBv2.DataModel.BatchWrite`1.AddPutItems(IEnumerable`1 values)
   at AbilityMigration.Services.ProcessBatchService.FeedBatchWrite[T](List`1 batchContent) in C:\...\Services\ProcessBatchService.cs:line 95
```

## Steps to Reproduce (for bugs)
Hit ProcessAsync with multiple threads with a "batch" file containing a list of items to put.

I have seeing it throw this exception before the first "ExecuteAsync", so the problem is not a concurrency in erasing the batchWrites list

``` csharp

    public class ProcessBatchService
    {
        private readonly DynamoDBContext clientContext;
        private List<BatchWrite> batchWrites = new List<BatchWrite>();
        private int executions = 0;
        private static ReaderWriterLock rwl = new ReaderWriterLock();
        private int lockTimeout = 100; // 100ms should be more than enough for this requirement

        private int tempCounterForBugReport = 0;

        public ProcessBatchService(AmazonDynamoDBClient client)
        {
            this.clientContext = new DynamoDBContext(client);
        }

        public async Task ProcessAsync(Batch batch)
        {
            this.tempCounterForBugReport += batch.Content.Count;
            var type = batch.Content[0].GetType();

            switch (batch.Type)
            {
                case Batch.BatchType.A:
                    this.FeedBatchWrite<A>(batch.Content);
                    break;
                case Batch.BatchType.B:
                    this.FeedBatchWrite<B>(batch.Content);
                    break;
                case Batch.BatchType.C:
                    this.FeedBatchWrite<C>(batch.Content);
                    break;
                default:
                    break;
            }

            if (this.tempCounterForBugReport / 1000 > executions)
            {
                List<BatchWrite> listRef;
                List<Task> tasks;
                try
                {
                    rwl.AcquireWriterLock(lockTimeout);
                    executions++;
                    listRef = this.batchWrites.ToList();
                    tasks = listRef.ConvertAll(b => b.ExecuteAsync());
                    this.batchWrites = new List<BatchWrite>();
                }
                finally
                {
                    rwl.ReleaseWriterLock();
                }

                await Task.WhenAll(tasks);
                listRef = null;
            }
        }

        public async Task EnsureProcessed()
        {
            await Task.WhenAll(this.batchWrites.ConvertAll(b => b.ExecuteAsync()));
        }

        private void FeedBatchWrite<T>(List<DynamoAbilityBase> batchContent) where T : class, new()
        {
            BatchWrite<T> batchWrite;
            try
            {
                rwl.AcquireReaderLock(lockTimeout);
                batchWrite = this.batchWrites.FirstOrDefault(b => b.GetType() == typeof(BatchWrite<T>)) as BatchWrite<T>;

                if (batchWrite == default)
                {
                    batchWrite = this.clientContext.CreateBatchWrite<T>();
                    this.batchWrites.Add(batchWrite);
                }
                batchWrite.AddPutItems(batchContent.ConvertAll(t => t as T));
            }
            catch (System.InvalidOperationException ex)
            {
                Console.Error.WriteLine(ex.Message);
            }
            finally
            {
                rwl.ReleaseReaderLock();
            }

        }
    }


```

## Context
Trying to migrate multiple items to multiple tables into dynamoDb

## Your Environment
* AWSSDK.Core version used: 3.3.104.31
* Operating System and version: Windows 10 Enterprise version 10.0.17763
* Visual Studio version: Microsoft Visual Studio Professional 2019 Version 16.4.5
* Targeted .NET platform:  .Net Core 3.1

## .NET Core Info
Output of `dotnet --info`: 
``` text
 .NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  2.2.301 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by normj** [comment]
Looking at the `FeedBatchWrite` operation a read lock is acquired but it is doing mutations to the BatchWrite collection which is not thread safe and needs to be done within a write lock.
