### ISSUE TITLE
Error when initializing AmazonSimpleSystemsManagementClient

### ISSUE THREAD

**Issue by ezraexposito** [aws/aws-sdk-net#1554]
Getting a null reference exception when trying to initialize a AmazonSimpleSystemsManagementClient object. Using it as follows in 4.7.2 framework library being referenced by a web application:

var client = new AmazonSimpleSystemsManagementClient(new AmazonSimpleSystemsManagementConfig { RegionEndpoint = Amazon.RegionEndpoint.USEast1 });

The stack trace is:
   at Amazon.AWSConfigs.get_LoggingConfig() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\AWSConfigs.cs:line 416
   at Amazon.Runtime.ClientConfig..ctor() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\ClientConfig.cs:line 59
   at Amazon.SimpleSystemsManagement.AmazonSimpleSystemsManagementConfig..ctor() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Services\SimpleSystemsManagement\Generated\AmazonSimpleSystemsManagementConfig.cs:line 42
   at Microsoft.Configuration.ConfigurationBuilders.AwsSsmConfigBuilder3.ProcessConfigurationSection(ConfigurationSection configSection) in C:\Users\eexposito\Downloads\AwsSsmConfigBuilderPoC-master\AwsSsmConfigBuilderPoC-master\AwsSsmConfigBuilder\AwsSsmConfigBuilder3.cs:line 23
   at System.Configuration.Internal.InternalConfigHost.System.Configuration.Internal.IInternalConfigurationBuilderHost.ProcessConfigurationSection(ConfigurationSection configSection, ConfigurationBuilder builder)
   at System.Configuration.Internal.DelegatingConfigHost.ProcessConfigurationSection(ConfigurationSection configSection, ConfigurationBuilder builder)
   at System.Configuration.BaseConfigurationRecord.CallHostProcessConfigurationSection(ConfigurationSection configSection, ConfigurationBuilder configBuilder)

In the web.config have logging set to:
```
<aws region="us-east-1">
    <logging logTo="None" />
  </aws>
```

**Comment by klaytaybai** [comment]
Did you figure it out?
