### ISSUE TITLE
AmazonS3Client throws Argument exception when trying to fetch valid object

### ISSUE THREAD

**Issue by ciceroneves** [aws/aws-sdk-net#1590]
Sometimes, in my .net framework application, when it tries to get a file from S3 the S3Client is throwing the following error: **System.ArgumentException: An item with the same key has already been added. Key: accelerate**

## Expected Behavior
I expect the object for the key provided to be returned (considering it is present in the S3 bucket)

## Current Behavior
An exception is thrown with the following stacktrace
```
 Exception: System.ArgumentException: An item with the same key has already been added. Key: accelerate
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Amazon.RegionEndpoint.NewEndpoint(String systemName, String displayName)
   at Amazon.RegionEndpoint.GetBySystemName(String systemName)
   at Amazon.S3.Util.AmazonS3Uri..ctor(Uri uri)
   at Amazon.S3.Util.AmazonS3Uri..ctor(String uri)
   at Amazon.S3.Internal.AmazonS3KmsHandler.EvaluateIfSigV4Required(IRequest request)
   at Amazon.S3.Internal.AmazonS3KmsHandler.PreInvoke(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3KmsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointResolver.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3PostMarshallHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Marshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3PreMarshallHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.<>n__0[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
```

## Possible Solution
I have no idea what could be done to fix this. Seems like some concurrency issue but I am not doing any multi-thread op in when doing this call.

## Steps to Reproduce (for bugs)
This is the method I am using to get the files from S3
``` C#
public async Task<GetObjectResponse> FetchObject(string key, string bucketName)
{
    var getObjectRequest = new GetObjectRequest
    {
        BucketName = bucketName,
        Key = key
    };
    var response = await _s3Client.GetObjectAsync(getObjectRequest);

    return response;
}
```

## Context

I have an AspNetCore application that provides APIs to upload and retrieve objects from S3
The code snipped above is in the lowest layer of that service (located in a .NET Standard 2.0 lib)
The S3 client is a singleton during the application's life-cycle

## Your Environment

* AWSSDK.Core version used: AWSSDK.Core (3.3.31.9)
* Service assembly and version used: 
* Operating System and version: Windows Server 2016 Standard
* Visual Studio version: Visual Studio 2019 Version 16.5.3
* Targeted .NET platform: .NET Framework 4.7.2

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by ashishdhingra** [comment]
Hi @ciceroneves,

Thanks for reporting the issue. I tried to use the above code snippet, using both .NET core and .NET Framework as target frameworks, on Windows platform (AWS .NET SDK version 3.3.31.9). The code works fine and the issue could not be reproduced. Please confirm if this is no longer an issue.

Thanks,
Ashish

**Comment by coder-td-123456** [comment]
We saw this issue on multiple hosts getting the same S3 object. AWS .NET SDK version 3.3.31.7 on Linux. Only a small percentage of hosts saw this error, so seems to be a low likelihood of occurring.

```
{ ExceptionStr: "System.AggregateException: One or more errors occurred. (GetObject failed. See inner exception for failure details. Bucket: **REDACTED** GetAttemptTimeInMinutes: 0.0007605833333333334) ---> System.IO.IOException: GetObject failed. See inner exception for failure details. Bucket: **REDACTED** Key: **REDACTED**
 GetAttemptTimeInMinutes: 0.0007605833333333334 ---> System.ArgumentException: An item with the same key has already been added. Key: accelerate at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior) at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value) at Amazon.RegionEndpoint.NewEndpoint(String systemName, String displayName) at Amazon.RegionEndpoint.GetBySystemName(String systemName) at Amazon.S3.Util.AmazonS3Uri..ctor(Uri uri) at Amazon.S3.Util.AmazonS3Uri..ctor(String uri) at Amazon.S3.Internal.AmazonS3KmsHandler.EvaluateIfSigV4Required(IRequest request) at Amazon.S3.Internal.AmazonS3KmsHandler.PreInvoke(IExecutionContext executionContext) at Amazon.S3.Internal.AmazonS3KmsHandler.InvokeAsync[T](IExecutionContext executionContext) at Amazon.Runtime.Internal.PipelineHandler.InvokeAsync[T](IExecutionContext executionContext) at Amazon.Runtime.Internal.EndpointResolver.InvokeAsync[T](IExecutionContext executionContext) at Amazon.Runtime.Internal.PipelineHandler.InvokeAsync[T](IExecutionContext executionContext) at Amazon.S3.Internal.AmazonS3PostMarshallHandler.InvokeAsync[T](IExecutionContext executionContext) at Amazon.Runtime.Internal.PipelineHandler.InvokeAsync[T](IExecutionContext executionContext) at Amazon.Runtime.Internal.Marshaller.InvokeAsync[T](IExecutionContext executionContext) at Amazon.Runtime.Internal.PipelineHandler.InvokeAsync[T](IExecutionContext executionContext) at Amazon.S3.Internal.AmazonS3PreMarshallHandler.InvokeAsync[T](IExecutionContext executionContext) at Amazon.Runtime.Internal.PipelineHandler.InvokeAsync[T](IExecutionContext executionContext) at Amazon.Runtime.Internal.CallbackHandler.<>n__0[T](IExecutionContext executionContext) at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext) at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeAsync[T](IExecutionContext executionContext) at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext) at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext) at TheTradeDesk.AdPlatform.Shared.Amazon.S3Utility.PrivateGetObjectAsync(String bucket, String key, Stream stream, CancellationToken cancellationToken) in /builds/thetradedesk/ttd.common/src/AWS/TTD.Common.AWS/S3Utility.cs:line 2684 --- End of inner exception stack trace --- at TheTradeDesk.AdPlatform.Shared.Amazon.S3Utility.PrivateGetObjectAsync(String bucket, String key, Stream stream, CancellationToken cancellationToken) in /builds/thetradedesk/ttd.common/src/AWS/TTD.Common.AWS/S3Utility.cs:line 2716 at TheTradeDesk.AdPlatform.Shared.Amazon.S3Utility.GetObjectAsync(String bucket, String key, Stream stream, CancellationToken cancellationToken) in /builds/thetradedesk/ttd.common/src/AWS/TTD.Common.AWS/S3Utility.cs:line 1150 at TheTradeDesk.AdPlatform.Shared.Amazon.S3Utility.GetAndDecompressObjectAsync(String bucket, String key, Stream stream, CancellationToken cancellationToken) in /builds/thetradedesk/ttd.common/src/AWS/TTD.Common.AWS/S3Utility.cs:line 1206 at TheTradeDesk.AdPlatform.Shared.Amazon.S3Utility.GetAndDecompressObjectAsync(String bucket, String key, CancellationToken cancellationToken) in /builds/thetradedesk/ttd.common/src/AWS/TTD.Common.AWS/S3Utility.cs:line 1174 --- End of inner exception stack trace --- at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) at System.Threading.Tasks.Task`1.get_Result() at TheTradeDesk.AdPlatform.Shared.Caching.DiffCache.DiffCacheClientIndexFileManager.GetComponentIndex(String componentName, String s3Path, String indexFileS3Key, Int64 minutesSinceEpoch) in /home/bamboo/bamboo-agent-home/xml-data/build-dir/ADPLATFORM-REL9-BDI/AdPlatform/TTD/Common/DiffCache/TTD.Common.DiffCache.Consumer/DiffCacheClientIndexFileManager.cs:line 811", ExceptionStack: \{ Value: "1567675302", Count: 1 }
```
