### ISSUE TITLE
"Expected hash not equal to calculated hash" when using PutObjectAsync

### ISSUE THREAD

**Issue by Gr1mR3aver** [aws/aws-sdk-net#1593]
## Expected Behavior
PutObjectAsync Succeeds

## Current Behavior
PutObjectAsync fails with "Expected hash not equal to calculated hash"
StackTrace:    at Amazon.S3.Internal.AmazonS3ResponseHandler.CompareHashes(String etag, Byte[] hash)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.ProcessResponseHandlers(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)

## Steps to Reproduce (for bugs)

            Amazon.S3.Model.PutObjectRequest por = new Amazon.S3.Model.PutObjectRequest()
            {
                BucketName = <bucketName>,
                InputStream = <sourceStream>,
                Key = <targetFileKey>
            };

            por.Headers.ContentLength = <targetFileSize>;
            <s3client>.PutObjectAsync(por).GetAwaiter().GetResult();  <--- exception thrown

  

## Context
Attempting to upload a file extracted from a ZIP archive to S3 sourceStream is the output stream of the decompression algorithm from SharpCompress.

## Your Environment

* AWSSDK.Core version used: 3.3.106.14
* Visual Studio version: 16.5.2
* Targeted .NET platform: Core2.1

## .NET Core Info
* .NET Core version used for development: 2.1
* .NET Core version installed in the environment where application runs: 2.1
* Output of `dotnet --info`: don't know (lambda function)
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by gsfataviva** [comment]
FWIW I am seeing the same problem when using TransferUtility.UploadDirectoryAsync.

**Comment by ashishdhingra** [comment]
Hi @Gr1mR3aver,

Please confirm if this is still an issue. If yes, kindly advise if first persisting the file extracted from ZIP file to file system and then uploading to S3 works. I'm not sure if while decompression is in progress, the steam could be passed directly to S3, since the hash calculated while decompression is still in progress, might not be the expected hash of the final extracted file (just a wild guess).

Thanks,
Ashish

**Comment by maheshm7090** [comment]
Issue is not resolved, am using AWSSDK.S3 (3.5.1.7).
TransferUtility.UploadAsync throws error "Expected hash not equal to calculated hash"
