### ISSUE TITLE
AWS Chime is Giving Meeting ended when CreateAttendeeAsync

### ISSUE THREAD

**Issue by koni-a** [aws/aws-sdk-net#1618]
Please let me know if there is a better place to report Chime issues.

## Expected Behavior
when trying to call `CreateAttendeeAsync` User should add-in that meeting.

## Current Behavior
Calling `CreateAttendeeAsync` will occasionally throw a "Meeting Ended". This occurs when I am attempting to add  user in meeting.

## Steps to Reproduce (for bugs)
Create a Meeting, CreateAttendee for Joining Call,

## Your Environment
AWSSDK.Chime 3.3.107.18

**Comment by ashishdhingra** [comment]
Hi @koni-a,

Good afternoon.

I was trying to reproduce the issue invoking `CreateAttendeeAsync() `after creating a meeting. Calls to `CreateAttendeeAsync() `work fine for me. Please share the Amazon Chime service configuration, sample code and logs in order to further troubleshoot the issue. In case this is no longer an issue, please confirm it could be closed.

Thanks,
Ashish

**Comment by koni-a** [comment]
Hi Ashish,

I am using .Net Core to aws chime sdk,

Example : 
 I Created a meeting Request today, I am trying to access tomorrow to join the meeting that it is throwing error. i will repo to my github i will share with you.

**Comment by koni-a** [comment]
Sorry for the delay here i am attaching the code repo 

Repo : **https://github.com/koni-a/AWSChime**

gave the access to your id **"ashishdhingra"** 

Can you please add Client ID and Client Secret Key in WeatherForecastController.cs

Below are the endpoints 

Create Meeting :
Method: Get
Url: http://localhost:51468/weatherforecast/create

Join Attendee : 
Method: Get
Url: http://localhost:51468/weatherforecast/my/{meetingId}/{Name}

try to join Meeting after 15 Min


Below are the error message : 

Amazon.Chime.Model.NotFoundException: Meeting <meetingId> not found
 ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ExceptionHandler`1.Handle(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at ChimeVideoAPI.Controllers.WeatherForecastController.JoinMeeting(String meetingId, String name) in C:\MyWork\ChimeVideoAPI\ChimeVideoAPI\Controllers\WeatherForecastController.cs:line 81
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Accept: */*
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Host: localhost:51468
User-Agent: PostmanRuntime/7.26.5
Postman-Token: 6739d2c3-6007-41c9-8d44-5b328eefbd95

**Comment by ashishdhingra** [comment]
Hi @koni-a,

Good afternoon.

I was going through backlog and came across this issue. As per your reproduction steps, the attendee tries to join the meeting after 15 minutes and then `Meeting not found` exception is thrown. As per documentation at [Creating meetings with the Amazon Chime SDK](https://docs.aws.amazon.com/chime/latest/dg/mtgs-sdk-mtgs.html), a meeting automatically ends after a period of inactivity, such as the following:
- No audio connections are present in the meeting for more than five minutes.
- Less than two audio connections are present in the meeting for more than 30 minutes.
- Screen share viewer connections are inactive for more than 30 minutes.
- The meeting time exceeds 24 hours.

In your scenario, since there are no audio connections are present in the meeting for more than five minutes, the meeting might have ended automatically.

Hope this provides possible reasoning.

Thanks,
Ashish
