### ISSUE TITLE
AWS SDK And S3 Client Example doesn't work on Android device. Unity 2019.2.9f1

### ISSUE THREAD

**Issue by KAbakumov** [aws/aws-sdk-net#1630]
I am getting the following error when trying to run example scene on Android device:

```
2020-06-03 08:15:22.034 16403-16403/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.DefaultCompany.Test, PID: 16403
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.DefaultCompany.Test/com.unity3d.player.UnityPlayerNativeActivity}: java.lang.ClassNotFoundException: Didn't find class "com.unity3d.player.UnityPlayerNativeActivity" on path: DexPathList[[zip file "/data/app/com.DefaultCompany.Test-s-l-BzVmN-VN48UDpMgqbQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.DefaultCompany.Test-s-l-BzVmN-VN48UDpMgqbQ==/lib/arm, /data/app/com.DefaultCompany.Test-s-l-BzVmN-VN48UDpMgqbQ==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/product/lib]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3194)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.unity3d.player.UnityPlayerNativeActivity" on path: DexPathList[[zip file "/data/app/com.DefaultCompany.Test-s-l-BzVmN-VN48UDpMgqbQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.DefaultCompany.Test-s-l-BzVmN-VN48UDpMgqbQ==/lib/arm, /data/app/com.DefaultCompany.Test-s-l-BzVmN-VN48UDpMgqbQ==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1250)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3182)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

Tried to fix it according to https://github.com/aws/aws-sdk-net/issues/1128 by changing UnityPlayerNativeActivity  to UnityPlayerActivity in Android Manifest and got the following error:

```
2020-06-03 08:33:26.399 17241-17264/? E/Unity: ArgumentException: Object of type 'System.Object[]' cannot be converted to type 'UnityEngine.AndroidJavaObject[]'.
      at System.RuntimeType.CheckValue (System.Object value, System.Reflection.Binder binder, System.Globalization.CultureInfo culture, System.Reflection.BindingFlags invokeAttr) [0x00071] in <31c751c7f24e441c95072fa1e96928f2>:0 
      at System.Reflection.MonoMethod.ConvertValues (System.Reflection.Binder binder, System.Object[] args, System.Reflection.ParameterInfo[] pinfo, System.Globalization.CultureInfo culture, System.Reflection.BindingFlags invokeAttr) [0x00069] in <31c751c7f24e441c95072fa1e96928f2>:0 
      at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00011] in <31c751c7f24e441c95072fa1e96928f2>:0 
      at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <31c751c7f24e441c95072fa1e96928f2>:0 
```

## Expected Behavior
App runs correctly

## Current Behavior
App crashes on startup

## Steps to Reproduce (for bugs)
Create Unity APP,
Download archive from http://sdk-for-net.amazonwebservices.com/latest/aws-sdk-unity.zip
Add S3 unity package to your project
Open Example Scene
Run on Android
ER: App runs correctly
AR: App crashes

However it runs well in editor 

## Context
Using Unity 2019.2.9f1

## Your Environment

* AWSSDK.Core version used: aws-sdk-unity_3.3.750.0
* Service assembly and version used: 
* Operating System and version:  Android 10
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by derwaldgeist** [comment]
Did you get this resolved?

**Comment by KAbakumov** [comment]
No. But as far as I can see it is a known problem https://lhkmarcus.com/2020/04/05/how-to-use-aws-sdk-in-unity-2019/

**Comment by derwaldgeist** [comment]
Yes, I have seen that. These kind of problems are an indication to me that this SDK could need some more love on the Unity integration side, which is why I have raised the question in #1635 whether this Unity integration has a long-term support. Integrating an SDK that might break every once in a while and requires workarounds like those mentioned in the link above is not a way to go forward for us, so we need some clarity on its status.

**Comment by KAbakumov** [comment]
I ended up getting rid of AWS SDK and use REST API directly

**Comment by derwaldgeist** [comment]
@KAbakumov Same here. I'm now using signed HTTP POSTs, works.

**Comment by apatelcgs** [comment]
@KAbakumov @derwaldgeist how you are using http for s3, is there any documentation link ? i didn't found any

**Comment by derwaldgeist** [comment]
Here's some infos: https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-post-example.html

**Comment by jwvanderbeck** [comment]
The confusing AF signature bit with HTTP is why I wanted to use this in the first place.  Why the heck can't there be a simple way to connect these? All I want to do is have my app download some data from S3 using SOME form of authentication (even if it is just hardcoded in the source) so that the data isn't available to just anyone trolling the internet.

**Comment by derwaldgeist** [comment]
I ended up doing the HTTP request signing on server-side, where there's tons of libraries supporting this, like
https://www.npmjs.com/package/aws4
https://www.npmjs.com/package/fetch-aws4 (also works in a browser)

This works for me, since
- I am sending everything over a secure SSL connection and
- the user is logged in via our own user management

I copied this approach from this library
https://github.com/CulturalMe/meteor-slingshot
which is pretty popular in the Meteor ecosystem.

If you want to mimic the same in a pure Unity client application, you'd need to find the appropriate encryption libraries. This might as well be part of the .NET framework already, but I haven't researched the APIs in detail.

**Comment by derwaldgeist** [comment]
As you can see in #1635, nobody on the AWS side seems to care about this. Hence, I think using this AWS SDK for Unity is not the best idea.

**Comment by ashishdhingra** [comment]
Hi @derwaldgeist,

Starting with version 3.5 of the AWS SDK for .NET, projects using Unity 2018.1 or later should target the .NET Standard 2.0 release of the SDK. You can find additional information in the developer guide: [Unity support](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/unity-special.html) and [Migrating your Unity application](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/net-dg-v35.html#net-dg-v35-changes-unity).

Please try using the .NET Standard 2.0 version of the AWS SDK for .NET (version 3.5). 

Thanks,
Ashish
