### ISSUE TITLE
AWS Lambda & DynamoDB: Random ddbClient null exception

### ISSUE THREAD

**Issue by teemuniiranen** [aws/aws-sdk-net#1631]
DynamoDB calls return status code 400 randomly with exception `System.ArgumentNullException: Value cannot be null. (Parameter 'ddbClient')`.

## Current Behavior
```
System.ArgumentNullException: Value cannot be null. (Parameter 'ddbClient')
   at Amazon.DynamoDBv2.DocumentModel.Table..ctor(IAmazonDynamoDB ddbClient, TableConfig config)
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.GetUnconfiguredTable(String tableName)
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.GetTargetTable(ItemStorageConfig storageConfig, DynamoDBFlatConfig flatConfig, DynamoDBConsumer consumer)
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.SaveHelperAsync[T](T value, DynamoDBOperationConfig operationConfig, CancellationToken cancellationToken)
   at OurOwnCode.Infrastructure.Database.BaseRepository`1.SaveAsync
```

## Possible Solution
Could it be because of DynamoDB connection timeouts? Wrong implementation with AWS Lambda to reuse connections?

## Steps to Reproduce (for bugs)
Snippets from our configuration

DynamoDB client configuration:
``` c#
public static IServiceCollection ConfigureDynamoDB(this IServiceCollection services, IConfiguration configuration)
        {
            string stage = configuration.GetValue<string>("STAGE");

            var client = ConfigureAmazonDynamoDBClient(stage, configuration);
            var context = ConfigureDynamoDBContext(stage, client);
            services.AddScoped<IDynamoDBContext>(provider => context);
            services.AddScoped<IAmazonDynamoDB>(provider => client); 

            return services;
        }

private static AmazonDynamoDBClient ConfigureAmazonDynamoDBClient(string stage, IConfiguration configuration)
        {
                return new AmazonDynamoDBClient();
        }

private static DynamoDBContext ConfigureDynamoDBContext(string stage, AmazonDynamoDBClient client)
        {
            return new DynamoDBContext(
                client, new DynamoDBOperationConfig()
                {
                    TableNamePrefix = stage + "_",
                    IndexName = "GSI1"
                });
        }
    } 
```
Actual call that throws exception randomly:
```
public async Task SaveAsync(T item)
 {
     await _dynamoDbContext.SaveAsync(item);
 }
```
For some reason `IAmazonDynamoDB` inside `dynamoDBContext` is null?

## Your Environment
* AWSSDK.Core version used:
  * AWSSDK.DynamoDBv2 3.3.106.9
  * AWSSDK.Extensions.NETCore.Setup 3.3.101
* Targeted .NET platform:
  * AWS Lambda for .NET Core 3.1
  * Amazon.Lambda.AspNetCoreServer 5.1.1

**Comment by viktor-nikolaev** [comment]
Same problem

**Comment by teemuniiranen** [comment]
@viktor-nikolaev any progress? This is still happening in the same random fashion.

**Comment by viktor-nikolaev** [comment]
@teemuniiranen I changed service lifetime to singleton and it worked.

My configuration is:
```
      if (appOptions.DynamoDb.RunLocally)
      {
        services.AddSingleton<IAmazonDynamoDB>(_ =>
        {
          var clientConfig = new AmazonDynamoDBConfig
          {
            ServiceURL = appOptions.DynamoDb.LocalServiceUrl,
          };

          return new AmazonDynamoDBClient("x", "x", clientConfig);
        });
      }
      else
      {
        services.AddAWSService<IAmazonDynamoDB>();
      }
```

**Comment by teemuniiranen** [comment]
@viktor-nikolaev you encountered the same error with local DynamoDB (based on the code you provided)? This is happening with the Lambdas so the else block in your code.

**Comment by viktor-nikolaev** [comment]
@teemuniiranen the error was the same when I used `.AddScoped` for my local dynamo db

**Comment by ashishdhingra** [comment]
Hi @teemuniiranen,

I guess the solution provided by @viktor-nikolaev is correct to use AddSingleton(). I came across the article https://aws.amazon.com/blogs/developer/object-lifecycles/ which might be useful. Please let me know if solution to use AddSingleton() doesn't work, I will do some more research into it.

Thanks,
Ashish

**Comment by viktor-nikolaev** [comment]
@teemuniiranen moreover you use `.AddScoped()` but your `client` and `context` are actually singletons - you use the same reference in the lambda closure => so asp.net core will dispose these when a request ends.
If you still want to use scoped dependencies, try something like this:

```

public static IServiceCollection ConfigureDynamoDB(this IServiceCollection services, IConfiguration configuration)
{
	string stage = configuration.GetValue<string>("STAGE");

	
	services.AddScoped<IAmazonDynamoDB>(provider => ConfigureAmazonDynamoDBClient(stage, configuration)); 		
	services.AddScoped<IDynamoDBContext>(provider => = ConfigureDynamoDBContext(stage, provider.GetRequiredService<IAmazonDynamoDB>()));
	

	return services;
}

private static AmazonDynamoDBClient ConfigureAmazonDynamoDBClient(string stage, IConfiguration configuration)
{
	return new AmazonDynamoDBClient();
}

private static DynamoDBContext ConfigureDynamoDBContext(string stage, IAmazonDynamoDBClient client)
{
	return new DynamoDBContext(
		client, new DynamoDBOperationConfig()
		{
			TableNamePrefix = stage + "_",
			IndexName = "GSI1"
		});
}

```
