### ISSUE TITLE
S3 ListObjectsV2Async XmlException invalid character

### ISSUE THREAD

**Issue by KoalaBear84** [aws/aws-sdk-net#1633]
XmlException while doing a ListObjectsV2Async

## Expected Behavior

It should correctly handle the response of AWS API

## Current Behavior

It throws a XmlException
```
System.Xml.XmlException: '', hexadecimal value 0x1E, is an invalid character. Line 2, position 36698.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseNumericCharRefInline(Int32 startPos, Boolean expand, StringBuilder internalSubsetBuilder, Int32& charCount, EntityType& entityType)
   at System.Xml.XmlTextReaderImpl.ParseCharRefInline(Int32 startPos, Int32& charCount, EntityType& entityType)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at Amazon.Runtime.Internal.Transform.XmlUnmarshallerContext.ReadElement()
   at Amazon.Runtime.Internal.Transform.XmlUnmarshallerContext.Read()
   at Amazon.S3.Model.Internal.MarshallTransformations.S3UnmarshallerContext.Read()
   at Amazon.S3.Model.Internal.MarshallTransformations.ContentsItemUnmarshaller.Unmarshall(XmlUnmarshallerContext context)
   at Amazon.S3.Model.Internal.MarshallTransformations.ListObjectsV2ResponseUnmarshaller.UnmarshallResult(XmlUnmarshallerContext context, ListObjectsV2Response response)
   at Amazon.S3.Model.Internal.MarshallTransformations.ListObjectsV2ResponseUnmarshaller.Unmarshall(XmlUnmarshallerContext context)
   at Amazon.Runtime.Internal.Transform.XmlResponseUnmarshaller.Unmarshall(UnmarshallerContext input)
   at Amazon.S3.Model.Internal.MarshallTransformations.S3ReponseUnmarshaller.Unmarshall(UnmarshallerContext input)
   at Amazon.Runtime.Internal.Transform.ResponseUnmarshaller.UnmarshallResponse(UnmarshallerContext context)
   at Amazon.Runtime.Internal.Unmarshaller.UnmarshallResponse(UnmarshallerContext context, IRequestContext requestContext)
   at Amazon.Runtime.Internal.Unmarshaller.UnmarshallAsync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
```

## Possible Solution

No idea

## Steps to Reproduce (for bugs)

[ConsoleApp_20200607_1219_AWSReproduce.zip](https://github.com/aws/aws-sdk-net/files/4741838/ConsoleApp_20200607_1219_AWSReproduce.zip)

I can deliver the corresponding BucketName and ContinuationToken in private.

## Context

Cannot get objects of bucket

## Your Environment

* AWSSDK.Core version used: 3.3.107.8
* Service assembly and version used: AWSSDK.S3 3.3.111.9
* Operating System and version: W10 Pro 2004
* Visual Studio version: 2019 Preview 16.7.0 Preview 2.0
* Targeted .NET platform: .NET Core 3.1

## .NET Core Info

* .NET Core version used for development: .NET Core 3.1
* .NET Core version installed in the environment where application runs: .NET Core 3.1
* Output of `dotnet --info`:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.400-preview-015151
 Commit:    0755a9e324

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.400-preview-015151\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.800 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100-preview2-014569 [C:\Program Files\dotnet\sdk]
  3.1.400-preview-015151 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview9.19424.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0-preview3.19555.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0-preview3.19553.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

* Contents of project.json/project.csproj: 
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Core" Version="3.3.107.8" />
    <PackageReference Include="AWSSDK.S3" Version="3.3.111.9" />
    <PackageReference Include="log4net" Version="2.0.8" />
  </ItemGroup>

  <ItemGroup>
    <None Update="log4net.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
```

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by rodrigolzm** [comment]
Facing the same issue. 
Switched to ListObjectsAsync as a workaround. ListObjectsAsync works fine.

**Comment by KoalaBear84** [comment]
@NGL321 I can give you the details to reproduce, just tell me where to send it to.

Probably some 'strange' characters which are not encoded in correct XML, it maybe a specific encoding issue in .NET.

**Comment by ashishdhingra** [comment]
Hi @KoalaBear84,

Good evening.

After making slight modifications to your code to use ContinuationToken, as below, I'm unable to reproduce the issue:

```C#
using Amazon;
using Amazon.S3;
using Amazon.S3.Model;
using log4net;
using log4net.Config;
using log4net.Repository;
using System;
using System.IO;
using System.Reflection;
using System.Threading.Tasks;

namespace ConsoleApp_20200607_1219_AWSReproduce
{
    class Program
    {
        static async Task Main(string[] args)
        {
            Console.WriteLine("Started!");

            // Load configuration
            ILoggerRepository logRepository = LogManager.GetRepository(Assembly.GetEntryAssembly());
            XmlConfigurator.Configure(logRepository, new FileInfo("log4net.config"));

            // Couldn't get the app.config thing to work
            AWSConfigs.Logging = LoggingOptions.Log4Net | LoggingOptions.SystemDiagnostics;

            Console.WriteLine("Initializing AmazonS3Client...");

            string awsAccessKeyId = string.Empty;
            string secretAccessKey = string.Empty;

            try
            {
                AmazonS3Client client = new AmazonS3Client("<accessKey>", "<secretKey>", RegionEndpoint.USEast1);
                Console.WriteLine("Initialized AmazonS3Client");

                ListObjectsV2Request listObjectsV2Request = new ListObjectsV2Request
                {
                    BucketName = "test-bucket-1633",
                    MaxKeys = 2
                };

                ListObjectsV2Response response;
                do
                {
                    response = await client.ListObjectsV2Async(listObjectsV2Request);

                    // Process the response.
                    foreach (S3Object entry in response.S3Objects)
                    {
                        Console.WriteLine("key = {0} size = {1}",
                            entry.Key, entry.Size);
                    }
                    Console.WriteLine("Next Continuation Token: {0}", response.NextContinuationToken);
                    listObjectsV2Request.ContinuationToken = response.NextContinuationToken;
                } while (response.IsTruncated);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"ERROR: {ex}");
            }

            Console.WriteLine("Finished!");
            Console.ReadKey(intercept: true);
        }
    }
}
```

Please let me know if this is still an issue.

Thanks,
Ashish
