### ISSUE TITLE
Method not found RequestRetryMode Amazon.Runtime.IClientConfig.get_RetryMode()

### ISSUE THREAD

**Issue by Cephei** [aws/aws-sdk-net#1652]
## Description
```
var sharedCredentials = new SharedCredentialsFile();
CredentialProfile profile;
if (!sharedCredentials.TryGetProfile(ConfigurationManager.AppSettings["AWSProfileName"], out profile))
    throw new System.Exception();

var awsCredentials = profile.GetAWSCredentials(sharedCredentials);
....
new AmazonDynamoDBClient(awsCredentials, profile.Region);   <<<<<<<<< throws exception often, but not always
```

## Reproduction Steps
Sometimes it works, other times I'm getting: `System.MissingMethodException: 'Method not found: 'Amazon.Runtime.RequestRetryMode Amazon.Runtime.IClientConfig.get_RetryMode()'.'`

### Environment

* SDK Version: 
* Package Version: 3.3.107.19
* OS Info: Windows 10
* Build Environment: Visual Studio
* Targeted .NET Platform:  4.6.2

### Stack Trace
```
   at Amazon.DynamoDBv2.AmazonDynamoDBClient.CustomizeRuntimePipeline(RuntimePipeline pipeline) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Generated\_bcl45\AmazonDynamoDBClient.cs:line 247
   at Amazon.Runtime.AmazonServiceClient.BuildRuntimePipeline() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\AmazonServiceClient.cs:line 517
```

---

This is a :bug: bug-report

**Comment by Cephei** [comment]
Still getting this error randomly, but very often.
```
Method not found: 'Amazon.Runtime.RequestRetryMode Amazon.Runtime.IClientConfig.get_RetryMode()'.
{
  "ClassName": "System.MissingMethodException",
  "Message": "Method not found: 'Amazon.Runtime.RequestRetryMode Amazon.Runtime.IClientConfig.get_RetryMode()'.",
```

**Comment by Cephei** [comment]
https://github.com/aws/aws-toolkit-visual-studio/issues/71
https://github.com/aws/aws-lambda-dotnet/issues/619

**Comment by Cephei** [comment]
Most likely due to varied dependency versions across our solution. Will correct locally and test. Closing for now.
