### ISSUE TITLE
Amazon.DynamoDBv2.AmazonDynamoDBException : The security token included in the request is invalid.

### ISSUE THREAD

**Issue by antdimot** [aws/aws-sdk-net#1660]
## Description
When I'm using
``` c#
var table = Table.LoadTable( Client, "mytable" );
```
I have the following error:

 Error Message:
```
   Amazon.DynamoDBv2.AmazonDynamoDBException : The security token included in the request is invalid.
---- Amazon.Runtime.Internal.HttpErrorResponseException : Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
```
## Reproduction Steps
At runtime. I'm using `eu-west-1`

### Logs
```
  Error Message:
   Amazon.DynamoDBv2.AmazonDynamoDBException : The security token included in the request is invalid.
---- Amazon.Runtime.Internal.HttpErrorResponseException : Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
  Stack Trace:
     at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ExceptionHandler`1.Handle(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Signer.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointResolver.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Marshaller.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.AmazonServiceClient.Invoke[TResponse](AmazonWebServiceRequest request, InvokeOptionsBase options)
   at Amazon.DynamoDBv2.AmazonDynamoDBClient.DescribeTable(DescribeTableRequest request)
   at Amazon.DynamoDBv2.DocumentModel.Table.DescribeTable(String tableName)
   at Amazon.Runtime.Internal.Util.Cache`2.GetValueHelper(TKey key, Boolean& isStaleItem, Func`2 creator)
   at Amazon.Runtime.Internal.Util.Cache`2.GetValue(TKey key, Func`2 creator, Boolean& isStaleItem)
   at Amazon.DynamoDBv2.DocumentModel.Table.LoadTableInfo()
   at Amazon.DynamoDBv2.DocumentModel.Table.LoadTable(IAmazonDynamoDB ddbClient, TableConfig config)
   at Amazon.DynamoDBv2.DocumentModel.Table.LoadTable(IAmazonDynamoDB ddbClient, String tableName, DynamoDBEntryConversion conversion, Boolean isEmptyStringValueEnabled)
   at Amazon.DynamoDBv2.DocumentModel.Table.LoadTable(IAmazonDynamoDB ddbClient, String tableName)
   ...
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
----- Inner Stack Trace -----
   at Amazon.Runtime.HttpWebRequestMessage.GetResponse()
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
```
### Environment
* Package Version: dynamodb v 3.3.106.32
* OS Info: Windows 10
* Build Environment Visual Studio 2019
* Targeted .NET Platform:  .net core 3.1
---

This is a :bug: bug-report

**Comment by NGL321** [comment]
Hi @antdimot!

Thank you for reporting this. At first review this seems like it may be an issue with the way you manage your credentials locally.

[This post](https://aws.amazon.com/premiumsupport/knowledge-center/security-token-expired/) gives more information on standard mitigations and resolutions for credentials issues. It may help your fix.

If that doesn't resolve your problem, please leave another comment here with more information about how your credentials are configured locally, then someone can look into the issue!

😸 😷

**Comment by antdimot** [comment]
Hi @NGL321,

Thank you for availability.
I agree with you about a credential problem management, but I'm using aws cli configured with an IAM administrator user and It works well. I'm using dynamodb with another application built with aws node sdk which works well also.

**Comment by chiemeleakoma** [comment]
Hi, I am also experiencing the same error.  in my case, im using powershell 7.0.1 and using session token from environment variables.

in the same script block, data is returned from dynamodb using the cli and Read-S3object, but would fail on '$table.GetItem($hashKey)', pointing to the '$dbclient' as the source of error and the error message posted.

I have tried using the Initialize-AWSDefaults (with the same credentials saved to profile). i can make other aws calls, but will always fail on the dbclient call. like it uses a different set of credentials.

Note: I have also tried and it yielded same result
`$awsCred = Get-AWSCredential -ProfileName 'removed'
  $dbClient = New-Object Amazon.DynamoDBv2.AmazonDynamoDBClient($awsCred, $regionEndpoint)`

`try {
    Clear-Host
    #Import-Module AWSPowerShell
    #Import-Module AWS.Tools.Common
    $env:AWS_ACCESS_KEY_ID = 'removed'
    $env:AWS_SECRET_ACCESS_KEY = 'removed'
    $env:AWS_SESSION_TOKEN = 'removed'
    
    $data = aws dynamodb get-item --table-name 'removed' --key '{\"removed\": {\"S\": \"removed\"}}' # added fo verification, and returns results

    $s3_bucket = "removed" 
    $s3_def_src_path = "default" #$env:s3_def_src_path
    Read-S3Object -BucketName $s3_bucket -KeyPrefix $s3_def_src_path -Folder . # added fo verification, and returns results)
    
    $region='removed'
    $regionEndpoint=[Amazon.RegionEndPoint]::GetBySystemName("$region")
    
    $dbClient = New-Object Amazon.DynamoDBv2.AmazonDynamoDBClient($regionEndpoint)
    $table = [Amazon.DynamoDBv2.DocumentModel.Table]::LoadTable($dbClient, "removed")
    $hashKey = [Amazon.DynamoDBv2.DocumentModel.Primitive]::new('removed')
    $result = $table.GetItem($hashKey)
}
catch {
    $err = $_
}

`
4.0.5.0               AWS.Tools.Common
4.0.5.0               AWS.Tools.EC2
1.0.1.0               AWS.Tools.Installer
4.0.5.0               AWS.Tools.S3
4.0.6.0               AWSPowerShell
4.0.5.0               AWSPowerShell.NetCore
7.0.1                 Powershell

`Get-AWSPowerShellVersion

AWS Tools for Windows PowerShell
Version 4.0.6.0
Amazon Web Services SDK for .NET
Core Runtime Version 3.3.107.9
`

**Comment by antdimot** [comment]
Hi, I have just discovered that AWS SDK .NET could use a specific [profile credentials](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-creds.html).

The problem was that aws .net sdk used and aws cli were using a different credential profile, so I was using an old profile.

I have update it and now works well.

Another way for setting the right profile is using AWS Toolkit for Visual Studio (by AWS explorer panel).

**Comment by chiemeleakoma** [comment]
but i think there is a bug, because the above works if there is no session token in the profile.
it seems like the issue is usign Sessions token. the documentations also did not specify any thing for sessions tokens, just accesskey and secretkey.
i will look at the sdk .net profile credentials and see if it works

**Comment by ashishdhingra** [comment]
Hi @antdimot, 

Please confirm if the issue is resolved for you.

Thanks,
Ashish
