### ISSUE TITLE
MissingMethodException: Method not found: 'Amazon.Runtime.RequestRetryMode Amazon.Runtime.IClientConfig.get_RetryMode()'.

### ISSUE THREAD

**Issue by afajardomoya** [aws/aws-sdk-net#1662]
## Description
MissingMethodException: Method not found: 'Amazon.Runtime.RequestRetryMode Amazon.Runtime.IClientConfig.get_RetryMode()'.
This Exception gets throwed once I deployed my service to AWS. Locally it works fine.

## Reproduction Steps
1. I added the IAmazonS3 interface to the service collection on the Startup file: 
public class Startup
{
    public void ConfigureServices (IServiceCollection services)
    {
        ...
        services.AddAWSService`<IAmazonS3`>();
    }
}

2. I created a helper service to perform several S3 operations:

public class S3BucketService
{
    private readonly IAmazonS3 _client;

    public S3BucketService (IAmazonS3 client)
    {
        _client = client;
    }
    ...
}

3. I deployed my RESTful API using dotnet lambda tools, and serverless framework.
4. When I try to invoke my endpoint, I get the following error:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingMethodException: Method not found: 'Amazon.Runtime.RequestRetryMode Amazon.Runtime.IClientConfig.get_RetryMode()'.
   at Amazon.S3.AmazonS3Client.CustomizeRuntimePipeline(RuntimePipeline pipeline)
   at Amazon.Runtime.AmazonServiceClient.BuildRuntimePipeline()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Amazon.Extensions.NETCore.Setup.ClientFactory.CreateClient(Type serviceInterfaceType, AWSCredentials credentials, ClientConfig config)
   at Amazon.Extensions.NETCore.Setup.ClientFactory.CreateServiceClient(ILogger logger, Type serviceInterfaceType, AWSOptions options)
   at Amazon.Extensions.NETCore.Setup.ClientFactory.CreateServiceClient(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

### Logs
AWS CloudWatch logs:
2020-07-20T10:45:22.690-04:00
START RequestId: 605163f2-54ab-4694-8bec-267a28216942 Version: $LATEST

2020-07-20T10:45:22.694-04:00
[Information] Microsoft.AspNetCore.Hosting.Internal.WebHost: Request starting POST https://kj5axs4mjk.execute-api.us-west-2.amazonaws.com/development/api/v1/workstation/page application/json

2020-07-20T10:45:22.694-04:00
[Information] Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker: Route matched with {action = "GetAllByPageAction", controller = "Workstation"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.ActionResult`1[DynamoDB.Model.DynamoDBPage`1[API.Core.Models.Workstation]] GetAllByPageAction(DynamoDB.Model.Pageable) on controller API.Controllers.WorkstationController (API).

2020-07-20T10:45:22.742-04:00
[Information] AWSSDK: Found credentials using the AWS SDK's default credential search

2020-07-20T10:45:22.743-04:00
[Information] Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker: Executed action API.Controllers.WorkstationController.GetAllByPageAction (API) in 48.494ms 

2020-07-20T10:45:22.743-04:00
[Error] Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: An unhandled exception has occurred while executing the request. 

2020-07-20T10:45:22.747-04:00
[Information] Microsoft.AspNetCore.Hosting.Internal.WebHost: Request finished in 53.4468ms 500 text/html; charset=utf-8

2020-07-20T10:45:22.748-04:00
END RequestId: 605163f2-54ab-4694-8bec-267a28216942

2020-07-20T10:45:22.748-04:00
REPORT RequestId: 605163f2-54ab-4694-8bec-267a28216942 Duration: 54.39 ms Billed Duration: 100 ms Memory Size: 1024 MB Max Memory Used: 146 MB

 ### Environment

* SDK Version: 3
* Package Version:
     "AWSSDK.Core" Version="3.3.107.26"
     "AWSSDK.Extensions.NETCore.Setup" Version="3.3.101"
     "AWSSDK.S3" Version="3.3.111.27"
* OS Info: AWS Linux machine executor
* Build Environment: Terminal `dotnet`
 $ dotnet restore
 $ dotnet lambda package --configuration release --framework netcoreapp2.1 --output-package bin/release/netcoreapp2.1/api.zip

* Targeted .NET Platform:  .Net Core 2.1.1

---

This is a :bug: bug-report

**Comment by supriya-guin-incontact** [comment]
How did you resolve this bug? Do you have any solution for this? I am also facing the same issue.
