### ISSUE TITLE
WebException while uploading NodeJS Lambda from visual studio

### ISSUE THREAD

**Issue by vickyrathee** [aws/aws-sdk-net#1672]
## Description
Unable to upload Lambda function code using Visual Studio 2017 and AWS toolkit version 1.18.0.0. 
The dialog box logs just says `A WebException with status RequestCanceled was thrown.`. This is not helpful at all to understand what happened.

![image](https://user-images.githubusercontent.com/6106479/89496339-d2098080-d7d7-11ea-9df0-5db959357ea3.png)

When I read the logs in AppData, I found

```
2020-08-06 11:15:00,695 [1] INFO  Amazon.AWSToolkit.MobileAnalytics.SimpleMobileAnalytics - Queuing analytics event in local queue with timestamp: 08/06/2020 05:45:00
2020-08-06 11:15:00,695 [1] INFO  Amazon.AWSToolkit.MobileAnalytics.SimpleMobileAnalytics - Queuing analytics event in local queue with timestamp: 08/06/2020 05:45:00
2020-08-06 11:15:00,800 [1] INFO  Amazon.AWSToolkit.S3FileFetcher - Null/empty hosted files location override
2020-08-06 11:15:00,800 [1] INFO  Amazon.AWSToolkit.S3FileFetcher - Loading hosted file 'AccountTypes.xml' from local path 'C:\Users\UserName\AppData\Local/AWSToolkit/downloadedfiles/AccountTypes.xml'
2020-08-06 11:15:00,800 [1] INFO  Amazon.AWSToolkit.S3FileFetcher - Null/empty hosted files location override
2020-08-06 11:15:00,801 [1] INFO  Amazon.AWSToolkit.S3FileFetcher - Loading hosted file 'AccountTypes.xml' from local path 'C:\Users\UserName\AppData\Local/AWSToolkit/downloadedfiles/AccountTypes.xml'
2020-08-06 11:15:20,224 [32] INFO  Amazon.AWSToolkit.CommonUI.WizardFramework.AWSBaseWizardImpl - Querying KMS keys
2020-08-06 11:15:20,224 [1] INFO  Amazon.AWSToolkit.MobileAnalytics.SimpleMobileAnalytics - Queuing analytics event in local queue with timestamp: 08/06/2020 05:45:20
2020-08-06 11:15:21,614 [32] ERROR Amazon.AWSToolkit.CommonUI.WizardFramework.AWSBaseWizardImpl - Amazon.AWSToolkit.SimpleWorkers.QueryKMSKeysWorker, exception in Worker
Amazon.KeyManagementService.AmazonKeyManagementServiceException: User: arn:aws:iam::USER_ID:user/aws_cli is not authorized to perform: kms:ListKeys on resource: * ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpRequest.GetResponse()
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ExceptionHandler`1.Handle(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Signer.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointResolver.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Marshaller.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.AmazonServiceClient.Invoke[TResponse](AmazonWebServiceRequest request, InvokeOptionsBase options)
   at Amazon.KeyManagementService.AmazonKeyManagementServiceClient.ListKeys(ListKeysRequest request)
   at Amazon.AWSToolkit.SimpleWorkers.QueryKMSKeysWorker.Worker(Object sender, DoWorkEventArgs e)
```

This is a :bug: bug-report

How can I attach the policy to give kms:ListKeys access ? I searched in IAM an don't find any policy with name : kms

**Comment by ashishdhingra** [comment]
Hi @vickyrathee,

Good afternoon.

Could you please try publishing Node.js lambda using AWS CLI and see if it works? This looks like a policy issue with the credentials used to deploy lambda from Visual Studio.

Thanks,
Ashish

**Comment by vickyrathee** [comment]
I think this was due to older version of Node-v8 selected in my Lambda function from many years.
I created a new function with Node-v12 and that uploaded fine.

**Comment by ashishdhingra** [comment]
@vickyrathee I'm glad upgrading Node.js worked.
