### ISSUE TITLE
S3 client incorrectly handles Amazon.CognitoIdentity.Model.NotAuthorizedException

### ISSUE THREAD

**Issue by orinem** [aws/aws-sdk-net#1693]
## Description

The S3 client analyzes an Amazon.CognitoIdentity.Model.NotAuthorizedException as an S3 exception.  If the underlying HTTP status is 400 (Bad Request), SharedRetryForExceptionSync, SharedRetryForException and SharedRetryForExceptionSync in AmazonS3RetryPolicy all treat the Amazon.CognitoIdentity.Model.NotAuthorizedException as an S3 exception and end up calling BucketRegionDetector.DetectMismatchWithHeadBucketFallbackAsync().  This currently results in a null reference exception (see #1166).

This is not a duplicate of #1166 but a second issue that could cause the issue described in #1166.  There are other ways of causing the issue in #1166.

## Reproduction Steps

Setup a Cognito User Pool/Identity pool such that a user is denied by the Identity Pool rules.
Create CognitoAWSCredentials for such a user but do not call GetCredentialsAsync().
Attempt an S3 call using these credentials.

See #1166 and https://stackoverflow.com/questions/63604085/upload-file-to-s3-bucket-a-null-reference-exception-on-await-filetransferutilit/63700426

### Logs

Call stack
``` 	AWSSDK.S3.dll!Amazon.S3.Util.BucketRegionDetector.GetUsEast1ClientFromCredentials(Amazon.Runtime.ImmutableCredentials credentials) Line 138	C#
 	AWSSDK.S3.dll!Amazon.S3.Util.BucketRegionDetector.GetHeadBucketPreSignedUrl(string bucketName, Amazon.Runtime.ImmutableCredentials credentials) Line 115	C#
 	AWSSDK.S3.dll!Amazon.S3.Util.BucketRegionDetector.GetBucketRegionNoPipelineAsync(string bucketName, Amazon.Runtime.ImmutableCredentials credentials) Line 63	C#
 	AWSSDK.S3.dll!Amazon.S3.Util.BucketRegionDetector.DetectMismatchWithHeadBucketFallbackAsync(Amazon.S3.Util.AmazonS3Uri requestedBucketUri, Amazon.Runtime.AmazonServiceException serviceException, Amazon.Runtime.ImmutableCredentials credentials) Line 47	C#
 	AWSSDK.S3.dll!Amazon.S3.Internal.AmazonS3RetryPolicy.SharedRetryForExceptionAsync(Amazon.Runtime.IExecutionContext executionContext, System.Exception exception, System.Func<Amazon.Runtime.IExecutionContext, System.Exception, bool?> retryForExceptionSync, System.Func<Amazon.Runtime.IExecutionContext, System.Exception, bool> baseRetryForException) Line 57	C#
 	AWSSDK.S3.dll!Amazon.S3.Internal.AmazonS3RetryPolicy.RetryForExceptionAsync(Amazon.Runtime.IExecutionContext executionContext, System.Exception exception) Line 38	C#
 	AWSSDK.Core.dll!Amazon.Runtime.RetryPolicy.RetryAsync(Amazon.Runtime.IExecutionContext executionContext, System.Exception exception) Line 46	C#
 	AWSSDK.Core.dll!Amazon.Runtime.Internal.RetryHandler.InvokeAsync<Amazon.S3.Model.ListObjectsV2Response>(Amazon.Runtime.IExecutionContext executionContext) Line 137	C#
 	[Resuming Async Method]	
 	[Async Call Stack]	
 	[Async] AWSSDK.Core.dll!Amazon.Runtime.Internal.CallbackHandler.InvokeAsync<Amazon.S3.Model.ListObjectsV2Response>(Amazon.Runtime.IExecutionContext executionContext) Line 61	C#
 	[Async] AWSSDK.Core.dll!Amazon.Runtime.Internal.CallbackHandler.InvokeAsync<Amazon.S3.Model.ListObjectsV2Response>(Amazon.Runtime.IExecutionContext executionContext) Line 61	C#
 	[Async] AWSSDK.S3.dll!Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeAsync<Amazon.S3.Model.ListObjectsV2Response>(Amazon.Runtime.IExecutionContext executionContext) Line 57	C#
 	[Async] AWSSDK.Core.dll!Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync<Amazon.S3.Model.ListObjectsV2Response>(Amazon.Runtime.IExecutionContext executionContext) Line 53	C#
 	[Async] AWSSDK.Core.dll!Amazon.Runtime.Internal.MetricsHandler.InvokeAsync<Amazon.S3.Model.ListObjectsV2Response>(Amazon.Runtime.IExecutionContext executionContext) Line 65	C#

```
```
Amazon Information: 0 : The environment variable AWS_ENABLE_ENDPOINT_DISCOVERY was not set with a value.
Amazon Information: 1 : The environment variable AWS_MAX_ATTEMPTS was not set with a value.
Amazon Information: 2 : The environment variable AWS_RETRY_MODE was not set with a value.
Amazon Information: 0 : There is no endpoint_discovery_enabled set in the profile named 'default' in store Amazon.Runtime.CredentialManagement.CredentialProfileStoreChain
Amazon Information: 1 : There is no retry_mode set in the profile named 'default' in store Amazon.Runtime.CredentialManagement.CredentialProfileStoreChain
Amazon Information: 2 : There is no max_attempts set in the profile named 'default' in store Amazon.Runtime.CredentialManagement.CredentialProfileStoreChain
Amazon Information: 0 : Region found in profile 'default' in store Amazon.Runtime.CredentialManagement.CredentialProfileStoreChain
Amazon Information: 0 : Request metrics: AsyncCall = True; ServiceName = Amazon.CognitoIdentity; ServiceEndpoint = https://cognito-identity.us-east-2.amazonaws.com/; MethodName = GetIdRequest; RequestSize = 1692; StatusCode = OK; BytesProcessed = 63; AWSRequestID = 1005519b-099d-4fc7-858c-c2ed911ae231; HttpRequestTime = 00:00:00.3129675; ResponseUnmarshallTime = 00:00:00.0032607; ResponseProcessingTime = 00:00:00.0058294; ClientExecuteTime = 00:00:00.3410615; 
Amazon Error: 1 : An exception of type HttpErrorResponseException was handled in ErrorHandler., Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.HttpRequest.<GetResponseAsync>d__19.MoveNext() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_bcl\HttpWebRequestFactory.cs:line 395
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpRequest.<GetResponseAsync>d__19.MoveNext() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_bcl\HttpWebRequestFactory.cs:line 416
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.HttpHandler`1.<InvokeAsync>d__9`1.MoveNext() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:line 183
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.Unmarshaller.<InvokeAsync>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5`1.MoveNext()
Amazon Error: 2 : NotAuthorizedException making request GetCredentialsForIdentityRequest to https://cognito-identity.us-east-2.amazonaws.com/. Attempt 1., Amazon.CognitoIdentity.Model.NotAuthorizedException: The ambiguous role mapping rules for: cognito-idp.us-east-2.amazonaws.com/us-east-2_SG4sRsCRS denied this request. ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.HttpRequest.<GetResponseAsync>d__19.MoveNext() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_bcl\HttpWebRequestFactory.cs:line 395
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpRequest.<GetResponseAsync>d__19.MoveNext() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_bcl\HttpWebRequestFactory.cs:line 416
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.HttpHandler`1.<InvokeAsync>d__9`1.MoveNext() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:line 183
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.Unmarshaller.<InvokeAsync>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5`1.MoveNext()
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\HttpErrorResponseExceptionHandler.cs:line 115
   at Amazon.Runtime.Internal.ExceptionHandler`1.Handle(IExecutionContext executionContext, Exception exception) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ExceptionHandler.cs:line 38
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 204
   at Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5`1.MoveNext() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.<InvokeAsync>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.<InvokeAsync>d__2`1.MoveNext() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\EndpointDiscoveryHandler.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7`1.MoveNext() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CredentialsRetriever.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
Amazon Information: 3 : Request metrics: AsyncCall = True; ServiceName = Amazon.CognitoIdentity; ServiceEndpoint = https://cognito-identity.us-east-2.amazonaws.com/; MethodName = GetCredentialsForIdentityRequest; RequestSize = 1688; Exception = Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Amazon.Runtime.Internal.HttpRequest.<GetResponseAsync>d__19.MoveNext() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_bcl\HttpWebRequestFactory.cs:line 395\r\n   --- End of inner exception stack trace ---\r\n   at Amazon.Runtime.Internal.HttpRequest.<GetResponseAsync>d__19.MoveNext() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_bcl\HttpWebRequestFactory.cs:line 416\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Amazon.Runtime.Internal.HttpHandler`1.<InvokeAsync>d__9`1.MoveNext() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:line 183\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Amazon.Runtime.Internal.Unmarshaller.<InvokeAsync>d__3`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5`1.MoveNext(); StatusCode = BadRequest; AWSRequestID = 22170ce8-5b09-4ab5-95f6-4f6a4bbfc719; AWSErrorCode = NotAuthorizedException; HttpRequestTime = 00:00:00.1629854; ClientExecuteTime = 00:00:00.6380782; 
```

### Environment
* Exists in 3.5.7.0 from github master, stack trace is from below.

* Package Version: S3: 3.3.113.2
* OS Info: Windows 10
* Build Environment Visual Studio 2019
* Targeted .NET Platform:  4.8

## Resolution

Workaround: call GetCredentialsAsync() on the CognitoAWSCredentials object before every S3 call and deal with any exception.

Solution:  Do not attempt to analyze an Amazon.CognitoIdentity.Model.NotAuthorizedException as an S3 exception.  It is debatable whether such an exception should be turned into an S3 access denied exception.  That would require the S3 client have knowledge of Cognito exceptions which it currently does not have.

Perhaps it is as simple as insisting on the exception being an S3 exception before analyzing it in SharedRetryForExceptionSync.

```
        internal static bool? SharedRetryForExceptionSync(Runtime.IExecutionContext executionContext, Exception exception, 
            Runtime.Internal.Util.ILogger logger,
            Func<Runtime.IExecutionContext, Exception, bool> baseRetryForException)
        {
            var s3Exception = exception as AmazonS3Exception;
            if (s3Exception != null)
            {
                // Snip with serviceException renamed to s3Exception

```

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @orinem,

The PR https://github.com/aws/aws-sdk-net/pull/1694 is merged. Please verify if this is fixed in the latest version.

Thanks,
Ashish
