### ISSUE TITLE
ImportInstance returning null error unhandled

### ISSUE THREAD

**Issue by ksk1022** [aws/aws-sdk-net#170]
Hi,

When instantiating a DiskImageImporter and using it to call ImportInstance (below) , when I try to capture the importInstanceResponse, I receive the error that a null exception error is unhandled in the AWSSDK. Have you come across this issue at all? If I click continue on the error, the method executes and the ImportInstanceResponse is accessible, but we can't get the error to go away. 

public ImportInstanceResponse ImportInstance(string imageFilepath,
                                                     string fileFormat,
                                                     long? volumeSize,
                                                     string keyPrefix,
                                                     ImportLaunchConfiguration launchConfiguration,
                                                     ImportProgressCallback progressCallback)

**Comment by PavelSafronov** [comment]
Can you post the code that creates and invokes `DiskImageImporter`? Do you have a callstack for the exception?

**Comment by ksk1022** [comment]
Hi,

Sorry - was unable to post the code. But I found the cause of the error and now would like to report a possible bug. 

We are running code very similar to this blog post .NET example 
http://blogs.aws.amazon.com/net/post/Tx3NCNILLIB5M4P/Importing-VM-Images-and-Volumes-with-PowerShell-and-C
(almost identical) except we capture the ImportInstance response as a var. 

In our app config we have this set:
<aws>
logging logTo="Log4Net" logMetrics="true" logMetricsFormat="JSON" logResponses="OnError"
</aws>

and get this error below: 
log4net:ERROR Exception while rendering object of type [Amazon.Runtime.Internal.Util.LogMessage]
System.NullReferenceException: Object reference not set to an instance of an object.
   at Amazon.Runtime.Internal.Util.RequestMetrics.ToJSON() in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Internal\Util\Metrics.cs:line 376
   at Amazon.Runtime.Internal.Util.RequestMetrics.ToString() in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Internal\Util\Metrics.cs:line 321
   at System.Text.StringBuilder.AppendFormat(IFormatProvider provider, String format, Object[] args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at log4net.ObjectRenderer.DefaultRenderer.RenderObject(RendererMap rendererMap, Object obj, TextWriter writer)
   at log4net.ObjectRenderer.RendererMap.FindAndRender(Object obj, TextWriter writer)
log4net:ERROR Exception while rendering object of type [Amazon.Runtime.Internal.Util.LogMessage]
System.NullReferenceException: Object reference not set to an instance of an object.
   at Amazon.Runtime.Internal.Util.RequestMetrics.ToJSON() in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Internal\Util\Metrics.cs:line 376
   at Amazon.Runtime.Internal.Util.RequestMetrics.ToString() in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Internal\Util\Metrics.cs:line 321
   at System.Text.StringBuilder.AppendFormat(IFormatProvider provider, String format, Object[] args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at log4net.ObjectRenderer.DefaultRenderer.RenderObject(RendererMap rendererMap, Object obj, TextWriter writer)
   at log4net.ObjectRenderer.RendererMap.FindAndRender(Object obj, TextWriter writer)
2015-03-10 20:39:46 ERROR IOCompletionCallback



When we set the value to false and for logMetrics, the error is gone.

Can you let me know how this can be fixed? We would like to have our logMetrics on in the future.

Thanks,
Katharine

**Comment by PavelSafronov** [comment]
Thanks for the extra information. This is indeed a bug in the SDK. We're fixing this in our private repo and will include the change in the next SDK release.

**Comment by PavelSafronov** [comment]
Version 2.3.26 of the SDK has just been released and it contains this fix.
