### ISSUE TITLE
ObjectDisposedException thrown after many failed (and retried) async calls to WorkSpaces client

### ISSUE THREAD

**Issue by philipflesher** [aws/aws-sdk-net#1708]
## Description
Making many parallel calls to DescribeTags (among others) on a WorkSpaces client, an ObjectDisposedException will usually occur after several minutes during an attempt to await a DescribeTagsAsync response. We're currently experiencing throttling errors that cause a large number of exceptions and subsequent retries, but we don't expect exceptions or repeated calls to the client to cause any ODE's deep in the SDK when accessing a response object.

## Reproduction Steps

Difficult to reproduce without a lot of simultaneous calls to the WorkSpaces client, with associated failures and retries. I don't have any succinct repro at this time, but can work on developing one if this is not otherwise understood.

The specific line in our code that's awaiting the async response is as such (where `this.Client` is an `AmazonWorkSpacesClient`):

```
response = await this.Client.DescribeTagsAsync(request);
```

### Logs

Exception message is:
`"Cannot access a disposed object.\nObject name: 'SslStream'."`

Stack trace from the top, snipped from the calling point into the SDK for abbreviation:

```
An exception of type 'System.ObjectDisposedException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'Cannot access a disposed object.'
   at Amazon.Runtime.HttpWebRequestMessage.<GetResponseAsync>d__20.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.HttpHandler`1.<InvokeAsync>d__9`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.Unmarshaller.<InvokeAsync>d__3`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.<InvokeAsync>d__2`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.<InvokeAsync>d__2`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at [snipped-calling-code-method].<>c__DisplayClass5_0.<<GetTags>b__0>d.MoveNext() in /Users/[snipped-calling-code-file]:line 89
```

### Environment
* SDK Version: 3
* Package Version: AWSSDK.WorkSpaces 3.3.108.73 / AWSSDK.Core 3.3.107.12
* OS Info: OSX Catalina
* Build Environment VSCode + Terminal `dotnet`
* Targeted .NET Platform:  .NET Core 3.1

## Resolution
I would be happy to try to debug this further in our environment if I can get an assist with getting a local copy of the SDK source on a dev machine.

---

This is a :bug: bug-report

**Comment by philipflesher** [comment]
Additional information after more logging and debugging:

I can verify that the `AmazonWorkSpacesClient` object itself is not being disposed prior to receiving the `ObjectDisposedException`.

I'm able to repro this consistently enough that, with some help getting the source/symbols in my local environment, I could probably catch the problem down in the SDK.

**Comment by philipflesher** [comment]
Can anyone help me get better stack information on this one? I likely just need a pointer in the right direction getting the source linked into our VS Code project on OSX.

**Comment by ashishdhingra** [comment]
> Can anyone help me get better stack information on this one? I likely just need a pointer in the right direction getting the source linked into our VS Code project on OSX.

Hi @philipflesher,

Good afternoon.

I was going through backlog and came across this issue. Are you referring to debug to the SDK source to possibly identify the root cause of the issue given that you have a consistent reproduction? If yes, 
- You can clone this repository to your local environment
- Add existing projects `sdk/src/Core/AWSSDK.Core.NetStandard.csproj` and `sdk/src/Services/WorkSpaces/AWSSDK.WorkSpaces.NetStandard.csproj` to you solution
- Add reference to the above 2 projects in your project that has logic `this.Client.DescribeTagsAsync(request);`
- Debug the code.

I'm not sure how successfully it would work with VS Code on OSX, it works well with Visual Studio 2019 on Windows.

For troubleshooting on our side, would it be possible for you to share the sample code to reproduce the issue?

Thanks,
Ashish
