### ISSUE TITLE
Should I use single instance AmazonS3Client for whole web application or per web request create new instance

### ISSUE THREAD

**Issue by madhub** [aws/aws-sdk-net#1713]
## The Question
Should I use single instance AmazonS3Client for whole web application or per web request create new instance.

We are using AWS S3 SDK to upload objects inside our **ASP.NET Core web** application. 
* Is AmazonS3Client thread safe to use across requests processing in ASP.NET core Web application?
* Should we use **single instance** of **AmazonS3Client** or create **per request new instance** ?
* Should we register **AmazonS3Client**  in the ASP.NET DI system as **transient, scoped or singleton** ?.

### Environment
* SDK Version: AWSSDK.Core    3.3.103.70, AWSSDK.S3         3.3.108.4
* Package Version:
* OS Info: Linux
* Build Environment : Visual Studio 
* Targeted .NET Platform:  .NET Core 2.1

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @madhub,

As a general guidance, using the Singleton instance of AmazonS3Client class is a better approach as opposed to creating instance every time, since the credentials and profile resolution are done once. Also, if you use the `AWSSDK.Extensions.NETCore.Setup` to configure AWS services (example [here](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-netcore.html)), it creates the service client as Singleton. 

Hope this provides some guidance.

Thanks,
Ashish

**Comment by ArchanaNeog** [comment]
@ashishdhingra: I am using a single instance of AmazonS3Client for one of my web applications. It is noticed that if I make a concurrent request to PutObjectAsync, it throws an intermittent error. Below is the stack trace

InnerException StackTrace    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
      at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
      at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
      at System.Net.Security.SslState.ThrowIfExceptional()
      at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
      at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
      at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
      at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__47_1(IAsyncResult iar)
      at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of stack trace from previous location where exception was thrown ---
      at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
     at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RedirectHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   
Any input is really appreciated.

**Comment by ashishdhingra** [comment]
@ArchanaNeog Could you please share code snippet to investigate further? I'm not sure if this is an issue with the SDK since it appears to be SocketException. Also confirm of instantiating client for every request gives the same intermittent error.

Also note that objects which are Disposable should be disposed properly.

**Comment by madhub** [comment]
> 
> ## The Question
> 
> Should I use single instance AmazonS3Client for whole web application or per web request create new instance.
> 
> We are using AWS S3 SDK to upload objects inside our **ASP.NET Core web** application.
> 
>     * Is AmazonS3Client thread safe to use across requests processing in ASP.NET core Web application?
> 
>     * Should we use **single instance** of **AmazonS3Client** or create **per request new instance** ?
> 
>     * Should we register **AmazonS3Client**  in the ASP.NET DI system as **transient, scoped or singleton** ?.
> 
> 
> ### Environment
> 
>     * SDK Version: AWSSDK.Core    3.3.103.70, AWSSDK.S3         3.3.108.4
> 
>     * Package Version:
> 
>     * OS Info: Linux
> 
>     * Build Environment : Visual Studio
> 
>     * Targeted .NET Platform:  .NET Core 2.1
> 
> 
> This is a ❓ general question



> 
> 
> Hi @madhub,
> 
> As a general guidance, using the Singleton instance of AmazonS3Client class is a better approach as opposed to creating instance every time, since the credentials and profile resolution are done once. Also, if you use the `AWSSDK.Extensions.NETCore.Setup` to configure AWS services (example [here](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-netcore.html)), it creates the service client as Singleton.
> 
> Hope this provides some guidance.
> 
> Thanks,
> Ashish

What if we have use **temporary credentials** ? then single instance  created in the beginning won't work right ?.

Our application is **Asp.net Core web API** stores data to into **S3** , it receives **temporary S3 credentials and bucket from another service**.  What is the recommendation  for this use case ?.
Currently we create **AmazonS3Client** instance for   **temporary S3 credentials and bucket  combination**  and when token  expires we dispose AmazonS3Client instance . Is it right approach ?. 

Madhu

**Comment by madhub** [comment]
@ashishdhingra 
Thanks for the reply.

What if we have use **temporary credentials** ? then single instance  created in the beginning won't work right ?.

Our application is **Asp.net Core web API** which stores data to into **S3** , it receives **temporary S3 credentials and bucket** from **another service**.  What is the recommendation  for this use case ?.
Currently we create **AmazonS3Client** instance for   **temporary S3 credentials and bucket  combination**  and when token  expires we dispose AmazonS3Client instance .  In this approach we may have multiple instance of **AmazonS3Client**s (temp creds+bucket combination) in single ASP.NET core process , Is it right approach ?.  Is their better way to handle this ?


Madhu

**Comment by ashishdhingra** [comment]
@madhub The use of single instance versus instance per request depends on your application scenario, where single instance has added benefit of executing initialization tasks only once. In case your AmazonS3Client requests temporary credentials from another service, then using instance per request is recommended. In this case, if you decide to use single/shared instance, then extra step to refresh the credentials, if expired, is required. Hope this helps.

Thanks,
Ashish

**Comment by madhub** [comment]
One observation was if `AmazonS3Client.PutObjectAsync` function times out , API was throwing `"OperationCanceledException/TaskCanceledException ."` even though we did not use the cancellation tokens, after further investigation found that issue is due to .NET HttpClient behavior . It good to document this behavior in the API.

For information about the HttpClient API behavior here
https://github.com/dotnet/runtime/issues/21965 
https://github.com/dotnet/runtime/pull/2281
Update MSDN documentation on this issue https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.sendasync?view=net-5.0
