### ISSUE TITLE
Stream Exceptions When Calling AmazonS3Client.GetObject(GetObjectRequest)

### ISSUE THREAD

**Issue by alexleen** [aws/aws-sdk-net#1718]
## Description
We've been seeing some `System.ArgumentException: Stream was not readable.` and `System.IO.InvalidDataException: HashStream does not support base streams that are not capable of reading or writing` exceptions when calling `AmazonS3Client.GetObject(GetObjectRequest)` recently. They appear to be caused by internal SDK code.

### Logs
```
System.IO.InvalidDataException: HashStream does not support base streams that are not capable of reading or writing
   at Amazon.Runtime.Internal.Util.HashStream.ValidateBaseStream()
   at Amazon.Runtime.Internal.Util.HashStream`1..ctor(Stream baseStream, Byte[] expectedHash, Int64 expectedLength)
   at Amazon.Runtime.Internal.Util.MD5Stream..ctor(Stream baseStream, Byte[] expectedHash, Int64 expectedLength)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.ProcessResponseHandlers(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
```
```
System.IO.InvalidDataException: HashStream does not support base streams that are not capable of reading or writing
   at Amazon.Runtime.Internal.Util.HashStream.ValidateBaseStream()
   at Amazon.Runtime.Internal.Util.HashStream`1..ctor(Stream baseStream, Byte[] expectedHash, Int64 expectedLength)
   at Amazon.Runtime.Internal.Util.MD5Stream..ctor(Stream baseStream, Byte[] expectedHash, Int64 expectedLength)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.ProcessResponseHandlers(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext)
```
```
System.IO.InvalidDataException: HashStream does not support base streams that are not capable of reading or writing
   at Amazon.Runtime.Internal.Util.HashStream.ValidateBaseStream()
   at Amazon.Runtime.Internal.Util.HashStream`1..ctor(Stream baseStream, Byte[] expectedHash, Int64 expectedLength)
   at Amazon.Runtime.Internal.Util.MD5Stream..ctor(Stream baseStream, Byte[] expectedHash, Int64 expectedLength)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.ProcessResponseHandlers(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.AmazonServiceClient.Invoke[TResponse](AmazonWebServiceRequest request, InvokeOptionsBase options)
   at [call from our code]
```

### Environment
* SDK Version: ?
* Package Version: AWSSDK.S3 ~3.5.1.6~ 3.5.1
* OS Info: Windows 10
* Build Environment: Visual Studio
* Targeted .NET Platform: .NET 4.8

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @alexleen,

Good afternoon.

Thanks for reporting the issue. I will try to reproduce the issue. Also, it would be helpful if you could share some sample code to troubleshoot the issue.

Thanks,
Ashish

**Comment by alexleen** [comment]
We're disposing the response inside a for loop (for retries):
```
var request = new GetObjectRequest
{
    BucketName = bucketName,
    Key = key
};

for (int i = 0; i <= 5; i++)
{
    try
    {
        using (var response = _client.GetObject(request))
        {
            // download code...
        }
    }
    catch (...)
    {
        // ...
    }
}
```
but we don't refer to the response outside of the using - or any of its members.

**Comment by ashishdhingra** [comment]
Hi @alexleen,

Thanks for your reply.

Please help me with the following information:

- How frequently are you seeing this error in the log?
- Is the error logged after upgrading to AWSSDK.S3 3.5.1.6?
- Were you getting this error in previous version of AWSSDK.S3?

**Comment by alexleen** [comment]
Hey @ashishdhingra,

I apologize - we were actually seeing this with 3.5.1. We've since upgraded to 3.5.1.6. I'll update the issue above.

We saw the errors several times in quick succession one day last week, but haven't seen them since. I'll let you know if we see them again with 3.5.1.6.

**Comment by ashishdhingra** [comment]
@alexleen Thanks for the update. We can keep this issue open for few days and see if you see the exceptions again.
