### ISSUE TITLE
System.PlatformNotSupportedException: 'Property AllowAutoRedirect is not supported' when using AmazonS3Client PutObjectAsync in blazor wasm (.netstandard 2.1)

### ISSUE THREAD

**Issue by aaperfilev92** [aws/aws-sdk-net#1738]
## Description
I get the exception System.PlatformNotSupportedException: 'Property AllowAutoRedirect is not supported' when I try to send an object to S3. 
I work with .NETCore 3.1 Blazor app. AWSSDK.S3 version - 3.5.4. The code is called from .Net Standard 2.1 library
Exception:

```
System.PlatformNotSupportedException: Property AllowAutoRedirect is not supported.
  at System.Net.Http.HttpClientHandler.set_AllowAutoRedirect (System.Boolean value) <0x5095450 + 0x0000c> in <filename unknown>:0 
  at Amazon.Runtime.HttpRequestMessageFactory.CreateManagedHttpClient (Amazon.Runtime.IClientConfig clientConfig) [0x0002a] in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_netstandard\HttpRequestMessageFactory.cs:261 
  at Amazon.Runtime.HttpRequestMessageFactory.CreateHttpClient (Amazon.Runtime.IClientConfig clientConfig) [0x00008] in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_netstandard\HttpRequestMessageFactory.cs:234 
  at Amazon.Runtime.HttpRequestMessageFactory.CreateHttpClientCache (Amazon.Runtime.IClientConfig clientConfig) [0x00010] in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_netstandard\HttpRequestMessageFactory.cs:224 
  at Amazon.Runtime.HttpRequestMessageFactory.CreateHttpRequest (System.Uri requestUri) [0x000c5] in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_netstandard\HttpRequestMessageFactory.cs:170 
  at Amazon.Runtime.Internal.HttpHandler`1[TRequestContent].CreateWebRequest (Amazon.Runtime.IRequestContext requestContext) [0x0000e] in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:471 
  at Amazon.Runtime.Internal.HttpHandler`1[TRequestContent].InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x0003f] in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:148 
  at Amazon.Runtime.Internal.RedirectHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x00036] in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\RedirectHandler.cs:59 
  at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x00034] in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\Unmarshaller.cs:85 
  at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x0002d] in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Services\S3\Custom\Internal\AmazonS3ResponseHandler.cs:58 
  at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x000a7] in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:107 
  at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x00039] in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:61 
  at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x00063] in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\EndpointDiscoveryHandler.cs:75 
  at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x000d8] in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\EndpointDiscoveryHandler.cs:85 
  at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x00113] in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CredentialsRetriever.cs:98 
  at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x000e6] in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\RetryHandler\RetryHandler.cs:128 
  at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x00211] in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\RetryHandler\RetryHandler.cs:143 
  at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x00039] in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:61 
  at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x00039] in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:61 
  at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x0008f] in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Services\S3\Custom\Internal\AmazonS3ExceptionHandler.cs:62 
  at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x0008f] in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\ErrorCallbackHandler.cs:58 
  at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x00066] in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\MetricsHandler.cs:65 

```
## Reproduction Steps

```
var s3Config = new AmazonS3Config
{
    MaxErrorRetry = int.Parse(_awsS3Settings.MaxErrorRetry),
    RegionEndpoint = RegionEndpoint.USEast1,
    AllowAutoRedirect = false
};
using (var s3Client = new AmazonS3Client(_awsS3Settings.AccessKey, _awsS3Settings.SecretKey, s3Config))
{

    PutObjectResponse s3Response;
    await using (var stream = new MemoryStream(content))
    {
        s3Response = await s3Client.PutObjectAsync(new PutObjectRequest
        {
            InputStream = stream,
            ContentType = "image/jpeg",
            BucketName = _awsS3Settings.UploadedFilesBucketName,
            Key = $"{_awsS3Settings.TargetPath}/{fileKey}",
            CannedACL = S3CannedACL.BucketOwnerFullControl
        });
    }
}
```

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @aaperfilev92,

Good afternoon.

Looks like this is a limitation of Blazor runtime that it would not allow `AllowAutoRedirect`. At this point of time, there might not be a way to determine if we are running under Blazor runtime or some other platform. Does not explicitly setting the `AllowAutoRedirect` property works fine? Could you also share your use case which needs explicit setting of this property to `false`?

Thanks,
Ashish

**Comment by aaperfilev92** [comment]
Hi, @ashishdhingra,
Thank you very much for your response.
Explicit use of the `AllowAutoRedirect ` does not affect the operation in any way.
As stated in https://github.com/octokit/octokit.net/issues/2188#issuecomment-632924713 , setting the `AllowAutoRedirect ` helps avoid this problem.

Now I migrate my app to .NET 5 and now I don't get this exception. However, now there is another problem:

```
Exception: System.PlatformNotSupportedException: System.Security.Cryptography.Algorithms is not supported on this platform.
   at System.Security.Cryptography.HMACSHA256..ctor()
   at Amazon.Util.CryptoUtilFactory.CryptoUtil.CreateKeyedHashAlgorithm(SigningAlgorithm algorithmName)
   at Amazon.Util.CryptoUtilFactory.CryptoUtil.HMACSignBinary(Byte[] data, Byte[] key, SigningAlgorithm algorithmName)
   at Amazon.Runtime.Internal.Auth.AWS4Signer.ComputeKeyedHash(SigningAlgorithm algorithm, Byte[] key, Byte[] data)
   at Amazon.Runtime.Internal.Auth.AWS4Signer.ComposeSigningKey(String awsSecretAccessKey, String region, String date, String service)
   at Amazon.Runtime.Internal.Auth.AWS4Signer.ComputeSignature(String awsAccessKey, String awsSecretAccessKey, String region, DateTime signedAt, String service, String signedHeaders, String canonicalRequest, RequestMetrics metrics)
   at Amazon.Runtime.Internal.Auth.AWS4Signer.SignRequest(IRequest request, IClientConfig clientConfig, RequestMetrics metrics, String awsAccessKeyId, String awsSecretAccessKey)
   at Amazon.Runtime.Internal.Auth.S3Signer.Sign(IRequest request, IClientConfig clientConfig, RequestMetrics metrics, String awsAccessKeyId, String awsSecretAccessKey)
   at Amazon.S3.Internal.S3Signer.Sign(IRequest request, IClientConfig clientConfig, RequestMetrics metrics, String awsAccessKeyId, String awsSecretAccessKey)
   at Amazon.Runtime.Internal.Signer.SignRequest(IRequestContext requestContext)
   at Amazon.Runtime.Internal.Signer.PreInvoke(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Signer.InvokeAsync[PutObjectResponse](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeAsync[PutObjectResponse](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.<>n__0[PutObjectResponse](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.<InvokeAsync>d__2`1[[Amazon.S3.Model.PutObjectResponse, AWSSDK.S3, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604]].MoveNext()
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.<InvokeAsync>d__2`1[[Amazon.S3.Model.PutObjectResponse, AWSSDK.S3, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604]].MoveNext()
   at Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7`1[[Amazon.S3.Model.PutObjectResponse, AWSSDK.S3, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604]].MoveNext()
   at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1[[Amazon.S3.Model.PutObjectResponse, AWSSDK.S3, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604]].MoveNext()
   at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1[[Amazon.S3.Model.PutObjectResponse, AWSSDK.S3, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604]].MoveNext()
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1[[Amazon.S3.Model.PutObjectResponse, AWSSDK.S3, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604]].MoveNext()
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1[[Amazon.S3.Model.PutObjectResponse, AWSSDK.S3, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604]].MoveNext()
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.<InvokeAsync>d__1`1[[Amazon.S3.Model.PutObjectResponse, AWSSDK.S3, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604]].MoveNext()
   at Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5`1[[Amazon.S3.Model.PutObjectResponse, AWSSDK.S3, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604]].MoveNext()
   at Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1`1[[Amazon.S3.Model.PutObjectResponse, AWSSDK.S3, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604]].MoveNext()
```
