### ISSUE TITLE
Dynamo DB Client throws NullReferenceException when inserting / updating a document created from JSON containing an array with an empty string

### ISSUE THREAD

**Issue by swlasse** [aws/aws-sdk-net#1787]
## Description

We get a `NullReferenceException` when invoking `PutItemAsync` and `UpdateItemAsync` with a document created from JSON that includes a string array with an empty string.

## Reproduction Steps

We can reproduce the exception using the following sample code:

```
public class Program
{
    public static async Task Main(string[] _)
    {
        using var ddbClient = new AmazonDynamoDBClient();
        var ddbTable = Table.LoadTable(ddbClient, "FruitsTable");

        var item = new Fruit
        {
            Name = "orange",
            Reviews = new[]
            {
                "very tasty",
                "" // NOTE: Changing this to null resolves the null-ref
            }
        };
        var documentJson = JsonConvert.SerializeObject(item);
        var document = Document.FromJson(documentJson);

        // NOTE: With an empty string review in the Reviews array, this throws a null-ref
        await ddbTable.PutItemAsync(document);
    }
}

public class Fruit
{
    public string Name { get; set; }
    public string[] Reviews { get; set; }
}
```

### Logs
Exception details:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=AWSSDK.DynamoDBv2
  StackTrace:
   at Amazon.DynamoDBv2.Model.Internal.MarshallTransformations.AttributeValueMarshaller.Marshall(AttributeValue requestObject, JsonMarshallerContext context)
   at Amazon.DynamoDBv2.Model.Internal.MarshallTransformations.AttributeValueMarshaller.Marshall(AttributeValue requestObject, JsonMarshallerContext context)
   at Amazon.DynamoDBv2.Model.Internal.MarshallTransformations.PutItemRequestMarshaller.Marshall(PutItemRequest publicRequest)
   at Amazon.DynamoDBv2.Model.Internal.MarshallTransformations.PutItemRequestMarshaller.Marshall(AmazonWebServiceRequest input)
   at Amazon.Runtime.Internal.Marshaller.PreInvoke(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Marshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.<>n__0[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Amazon.DynamoDBv2.DocumentModel.Table.<PutItemHelperAsync>d__81.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApp2.DynamoDbDebug.Program.<Main>d__0.MoveNext()
```

### Environment

* SDK Version: `<PackageReference Include="AWSSDK.DynamoDBv2" Version="3.5.4.24" />`
* OS Info: Windows 10, 2004
* Build Environment: Visual Studio 2019 16.8.4
* Targeted .NET Platform:  netcoreapp3.1

## Resolution
If we change the empty string to a `null`  value instead, we can invoke `PutItemAsync` and `UpdateItemAsync` without issues. A temp. workaround for us has been to create a JSON converter that changes empty strings to `null` during creation of the document JSON.

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @swlasse,

Thanks for posting the issue.

Could you please try the same logic using AWS CLI and verify if it works there? This would help us isolate the root cause of the issue.

Thanks,
Ashish

**Comment by swlasse** [comment]
Hi again,

It seems to work fine from the CLI (version `aws-cli/2.1.22 Python/3.7.9 Windows/10 exe/AMD64`). For reference, here are the steps I took to verify the functionality in the CLI:

First, I declared the input file: `fruit.json`
```
{
  "Name": {
    "S": "orange"
  },
  "Reviews": {
    "L": [
      {
        "S": "very tasty"
      },
      {
        "S": ""
      }
    ]
  }
}
```
... and then I executed the following CLI command: `aws dynamodb put-item --table-name FruitsTable --item file://fruit.json` which completed successfully.

**Comment by ashishdhingra** [comment]
Reproducible using the code shared by user. Looks like .NET SDK does not accept empty string in List type.

The corresponding AWS CLI command `aws dynamodb put-item --table-name FruitsTable --item '{"Name": {"S": "orange"}, "Reviews": {"L": [{"S": "very tasty"}, {"S": ""}]}}'` works fine.

**Comment by ashishdhingra** [comment]
Hi @swlasse,

Good evening.

Based on our investigation, here are the findings:
- We found that there is a flag `Table.isEmptyStringValueEnabled` which controls whether empty values are allowed in DynamoDB List or not. This flag defaults to `false`.
- Changing the default value for `Table.isEmptyStringValueEnabled` flag to `true` would be a breaking change.
- There was an overload `Table LoadTable(IAmazonDynamoDB ddbClient, string tableName, DynamoDBEntryConversion conversion, bool isEmptyStringValueEnabled)` which allows setting `isEmptyStringValueEnabled`. However, this also requires value for `DynamoDBEntryConversion`.

In the commit https://github.com/aws/aws-sdk-net/commit/a0e6af3ed18f604a87e59c92325fff9bc0026262, we have added and overload for `Amazon.DynamoDBv2.DocumentModel.Table.LoadTable()` method which could be invoked with value for `isEmptyStringValueEnabled`, without specifying value for `DynamoDBEntryConversion`.

Please use the latest version of `AWSSDK.DynamoDBv2` package and modify your code to below:
```C#
public class Program
{
    public static async Task Main(string[] _)
    {
        using var ddbClient = new AmazonDynamoDBClient();
        var ddbTable = Table.LoadTable(ddbClient, "FruitsTable", true);

        var item = new Fruit
        {
            Name = "orange",
            Reviews = new[]
            {
                "very tasty",
                "" // NOTE: Changing this to null resolves the null-ref
            }
        };
        var documentJson = JsonConvert.SerializeObject(item);
        var document = Document.FromJson(documentJson);

        // NOTE: With an empty string review in the Reviews array, this throws a null-ref
        await ddbTable.PutItemAsync(document);
    }
}

public class Fruit
{
    public string Name { get; set; }
    public string[] Reviews { get; set; }
}
```

This would resolve your issue.

Thanks,
Ashish
