### ISSUE TITLE
Amazon.Runtime.AmazonClientException: Error calling AssumeRole for role arn:*

### ISSUE THREAD

**Issue by ArtemGontar** [aws/aws-sdk-net#1802]
## Description

Amazon.Runtime.AmazonClientException: Error calling AssumeRole for role arn:*
System.TimeoutException: The operation was canceled.

## Question

Now I stuck onto the issue TimeoutException with stack trace above. Here is the flow:
 - Try to renew credentials in STS
 - Call AssumeRoleAWSCredentials.GenerateNewCredentials()
 - Some magic happend on Amazon.Runtime part
 - Dotnet runtime add to request CancelationToken when creating HttpClient
 - Get error TaskCanceledException: The operation was canceled. (TimeoutException: The operation was canceled.)

I tried to investigate some information. While investigation I notice: no retries happend.
Look to source code:
https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Pipeline/RetryHandler/RetryPolicy.cs
Comment on 343 line:
//OperationCanceledException thrown by HttpClient not the CancellationToken supplied by the user.
//This exception can wrap at least IOExceptions, ObjectDisposedExceptions and should be retried
But I do not supply CancellationToken by myself.

Any suggestion on how I can avoid that issue?

## Expected Behavior
No error appears.
Credentials are refreshed

### Current Behavior
AmazonClientException appears
Credentials aren't refreshed

### Possible Solution
Add case to retry logic on aws-sdk source code

### Steps to Reproduce (for bugs)

Not reproduce by certain steps.
The service deployed in on-prem Kubernetes cluster and call STS service in AWS
One moment of time (maybe network connectivity is bad, some sts issue happened, etc) exception appear

### Context

```
/// <summary>
/// Init _assumeRoleAwsCredentialsManager from configuration
/// </summary>
/// <returns></returns>
private AssumeRoleAWSCredentials CreateAssumeRoleAwsCredentialsManager()
{
    var basicAwsCredentials = new BasicAWSCredentials(_configuration.AccessKeyId, _configuration.SecretKey);

    var roleSessionIdentifier = Guid.NewGuid().ToString();

    var options = new AssumeRoleAWSCredentialsOptions()
    {
        DurationSeconds = _configuration.SessionCredentialsDurationSeconds,

    };

    _eventSource.AssumeRoleAWSCredentialsServiceInitialized(roleSessionIdentifier, _configuration.SessionCredentialsDurationSeconds);

    return new AssumeRoleAWSCredentials(basicAwsCredentials, _configuration.RoleArn, roleSessionIdentifier, options);
}
```

```
public async Task<AWSCredentials> CreateCredentialsAsync()
{
    _assumeRoleAwsCredentialsManager.ClearCredentials();
    var credentials = await _assumeRoleAwsCredentialsManager.GetCredentialsAsync()
        .ConfigureAwait(false); // Here is the method which evaluate exception
    
    var sessionAwsCredentials = new SessionAWSCredentials(credentials.AccessKey, credentials.SecretKey, credentials.Token);

    return sessionAwsCredentials;
}
```

### Logs

Amazon.Runtime.AmazonClientException: Error calling AssumeRole for role arn:aws:iam:
---> System.TimeoutException: The operation was canceled.
---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken) --- End of inner exception stack trace --- at Amazon.Runtime.HttpWebRequestMessage.GetResponse() at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext)
at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext)
at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeSync(IExecutionContext executionContext)
at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext)
at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext)
at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext)
at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext)
at Amazon.Runtime.AmazonServiceClient.Invoke[TResponse](AmazonWebServiceRequest request, InvokeOptionsBase options)
at Amazon.SecurityToken.AmazonSecurityTokenServiceClient.Amazon.Runtime.SharedInterfaces.ICoreAmazonSTS.CredentialsFromAssumeRoleAuthentication(String roleArn, String roleSessionName, AssumeRoleAWSCredentialsOptions options)
--- End of inner exception stack trace ---
at Amazon.SecurityToken.AmazonSecurityTokenServiceClient.Amazon.Runtime.SharedInterfaces.ICoreAmazonSTS.CredentialsFromAssumeRoleAuthentication(String roleArn, String roleSessionName, AssumeRoleAWSCredentialsOptions options)
at Amazon.Runtime.AssumeRoleAWSCredentials.GenerateNewCredentials()
at System.Threading.Tasks.Task`1.InnerInvoke() at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location --- at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) --- End of stack trace from previous location --- at Amazon.Runtime.RefreshingAWSCredentials.GetCredentialsAsync() at <Some>.AmazonServices.AmazonS3Client.CredentialManager.AssumeRoleCredentialsManager.CreateCredentialsAsync() at <Some>.AmazonServices.AmazonS3Client.ClientManager.AmazonS3ClientBuilder.<InitLazyClient>b__9_0() at <Some>.AmazonServices.AmazonS3Client.AmazonS3Client.PerformOperationAsync[TResult](Func`2 action)
at Alsoview.Providers.AmazonS3Provider.ListObjectsAsync() in /builds/agent1/35/s/src/A/Providers/AmazonS3Provider.cs:line 50

### Environment

- SDK Version:
Nugets
AWSSDK.Extensions.NETCore.Setup Version="3.3.101"
AWSSDK.S3 Version="3.5.8.4"
AWSSDK.SecurityToken Version="3.5.1.49"

- OS Info: Linux/Kubernetes
- Build Environment: Terminal `dotnet`
- Targeted .NET Platform: netstandard2.0
- Visual Studio version: -
- Kubernetes version: 1.13
- Output of dotnet --info:
.NET SDK (reflecting any global.json):
```
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  1.0.4 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- .NET Core version installed in the environment where application runs: 5.0.100
---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @ArtemGontar,

Good morning.

Thanks for posting the guidance question. I will try to reproduce the issue. Could you please provide your environment details and sample code in the following format:



## Expected Behavior



## Current Behavior






## Possible Solution



## Steps to Reproduce (for bugs)





## Context



## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

Thanks,
Ashish

**Comment by ArtemGontar** [comment]
Thanks for the reaction, @ashishdhingra 
I did updates in the start comment.
I tried explaining it as clear as I could for now.
If any unclear - let me now

Best wishes, Artsiom

**Comment by ashishdhingra** [comment]
> Thanks for the reaction, @ashishdhingra
> I did updates in the start comment.
> I tried explaining it as clear as I could for now.
> If any unclear - let me now
> 
> > The timeout could occur for several reasons, may be during EC2 instance scale up/down operation. Does this issue happens at regular intervals?
> 
> No not regular one, but it reproduced not in EKS cluster, sorry for the disinformation, it is an on-prem location cluster
> 
> Best wishes, Artsiom

Hi @ArtemGontar,

Good morning.

I'm not sure what to suggest here since your application is deployed to on-prem Kubernetes cluster. Does this issue happens intermittently or at regular intervals? The error happens at `System.Net.Http.ConnectHelper`, which indicates the connectivity issue from container. While I'm not a container expert, may be troubleshooting the outbound rules for docker container might help. Just FYI, the link [Making requests using IAM user temporary credentials](https://docs.aws.amazon.com/AmazonS3/latest/userguide/AuthUsingTempSessionToken.html) provides a sample code on how to request credentials from STS service. Also, the logs state that `Error calling AssumeRole for role arn:aws:iam:`, is the role removed from logs intentionally?

Thanks,
Ashish
