### ISSUE TITLE
TransferUtility causing SignatureDoesNotMatch for files bigger than MinSizeBeforePartUpload

### ISSUE THREAD

**Issue by rdasilvaspotzer** [aws/aws-sdk-net#1803]
## Description

For context: my code was working as expected until a couple of days ago.
Since then I'm seeing errors when trying to upload files to a S3 bucket anything bigger than 16mb.

What I've tried:
1. Changed credentials of S3 access
2. Check any limits on ACLs, Firewall and ELBs
3. Updated nuget packages to most recent version

Finally I got down to the code and realized this 16mb threshold was the same of the default value for `MinSizeBeforePartUpload` on `TransferUtilityConfig`.

## Reproduction Steps
```C#
using (MultipartStream stream = new MultipartStream(fileStream, fileSize))
{
  var fileTransferUtilityRequest = new TransferUtilityUploadRequest
  {
      BucketName = bucketName,
      StorageClass = S3StorageClass.Standard,
      CannedACL = S3CannedACL.PublicRead,
      InputStream = stream,
      Key = filePath,
  };

  Dictionary<string, string> newHeaders = new Dictionary<string, string>()
      {
          { "Content-Type", "application/octet-stream; charset=utf-8" },
          { "Content-Length", fileSize.ToString() },
          { "Content-Disposition", @$"attachment; filename = ""{encodedFilename}""; filename *= ""{encodedFilename}""" },
          { "Cache-Control","no-cache" }
      };

  foreach (KeyValuePair<string, string> header in newHeaders)
  {
      fileTransferUtilityRequest.Headers[header.Key] = header.Value;
  }

  string accessKey = configuration["AWS:AccessKey"];
  string secretKey = configuration["AWS:SecretKey"];

  AmazonS3Config amazonS3Config = new AmazonS3Config()
  {
      RegionEndpoint = RegionEndpoint.GetBySystemName(configuration["AWS:Region"])
  };

  using (IAmazonS3 client = new AmazonS3Client(accessKey, secretKey, amazonS3Config))
  {
      using (TransferUtility transferUtility = new TransferUtility(client,new TransferUtilityConfig()
      {
          MinSizeBeforePartUpload = 16* 1024 * 1024 // this is the default value
      }))
      {
          await transferUtility.UploadAsync(fileTransferUtilityRequest);
      }
  }
}
```
### Logs
```JSON
{
  "Exception": {
    "Type": "Amazon.S3.AmazonS3Exception",
    "Message": "The request signature we calculated does not match the signature you provided. Check your key and signing method.",
    "StackTrace": "at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
                   at Amazon.Runtime.Internal.ExceptionHandler`1.Handle(IExecutionContext executionContext, Exception exception)
                   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
                   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
                   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
                   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
                   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
                   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
                   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
                   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
                   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
                   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
                   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeAsync[T](IExecutionContext executionContext)
                   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
                   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
                   at Amazon.S3.Transfer.Internal.MultipartUploadCommand.ExecuteAsync(CancellationToken cancellationToken)",
    "InnerExceptions": [
      {
        "Type": "Amazon.Runtime.Internal.HttpErrorResponseException",
        "Message": "Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.",
        "StackTrace": "   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)\r\n   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)\r\n   at Amazon.Runtime.Internal.RedirectHandler.InvokeAsync[T](IExecutionContext executionContext)\r\n   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)\r\n   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeAsync[T](IExecutionContext executionContext)\r\n   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)",
        "InnerExceptions": []
      }
    ]
  }
}

```

### Environment

* SDK Version: v3
* Package Version: 
AWSSDK.Core: 3.5.3.2
AWSSDK.Extensions.NETCore.Setup: 3.3.101
AWSSDK.S3: 3.5.8.8
AWSSDK.Transfer: 3.5.3
* OS Info: Windows 10
* Build Environment: Visual Studio
* Targeted .NET Platform:  .Net Core 3.1

## Resolution

For now I was able to increase the `MinSizeBeforePartUpload` to 200mb (200 * 1024 * 1024) to be able to upload files up to that size.

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @rdasilvaspotzer,

Good afternoon.

Could you please try removing the `Content-Length` header from your collection and verify if that resolves the issue?

Thanks,
Ashish

**Comment by rdasilvaspotzer** [comment]
Perfect, that's all I needed to change.
Thank you
