### ISSUE TITLE
IL2CPP Error with Microsoft.Bcl.AsyncInterfaces for Unity->iOS

### ISSUE THREAD

**Issue by ashovlin** [aws/aws-sdk-net#1810]
@ashovlin I am still having problems building with the version you provided. When I try to build I get the following error: 

This is happening with Unity 2020.2.4f1 with iOS as the build target and Api compatibility set to .NET Standard 2.0

```
Exception: IL2CPP error for type 'System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1' in assembly '/Users/halzate/Projects/YumeGO/Temp/StagingArea/Data/Managed/Microsoft.Bcl.AsyncInterfaces.dll'
System.NullReferenceException: Object reference not set to an instance of an object.
   at Mono.Cecil.GenericInstanceType..ctor(TypeReference type)
   at Unity.IL2CPP.GenericsCollection.Inflater.ConstructGenericType(GenericContext context, TypeDefinition typeDefinition, IEnumerable`1 genericArguments) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/Inflater.cs:line 71
   at Unity.IL2CPP.GenericsCollection.Inflater.InflateType(GenericContext context, GenericInstanceType genericInstanceType) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/Inflater.cs:line 25
   at Unity.IL2CPP.GenericsCollection.Inflater.InflateType(GenericContext context, TypeReference typeReference) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/Inflater.cs:line 11
   at Unity.IL2CPP.GenericsCollection.Inflater.ConstructGenericType(GenericContext context, TypeDefinition typeDefinition, IEnumerable`1 genericArguments) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/Inflater.cs:line 73
   at Unity.IL2CPP.GenericsCollection.Inflater.InflateType(GenericContext context, GenericInstanceType genericInstanceType) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/Inflater.cs:line 25
   at Unity.IL2CPP.GenericsCollection.GenericContextAwareVisitor.Visit(FieldReference fieldReference, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericContextAwareVisitor.cs:line 116
   at Unity.Cecil.Visitor.Visitor.Visit(Instruction instruction, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.Cecil.Visitor/Visitor.cs:line 365
   at Unity.IL2CPP.GenericsCollection.GenericContextAwareVisitor.Visit(Instruction instruction, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericContextAwareVisitor.cs:line 177
   at Unity.Cecil.Visitor.Visitor.Visit(MethodBody methodBody, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.Cecil.Visitor/Visitor.cs:line 348
   at Unity.Cecil.Visitor.Visitor.Visit(MethodDefinition methodDefinition, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.Cecil.Visitor/Visitor.cs:line 264
   at Unity.IL2CPP.GenericsCollection.GenericContextAwareVisitor.Visit(MethodDefinition methodDefinition, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericContextAwareVisitor.cs:line 76
   at Unity.Cecil.Visitor.Visitor.Visit(TypeDefinition typeDefinition, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.Cecil.Visitor/Visitor.cs:line 193
   at Unity.IL2CPP.GenericsCollection.GenericContextAwareVisitor.ProcessGenericType(PrimaryCollectionContext context, GenericInstanceType type, InflatedCollectionCollector generics, GenericInstanceMethod contextMethod) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericContextAwareVisitor.cs:line 229
   at Unity.IL2CPP.GenericsCollection.GenericContextAwareVisitor.Visit(FieldReference fieldReference, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericContextAwareVisitor.cs:line 119
   at Unity.Cecil.Visitor.Visitor.Visit(Instruction instruction, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.Cecil.Visitor/Visitor.cs:line 365
   at Unity.IL2CPP.GenericsCollection.GenericContextAwareVisitor.Visit(Instruction instruction, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericContextAwareVisitor.cs:line 177
   at Unity.Cecil.Visitor.Visitor.Visit(MethodBody methodBody, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.Cecil.Visitor/Visitor.cs:line 348
   at Unity.Cecil.Visitor.Visitor.Visit(MethodDefinition methodDefinition, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.Cecil.Visitor/Visitor.cs:line 264
   at Unity.IL2CPP.GenericsCollection.GenericContextAwareVisitor.Visit(MethodDefinition methodDefinition, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericContextAwareVisitor.cs:line 76
   at Unity.Cecil.Visitor.Visitor.Visit(TypeDefinition typeDefinition, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.Cecil.Visitor/Visitor.cs:line 193
   at Unity.IL2CPP.GenericsCollection.GenericContextAwareVisitor.ProcessGenericType(PrimaryCollectionContext context, GenericInstanceType type, InflatedCollectionCollector generics, GenericInstanceMethod contextMethod) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericContextAwareVisitor.cs:line 229
   at Unity.IL2CPP.GenericsCollection.GenericContextFreeVisitor.Visit(TypeDefinition typeDefinition, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericContextFreeVisitor.cs:line 26
   at Unity.Cecil.Visitor.Visitor.Visit(ModuleDefinition moduleDefinition, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.Cecil.Visitor/Visitor.cs:line 178
   at Unity.Cecil.Visitor.Visitor.Visit(AssemblyDefinition assemblyDefinition, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.Cecil.Visitor/Visitor.cs:line 172
   at Unity.IL2CPP.GenericsCollection.GenericsCollector.Collect(PrimaryCollectionContext context, ReadOnlyCollection`1 assemblies) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericsCollector.cs:line 13
   at Unity.IL2CPP.AssemblyConversion.PrimaryCollection.Steps.Global.GenericsCollection.ProcessAllItems(GlobalPrimaryCollectionContext context, ReadOnlyCollection`1 items) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/AssemblyConversion/PrimaryCollection/Steps.Global/GenericsCollection.cs:line 32
   at Unity.IL2CPP.AssemblyConversion.Steps.Base.GlobalScheduledStepFunc`3.WorkerWrapper(WorkItemData`3 workerData) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/AssemblyConversion/Steps.Base/GlobalScheduledStepFunc.cs:line 41
   at Unity.IL2CPP.Contexts.Scheduling.PhaseWorkScheduler`1.WorkerLoop(Object data) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/Contexts.Scheduling/PhaseWorkScheduler.cs:line 247
UnityEditorInternal.Runner.RunProgram (UnityEditor.Utils.Program p, System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:129)
UnityEditorInternal.Runner.RunManagedProgram (System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser, System.Action`1[T] setupStartInfo) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:65)
UnityEditorInternal.IL2CPPBuilder.RunIl2CppWithArguments (System.Collections.Generic.List`1[T] arguments, System.Action`1[T] setupStartInfo, System.String generatedCppOutputDirectory) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:793)
UnityEditorInternal.IL2CPPBuilder.ConvertPlayerDlltoCpp (UnityEditor.Il2Cpp.Il2CppBuildPipelineData data, System.String outputDirectory, System.Boolean platformSupportsManagedDebugging) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:765)
UnityEditorInternal.IL2CPPBuilder.Run () (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:598)
UnityEditorInternal.IL2CPPUtils.RunIl2Cpp (System.String tempFolder, System.String stagingAreaData, UnityEditorInternal.IIl2CppPlatformProvider platformProvider, System.Action`1[T] modifyOutputBeforeCompile, UnityEditor.RuntimeClassRegistry runtimeClassRegistry) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:269)
UnityEditor.iOS.PostProcessiPhonePlayer.CrossCompileManagedDlls (UnityEditor.iOS.PostProcessiPhonePlayer+BuildSettings bs, UnityEditor.iOS.PostProcessiPhonePlayer+ProjectPaths paths, UnityEditor.AssemblyReferenceChecker checker, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport buildReport) (at /Users/bokken/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs:908)
UnityEditor.iOS.PostProcessiPhonePlayer.PostProcess (UnityEditor.iOS.PostProcessiPhonePlayer+BuildSettings bs, UnityEditor.iOS.PostProcessiPhonePlayer+ProjectPaths paths, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport buildReport) (at /Users/bokken/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs:718)
UnityEditor.iOS.PostProcessiPhonePlayer.PostProcess (UnityEditor.iOS.PostProcessorSettings postProcessorSettings, UnityEditor.Modules.BuildPostProcessArgs args) (at /Users/bokken/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs:663)
UnityEditor.iOS.iOSBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at /Users/bokken/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/ExtensionModule.cs:45)
Rethrow as BuildFailedException: Exception of type 'UnityEditor.Build.BuildFailedException' was thrown.
UnityEditor.iOS.iOSBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at /Users/bokken/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/ExtensionModule.cs:49)
UnityEditor.Modules.DefaultBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at /Users/bokken/buildslave/unity/build/Editor/Mono/Modules/DefaultBuildPostprocessor.cs:29)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:337)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)
```

_Originally posted by @halzate93 in https://github.com/aws/aws-sdk-net/issues/1722#issuecomment-789244494_

**Comment by ashovlin** [comment]
@halzate93 - moved this over to a new, iOS-specific issue since that last one focused on the fact we weren't bundling the new dependencies with the SDK in the first place. 

I don't have immediate access to mac/iOS for testing, but let me try to find a colleague who does.

**Comment by halzate93** [comment]
Thanks @ashovlin,

Let me know if you need more information from my end.

**Comment by halzate93** [comment]
An update on this, I created an empty repro project just with the SDK and some test code and everything seems to work fine. I also removed AWS SDK from my project and the build works.

So it seems to be an interaction of the SDK with our project specifically, let me know if you guys have any pointers on your end as to how to debug it.

**Comment by halzate93** [comment]
Following up on this, I rolled back to 3.3 and everything seems to be working ok, I also had to use the TransferUtility class rather than the S3Client directly since for some reason the files being downloaded through 3.3 were coming incomplete.

**Comment by ganeshnj** [comment]
@halzate93 I made a [sample app](https://github.com/ganeshnj/aws-sdk-net-unity-sample) that targets both iOS and Android.

Do you have a simple example that throws the mentioned exception?
