### ISSUE TITLE
signature mismatch when uploading object to S3 with metadata value ending in space character.

### ISSUE THREAD

**Issue by sugacube** [aws/aws-sdk-net#1833]
## Description
Upload of an object to S3 with metadata value ending in space character fails with an exception :

The request signature we calculated does not match the signature you provided. Check your key and signing method

## Reproduction Steps

       	TransferUtilityUploadRequest request = new TransferUtilityUploadRequest() {
		BucketName = bucket,
		Key = key,
		AutoCloseStream = false,
		Timeout = new TimeSpan(0,5,0)
       	};
	request.Metadata.Add("DOCUMENT", "ABC ");   // value ending with space
        request.InputStream = str;
        util.Upload(request);

### Logs
ErrorMessage: The request signature we calculated does not match the signature you provided. Check your key and signing method. Stack:    at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ExceptionHandler`1.Handle(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Signer.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3KmsHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointResolver.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3PostMarshallHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Marshaller.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3PreMarshallHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.AmazonServiceClient.Invoke[TResponse](AmazonWebServiceRequest request, InvokeOptionsBase options)
   at Amazon.S3.AmazonS3Client.PutObject(PutObjectRequest request)
   at Amazon.S3.Transfer.Internal.SimpleUploadCommand.Execute()
   at Amazon.S3.Transfer.TransferUtility.Upload(TransferUtilityUploadRequest request)
   at ....

### Environment
* SDK Version: S3 3.3.113.1
* Package Version: S3 3.3.113.1
* OS Info: Windows 10 
* Build Environment other
* Targeted .NET Platform:  4.0 

## Resolution
-?

## Workaround 
Trim spaces from metadata key and value

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Reproducible using `AWSSDK.S3` version `3.7.0.14`.

```C#
using System.IO;
using Amazon.S3.Transfer;

namespace S3SpaceSig_Issue1833
{
    class Program
    {
        private static string bucket = "elasticbeanstalk-us-east-2-139480602983";
        private static string key = "testkey";
        private static string filePath = "/Users/ashdhin/Downloads/AwsHelpers.txt";

        static void Main(string[] args)
        {
            TransferUtility util = new TransferUtility();
            TransferUtilityUploadRequest request = new TransferUtilityUploadRequest()
            {
                BucketName = bucket,
                Key = key,
                AutoCloseStream = false
            };

            request.Metadata.Add("DOCUMENT", "ABC ");   // value ending with space
            request.InputStream = File.OpenRead(filePath);
            
            util.Upload(request);
        }
    }
}
```
