### ISSUE TITLE
unable to get Ssm params for aws/aws-dotnet-extensions-configuration .AddSystemsManager

### ISSUE THREAD

**Issue by WarrenFerrell** [aws/aws-sdk-net#1834]
## Description
calling IAmazonSimpleSystemsManagement.GetParametersByPathAsync from line 65 of [SystemsManagerProcessor in aws/aws-dotnet-extensions-configuration ](https://github.com/aws/aws-dotnet-extensions-configuration/blob/fe87a4c88b8819bdb705844b013f0c5efbbaf01d/src/Amazon.Extensions.Configuration.SystemsManager/Internal/SystemsManagerProcessor.cs) times out. Have an [issue posted there](https://github.com/aws/aws-dotnet-extensions-configuration/issues/88) but I have no way to tell which library or if I have something misconfigured.

## Reproduction Steps
Using Amazon.Lambda.RuntimeSupport to run a .NET 5 container. Running latest lambda, CDK, packages and latest amazonlinux. Increase lambda timeout to 300 seconds. Call GetParametersByPathAsync , times out after 30 seconds.

### Logs
```
2021-04-17T16:15:09.394-06:00	---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
2021-04-17T16:15:09.394-06:00	at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
2021-04-17T16:15:09.394-06:00	at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2021-04-17T16:15:09.394-06:00	at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2021-04-17T16:15:09.394-06:00	at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2021-04-17T16:15:09.394-06:00	at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
2021-04-17T16:15:09.394-06:00	at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2021-04-17T16:15:09.394-06:00	at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
2021-04-17T16:15:09.394-06:00	--- End of inner exception stack trace ---
2021-04-17T16:15:09.394-06:00	at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
2021-04-17T16:15:09.394-06:00	at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
2021-04-17T16:15:09.394-06:00	at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
2021-04-17T16:15:09.394-06:00	at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
2021-04-17T16:15:09.394-06:00	at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
2021-04-17T16:15:09.394-06:00	at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
2021-04-17T16:15:09.394-06:00	at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
2021-04-17T16:15:09.394-06:00	at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
2021-04-17T16:15:09.394-06:00	at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
2021-04-17T16:15:09.394-06:00	at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
2021-04-17T16:15:09.394-06:00	at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
2021-04-17T16:15:09.394-06:00	at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
2021-04-17T16:15:09.394-06:00	at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
2021-04-17T16:15:09.394-06:00	at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
2021-04-17T16:15:09.394-06:00	at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
2021-04-17T16:15:09.394-06:00	at Amazon.Extensions.Configuration.SystemsManager.Internal.SystemsManagerProcessor.GetParametersByPathAsync() in /sln/aws-dotnet-extensions-configuration/src/Amazon.Extensions.Configuration.SystemsManager/Internal/SystemsManagerProcessor.cs:line 71
2021-04-17T16:15:09.394-06:00	at Amazon.Extensions.Configuration.SystemsManager.Internal.SystemsManagerProcessor.GetDataAsync() in /sln/aws-dotnet-extensions-configuration/src/Amazon.Extensions.Configuration.SystemsManager/Internal/SystemsManagerProcessor.cs:line 49
2021-04-17T16:15:09.394-06:00	at Amazon.Extensions.Configuration.SystemsManager.SystemsManagerConfigurationProvider.LoadAsync(Boolean reload) in /sln/aws-dotnet-extensions-configuration/src/Amazon.Extensions.Configuration.SystemsManager/SystemsManagerConfigurationProvider.cs:line 116
2021-04-17T16:15:09.394-06:00	at Amazon.Extensions.Configuration.SystemsManager.SystemsManagerConfigurationProvider.Load() in /sln/aws-dotnet-extensions-configuration/src/Amazon.Extensions.Configuration.SystemsManager/SystemsManagerConfigurationProvider.cs:line 107
2021-04-17T16:15:09.394-06:00	at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
2021-04-17T16:15:09.394-06:00	at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
2021-04-17T16:15:09.394-06:00	at AbsenceSoft.AmazonRuntime.LambdaStarter.GetConfig() in /sln/src/shared/AbsenceSoft.AmazonRuntime/LambdaStarter.cs:line 38
2021-04-17T16:15:09.394-06:00	at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
2021-04-17T16:15:09.394-06:00	at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
2021-04-17T16:15:09.394-06:00	at System.Lazy`1.CreateValue()
2021-04-17T16:15:09.394-06:00	at System.Lazy`1.get_Value()
```

### Environment
* SDK Version: 3.7.0.1
* Package Version: AWSSDK.SimpleSystemsManagement 3.7.0.1
* * OS Info: AmazonLinux 
* Build Environment:  Terminal `dotnet publish` inside .net 5 SDK container
* * Targeted .NET Platform:  net5.0

## Resolution

---

This is a :bug: bug-report

**Comment by WarrenFerrell** [comment]
Issue turned out to be some reconfiguration of VPN subnet rules I was not made aware.

**Comment by gerdb42** [comment]
> Issue turned out to be some reconfiguration of VPN subnet rules I was not made aware of.

Could you please elaborate more on that subnet reconfiguration? I ran into the same issue after attaching my lambda to a custom VPC but have no clue what is wrong.

**Comment by WarrenFerrell** [comment]
@gerdb42 
IIRC, the VPC internal subnet masks did not correspond to the subnets configured for the security group the lambda was being deployed with. The result was that the lambda was trying to communicate with SSM via an IP that the VPC did not allow traffic on. 

If you are having trouble with cold start times. You might want to connect to SSM before deploying and insert config values 
into an environment variable(s). We had significant performance issues once we hit more than 40 SSM params (SSM params are grabbed in batches of 10).

**Comment by gerdb42** [comment]
@WarrenFerrell 
Thank you for sharing the information.

It turned out that my issue was a bit different: I had erroneously attached the public subnet directly to the VPC and thus created an ambiguous route. And every time the public subnet was chosen, packets were dropped.
