### ISSUE TITLE
Null reference exception in AWS4Signer.CanonicalizeHeaders

### ISSUE THREAD

**Issue by Petr-Kovalev** [aws/aws-sdk-net#1855]
## Description
Null reference exception thrown in the method AWS4Signer.CanonicalizeHeaders if the header value is null.

Likely was introduced by the Trim() method call in this commit, line 772: https://github.com/aws/aws-sdk-net/commit/51023cdd2a7ee03ac3cc80aa01da56a1fe8296d0#diff-c46726950b194a60976c5076f359cc1822792c609547c93377453e9c29013d0c

This exception is not thrown in AWSSDK.Core 3.7.0.19 and lower but happens on later versions.

## Reproduction Steps

**Command line project to reproduce this issue:**

```
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Amazon;
using Amazon.Runtime;
using Amazon.S3;
using Amazon.S3.Model;

namespace NullRef
{
    internal sealed class Program
    {
        private static async Task Main(string[] args)
        {
            await UpdateMetadata(
                "bucket-name",
                "File.txt",
                new Dictionary<string, string> {{"key", null}},
                CancellationToken.None);
        }

        private static async Task UpdateMetadata(
            string bucket,
            string fileKey,
            IDictionary<string, string> metadata,
            CancellationToken token)
        {
            using var client = new AmazonS3Client(
                new BasicAWSCredentials("", ""), 
                RegionEndpoint.EUCentral1);

            var request = new CopyObjectRequest
            {
                SourceBucket = bucket,
                DestinationBucket = bucket,
                SourceKey = fileKey,
                DestinationKey = fileKey,
                MetadataDirective = S3MetadataDirective.REPLACE
            };

            foreach (var item in metadata)
            {
                request.Metadata.Add(item.Key, item.Value);
            }

            await client.CopyObjectAsync(request, token);
        }
    }
}
```

**Stack trace:**

```
   at Amazon.Runtime.Internal.Auth.AWS4Signer.CanonicalizeHeaders(IEnumerable`1 sortedHeaders)
   at Amazon.Runtime.Internal.Auth.AWS4Signer.CanonicalizeRequestHelper(Uri endpoint, String resourcePath, String httpMethod, IDictionary`2 sortedHeaders, String canonicalQueryString, String precomputedBodyHash, IDictionary`2 pathResources, Int32 marshallerVersion, Boolean detectPreEncode)
   at Amazon.Runtime.Internal.Auth.AWS4Signer.CanonicalizeRequest(Uri endpoint, String resourcePath, String httpMethod, IDictionary`2 sortedHeaders, String canonicalQueryString, String precomputedBodyHash, IDictionary`2 pathResources, Int32 marshallerVersion, String service)
   at Amazon.Runtime.Internal.Auth.AWS4Signer.SignRequest(IRequest request, IClientConfig clientConfig, RequestMetrics metrics, String awsAccessKeyId, String awsSecretAccessKey)
   at Amazon.Runtime.Internal.Auth.S3Signer.Sign(IRequest request, IClientConfig clientConfig, RequestMetrics metrics, String awsAccessKeyId, String awsSecretAccessKey)
   at Amazon.S3.Internal.S3Signer.Sign(IRequest request, IClientConfig clientConfig, RequestMetrics metrics, String awsAccessKeyId, String awsSecretAccessKey)
   at Amazon.Runtime.Internal.Signer.SignRequest(IRequestContext requestContext)
   at Amazon.Runtime.Internal.Signer.PreInvoke(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Signer.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.<>n__0[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.<InvokeAsync>d__2`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.<InvokeAsync>d__2`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.<InvokeAsync>d__1`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NullRef.Program.<UpdateMetadata>d__1.MoveNext() in C:\NullRef\Program.cs:line 46`
```

### Environment

* Package Version: AWSSDK.Core 3.7.0.20+
* OS Info: Windows 10
* Build Environment: Visual Studio
* Targeted .NET Platform:  .NET 5

## Resolution

Proposed solution: add null reference check before the trim call like this: ?.Trim()

---

This is a :bug: bug-report

**Comment by ashovlin** [comment]
Thank you for the report. Agree this is reproducible, even for a simpler `PutObject` example too. We'll get started on a fix.

**Comment by Petr-Kovalev** [comment]
Would be great to have possible null value in headers be covered by unit tests. Thank you very much!

**Comment by ashovlin** [comment]
This should be fixed via 2e002513ba522592f5ddc4dfaf7729846b052df9 (with improved test coverage) which was released today in [version 3.7.36.1 of the SDK](https://github.com/aws/aws-sdk-net/releases/tag/3.7.36.1) ([version 3.7.0.23 of AWSSDK.Core](https://www.nuget.org/packages/AWSSDK.Core/3.7.0.23) and [version 3.7.0.24 of AWSSDK.S3](https://www.nuget.org/packages/AWSSDK.S3/3.7.0.24)).

**Comment by Petr-Kovalev** [comment]
Great, turned our code back to the latest AWSSDK versions. Thanks a lot!

**Comment by ashishdhingra** [comment]
Closing the issue.
