### ISSUE TITLE
SQS Client SendMessageBatchAsync Broken pipe

### ISSUE THREAD

**Issue by hounddog22030** [aws/aws-sdk-net#1858]
## The Question
Why might we be getting the below error when calling SendMessageBatchAsync during a heavy load?
This works fine under light load, but when really hit it hard, we are getting the below error eventually.

`System.IO.IOException: Unable to read data from the transport connection: Broken pipe.
   System.Net.Sockets.SocketException (32): Broken pipe
   --- End of inner exception stack trace ---
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.SQS.Internal.ValidationResponseHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at BubbleBoy.WebApi.Functions.Aces.AceXmlImporter.SendFileToQueueAsync`

### Environment

* SDK Version: 3.7.0.8
* Package Version: 3.7.0.8
* OS Info: AWS Lambda, either Ubuntu or AmazonLinux
* Targeted .NET Platform:  netcore3.1

**Comment by hounddog22030** [comment]
The problem was that I was exceeding the 256K limit.  I thought you could have 10 messages of 256K, but you can only have 256K in total for all messages.  A better Exception would improve that...
