### ISSUE TITLE
Unable to get IAM security credentials from EC2 Instance Metadata Service with local dynamodb instance

### ISSUE THREAD

**Issue by AlexGagne** [aws/aws-sdk-net#1878]
## Description
I have a local dynamodb instance running in Docker alongside another of my projects using Docker Compose. However, every time I try doing something with the SDK client, I get this error: "Unable to get IAM security credentials from EC2 Instance Metadata Service."

Which is odd since I'm not running in EC2, only a local program with the AWS SDK and the dynamodb local instance. I can also access the dynamodb local instance normally using the aws cli.

## Reproduction Steps
Here's a snippet of the code I am using (in F#, but it should be readable for C# people too):
``` fsharp
 let localAmazonDynamoDB = "http://localhost:8000"
 let clientConfig = AmazonDynamoDBConfig()
 clientConfig.ServiceURL <- localAmazonDynamoDB
 let client = new AmazonDynamoDBClient(clientConfig)

 printfn "Describing table"
 client.DescribeTableAsync("TestName") // Error happens here
     |> Async.AwaitTask
     |> Async.Ignore
     |> Async.RunSynchronously
 printfn "Described table"
```
I currently do a DescribeTable, but every call I try seems to fail with the same error.

I've included a version you can run yourself in this repository:
https://github.com/AlexGagne/DynamoDbBugExample

It also includes my Dockerfile and docker-compose.yml, if the error can be found there.

### Logs
Here is the whole stack trace:
```
Unhandled exception. System.AggregateException: One or more errors occurred. (Unable to get IAM security credentials from EC2 Instance Metadata Service.)
---> Amazon.Runtime.AmazonServiceException: Unable to get IAM security credentials from EC2 Instance Metadata Service.
at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.FetchCredentials()
at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentials()
at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentialsAsync()
at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
 --- End of inner exception stack trace ---
at Microsoft.FSharp.Control.AsyncResult`1.Commit() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 337
at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 870
at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 878
at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1142
at Program.main(String[] _arg1) in /src/AWSSDKBug/Program.fs:line 14
```

### Environment
* SDK Version: 3.7.0.38
* Package Version: 3.7.0.38
* OS Info: Windows 10
* Build Environment: dotnet cli inside a Dockerfile for my program
* Targeted .NET Platform:  dotnet 5

## Resolution
I should be able to perform operations on a table in a local DynamoDb instance without getting exceptions.

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @AlexGagne,

Good afternoon.

Could you please share from where you are executing AWS CLI commands which are working correctly? 

In AWS SDK for .NET, credential resolution is separate from service endpoint resolution. Since you are executing the F# program using `AWSSDK.DynamoDBv2` from inside the docker environment and do not have configured credentials in the Docker environment, it fails ultimately while following the [Credential and profile resolution](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/creds-assign.html) order. You could pass the credentials via environment variables to Docker environment, refer [Docker run](https://docs.docker.com/engine/reference/commandline/run/) for more details.

Thanks,
Ashish

**Comment by AlexGagne** [comment]
Hello @ashishdhingra,

Thanks for the quick response. Here's are examples from the cli that work correctly:
`aws dynamodb list-tables --endpoint-url http://localhost:8000`
`aws dynamodb describe-table --table-name "TestName" --endpoint-url http://localhost:8000`

I have added the environment variables in the Docker compose, but it now seems to freeze up and eventually end up with this exception:
 ```
Unhandled exception. System.AggregateException: One or more errors occurred. (Cannot assign requested address (localhost:8000))
---> System.Net.Http.HttpRequestException: Cannot assign requested address (localhost:8000)
---> System.Net.Sockets.SocketException (99): Cannot assign requested address
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
--- End of inner exception stack trace ---
at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
--- End of inner exception stack trace ---
 at Microsoft.FSharp.Control.AsyncResult`1.Commit() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 337
at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 870
at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 878
at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1142
at Program.main(String[] _arg1) in /src/AWSSDKBug/Program.fs:line 15
```

I've also tried setting the credentials in code using this:
``` fsharp
let localAmazonDynamoDB = "http://localhost:8000"
    
let accessKey = Environment.GetEnvironmentVariable("AWS_ACCESS_KEY_ID")
let secretAccessKey = Environment.GetEnvironmentVariable("AWS_SECRET_ACCESS_KEY")
let credentials = BasicAWSCredentials(accessKey, secretAccessKey)
    
let clientConfig = AmazonDynamoDBConfig()
clientConfig.ServiceURL <- localAmazonDynamoDB
let client = new AmazonDynamoDBClient(credentials, clientConfig)

printfn "Describing table"
client.DescribeTableAsync("TestName")
    |> Async.AwaitTask
    |> Async.Ignore
    |> Async.RunSynchronously
```

But I get the except same behaviour. I've updated the Github repository with my latest code.

**Comment by ashishdhingra** [comment]
> Hello @ashishdhingra,
> 
> 
> 
> Thanks for the quick response. Here's are examples from the cli that work correctly:
> 
> `aws dynamodb list-tables --endpoint-url http://localhost:8000`
> 
> `aws dynamodb describe-table --table-name "TestName" --endpoint-url http://localhost:8000`
> 
> 
> 
> I have added the environment variables in the Docker compose, but it now seems to freeze up and eventually end up with this exception:
> 
>  ```
> 
> Unhandled exception. System.AggregateException: One or more errors occurred. (Cannot assign requested address (localhost:8000))
> 
> ---> System.Net.Http.HttpRequestException: Cannot assign requested address (localhost:8000)
> 
> ---> System.Net.Sockets.SocketException (99): Cannot assign requested address
> 
> at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
> 
> at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
> 
> at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
> 
> at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
> 
> at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
> 
> --- End of inner exception stack trace ---
> 
> at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
> 
> at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
> 
> at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
> 
> at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
> 
> at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
> 
> at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
> 
> at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
> 
> at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
> 
> at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
> 
> at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
> 
> at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
> 
> at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
> 
> at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
> 
> at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
> 
> at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
> 
> at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
> 
> at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
> 
> at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
> 
> at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
> 
> at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
> 
> at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
> 
> at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
> 
> --- End of inner exception stack trace ---
> 
>  at Microsoft.FSharp.Control.AsyncResult`1.Commit() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 337
> 
> at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 870
> 
> at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 878
> 
> at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1142
> 
> at Program.main(String[] _arg1) in /src/AWSSDKBug/Program.fs:line 15
> 
> ```
> 
> 
> 
> I've also tried setting the credentials in code using this:
> 
> ``` fsharp
> 
> let localAmazonDynamoDB = "http://localhost:8000"
> 
>     
> 
> let accessKey = Environment.GetEnvironmentVariable("AWS_ACCESS_KEY_ID")
> 
> let secretAccessKey = Environment.GetEnvironmentVariable("AWS_SECRET_ACCESS_KEY")
> 
> let credentials = BasicAWSCredentials(accessKey, secretAccessKey)
> 
>     
> 
> let clientConfig = AmazonDynamoDBConfig()
> 
> clientConfig.ServiceURL <- localAmazonDynamoDB
> 
> let client = new AmazonDynamoDBClient(credentials, clientConfig)
> 
> 
> 
> printfn "Describing table"
> 
> client.DescribeTableAsync("TestName")
> 
>     |> Async.AwaitTask
> 
>     |> Async.Ignore
> 
>     |> Async.RunSynchronously
> 
> ```
> 
> 
> 
> But I get the except same behaviour. I've updated the Github repository with my latest code.
> 
> 
> 
> Also, please confirm my understanding: The Access key Id and Secret Access Key do not matter since I'm running a local instance of dynamodb, correct? I've been using FAKEACCESSKEY and FAKESECRETACCESSKEY respectively.

@AlexGagne Please confirm from where you are executing the AWS CLI commands? Is it from your local machine or Docker environment?

**Comment by AlexGagne** [comment]
@ashishdhingra Ah yes, good point, it is from my local machine.

**Comment by ashishdhingra** [comment]
> @ashishdhingra Ah yes, good point, it is from my local machine.

@AlexGagne From your local machine, the credentials are retrieved normally based on credential search order. 

Is your application running inside Docker image? Please confirm. Assuming that this is true, the only way for credential resolution is environment variables.

Could you try running the application from your local machine and see if it works?

**Comment by AlexGagne** [comment]
@ashishdhingra 

> Is your application running inside Docker image? Please confirm. Assuming that this is true, the only way for credential resolution is environment variables.
It is.

> Could you try running the application from your local machine and see if it works?
I have run it locally and it does work, so you're right that I have something missing in my Docker container. I don't really know what that would be.

I have done a few tests:
* From the Docker container: I can print the environment variables for AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY, so they exist and are accessible. This is using Docker compose to set the environment variables

* From the Docker container: I've inlined all of the variables and created the credentials manually in code. I get the same issue.

* I've added these lines inside of the Dockerfile for the Docker container:
```
    ENV AWS_ACCESS_KEY_ID='FAKEACCESS'
    ENV AWS_SECRET_ACCESS_KEY='FAKESECRETACCESS'
```
I still get the same issue

* I have added the environment variables while doing docker run:
`docker run --env AWS_ACCESS_KEY_ID="ACCESS" --env AWS_SECRET_ACCESS_KEY="SECRET" awsbug:latest`
I still get the same issue

**Comment by ashishdhingra** [comment]
> @ashishdhingra 
> 
> 
> 
> > Is your application running inside Docker image? Please confirm. Assuming that this is true, the only way for credential resolution is environment variables.
> 
> 
> 
> It is.
> 
> 
> 
> > Could you try running the application from your local machine and see if it works?
> 
> 
> 
> I have run it locally and it does work, so you're right that I have something missing in my Docker container. I don't really know what that would be.
> 
> 
> 
> I have done a few tests:
> 
> * From the Docker container: I can print the environment variables for AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY, so they exist and are accessible. This is using Docker compose to set the environment variables
> 
> 
> 
> * From the Docker container: I've inlined all of the variables and created the credentials manually in code. I get the same issue.
> 
> 
> 
> * I've added these lines inside of the Dockerfile for the Docker container:
> 
> ```
> 
>     ENV AWS_ACCESS_KEY_ID='FAKEACCESS'
> 
>     ENV AWS_SECRET_ACCESS_KEY='FAKESECRETACCESS'
> 
> ```
> 
> I still get the same issue
> 
> 
> 
> * I have added the environment variables while doing docker run:
> 
> `docker run --env AWS_ACCESS_KEY_ID="ACCESS" --env AWS_SECRET_ACCESS_KEY="SECRET" awsbug:latest`
> 
> I still get the same issue

@AlexGagne The stack trace shared by you earlier indicates that it's unable to reach local DynamoDB endpoint from inside the Docker container which is running your application. This makes sense since local DynamoDB endpoint is exposed to your machine, not the Docker container.

Try accessing any of the public AWS services from your application, it should work.

**Comment by AlexGagne** [comment]
@ashishdhingra 

Thank you for the clarification. I can confirm that it works with public AWS services, but not for my local machine.

I've finally found the solution and that's due to a misunderstanding from my part on the [Docker compose file from AWS](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.DownloadingAndRunning.html). If I switch the url to "http://dynamodb-local:8000" instead of "http://localhost:8000", it works.

Thanks a lot for your help, it clarified a lot of things for me.
