### ISSUE TITLE
Blazor .Net 5 cannot use DynamoDB

### ISSUE THREAD

**Issue by genifycom** [aws/aws-sdk-net#1890]
## Description
If you attempt to use DynamoDB in a Blazor WASM .NET 5 application, you will get "System.Security.Cryptography.Algorithms is not supported on this platform".

Please note : https://github.com/dotnet/aspnetcore/issues/26123

This indicates "Closed by design".

Does this mean that we will not be able to call the DynamoDB AWSSDK from Balzor WASM .Net 5?

## Reproduction Steps
Table listingsTable = Table.LoadTable(_ddbClient, "myTable");

Gets an exception "System.Security.Cryptography.Algorithms is not supported on this platform".

### Environment

* SDK Version: 5.0.302
* Package Version: AWSSDK.ApiGatewayV2  Version:3.7.0.35
* OS Info: 

---

This is a :bug: bug-report

**Comment by ganeshnj** [comment]
@genifycom could you provide the full stacktrace?

If you can share sample app with reproducibility that would help greatly.

**Comment by genifycom** [comment]
ERROR in GetJSONListing System.Security.Cryptography.Algorithms is not supported on this platform.
   at System.Security.Cryptography.HMACSHA256..ctor()
   at Amazon.Util.CryptoUtilFactory.CryptoUtil.CreateKeyedHashAlgorithm(SigningAlgorithm algorithmName)
   at Amazon.Util.CryptoUtilFactory.CryptoUtil.HMACSignBinary(Byte[] data, Byte[] key, SigningAlgorithm algorithmName)
   at Amazon.Runtime.Internal.Auth.AWS4Signer.ComputeKeyedHash(SigningAlgorithm algorithm, Byte[] key, Byte[] data)
   at Amazon.Runtime.Internal.Auth.AWS4Signer.ComposeSigningKey(String awsSecretAccessKey, String region, String date, String service)
   at Amazon.Runtime.Internal.Auth.AWS4Signer.ComputeSignature(String awsAccessKey, String awsSecretAccessKey, String region, DateTime signedAt, String service, String signedHeaders, String canonicalRequest, RequestMetrics metrics)
   at Amazon.Runtime.Internal.Auth.AWS4Signer.SignRequest(IRequest request, IClientConfig clientConfig, RequestMetrics metrics, String awsAccessKeyId, String awsSecretAccessKey)
   at Amazon.Runtime.Internal.Auth.AWS4Signer.Sign(IRequest request, IClientConfig clientConfig, RequestMetrics metrics, String awsAccessKeyId, String awsSecretAccessKey)
   at Amazon.Runtime.Internal.Signer.SignRequest(IRequestContext requestContext)
   at Amazon.Runtime.Internal.Signer.PreInvoke(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Signer.InvokeAsync[GetItemResponse](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeAsync[GetItemResponse](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.<>n__0[GetItemResponse](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.<InvokeAsync>d__2`1[[Amazon.DynamoDBv2.Model.GetItemResponse, AWSSDK.DynamoDBv2, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604]].MoveNext()
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.<InvokeAsync>d__2`1[[Amazon.DynamoDBv2.Model.GetItemResponse, AWSSDK.DynamoDBv2, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604]].MoveNext()
   at Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7`1[[Amazon.DynamoDBv2.Model.GetItemResponse, AWSSDK.DynamoDBv2, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604]].MoveNext()
   at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1[[Amazon.DynamoDBv2.Model.GetItemResponse, AWSSDK.DynamoDBv2, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604]].MoveNext()
   at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1[[Amazon.DynamoDBv2.Model.GetItemResponse, AWSSDK.DynamoDBv2, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604]].MoveNext()
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1[[Amazon.DynamoDBv2.Model.GetItemResponse, AWSSDK.DynamoDBv2, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604]].MoveNext()
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1[[Amazon.DynamoDBv2.Model.GetItemResponse, AWSSDK.DynamoDBv2, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604]].MoveNext()
   at Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5`1[[Amazon.DynamoDBv2.Model.GetItemResponse, AWSSDK.DynamoDBv2, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604]].MoveNext()
   at Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1`1[[Amazon.DynamoDBv2.Model.GetItemResponse, AWSSDK.DynamoDBv2, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604]].MoveNext()
   at WebApplication1.Pages.Index.Test() in C:\Dev\Projects\PlatteStoreApplications\PFApps\WebApplication1\Pages\Index.razor:line 43

**Comment by genifycom** [comment]
Hi ganeshnj,

Do you have enough information on this one?

It seems that I currently cannot use any AWS API functions from Blazor. They all fail with the same problem. This is a major problem for me.

**Comment by ganeshnj** [comment]
AWS SDK uses HmacSHA256 or HmacSHA1 for signing requests depending on the configuration which are not available in WASM 😟.

Microsoft plans to introduce HMACSHA* algorithms in [.NET 6](https://github.com/dotnet/designs/blob/main/accepted/2021/blazor-wasm-crypto.md).

**Comment by ganeshnj** [comment]
I'm not sure about the use-case but you can use Blazor WebAssembly App with ASP.NET Core hosted backend.

**Comment by genifycom** [comment]
Ok, that is very disappointing news.

I have been able to use AWSSDK via Blazor Mobile Bindings because that doesn't use WASM so that is one route :)

Thanks
