### ISSUE TITLE
Failing to get Profile Credential as Windows Core .Net Service using AWSSDK.Extensions.NETCore.Setup

### ISSUE THREAD

**Issue by john-gold-repay** [aws/aws-sdk-net#1892]
## Description
When running the exe on command line everything is fine and I can get SQS messages without error, however when I install and run as a windows service I get 'Access to the resource https://sqs.us-west-2.amazonaws.com/... is denied.' Even when specifying 'ProfileLocation'. And It however is obviously reading the config as the url for the sqs is defined there.

## Reproduction Steps
Create a 3.1 Core .Net Worker Service as per: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-3.1&tabs=visual-studio
Use profile credentials as per https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-netcore.html
Try to read messages from SQS in worker

### Logs
Amazon.SQS.AmazonSQSException: Access to the resource https://sqs.us-west-2.amazonaws.com/<...> is denied.
---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.SQS.Internal.ValidationResponseHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionStream(IRequestContext requestContext, IWebResponseData httpErrorResponse, HttpErrorResponseException exception, Stream responseStream)
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionAsync(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ExceptionHandler`1.HandleAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessExceptionAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at rcs_legacy_compliance.watcher.Worker.ExecuteAsync(CancellationToken stoppingToken) in C:\Git\...

### Environment

    <PackageReference Include="AWS.Logger.Log4net" Version="3.2.1" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.7.1" />
    <PackageReference Include="AWSSDK.SQS" Version="3.7.0.43" />
    <PackageReference Include="log4net" Version="2.0.12" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="5.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Log4Net.AspNetCore" Version="5.0.3" />
    <PackageReference Include="System.Management.Automation" Version="7.0.6" />
* OS Info: Windows 10
* Build Environment: Visual Studio 2019
* Targeted .NET Platform:  netcoreapp3.1

## Resolution

Throw an error on failing to get profile/create credential that tells how to fix

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @john-gold-repay,

Good afternoon.

Could you please share the sample code to reproduce the issue? When an application is deployed as Windows service, it runs under a different identity and hence may not have access to your default profile. As a test, could you try running your Windows service under your account and see if it works?

Thanks,
Ashish

**Comment by john-gold-repay** [comment]
@ashishdhingra was perms, Thanks!
