### ISSUE TITLE
Encountering NotImplementedException in .NET 5 + SSO + AssumeRole scenarios

### ISSUE THREAD

**Issue by mattdg** [aws/aws-sdk-net#1896]
## Description

In my organization, we have begun the process of adopting SSO logins for our developer accounts. With or without SSO, as a developer I have an AWS Profile set up with the account I log in with which must then assume a role in another account in order to access the application's resources.

 In our solution at large, we have processes which use .NET Framework, and some which use .NET 5. We have run into a problem related to the assuming of the application role with some of our existing code when we try to run it on .NET 5 (though I presume, any version of .NET Core would be the same) once we change to an SSO-enabled login account.
 
 The code runs fine on .NET Framework. But on .NET 5, we're encountering a `NotImplementedException` in the `AssumeRoleAWSCredentials.GenerateNewCredentials()` code path.

### Sample code
 
 The code that follows isn't lifted exactly from our code, but distills the problem the are having down to a simple form. This sample uses C# 9 so that I can use top-level statements to eliminate the usual boilerplate of `Main` and such.

 ```c#
using System;
using Amazon.SimpleSystemsManagement;
using Amazon.SimpleSystemsManagement.Model;

IAmazonSimpleSystemsManagement client = new AmazonSimpleSystemsManagementClient();
var result = await client.GetParametersByPathAsync(
    new GetParametersByPathRequest
    {
        Path = "/qap/client/test",
        Recursive = true
    });

foreach (var item in result.Parameters)
{
    Console.WriteLine($"{item.Name}");
}
 ```

And here's a minimal csproj file for the NuGet references, etc.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <LangVersion>latest</LangVersion>
    <TargetFrameworks>net472;net5.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.7.1" />
    <PackageReference Include="AWSSDK.SimpleSystemsManagement" Version="3.7.4.7" />
    <PackageReference Include="AWSSDK.SecurityToken" Version="3.7.1.39" />
    <PackageReference Include="AWSSDK.SSO" Version="3.7.0.49" />
    <PackageReference Include="AWSSDK.SSOOIDC" Version="3.7.0.49" />
  </ItemGroup>

</Project>

```

## Reproduction Steps

1. Configure ~/.aws/config for the SSO login. I've included what mine basically looks like below under **Environment**.
2. The code assumes we have the `AWS_PROFILE` set to the desired profile. In this example, **"dev"**.
3. Use the AWS CLI to login: ` aws sso login --profile dev`
4. Build and run the sample application. When I run the .NET Framework version, it runs fine and lists the paths of the SSM parameters, as expected. It fails on .NET 5.

### Logs

When run on .NET 5, the result is a `Amazon.Runtime.AmazonClientException` with an InnerException of `System.NotImplementedException`.  The exception details follow, though I've scrubbed the actual account ID and cut out a lot of the unimportant async-related stack frames.

```
Amazon.Runtime.AmazonClientException
  HResult=0x80131500
  Message=Error calling AssumeRole for role arn:aws:iam::<APPLICATION_ACCOUNT_ID>:role/OrganizationAccountAccessRole-Developer
  Source=AWSSDK.SecurityToken
  StackTrace:
   at Amazon.SecurityToken.AmazonSecurityTokenServiceClient.Amazon.Runtime.SharedInterfaces.ICoreAmazonSTS.CredentialsFromAssumeRoleAuthentication(String roleArn, String roleSessionName, AssumeRoleAWSCredentialsOptions options)
   at Amazon.Runtime.AssumeRoleAWSCredentials.GenerateNewCredentials()
   at Amazon.Runtime.RefreshingAWSCredentials.<GenerateNewCredentialsAsync>b__16_0()
   at System.Threading.Tasks.Task`1.InnerInvoke() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:line 497
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2359
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 274

   ---- removed a lot more async goop ----

   at <Program>$.<<Main>$>d__0.MoveNext() in W:\Samples\sso-assume-role-sample\Program.cs:line 6
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 56
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/TaskAwaiter.cs:line 173
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/TaskAwaiter.cs:line 150
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/TaskAwaiter.cs:line 105
   at <Program>$.<Main>(String[] args)

  This exception was originally thrown at this call stack:
    Amazon.Runtime.RefreshingAWSCredentials.GenerateNewCredentials()
    Amazon.Runtime.RefreshingAWSCredentials.GetCredentials()
    Amazon.Runtime.Internal.CredentialsRetriever.PreInvoke(Amazon.Runtime.IExecutionContext)
    Amazon.Runtime.Internal.CredentialsRetriever.InvokeSync(Amazon.Runtime.IExecutionContext)
    Amazon.Runtime.Internal.PipelineHandler.InvokeSync(Amazon.Runtime.IExecutionContext)
    Amazon.Runtime.Internal.RetryHandler.InvokeSync(Amazon.Runtime.IExecutionContext)
    Amazon.Runtime.Internal.PipelineHandler.InvokeSync(Amazon.Runtime.IExecutionContext)
    Amazon.Runtime.Internal.CallbackHandler.InvokeSync(Amazon.Runtime.IExecutionContext)
    Amazon.Runtime.Internal.PipelineHandler.InvokeSync(Amazon.Runtime.IExecutionContext)
    Amazon.Runtime.Internal.EndpointResolver.InvokeSync(Amazon.Runtime.IExecutionContext)
    ...
    [Call Stack Truncated]

Inner Exception 1:
NotImplementedException: The method or operation is not implemented.
```

### Environment

* The sample code above assumes that the AWS CLI (version 2.2.27) profile (~/.aws/config) is appropriately configured. Mine is something like:
```
[profile default]
region = us-east-1
output = json
sso_start_url = <MY_ORGANIZATION_START_URL>
sso_account_id = <MY_PERSONAL_ACCOUNT_ID>
sso_region = us-east-1
sso_role_name = QAP-Developer-AssumeRole

[profile dev]
source_profile = default
role_arn = arn:aws:iam::<APPLICATION_ACCOUNT_ID>:role/OrganizationAccountAccessRole-Developer
region = us-east-1
output = json
```

* The code sample assumes that the `AWS_PROFILE` environment variable is set to select the desired profile (**dev** in this case).
* SDK Version: 3.7.91.0
* Package Version: See the CSPROJ sample above.
* OS Info: Windows 10
* Build Environment: Visual Studio 2019 / JetBrains Rider 2021.2
* Targeted .NET Platform: Building with .NET SDK 5.0.302, currently running on .NET Runtime 5.0.8

## Resolution
- [x] :wave: I can/would-like-to implement a fix for this problem myself

I have done a bit of debugging of the issue using custom builds of the SDK libraries in question and setting Visual Studio to stop on `NotImplementedException`s.

Long story short, I ultimately found that I seemed to correct the problem (at least in this case) by making `Async` versions of two methods:

1. In **sdk/src/Core/Amazon.Runtime/Credentials/AssumeRoleAWSCredentials.cs**, add an async version of `AssumeRoleAWSCredentials.GenerateNewCredentials()`, and in order to support that ...
1. In **sdk/src/Services/SecurityToken/Custom/AmazonSecurityTokenServiceClient.Extension.cs**, add an async version of `AmazonSecurityTokenServiceClient.CredentialsFromAssumeRoleAuthentication()` (CredentialsFromAssumeRoleAuthenticationAsync) that the new `AssumeRoleAWSCredentials.GenerateNewCredentialsAsync()` can call.  (Also requires adding this method to the `ICoreAmazonSTS` interface.)

So, in the end, my experimentation led me to this make a custom build with this "patch": https://github.com/mattdg/aws-sdk-net/commit/043b592e885911b2f454658b3b0fef82c975fb80.  If I build the sample with my patched DLLs, the .NET 5 version now works.

I look to anyone more experienced with the workings of the SDK to say whether there are any problems with this, if it's not sufficient, etc??

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @mattdg,

Good morning.

I'm able to get error `The method or operation is not implemented.` from AWS SDK for .NET  when targeting .NET 5.0. Could you please share the following:
- Credentials file sample
- SSO configuration, including permission for assuming a role

Also confirm if you executed `aws sso login --profile dev` or `aws sso login --profile default` since AWS CLI appears to require required SSO configuration values: sso_start_url, sso_region, sso_role_name, sso_account_id even when using `source_profile`.

Thanks,
Ashish

**Comment by mattdg** [comment]
Hi Ashish,

Yes, there appears to be some insistency with the CLI SSO login command or at least they config file doesn't seem to work the way one might intuit...  but that's another problem.  :-)  

To perform the login, I guess it's OK to use `aws sso login --profile default`.  In practice, I typically initiate the login from the AWS web console and not the command line.  At any rate, once I'm logged in using the CLI and the default profile, I'm able to run

`aws sts get-caller-identity --profile dev`

and I get back

{
    "UserId": "AROAJGXTOKUNRLQO7JN7K:botocore-session-1628533158",
    "Account": "<APPLICATION_ACCOUNT_ID>",
    "Arn": "arn:aws:sts::<APPLICATION_ACCOUNT_ID>:assumed-role/OrganizationAccountAccessRole-Developer/botocore-session-1628533158"
}

Once switched over to SSO logins, I no longer have a `~/.aws/credentials` file (our IT folks instructed us to remove / rename it).

As for "SSO configuration, including permission for assuming a role"... if you mean how the accounts are configured, I'm not sure I have access to that.  All I can say is that however we are configured it seems to be correct and I don't think that has actually changed since before the SSO logins were enabled. (Even before SSO, we were using the same scheme with the same accounts and roles... the personal ones and the "application" ones). Plus, I don't think the code is actually getting far enough for that to matter?

**Comment by mattdg** [comment]
Yeah, I don't even have permission to even see the list of user accounts, or list my own roles. :-)

As it's been explained to me though, the SSO account (<MY_ACCOUNT_ID> above) is able to assume roles and not much else.  One of which in my case is to be able to assume the one specified by the ARN.  (Well, my account can actually assume three roles... the same **OrganizationAccountAccessRole-Developer** role that exists in 3 different accounts... one account for each deployment environment.)

**Comment by ryan-motive** [comment]
Running into this debugging in VS using SSO when I try to get a presigned URL from S3. Currently I can work around this by calling this in advance:

var creds = Task.Run(() => awsCredentials.GetCredentialsAsync()).Result;

It seems like the relevant code for   SSOAWSCredentials.GenerateNewCredentials() is blocked out with #if BCL. If you call the Async version ahead of time (as above) it caches the relevant info and the non-async GetCredentials call succeeds.

**Comment by phillip-proulx** [comment]
@ashishdhingra 
Hi Ashish,
We are having the same issue outline above. Has this issue been escalated and given an ETA on a deployed fix?

**Comment by normj** [comment]
I'm working on a fix now.
