### ISSUE TITLE
Cognito AdminInitiateAuthRequest returns NotAuthorizedException: Refresh Token has been revoked on fresh refresh token

### ISSUE THREAD

**Issue by mvinkovits** [aws/aws-sdk-net#1936]
Hi,
I have a code that worked perfectly fine roughly a year ago. It uses a refresh token to call the AdminInitiateAuthRequest from a .netcore 3.1 lambda. Now testing it, I get refresh token has been revoked even though the refresh token has been generated just a minute before. Using the exact same refresh token on the /token endpoint or the AWS CLI admin-initiate-auth call works perfectly fine.

**Comment by ashishdhingra** [comment]
Hi @mvinkovits,

Good morning.

Could you please share the sample code and the contents of your `.csproj` file to troubleshoot the issue?

Thanks,
Ashish

**Comment by mvinkovits** [comment]
### Expected Behavior
Code should return response.HttpStatusCode == HttpStatusCode.OK

### Current Behavior
  client.InitiateAuthAsync(adminInitiateAuthRequest, token) throws exception refreshing id token.

 ```
 Amazon.CognitoIdentityProvider.Model.NotAuthorizedException: Refresh Token has been revoked
  ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type     Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
```

### Possible Solution
I don't know the underlying flow the sdk uses to create the request.

### Steps to Reproduce (for bugs)

1. Create cognito user pool and app client allowing ALLOW_REFRESH_TOKEN_AUTH flow and enabling token revocation.
2. Login user with authorization code grant using the /token endpoint of user pool. Take refresh token.
3. Use refresh token to get new id token using AdminInitiateAuthReqeust.

### Context
  ```
AmazonCognitoIdentityProviderClient client = new AmazonCognitoIdentityProviderClient(
                RegionEndpoint.GetBySystemName(await SettingsUtil.GetCognitoRegion()));
            var hmac = new HMACSHA256();
            hmac.Key = Encoding.UTF8.GetBytes(await SettingsUtil.GetCognitoClientSecret());
            var secretHash = hmac.ComputeHash(Encoding.UTF8.GetBytes(userGuid + await SettingsUtil.GetCognitoClientId()));
            log.LogDebug("user:" + userGuid + " refresh token:" + refreshToken + " hash:" + Convert.ToBase64String(secretHash));
            var adminInitiateAuthRequest = new AdminInitiateAuthRequest()
            {
                ClientId = await SettingsUtil.GetCognitoClientId(),
                AuthFlow = AuthFlowType.REFRESH_TOKEN_AUTH,
                AuthParameters = new Dictionary<string, string>()
                { { "REFRESH_TOKEN", refreshToken }, { "SECRET_HASH", Convert.ToBase64String(secretHash) }
                }
            };
            try
            {
                var response = await client.AdminInitiateAuthAsync(adminInitiateAuthRequest, token);
```
### Your Environment

 AWSSDK.Core version used: AWSSDK.Core 3.7.4.1
 Operating System and version: lambda
 Targeted .NET platform: 3.1

.NET Core Info

.NET Core version installed in the environment where application runs: lambda
Contents of project.json/project.csproj:
   ```
<Project Sdk="Microsoft.NET.Sdk">
   <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
    </PropertyGroup>
    <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="2.1.0"/>
    <PackageReference Include="AWSSDK.CognitoIdentityProvider" Version="3.7.1.68"/>
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.2.0"/>
    </ItemGroup>
    <ItemGroup>
    <ProjectReference Include="..\..\..\..\common\LambdaUtil\LambdaUtil.csproj"/>
    <ProjectReference Include="..\..\..\..\common\SettingsUtil\SettingsUtil.csproj"/>
    <ProjectReference Include="..\..\..\..\common\Model\Model.csproj"/>
    </ItemGroup>
   </Project>
```

**Comment by ashishdhingra** [comment]
Hi @mvinkovits,

Good afternoon.

Thanks for providing reproduction steps. Somehow, I'm unable to reproduce the issue using the below customized (basic) code:
**.csproj**
```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.CognitoIdentityProvider" Version="3.7.1.69" />
  </ItemGroup>

</Project>
```
**Program.cs**
```C#
using System;
using System.Security.Cryptography;
using System.Text;
using System.Collections.Generic;
using Amazon.CognitoIdentityProvider;
using Amazon.CognitoIdentityProvider.Model;

namespace CognitoRefreshTokenTest_Issue1936
{
    class Program
    {
        private static string userId = "<<user_id>>";
        private static string tempPassword = "<<temp_password_for_new_user>>";
        private static string password = "<<password>>";
        private static string clientId = "<<client_id>>";
        private static string clientSecret = "<<client_secret>>";
        private static string userPoolId = "<<user_pool_id>>";

        static void Main(string[] args)
        {
            AmazonCognitoIdentityProviderClient amazonCognitoIdentityProviderClient = new AmazonCognitoIdentityProviderClient();
            string secretHash = GetUserPoolSecretHash(userId, clientId, clientSecret);
            string refreshToken = null;

            var signinResponse = amazonCognitoIdentityProviderClient.AdminInitiateAuthAsync(new AdminInitiateAuthRequest()
            {
                ClientId = clientId,
                AuthFlow = AuthFlowType.ADMIN_NO_SRP_AUTH,
                UserPoolId = userPoolId,
                AuthParameters = new Dictionary<string, string>() { 
                    { "USERNAME", userId }, { "PASSWORD", tempPassword }, { "SECRET_HASH", secretHash }
                }
            }).Result;

            if (signinResponse.AuthenticationResult == null && signinResponse.ChallengeName == ChallengeNameType.NEW_PASSWORD_REQUIRED)
            {
                var adminrespondToAuthChallengeResponse = amazonCognitoIdentityProviderClient.AdminRespondToAuthChallengeAsync(new AdminRespondToAuthChallengeRequest()
                {
                    ChallengeName = ChallengeNameType.NEW_PASSWORD_REQUIRED,
                    UserPoolId = userPoolId,
                    ClientId = clientId,
                    Session = signinResponse.Session,
                    ChallengeResponses = new Dictionary<string, string>() {
                    { "USERNAME", userId }, { "NEW_PASSWORD", password}, { "SECRET_HASH", secretHash } }
                }).Result;

                refreshToken = adminrespondToAuthChallengeResponse.AuthenticationResult?.RefreshToken;
            }
            else
            {
                refreshToken = signinResponse.AuthenticationResult?.RefreshToken;
            }

            if(!string.IsNullOrEmpty(refreshToken))
            {
                var refreshTokenResponse = amazonCognitoIdentityProviderClient.AdminInitiateAuthAsync(new AdminInitiateAuthRequest()
                {
                    ClientId = clientId,
                    AuthFlow = AuthFlowType.REFRESH_TOKEN_AUTH,
                    UserPoolId = userPoolId,
                    AuthParameters = new Dictionary<string, string>() {
                    { "REFRESH_TOKEN", refreshToken }, { "SECRET_HASH", secretHash }
                }
                }).Result;
            }
        }

        private static string GetUserPoolSecretHash(string userID, string clientID, string clientSecret)
        {
            string message = userID + clientID;
            byte[] keyBytes = Encoding.UTF8.GetBytes(clientSecret);
            byte[] messageBytes = Encoding.UTF8.GetBytes(message);

            HMACSHA256 hmacSha256 = new HMACSHA256(keyBytes);
            byte[] hashMessage = hmacSha256.ComputeHash(messageBytes);

            return Convert.ToBase64String(hashMessage);
        }
    }
}
``` 

Please revisit your code and user pool settings (specifically app client Refresh token expiration).

Thanks,
Ashish

**Comment by mvinkovits** [comment]
Thank you, good to know. I did disable token revocation in Cognito and then everything worked fine, so it is not an issue of the code, settings or lambda permissions.

**Comment by ashishdhingra** [comment]
> Thank you, good to know. I did disable token revocation in Cognito and then everything worked fine, so it is not an issue of the code, settings or lambda permissions.

@mvinkovits I can confirm that the above logic works with my user pool and app client, which has token revocation enabled:

<img width="971" alt="Screen Shot 2021-11-17 at 5 39 29 AM" src="https://user-images.githubusercontent.com/67916761/142211710-92f19349-4bb2-481e-b1a4-df5628154c58.png">

Since the issue is not reproducible, kindly confirm if it could be closed.

Thanks,
Ashish
