### ISSUE TITLE
HashSet duplicate key exception when setting up region endpoints

### ISSUE THREAD

**Issue by ckuehl** [aws/aws-sdk-net#1939]
This is a continuation of #986.

After upgrading to .Net 6 on Linux, we've begun seeing the following exception on some of the machines in our fleet upon startup:

```
System.ArgumentException: An item with the same key has already been added. Key: System.Collections.Generic.HashSet`1[System.String]
at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
at Amazon.Internal.RegionEndpointV3.ServiceMap.Add(String serviceName, Endpoint endpoint, HashSet`1 variants)
at Amazon.Internal.RegionEndpointV3.AddVariantEndpointsToServiceMap(JsonData mergedEndpoint, String regionName, String serviceName, Dictionary`2 mergedVariants)
at Amazon.Internal.RegionEndpointV3.AddServiceToMap(JsonData service, String serviceName)
at Amazon.Internal.RegionEndpointV3.ParseAllServices()
at Amazon.Internal.RegionEndpointV3.GetEndpointForService(String serviceName, HashSet`1 variants)
at Amazon.Internal.RegionEndpointV3.GetEndpointForService(String serviceName, Boolean dualStack)
at Amazon.Runtime.ClientConfig.GetUrl(RegionEndpoint regionEndpoint, String regionEndpointServiceName, Boolean useHttp, Boolean useDualStack)
at Amazon.Runtime.ClientConfig.DetermineServiceURL()
at Amazon.Runtime.Internal.DefaultRetryPolicy..ctor(IClientConfig config)
at Amazon.Runtime.AmazonServiceClient.BuildRuntimePipeline()
```

We're using version 3.7.1 of AWSSDK.Extensions.NETCore.Setup and the latest version of the service-specific SDKs.

Let me know if you need any additional details regarding our environment.

---

This is a :bug: bug-report

**Comment by ckuehl** [comment]
We've also seen:

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
  ?, in bool Enumerator.MoveNext()
  ?, in void RegionEndpointV3.MergeJsonData(JsonData target, JsonData source, Dictionary<HashSet<string>, JsonData> variants)
  ?, in void RegionEndpointV3.AddServiceToMap(JsonData service, string serviceName)
  ?, in void RegionEndpointV3.ParseAllServices()
  ?, in Endpoint RegionEndpointV3.GetEndpointForService(string serviceName, HashSet<string> variants) x 2
  ?, in Endpoint RegionEndpoint.GetEndpointForService(string serviceName, bool dualStack)
  ?, in string ClientConfig.GetUrl(RegionEndpoint regionEndpoint, string regionEndpointServiceName, bool useHttp, bool useDualStack)
  ?, in string ClientConfig.DetermineServiceURL()
  ?, in new DefaultRetryPolicy(IClientConfig config)
  ?, in void AmazonServiceClient.BuildRuntimePipeline()
  ?, in new AmazonServiceClient(AWSCredentials credentials, ClientConfig config)
  ?, in new AmazonEC2Client(AWSCredentials credentials, AmazonEC2Config clientConfig) x 2
```

**Comment by ckuehl** [comment]
Also seeing:

```
System.ArgumentException: An item with the same key has already been added. Key: access-analyzer
  ?, in bool Dictionary<TKey, TValue>.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
  ?, in void RegionEndpointV3.AddNormalEndpointToServiceMap(JsonData mergedEndpoint, string regionName, string serviceName)
  ?, in void RegionEndpointV3.AddServiceToMap(JsonData service, string serviceName)
  ?, in void RegionEndpointV3.ParseAllServices()
  ?, in Endpoint RegionEndpointV3.GetEndpointForService(string serviceName, HashSet<string> variants) x 2
  ?, in string ClientConfig.GetUrl(RegionEndpoint regionEndpoint, string regionEndpointServiceName, bool useHttp, bool useDualStack)
  ?, in string ClientConfig.DetermineServiceURL()
  ?, in new DefaultRetryPolicy(IClientConfig config)
  ?, in void AmazonServiceClient.BuildRuntimePipeline()
  ?, in new AmazonEC2Client(AWSCredentials credentials, AmazonEC2Config clientConfig) x 2
```

**Comment by brad-fitzwater** [comment]
I was able to write this test program that reproduces https://github.com/aws/aws-sdk-net/issues/1939#issuecomment-975977925. Since this is a race condition, it may take a few runs to actually see the Exception. I can usually see the exception within 20 runs or so.

I am running on .Net 6 and my AWSSDK.EC2 is @ `3.7.44`.

```csharp
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;

using Amazon;
using Amazon.EC2;

namespace TestProgram;

internal class Program
{
    private static void Main(string[] args)
    {
        CultureInfo.DefaultThreadCurrentCulture = new CultureInfo("en-US");

        var regions = new HashSet<string>
        {
            "us-east-1",
            "us-east-2",
            "us-west-1",
            "us-west-2",
            "ap-northeast-1",
            "ap-northeast-2",
            "ap-northeast-3",
            "ap-south-1",
            "ap-southeast-1",
            "ap-southeast-2",
            "ca-central-1",
            "eu-central-1",
            "eu-west-1",
            "eu-west-2",
            "eu-west-3",
            "eu-north-1",
            "sa-east-1"
        };

        Parallel.ForEach(regions, region =>
        {
            try
            {
                var endpoint = RegionEndpoint.EnumerableAllRegions.Single(r => r.SystemName == region);
                using var ec2Client = new AmazonEC2Client(endpoint);
                Console.WriteLine($"Finished: {region}");
            }
            catch (Exception)
            {
                Console.WriteLine($"Error: {region}");
                throw;
            }
        });
    }
}
```

**Comment by peterrsongg** [comment]
Hello, thank you for opening this issue with us. I am currently investigating this issue, do you mind sharing the code that caused this issue? Is the above code written by @brad-fitzwater causing this issue?

**Comment by peterrsongg** [comment]
Okay, thank you for the confirmation. I'll post any updates here.

**Comment by peterrsongg** [comment]
@brad-fitzwater I've run your snippet in excess of 50 times with your version of EC2 and .Net6, and have not seen that error message popping up. Is this error message something you guys are still seeing?

**Comment by ashishdhingra** [comment]
Another issue https://github.com/aws/aws-sdk-net/issues/2097 opened by other user.

**Comment by EyalMaozCP** [comment]
Hey @peterrsongg, any progression with this issue? ETA? Thanks

**Comment by eddiemcs3** [comment]
We're working on a status update and will respond shortly.

**Comment by ppittle** [comment]
Issue was traced to a subtle locking bug.  A [fix](https://github.com/aws/aws-sdk-net/commit/c6c55eadd97e546c42df2ca2bcb13a5c51f54322) has been published and is available in [AWSSDK.Core **3.7.13.11**](https://www.nuget.org/packages/AWSSDK.Core/3.7.13.11): https://github.com/aws/aws-sdk-net/commit/c6c55eadd97e546c42df2ca2bcb13a5c51f54322
