### ISSUE TITLE
S3: PutBucketAsync gives AmazonS3Exception: Please reduce your request rate

### ISSUE THREAD

**Issue by jacobz3dg** [aws/aws-sdk-net#1949]
The function

```
IAmazonS3 s3Client = new AmazonS3Client();
PutBucketRequest putBucketRequest = new()
{
    BucketName = "1704649d-ef82-429a-a02b-0748311a70c0", // this is a randomized bucket name that follows the conventions
    UseClientRegion = true,
    CannedACL = "private"
};
await s3Client.PutBucketAsync(putBucketRequest);
```

Returns the following error for `PutBucketAsync`

```
Amazon.S3.AmazonS3Exception: Please reduce your request rate.
```

This previously did not happen, and only started today. It is the only function running at this moment in time, there are no files going in or out any of the buckets. There are some SQL queries in the background but these shouldn't affect this specific function.

### Environment

* SDK Version: AWSSDK.S3 3.7.7.1
* Package Version: ?
* OS Info: Amazon Lambda / ECR / Docker
* Build Environment: Visual Studio 2022
* Targeted .NET Platform:  .NET 5.0

```
  | 2021-12-07T20:13:23.119+00:00 | Amazon.S3.AmazonS3Exception: Please reduce your request rate.
  | 2021-12-07T20:13:23.119+00:00 | ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
  | 2021-12-07T20:13:23.119+00:00 | at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
  | 2021-12-07T20:13:23.119+00:00 | at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
  | 2021-12-07T20:13:23.119+00:00 | at Amazon.Runtime.Internal.RedirectHandler.InvokeAsync[T](IExecutionContext executionContext)
  | 2021-12-07T20:13:23.119+00:00 | at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
  | 2021-12-07T20:13:23.119+00:00 | at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeAsync[T](IExecutionContext executionContext)
  | 2021-12-07T20:13:23.119+00:00 | at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
  | 2021-12-07T20:13:23.119+00:00 | --- End of inner exception stack trace ---
  | 2021-12-07T20:13:23.119+00:00 | at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionStream(IRequestContext requestContext, IWebResponseData httpErrorResponse, HttpErrorResponseException exception, Stream responseStream)
  | 2021-12-07T20:13:23.119+00:00 | at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionAsync(IExecutionContext executionContext, HttpErrorResponseException exception)
  | 2021-12-07T20:13:23.119+00:00 | at Amazon.Runtime.Internal.ExceptionHandler`1.HandleAsync(IExecutionContext executionContext, Exception exception)
  | 2021-12-07T20:13:23.119+00:00 | at Amazon.Runtime.Internal.ErrorHandler.ProcessExceptionAsync(IExecutionContext executionContext, Exception exception)
  | 2021-12-07T20:13:23.119+00:00 | at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
  | 2021-12-07T20:13:23.119+00:00 | at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
  | 2021-12-07T20:13:23.119+00:00 | at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
  | 2021-12-07T20:13:23.119+00:00 | at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
  | 2021-12-07T20:13:23.119+00:00 | at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
  | 2021-12-07T20:13:23.119+00:00 | at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
  | 2021-12-07T20:13:23.119+00:00 | at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
  | 2021-12-07T20:13:23.119+00:00 | at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
  | 2021-12-07T20:13:23.119+00:00 | at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
  | 2021-12-07T20:13:23.119+00:00 | at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeAsync[T](IExecutionContext executionContext)
  | 2021-12-07T20:13:23.119+00:00 | at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
  | 2021-12-07T20:13:23.119+00:00 | at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
  | 2021-12-07T20:13:23.119+00:00 | at AddCompany.Function.FunctionHandler(APIGatewayProxyRequest request, ILambdaContext context) in /src/AddCompany/Function.cs:line 85
  | 2021-12-07T20:13:23.155+00:00 | Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
  | 2021-12-07T20:13:23.155+00:00 | at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
  | 2021-12-07T20:13:23.155+00:00 | at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
  | 2021-12-07T20:13:23.155+00:00 | at Amazon.Runtime.Internal.RedirectHandler.InvokeAsync[T](IExecutionContext executionContext)
  | 2021-12-07T20:13:23.155+00:00 | at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
  | 2021-12-07T20:13:23.155+00:00 | at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeAsync[T](IExecutionContext executionContext)
  | 2021-12-07T20:13:23.155+00:00 | at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
```

---

This is a :bug: bug-report

**Comment by aaoswal** [comment]
Hi @jacobz3dg,
This issue is likely related to an AWS large scale event ongoing and should be resolved when said event is resolved, please see our [Service Health Dashboard](https://status.aws.amazon.com/) for updates on the situation.

Hope this helps!

Regards,
Anish.

**Comment by muralikrishnachakka-bh** [comment]
2023-09-01 19:10:26,707 DEBUG c.a.h.AmazonHttpClient$RequestExecutor [pool-28-thread-7] Received error response: com.amazonaws.services.s3.model.AmazonS3Exception: Please reduce your request rate. (Service: Amazon S3; Status Code: 503; Error Code: SlowDown; Request ID: xxxxxxx; S3 Extended Request ID: xxxxxxxxxx; Proxy: null), S3 Extended Request ID: xxxxxxx
