### ISSUE TITLE
SQS ChangeMessageVisibilityAsync gets stalled when called with invalid message receipt handle

### ISSUE THREAD

**Issue by a-wi** [aws/aws-sdk-net#1987]
## Description
When ChangeMessageVisibilityAsync() is called with invalid message receipt handle, it doesn't throw any exception but it gets stalled instead.

## Reproduction Steps
The issue can be reproduced with this code snippet:
```
static async Task TestChangeVisibilityTimeout()
{
    using (AmazonSQSClient SQS = new AmazonSQSClient("ignore", "ignore", new AmazonSQSConfig { ServiceURL = "http://localhost:4566" }))
    {
        CreateQueueResponse createQueueResp = await SQS.CreateQueueAsync("testQueue");
        try
        {
            Console.WriteLine($"[{DateTime.Now:T}] Changing visibility");
            await SQS.ChangeMessageVisibilityAsync(createQueueResp.QueueUrl, "InvalidHandle", 30);
            Console.WriteLine($"[{DateTime.Now:T}] Changed visibility");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"[{DateTime.Now:T}] Exception thrown: {ex}");
        }
        finally
        {
            await SQS.DeleteQueueAsync(createQueueResp.QueueUrl);
        }
    }
}
```

When this code is executed, the output is only like this and the application gets stalled:
`[13:46:14] Changing visibility`

Throwing AmazonSQSException is rather expected here.

Changing message visibility wit AWS CLI works as expected:

```
C:\> aws sqs create-queue --queue-name testQueue --endpoint-url http://localhost:4566
{
    "QueueUrl": "http://localhost:4566/000000000000/testQueue"
}

C:\> aws sqs change-message-visibility --queue-url http://localhost:4566/000000000000/testQueue --receipt-handle InvalidHandle --visibility-timeout 30 --endpoint-url http://localhost:4566

An error occurred (ReceiptHandleIsInvalid) when calling the ChangeMessageVisibility operation: The input receipt handle is invalid.

```

### Logs
See above.

### Environment
* SDK Version:  AWSSDK.SQS 3.7.2.28
* LocalStack: 0.14.0, 0.13.3
* OS Info: Windows 10
* Build Environment VS 2019
* Targeted .NET Platform:  Core 3.1

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @a-wi,

Good morning.

Unfortunately, I'm unable to reproduce the issue with the actual SQS service. Here's is the code that I used (notice I'm using the credentials configured at default location and default service endpoint):
```C#
using System;
using System.Threading.Tasks;
using Amazon.SQS;
using Amazon.SQS.Model;

namespace SQSChangeMessageVisibility_Issue1987
{
    class Program
    {
        static void Main(string[] args)
        {
            Task.WaitAll(TestChangeVisibilityTimeout());
        }

        static async Task TestChangeVisibilityTimeout()
        {
            using (AmazonSQSClient SQS = new AmazonSQSClient())// "ignore", "ignore", new AmazonSQSConfig { ServiceURL = "http://localhost:4566" }))
            {
                CreateQueueResponse createQueueResp = await SQS.CreateQueueAsync("testQueue");
                try
                {
                    Console.WriteLine($"[{DateTime.Now:T}] Changing visibility");
                    await SQS.ChangeMessageVisibilityAsync(createQueueResp.QueueUrl, "InvalidHandle", 30);
                    Console.WriteLine($"[{DateTime.Now:T}] Changed visibility");
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"[{DateTime.Now:T}] Exception thrown: {ex}");
                }
                finally
                {
                    await SQS.DeleteQueueAsync(createQueueResp.QueueUrl);
                }
            }
        }
    }
}
``` 

This fails immediately with the below exception:
```
[9:39:11 AM] Changing visibility
[9:39:17 AM] Exception thrown: Amazon.SQS.Model.ReceiptHandleIsInvalidException: The input receipt handle "InvalidHandle" is not a valid receipt handle.
 ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.SQS.Internal.ValidationResponseHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionStream(IRequestContext requestContext, IWebResponseData httpErrorResponse, HttpErrorResponseException exception, Stream responseStream)
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionAsync(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ExceptionHandler`1.HandleAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessExceptionAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at SQSChangeMessageVisibility_Issue1987.Program.TestChangeVisibilityTimeout() in /Users/ashdhin/dev/repros/SQSChangeMessageVisibility_Issue1987/SQSChangeMessageVisibility_Issue1987/Program.cs:line 23
```

I do notice that you might be using LocalStack. While AWS SDK for .NET should work fine with LocalStack, unfortunately, we could not support the differences in behavior here for the 3rd party platform.

Thanks,
Ashish

**Comment by a-wi** [comment]
Right, call to ChangeMessageVisibilityAsync() with invalid handle seems to work with AWS as expected but it fails with LocalStack.
This could suggest that LocalStack should be blamed but the catch is that AWS CLI works as expected (reporting error) with both AWS and LocalStack. If AWS CLI is able to handle error properly in both environments, SDK should be able to do so as well and the problem doesn't seem to lay in LocalStack.

**Comment by ashishdhingra** [comment]
> Right, call to ChangeMessageVisibilityAsync() with invalid handle seems to work with AWS as expected but it fails with LocalStack. This could suggest that LocalStack should be blamed but the catch is that AWS CLI works as expected (reporting error) with both AWS and LocalStack. If AWS CLI is able to handle error properly in both environments, SDK should be able to do so as well and the problem doesn't seem to lay in LocalStack.

@a-wi If you refer [ChangeMessageVisibilityAsync](https://github.com/aws/aws-sdk-net/blob/e677e053fbfd4bcd0f525add1c19844cde7d7e4e/sdk/src/Services/SQS/Generated/_netstandard/AmazonSQSClient.cs#L612), this is autogenerated and the result depends on the service returning the response. While AWS CLI might be working with LocalStack, we are unable to support differences in LocalStack emulated environment.
