### ISSUE TITLE
Cannot tag a Lex bot using the SDK

### ISSUE THREAD

**Issue by GurGaller** [aws/aws-sdk-net#1991]
## Description

I'm trying to add a tag to an Amazon Lex bot via the latest version of the .NET SDK.
I'm getting a validation error saying that the ARN I gave had the wrong format, *even when using the example ARN from the documentation* (which is `arn:aws:lex:us-east-2:123456789012:bot:OrderFlowers`).

## Reproduction Steps

1. Construct a new instance of the `AmazonLexModelsV2Client` class with the endpoint of an aws region 
2. Call the `TagResouceAsync` method like so:
```csharp
await _lexClient.TagResourceAsync(new TagResourceRequest
{
	ResourceARN = "arn:aws:lex:us-east-2:123456789012:bot:OrderFlowers",
	Tags =
	{
		[TagKey] = tagValue
	}
}, cancellationToken);
```

### Logs

```
Amazon.LexModelsV2.Model.ValidationException: RelativeId does not match Lex ARN format: bot:OrderFlowers
 ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionStream(IRequestContext requestContext, IWebResponseData httpErrorResponse, HttpErrorResponseException exception, Stream responseStream)
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionAsync(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ExceptionHandler`1.HandleAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessExceptionAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
```
### Environment

* SDK Version: 3.7.8.8
* Package Version: awssdk.lexmodelsv2 version 3.7.10.4
* OS Info: Windows 10
* Build Environment: MSBuild 17 using JetBrains Rider
* Targeted .NET Platform:  .NET 5.0

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @GurGaller,

Good afternoon.

Thanks for posting the question. Upon investigating further, looks like you are using the incorrect format for `ResourceARN`. Kindly refer [Tagging resources](https://docs.aws.amazon.com/lexv2/latest/dg/tagging.html) which specifies that Amazon Resource Name (ARN) for a Bot needs to be in the format `arn:aws:lex:${Region}:${account}:bot/${bot-id}` (notice the forward slash `/` before `${bot-id}`). Also `${bot-id}` is the capitalized alphanumeric string 10 characters long which could be obtained from AWS console:
![Screen Shot 2022-03-10 at 12 02 55 PM](https://user-images.githubusercontent.com/67916761/157745486-7529e0a2-dadd-4747-b179-333c815b3bae.png)

Following code works (using NuGet package `AWSSDK.LexModelsV2` version `3.7.11.20`):
```C#
using System;
using Amazon;
using Amazon.LexModelsV2;
using Amazon.LexModelsV2.Model;
using System.Collections.Generic;

namespace LexV2Tag_Issue1991
{
    class Program
    {
        static void Main(string[] args)
        {
            string lexBot = "<<Bot ID>>";// "OrderFlowers";
            string accountId = "<<Your AWS account ID>>";
            string region = "<<Region string>>";
            string lexBotArn = $"arn:aws:lex:{region}:{accountId}:bot/{lexBot}";

            using (var lexClient = new AmazonLexModelsV2Client(RegionEndpoint.GetBySystemName(region)))
            {
                Console.WriteLine($"Tagging Lex Bot {lexBotArn}...");
                var response = lexClient.TagResourceAsync(new TagResourceRequest()
                {
                    ResourceARN = lexBotArn,
                    Tags = new Dictionary<string, string>() {
                        { "tag1", "value1" },
                        { "tag2", "value2" }
                    }
                }).Result;
            }
        }
    }
}
```

Hope this helps.

Thanks,
Ashish
