### ISSUE TITLE
AmazonSQSClient.SendMessageAsync throws TaskCanceledException after messaged was published

### ISSUE THREAD

**Issue by cspital** [aws/aws-sdk-net#2004]
## Description
`AmazonSQSClient.SendMessageAsync` throws `TaskCanceledException` even though the message was published.

## Reproduction Steps
Reliable reproduction is not possible at this time. We only observed this issue during a load test. We noticed it on more than 1 occassion during the load test though.

```
System.Threading.Tasks.TaskCanceledException: A task was canceled.
    at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
    at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
    at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
    at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
    at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
    at UW.Data.Platform.Inbound.Messaging.JobPublisher.Publish(Job job, CancellationToken cancellationToken, IWorkScope work) in /src/core/Inbound.Lib/Messaging/JobPublisher.cs:line 150
    at UW.Data.Platform.Inbound.API.Services.Processors.BaseProcessor`1.Process(ProcessRequest`1 pr, CancellationToken cancellationToken) in /src/api/API/Services/Processors/BaseProcessor.cs:line 74
    at UW.Data.Platform.Inbound.API.Services.Processors.BaseProcessor`1.Process(ProcessRequest`1 pr, CancellationToken cancellationToken) in /src/api/API/Services/Processors/BaseProcessor.cs:line 74
    at UW.Data.Platform.Inbound.API.AccountingJournalEndpoints.PostAccountingJournal.HandleAsync(PostAccountingJournalRequest request, CancellationToken cancellationToken) in /src/api/API/AccountingJournalEndpoints/PostAccountingJournal.cs:line 75
    at lambda_method35(Closure , Object )
    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

Happy to provide message details in private if necessary.

### Logs
We have no logs with more information than the stack trace above.

### Environment
* SDK Version: AWSSDK.Core v3.7.7
* Package Version: AWSSDK.SQS v3.7.2.20
* OS Info: Debian 11 via mcr.microsoft.com/dotnet/aspnet:6.0-bullseye-slim
* Build Environment ubuntu:18.04
* Targeted .NET Platform:  net6

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

Seems to me if a message was successfully published, than any subsequent calls should not propagate exceptions to the caller. Collect metrics if you can, but don't blow up the call stack if you can't.

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @cspital,

Good afternoon.

Please share the application details and sample code to troubleshoot the issue. Also, are you running the code in Docker (per `OS Info` above).

Thanks,
Ashish

**Comment by cspital** [comment]
Hi, of course and thank you.

This is an ASP.NET Core application, it is serving a REST API for handling writes to the enterprise's underlying source of truth. We save the materials to s3 and send a message to a worker to march the submission through it's paces in the underlying system. What happened was the API fired a message but rolledback at the database and so the workers have been erroring on those (there were 8 instances of this happening during our load test).

We are running this application in AWS ECS Fargate instances.

I'm happy to share more details if this isn't enough, like I said this is the first time we've noticed this and it only happened at our peak tested load.

#### Controller Handler
```csharp
public override async Task<ActionResult<PostAccountingJournalResponse>> HandleAsync([FromBody] PostAccountingJournalRequest request, CancellationToken cancellationToken = default)
{
    var authorized = Authorize(request);
    if (!authorized)
    {
        return StatusCode(403, new ForbiddenResult(authorized));
    }
    
    var validated = AccountingJournalFactory.From(new WebAccountingJournalCandidateProvider(request));
    if (!validated)
    {
        foreach (var err in validated.Errors)
        {
            ModelState.AddModelError(err.Field, err.ToString());
            return ValidationProblem(ModelState);
        }
    }

    var pr = GetProcessRequest(request, validated.Item);

    var context = await _processor.Process(pr, cancellationToken); // thrown from here

    return Created(Url.Link("GetContext", new { uuid = context.Uuid.ToString() })!, new PostAccountingJournalResponse
    {
        Context = GetContextResponse.From(context)
    });
}
```

#### Processor
```csharp
public async Task<Context> Process(ProcessRequest<T> pr, CancellationToken cancellationToken = default)
{
    var publisher = _publisherFactory.GetPublisher(Resource);
    await _work.BeginTransaction(cancellationToken);

    try
    {
        var context = await CreateContext(pr.Payload, _work, cancellationToken);
        await EnrichContext(pr, context, cancellationToken);
        await publisher.Publish(GetJob(context), cancellationToken, _work); // thrown from here
        await _work.Commit(cancellationToken); // we've changed this to CancellationToken.None already
        return context;
    }
    catch
    {
        await Cleanup(); // rollback
        throw;
    }
}
```

#### Publisher
```csharp
public async Task Publish(Job job, CancellationToken cancellationToken = default, IWorkScope? work = null)
{
    try
    {
        _logger.LogInformation("Publishing {@job}", new { job.ContextId, job.ContextUuid, job.State, job.ContentLength, job.Resource, job.PlatformVersion });

        var payload = new JobPayload
        {
            ContextId = job.ContextId,
            ContextUuid = job.ContextUuid.ToString(),
            State = job.State.ToString(),
            ContentLength = job.ContentLength,
            Resource = job.Resource,
            PlatformVersion = job.PlatformVersion
        };

        await _queue.SendMessage<JobPayload>(payload, new SendParams
        {
            QueueUrl = _subbing.QueueUrl,
            Delay = TimeSpan.FromSeconds(0)
        }, cancellationToken); // thrown from here

        await _tracer.Write(new ContextEvent
        {
            ContextId = job.ContextId,
            EventType = EventType.Pushed,
            Success = true,
            ContainerId = _hosting.ContainerId,
            Detail = ContextEvent.GetDetailObject("PushedJobData", new
            {
                Sent = DateTime.UtcNow,
                Receives = job.Metadata.Receives,
                Received = job.Metadata.Received,
                Expires = job.Metadata.Expires
            })
        }, cancellationToken, work);
    }
    catch (Exception e) when (e.IsNotCancelled())
    {
        _logger.LogError(e, "Error publishing {@job}", new { job.ContextId, job.State });
        await _tracer.Write(new ContextEvent
        {
            ContextId = job.ContextId,
            EventType = EventType.Pushed,
            Success = false,
            ContainerId = _hosting.ContainerId,
            Detail = ContextEvent.GetDetailObject("PushedJobData", new
            {
                Sent = DateTime.UtcNow,
                Receives = job.Metadata.Receives,
                Received = job.Metadata.Received,
                Expires = job.Metadata.Expires
            })
        }, cancellationToken, work);
        throw;
    }
}
```

#### Queue
```csharp
public class SqsQueue : IQueueTTLReader, IQueueTTLWriter, IQueueWriter, IQueueReader, IMessageLifetimeWriter
{
    static readonly DateTime epoch = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);

    readonly IAmazonSQS _sqs;
    readonly JsonSerializerSettings _settings;

    public SqsQueue(
        IAmazonSQS amazonSQS)
    {
        _sqs = amazonSQS ?? throw new ArgumentNullException(nameof(amazonSQS));
        _settings = JsonSettings.Default;
    }

    // ...elided...

    public Task SendMessage<T>(T obj, SendParams @params, CancellationToken cancellationToken = default)
        where T : class
    {
        var body = JsonConvert.SerializeObject(obj, _settings);

        return _sqs.SendMessageAsync(new SendMessageRequest
        {
            QueueUrl = @params.QueueUrl,
            DelaySeconds = (int)@params.Delay.TotalSeconds,
            MessageBody = body
        }, cancellationToken);
    }
}
```

**Comment by BTBP** [comment]
Was there any determination as to what this issue was? We are getting these randomly as well and our setup seems to be the same: ASP.Net 6, AWSSDK.Core: 3.7.5.3, AWSSDK.S3 3.3.110.28

`{"message":"ProcessMessage failed: messageId=6e4a14d5-fb4c-453e-ad41-1b28fcb6618e error=\u0027A task was canceled.\u0027","level":"fail","logName":"OURCOMPANY.Distributed.Aws.SqsWorker.SqsWorkerService","eventId":0,"utcDateTime":"2022-09-07T20:37:13.6483638Z","exception":"System.Threading.Tasks.TaskCanceledException: A task was canceled.\n   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)\n   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)\n   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\n   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task\u00601 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)\n   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)\n   at Amazon.Runtime.Internal.HttpHandler\u00601.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.SQS.Internal.ValidationResponseHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at OURCOMPANY.Distributed.Aws.SqsWorker.QueueConsumer.DeleteMessageAsync(QueueMessage message, CancellationToken cancellationToken)\n   at OURCOMPANY.Distributed.Aws.SqsWorker.SqsWorkerServiceBase.ProcessMessage(QueueMessage message, CancellationToken stoppingToken)"} `

**Comment by dscpinheiro** [comment]
@cspital @BTBP I know it's been a while, but are either of you still running into the issue? The current reproduction code is not straightforward for us to troubleshoot.

**Comment by cspital** [comment]
I'm not sure, I don't work there anymore.

**Comment by dscpinheiro** [comment]
I see. I'll close this for now then, will re-open if another customer reports the issue again.
