### ISSUE TITLE
AmazonApiGatewayManagementApiClient.PostToConnectionAsync fails due to signature being invalid

### ISSUE THREAD

**Issue by anderspede** [aws/aws-sdk-net#2015]
### Describe the bug

Since updating AWSSDK.Core to 3.7.10.9 and above it is no longer possible to use the AmazonApiGatewayManagementApiClient to post to websocket connections as it is no longer capable of properly signing requests.

The issue appears related to [this change](https://github.com/aws/aws-sdk-net/commit/ac2471e4d9470fe04bc54b6b408aaa5be2553001) which appends a trailing slash to the ServiceURL. This, combined with the fact that the [ResourcePath is always prefixed with a slash](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/ApiGatewayManagementApi/Generated/Model/Internal/MarshallTransformations/PostToConnectionRequestMarshaller.cs#L65), creates a scenario where the request url will always contain double slashes which breaks the signing of the request.

Downgrading AWSSDK packages fixes the issue.

### Expected Behavior

Calling AmazonApiGatewayManagementApiClient.PostToConnectionAsync should not throw a signature validation exception assuming that the correct permissions are in place.

### Current Behavior

Regardless of permissions the SDK throws the following error:

```
Amazon.ApiGatewayManagementApi.AmazonApiGatewayManagementApiException : The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The Canonical String for this request should have been
'POST
/prod/%2540connections/~REDACTED~

content-length:0
content-type:application/x-www-form-urlencoded; charset=utf-8
host:~REDACTED~.execute-api.eu-west-1.amazonaws.com
user-agent:aws-sdk-dotnet-coreclr/3.7.0.144 aws-sdk-dotnet-core/3.7.10.11 .NET_Core/6.0.4 OS/Darwin_21.4.0_Darwin_Kernel_Version_21.4.0:_Fri_Mar_18_00:45:05_PDT_2022;_root:xnu-8020.101.4~15/RELEASE_X86_64 ClientAsync
x-amz-api-version:2018-11-29
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20220502T104440Z
x-amz-security-token:~REDACTED~

content-length;content-type;host;user-agent;x-amz-api-version;x-amz-content-sha256;x-amz-date;x-amz-security-token
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'

The String-to-Sign should have been
'AWS4-HMAC-SHA256
20220502T104440Z
20220502/eu-west-1/execute-api/aws4_request
dec041db993e84ebe8a13582928aaee821ae94e50b862f266810d09270c899ac'

  ----> Amazon.Runtime.Internal.HttpErrorResponseException : Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
    Stack Trace:
       at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionStream(IRequestContext requestContext, IWebResponseData httpErrorResponse, HttpErrorResponseException exception, Stream responseStream)
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionAsync(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ExceptionHandler`1.HandleAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessExceptionAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at OnConnect.Tests.FunctionTests.XXX() in /Users/dkandped/repos/dbix-backend/build-together/tst/OnConnect.Tests/FunctionTests.cs:line 50
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.DelegatingTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
--HttpErrorResponseException
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
```

### Reproduction Steps

Install any version of AWSSDK.APIGatewayManagementApi that has a dependency towards AWSSDK.Core 3.7.10.9 or higher (or simply reference AWSSDK.Core 3.7.10.9 or higher).

```csharp
var client = new AmazonApiGatewayManagementApiClient(credentials, new AmazonApiGatewayManagementApiConfig { ServiceURL = "https://~REDACTED~.execute-api.eu-west-1.amazonaws.com/websocket" });
await client.PostToConnectionAsync(new PostToConnectionRequest
{
    ConnectionId = "~REDACTED~",
    Data = new System.IO.MemoryStream()
});
```

Try to post anything to the websocket connection and you will get a signature validation error.

### Possible Solution

Revert [this breaking change](https://github.com/aws/aws-sdk-net/commit/ac2471e4d9470fe04bc54b6b408aaa5be2553001) or ensure that the client does not prefix the ResourcePath with a slash if it is already appended to the ServiceURL.

### AWS .NET SDK and/or Package version used

AWSSDK.Core 3.7.10.9 and above
AWSSDK.ApiGatewayManagementApi 3.7.0.144

### Targeted .NET Platform

.NET 6

### Operating System and version

OSX Monterey and Lambda .NET 6 managed runtime

**Comment by normj** [comment]
Thanks for reporting the issue. This was an accidental regression and we are working quickly to get a fix out soon.

**Comment by normj** [comment]
Version `3.7.10.13` of AWSSDK.Core has been released that fixes this issue. Apologize again for releasing the regression and thank you for bring it to our attention.

**Comment by anderspede** [comment]
@normj Thank you so much for the quick fix. I have upgraded to the new packages and everything works as expected. 🎉

**Comment by normj** [comment]
@anderspede Awesome thanks for verify the fix worked for you.
