### ISSUE TITLE
Default credentials profile is not not read by Amazon.SimpleEmailV2 SDK for .net

### ISSUE THREAD

**Issue by ThisIsArnab** [aws/aws-sdk-net#2026]
### Describe the bug

As per the documentation at [credential and profile resolution](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/creds-assign.html), the default credentials profile at `%USERPROFILE%\.aws\credentials` should be used by SDK, if available. However the `AWSSDK.SimpleEmailV2` SDK throws error.

### Expected Behavior

It should use the default profile as per the `credentials` file at the default location to make AWS API calls.

### Current Behavior

Exception is thrown when trying to use the default credentials (see reproduction steps). However I have verified the default credential is correct by the following code:
```C#
        var netSdkStore = new NetSDKCredentialsFile();        
        netSdkStore.TryGetProfile("default", out CredentialProfile profile);
        return profile;
```

I get the correct access key and the secret key using above and I am able to make API calls.

### Reproduction Steps

1. Create a Default profile at the location `%USERPROFILE%\.aws\credentials`.
   <img src="https://user-images.githubusercontent.com/13291820/170125554-b07381f2-29a6-4823-bd01-6ec04b9b2a63.png" width="500">
2. Use package `AWSSDK.SimpleEmailV2` Version="3.7.1.88"
3. Create client object using default constructor:
   ```C#
   AmazonSimpleEmailServiceV2Client client = AmazonSimpleEmailServiceV2Client();
   ````
4. When calling any method on `client` object, error is thrown:
   ```C#
   public async Task<CreateEmailIdentityResponse> Post()
    {
        // Create SES identity
        AmazonSimpleEmailServiceV2Client client = new AmazonSimpleEmailServiceV2Client() ;
        CreateEmailIdentityRequest request = new CreateEmailIdentityRequest()
        {
            EmailIdentity = "someone@example.com"
        };
        var response = await client.CreateEmailIdentityAsync(request);  //<- Error is thrown here

        return response;
    }
   ```
   ```
   An unhandled exception has occurred while executing the request.
      Amazon.SimpleEmailV2.AmazonSimpleEmailServiceV2Exception: The security token included in the request is invalid.
       ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
         at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
         at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
         at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
         at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
         --- End of inner exception stack trace ---
         at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionStream(IRequestContext requestContext, IWebResponseData httpErrorResponse, HttpErrorResponseException exception, Stream responseStream)
         at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionAsync(IExecutionContext executionContext, HttpErrorResponseException exception)
         at Amazon.Runtime.Internal.ExceptionHandler`1.HandleAsync(IExecutionContext executionContext, Exception exception)
         at Amazon.Runtime.Internal.ErrorHandler.ProcessExceptionAsync(IExecutionContext executionContext, Exception exception)
         at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
         at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
         at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
         at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
         at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
         at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
         at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
         at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
         at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
         at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
         at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
         at WorkerWebServerDemo.Controllers.WeatherForecastController.Post() in D:\dev_temp\WorkerWebServerDemo\Controllers\WeatherForecastController.cs:line 43
         at lambda_method5(Closure , Object )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)      
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)        
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   ``` 

### AWS .NET SDK and/or Package version used

AWSSDK.SimpleEmailV2 3.7.1.88

### Targeted .NET Platform

.NET 6

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
Hi @ThisIsArnab,

Good evening.

Few pointer:
- Are you using Visual Studio for your development and access AWS services using AWS Explorer? If yes, refer [Using the SDK Store (Windows only)](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/sdk-store.html), you might be using Windows SDK store located at `%USERPROFILE%\AppData\Local\AWSToolkit\RegisteredAccounts.json`. You may rename or move this file to a different location.
- Is environment variable `AWS_PROFILE ` set in your environment? If yes, please either remove it or update it with default profile.
- Could you check the output of `FallbackCredentialsFactory.GetCredentials()`? If these return credentials, could you check the source and credentials information to validate if the default credentials are returned?
- - If default credentials are returned as output of `FallbackCredentialsFactory.GetCredentials()`, could you try using them for your scenario? If this doesn't work, then most likely your credentials might be invalid. Kindly check by using these with other AWS services.
- - If default credentials are not returned as output of `FallbackCredentialsFactory.GetCredentials()`, then check the source.

Thanks,
Ashish

**Comment by ThisIsArnab** [comment]
Thank you @ashishdhingra that helped!

Credentials were indeed read from Windows SDK Store. Checked using `FallbackCredentialsFactory.GetCredentials()`. I found out this was set during the usage of AWS NoSql Workbench. I renamed the `RegisteredAccounts.json` file and now credentials are read from default shared credentials!
