### ISSUE TITLE
HttpRequestException is thrown when AmazonClientException expected

### ISSUE THREAD

**Issue by jinek** [aws/aws-sdk-net#2035]
### Describe the bug

I'm calling method `ListBucketsAsync` while service is not accessible.
It throws unexpected exception:

```
System.Net.Http.HttpRequestException: No such host is known.
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RedirectHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at BSH.MES.Archiver.Models.EcsStorage.BSH.MES.Foundations.Common.IHealthcheckProvider.Check() in C:\Users\jinek\Repo\mes-platform\services\BSH.MES.Archiver\Models\EcsStorage.cs:line 44
```

### Expected Behavior

AmazonClientException is thrown

### Current Behavior

HttpRequestException is thrown

### Reproduction Steps

Make a call to `ListBucketsAsync` for which server is unknown

### AWS .NET SDK and/or Package version used

AWSSDK 3.7.9.16

### Targeted .NET Platform

.NET Core 5

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
@jinek  Could you please elaborate `calling method ListBucketsAsync while service is not accessible`? Are you not using the public S3 endpoint(s)? Under what scenario you get this error?

**Comment by jinek** [comment]
Before I gathered all this information. My complain is about wrong exception type. Exception must be AmazonClientException rather than HttpRequestException.
Does this make sense?

**Comment by jinek** [comment]
>     * Elaborate `calling method ListBucketsAsync while service is not accessible`?
Server is down, for example, when we try to list all buckets

>     * Are you not using the public S3 endpoint(s)?
Correct, that is not public s3

>     * Under what scenario you get this error?
 S3 server is down, for example, when we try to list all buckets
 
>     * Share the sample code.
```
await new AmazonS3Client(
                new BasicAWSCredentials(environmentVariablesS3AccessKey, environmentVariablesS3SecretKey),
                new AmazonS3Config
                {
                    ForcePathStyle = true,
                    ServiceURL = environmentVariablesS3Url,
                    SignatureVersion = "2",
                    SignatureMethod = SigningAlgorithm.HmacSHA1,
                    UseHttp = false
                }).ListBucketsAsync();
```
>     * Share the detailed verbose logs.
How to do that?

>     * Are you using local stack (or any other virtualized environment)? We do not officially support these environments.
Yes, local, but that does not make difference I believe. 

> The error clearly states that the destination host is not accessible, may be due to network issue.
Exactly, that is network issue.


> @jinek As per my understanding, the AmazonClientException would be thrown if there is any error response from the service while processing the request and the response unmarshalled. Here there is a socket error while connecting to the endpoint while obtaining connection from Http connection pool.

Documentation states "Exception thrown by the SDK for errors that occur within the SDK" here https://docs.aws.amazon.com/sdkfornet1/latest/apidocs/html/T_Amazon_Runtime_AmazonClientException.htm
Consumer can not know whether AmazonS3Client uses HttpClient, Socket or File IO or anything else, it's internal encapsulated functionality, which can be changed in the future ( and which can not be injected by a consumer as I understand ). In this situation would be correct to re-throw exactly AmazonS3Client.
Similar to this situation, SqlClient throws SqlException when network issues happen.

**Comment by jinek** [comment]
> This issue has not received a response in 5 days. If you want to keep this issue open, please just leave a comment below and auto-close will be canceled.

What is the point to hurry to close a request from consumers? It's not necessary to work on unanswered requests, but closing the issue does not solve it.
