### ISSUE TITLE
Getting intermittent "Name or service not known" HttpRequestException while retrieving the SecretsValue from SecretsManager

### ISSUE THREAD

**Issue by ElectricVampire** [aws/aws-sdk-net#2105]
### Describe the bug

Randomly we get  "Name or service not known" HttpRequestException in our apps running in EKS and the only way to solve this problem is restart the application/api.
This exception is coming from assume role functionality even before retrieve call for GetSecrets

**Stack Trace:**
[16:31:31 ERR] Error occurred while fetching secret from SecretsManager. Secrets Request {"SecretId": "/rds-oracle/app-db-1207091ea31/TEST_APP"}
Amazon.Runtime.AmazonClientException: Error calling AssumeRole for role arn:aws:iam::506111192023:role/app-testapp-1-PodRle-testns-sa-eks-role
---> System.Net.Http.HttpRequestException: Name or service not known
---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name or service not known
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.SecurityToken.AmazonSecurityTokenServiceClient.Amazon.Runtime.SharedInterfaces.ICoreAmazonSTS_WebIdentity.CredentialsFromAssumeRoleWithWebIdentityAuthenticationAsync(String webIdentityToken, String roleArn, String roleSessionName, AssumeRoleWithWebIdentityCredentialsOptions options)
   --- End of inner exception stack trace ---
   at Amazon.SecurityToken.AmazonSecurityTokenServiceClient.Amazon.Runtime.SharedInterfaces.ICoreAmazonSTS_WebIdentity.CredentialsFromAssumeRoleWithWebIdentityAuthenticationAsync(String webIdentityToken, String roleArn, String roleSessionName, AssumeRoleWithWebIdentityCredentialsOptions options)
   at Amazon.Runtime.AssumeRoleWithWebIdentityCredentials.GenerateNewCredentialsAsync()
   at Amazon.Runtime.RefreshingAWSCredentials.GetCredentialsAsync()
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at AwsSecretsProvider.GetSecretValue(object secretRequest)

**Source Code**

_appsettings.json :_
 "AWS": {
    "SM": {
      "ServiceURL": "https://secretsmanager.us-east-1.amazonaws.com/" // Service urls for secrets manager
    }
  },

_ConfigureServices in DI :_
 var awsOptions = configuration.GetAWSOptions("AWS:SM");
 services.AddAWSService<IAmazonSecretsManager>(awsOptions);

_Actual Call For Secret:_
Inject IAmazonSecretsManager in class and call GetSecretValueAsync
var response = await _amazonSecretsManager.GetSecretValueAsync(request);

### Expected Behavior

Should not get any exception while making call for fetching the secrets

### Current Behavior

Getting an intermittent exception from sts token assume call.

### Reproduction Steps

Its not reproducible, just make a call to GetSecretsValue.

### Possible Solution

Reboot apps and apis in EKS cluster there is no other way out.

### AWS .NET SDK and/or Package version used

<PackageReference Include="AWSSDK.SecretsManager" Version="3.7.2.77" />
<PackageReference Include="AWSSDK.SecurityToken" Version="3.7.1.186" />
<PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.7.2" />

### Targeted .NET Platform

.NET CORE 3.1

### Operating System and version

AmazonLinux

**Comment by ashishdhingra** [comment]
Hi @ElectricVampire,

Good morning.

The issue could occur if the DNS for the service is not resolved.

- Are you able to retrieve values from Secrets Manager at all?
- Just curious if there is there any specific reason to hard code the `ServiceURL` for Secrets Manager, instead of relying on SDK to resolve endpoint Url for getting the secret based on region.

Came across similar issue https://github.com/aws-samples/aws-kube-codesuite/issues/4, may be it could help.

Could you also share the minimal steps to reproduce the issue:
- Steps and config to setup EKS cluster.
- Sample application code.

The documentation guide [Use AWS Secrets Manager secrets in Amazon Elastic Kubernetes Service](https://docs.aws.amazon.com/secretsmanager/latest/userguide/integrating_csi_driver.html) provides some guidance on integrating Secrets Manager and EKS, but not sure if it is relevant for you use case.

Thanks,
Ashish

**Comment by ElectricVampire** [comment]
@ashishdhingra Sorry for delayed reply, I didn't see any notification of comment.

`The issue could occur if the DNS for the service is not resolved.`
Does AWS sdk handles DNS changes in HttpClient call? I do not see they are using HttpClientFactory. What if someone do services.AddAWSService does it registers a singleton instance of HttpClient against ServiceUrl? What if behind the scenes IP for DNS get updated, does implementation is able to handle the DNS changes? 

`Are you able to retrieve values from Secrets Manager at all?`
Yes-99% of time it works, It only fails when I get exception mentioned in my ticket - only way out is to restart the app.

`Just curious if there is there any specific reason to hard code the ServiceURL for Secrets Manager, instead of relying on SDK to resolve endpoint Url for getting the secret based on region.`
There is a ClientConfig class in sdk which has lot of configurations, and I would like to control them via appsettings.json. In my case region is going to be east-1 always.

`Could you also share the minimal steps to reproduce the issue:`
I am not able to reproduce the issue on will. It occurs once in month or maybe once in two months. Code is nothing special just  register secretsManager service and try to GetSecretsValue. Btw, error is occured when calling AssumeRole api which i think get called internally when we try to create the instance of SecretsManager service.
