### ISSUE TITLE
Requests to S3 fail with signature mismatch exceptions when the object key contains space(s).

### ISSUE THREAD

**Issue by fyodorklimenko** [aws/aws-sdk-net#2463]
### Describe the bug

Requests to the S3 bucket (using `AmazonS3Client`) fail with `Amazon.S3.AmazonS3Exception: The request signature we calculated does not match the signature you provided.` when using `AWSSDK.S3` (`3.7.0.12`) and `AWSSDK.Core` (`3.7.100`) packages and object key contains space(s).

### Expected Behavior

The `AmazonS3Client`  does not throw an exception when the object key contains space(s).

### Current Behavior

Here is the stack trace from the snippet of code I attached to the ticket:

```
Unhandled exception. Amazon.S3.AmazonS3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method.
 ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RedirectHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionStream(IRequestContext requestContext, IWebResponseData httpErrorResponse, HttpErrorResponseException exception, Stream responseStream)
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionAsync(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ExceptionHandler`1.HandleAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessExceptionAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Signer.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Program.<Main>$(String[] args) in C:\Program.cs:line 15
   at Program.<Main>(String[] args)
```

### Reproduction Steps

Here is a snippet of code with the `PutObjectAsync` method.
The same happens for the `GetObjectAsync` method.
I think all other methods object-level methods throw too.

```csharp
using Amazon.S3;
using Amazon.S3.Model;

const string bucketName = ""; // Set the bucket name.
const string objectKey = "the object key with spaces";

using var client = new AmazonS3Client();

var request = new PutObjectRequest
{
    BucketName = bucketName,
    Key = objectKey
};

await client.PutObjectAsync(request); // throws `Amazon.S3.AmazonS3Exception`.
```

### AWS .NET SDK and/or Package version used

AWSSDK.Core 3.7.100
AWSSDK.S3 3.7.0.12

### Targeted .NET Platform

Reproduced using NET 6.0 (but I think it happens on any .NET platform)

### Operating System and version

Reproduced on Windows 10 and Debian (but I think it happens on any OS).

**Comment by dscpinheiro** [comment]
We just published a new version of Core (https://www.nuget.org/packages/AWSSDK.Core/3.7.100.6) that fixes this issue. I got this example to work:

```csharp
using var client = new AmazonS3Client();

var request = new PutObjectRequest
{
    BucketName = "demo",
    Key = "the object key with spaces",
    FilePath = "myfile.json"
};

await client.PutObjectAsync(request);
```

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Core" Version="3.7.100.6" />
    <PackageReference Include="AWSSDK.S3" Version="3.7.0.12" />
  </ItemGroup>
</Project>
```
