### ISSUE TITLE
DynamoDB local throws 400 error in GitHub Actions workflow

### ISSUE THREAD

**Issue by petro2050** [aws/aws-sdk-net#2472]
### Describe the bug

I'm trying to set up DynamoDB local in Github Actions to run a bunch of tests against a Web API controller. I was able to do this locally (i.e. all of my tests pass on my machine that has Docker Desktop installed); however, Github Actions fails with a 400 request when my test fixture is trying to **create** tables (which happens immediately after the Docker container starts).

The GA workflow runs on `ubuntu-latest`. I tested locally on a Windows machine.

EDIT: 

- I just tested `windows-latest`, and it failed with the same error.
- I also dropped `Docker.DotNet` and configured a container via [dynamodb-action](https://github.com/marketplace/actions/start-dynamodb-in-github-actions). It's the same issue which makes me believe this is happening on the AWS side.

### Expected Behavior

The behavior in GitHub Actions should match the local environment. I'm not sure if the issue is with GA or the AWS .NET SDK.

### Current Behavior

```
Error Message:
   System.Net.Http.HttpRequestException : Response status code does not indicate success: 400 (Bad Request).
---- System.Net.Http.HttpRequestException : Response status code does not indicate success: 400 (Bad Request).
  Stack Trace:
     at Amazon.Util.AWSSDKUtils.ExecuteHttpRequest(Uri uri, String requestType, String content, TimeSpan timeout, IWebProxy proxy, IDictionary`2 headers)
   at Amazon.Util.EC2InstanceMetadata.FetchApiToken(Int32 tries)
   at Amazon.Util.EC2InstanceMetadata.GetItems(String relativeOrAbsolutePath, Int32 tries, Boolean slurp, String token)
   at Amazon.Util.EC2InstanceMetadata.get_IAMSecurityCredentials()
   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.FetchCredentials()
   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentials()
   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentialsAsync()
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
```

### Reproduction Steps

The test fixture sets up the database like so:

    public async Task InitializeAsync()
    {
       var port = await _dockerManager.StartContainerAsync();

       _amazonDynamoDBClient = new AmazonDynamoDBClient(new AmazonDynamoDBConfig
       {
           ServiceURL = $"http://127.0.0.1:{port}"
       });

       // This line is throwing 400 in CI/CD
       await CreateTablesAsync();
    }

### AWS .NET SDK and/or Package version used

Docker.DotNet 3.125.12
Amazon.Lambda.AspNetCoreServer.Hosting 1.3.1
AWSSDK.DynamoDBv2 3.7.100.3

### Targeted .NET Platform

.NET 6

### Operating System and version

Ubuntu

**Comment by petro2050** [comment]
The issue was that I did not provide `BasicAWSCredentials`.

**Comment by denis-tazhkenov** [comment]
I had the same error because of the breaking change in version `2.0.0`, which forbid special symbols in credentials. Just leaving it here in case anyone would be searching.
