### ISSUE TITLE
Exception thrown when tryting to use serviceaccount in EKS to access CloudWatch

### ISSUE THREAD

**Issue by skovsende** [aws/aws-sdk-net#2473]
### Describe the bug

I am using a third-party library which uses AWSSDK.Cloudwatch to send logs( https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/issues/110 ). 

I am running my code in a pod on EKS and have a service account set up using AssumeRoleWithWebIdentity to get the correct permissions to communicate with Cloudwatch. The problem is that when AmazonCloudWatchLogsClient tries to use the credentials in the pod it fails with an exception.

### Expected Behavior

That the credentials from the service account is used without throwing an exception

### Current Behavior

I get this exception:

```
2022-11-07T10:21:08.9073970Z Error initializing log stream. No logs will be sent to AWS CloudWatch. Exception was System.InvalidOperationException: Assembly AWSSDK.SecurityToken could not be found or loaded. This assembly must be available at runtime to use Amazon.Runtime.AssumeRoleAWSCredentials.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'AWSSDK.SecurityToken, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'AWSSDK.SecurityToken, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, RuntimeAssembly requestingAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Amazon.Runtime.Internal.ServiceClientHelpers.GetSDKAssembly(String assemblyName)
   at Amazon.Runtime.Internal.ServiceClientHelpers.LoadServiceConfigType(String assemblyName, String serviceConfigClassName)
   at Amazon.Runtime.Internal.ServiceClientHelpers.CreateServiceConfig(String assemblyName, String serviceConfigClassName)
   at Amazon.Runtime.AssumeRoleWithWebIdentityCredentials.CreateClient()
   --- End of inner exception stack trace ---
   at Amazon.Runtime.AssumeRoleWithWebIdentityCredentials.CreateClient()
   at Amazon.Runtime.AssumeRoleWithWebIdentityCredentials.GenerateNewCredentialsAsync()
   at Amazon.Runtime.RefreshingAWSCredentials.GetCredentialsAsync()
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Serilog.Sinks.AwsCloudWatch.CloudWatchLogSink.CreateLogGroupAsync()
   at Serilog.Sinks.AwsCloudWatch.CloudWatchLogSink.EnsureInitializedAsync()
   at Serilog.Sinks.AwsCloudWatch.CloudWatchLogSink.EmitBatchAsync(IEnumerable`1 events).
```

### Reproduction Steps

Create a service account in and use it in an EKS pod when instantiating AmazonCloudWatchLogsClient using the empty construtor.

### Possible Solution

Make the AWSSDK.CloudWatchLogs nuget package have a dependency on the AWSSDK.SecurityToken nuget package.

### AWS .NET SDK and/or Package version used

AWSSDK.CloudWatchLogs 3.7.101.2

### Targeted .NET Platform

.:NET 6.0

### Operating System and version

Windows 11

**Comment by ashishdhingra** [comment]
Hi @skovsende,

Good morning.

Thanks for reporting the issue. Does your third-party library which uses `AWSSDK.Cloudwatch` also includes dependency to `AWSSDK.SecurityToken`? `AssumeRoleWithWebIdentity` uses [AmazonSecurityTokenServiceClient.AssumeRole()](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/SecurityToken/MSecurityTokenServiceAssumeRoleAssumeRoleRequest.html) behind the scenes which resides in `Amazon.SecurityToken, that requires `AWSSDK.SecurityToken` package. Could you manually add package `AWSSDK.SecurityToken` and see if it resolved the issue?

Thanks,
Ashish

**Comment by skovsende** [comment]
Yes, if I add a dependency to AWSSDK.SecurityToken it works. But that is very unintuitive and doesn't follow the principle of least surprise. If AWSSDK.CloudWatchLogs needs AWSSDK.SecurityToken to function properly I would suggest adding a dependency to that package. 

If you don't want to add that dependency, might I suggest that the code in AssumeRoleWithWebIdentityCredentials.CreateClient throws an exception that is more informative when it fails to instantiate AmazonSecurityTokenServiceConfig? Perhaps mention the fact that the AWSSDK.SecurityToken nuget package needs to be referenced as well?

But really - the first suggestion is the "correct" solution - at least it's the one that would surprise the least .net developers IMHO.

**Comment by ashishdhingra** [comment]
> AssumeRoleWithWebIdentity

@skovsende 

> Yes, if I add a dependency to AWSSDK.SecurityToken it works. But that is very unintuitive and doesn't follow the principle of least surprise. If AWSSDK.CloudWatchLogs needs AWSSDK.SecurityToken to function properly I would suggest adding a dependency to that package.
> 
> If you don't want to add that dependency, might I suggest that the code in AssumeRoleWithWebIdentityCredentials.CreateClient throws an exception that is more informative when it fails to instantiate AmazonSecurityTokenServiceConfig? Perhaps mention the fact that the AWSSDK.SecurityToken nuget package needs to be referenced as well?
> 
> But really - the first suggestion is the "correct" solution - at least it's the one that would surprise the least .net developers IMHO.

@skovsende `AWSSDK.CloudWatchLogs` is the package to send log messages to CloudWatch and perform API operations on CloudWatch. It doesn't assume any role and hence should not add dependency to `AWSSDK.SecurityToken`. The permissions are attached to EKS pod via role which lets assume a role. That role could have permission to send messages to CloudWatch logs, or, let's say, access S3 bucket. Also refer [IAM roles for service accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html)), this functionality allows application to pass JWT token to the AWS STS `AssumeRoleWithWebIdentity` API operation and receive IAM temporary role credentials. Applications which make use of this feature should include dependency on `AWSSDK.SecurityToken` package which enables to assume the role.

Thanks,
Ashish

**Comment by skovsende** [comment]
I understand how and why it works like it does. The problem is that when instantiating the client without specifying AWSCredentials it uses FallbackCredentialsFactory which has hardcoded credentials in the REset() method. Instead of figuring out which Credentials are actually available, it just uses a set list even though dependant assemblies aren't present. 

What would happen if I instantiate AmazonCloudWatchLogsClient with the empty constructor, runs in a pod under a service account that doesn't have permissions to access CloudLogs so I instead set EnvironmentVariables with credentials? My guess is that we would never get to reading the environment credentials because we fail AssumeRoleWithWebIdentityCredentials.Create() before I even get to trying to load EnvironmentVariablesAWSCredentials. So now my code fails because I don't include a dependency that I don't need...

Anyway - clearly you think this works as it should so I'm closing the issue, and then I just hope the next person running into the problem falls over this issue.

**Comment by matmany** [comment]
> AWSSDK.SecurityToken

this one worked for me

**Comment by tanukus** [comment]
I have same issue, with EKS Pods communicating with S3 service. Bad design, that dependency on Token library should be handled in the package.

**Comment by devbytyler** [comment]
This post saved me. I agree that this is annoying. The dep is only use case specific and not code specific.
