### ISSUE TITLE
Unity 2020.3 WebGl awssdk netstandard 2.0 dlopen error

### ISSUE THREAD

**Issue by M4dR0b** [aws/aws-sdk-net#2505]
### Describe the bug

Trying to use awssdk netstandard 2.0 with Untiy webGl but facing nasty issue, probably with .dll compiling or services. 
Tried to compile in all flavours and colors with different unity, target, sdk versions without success.
Everything works perfectly fine in editor.

Using:
```
<?xml version="1.0"?>
<linker>
    <assembly fullname="AWSSDK.Core" preserve="all"/>
    <assembly fullname="AWSSDK.CognitoIdentity" preserve="all"/>
	<assembly fullname="AWSSDK.S3" preserve="all"/>
	<assembly fullname="AWSSDK.SecurityToken" preserve="all"/>
	<assembly fullname="Microsoft.Bcl.AsyncInterfaces" preserve="all"/>
	<assembly fullname="System.Threading.Tasks.Extensions" preserve="all"/>
	<assembly fullname="System.Runtime.CompilerServices.Unsafe" preserve="all"/>
</linker>
```

The stacktrace from webGL indicates the eception generating in CognitoIdentity constructor:

`
Invoking error handler due to
abort("To use dlopen, you need to use Emscripten's linking support, see https://github.com/kripken/emscripten/wiki/Linking") at Error
    at jsStackTrace (http://localhost:3000/Build/Builds.framework.js:739:12)
    at stackTrace (http://localhost:3000/Build/Builds.framework.js:753:11)
    at abort (http://localhost:3000/Build/Builds.framework.js:19:44)
    at _dlopen (http://localhost:3000/Build/Builds.framework.js:9148:2)
    at __ZN6il2cpp2osL19LoadLibraryWithNameEPKci [il2cpp::os::LoadLibraryWithName(char const*, int)] (http://localhost:3000/Build/Builds.wasm:wasm-function[41588]:0xd96399)
    at __ZN6il2cpp2os13LibraryLoader22LoadDynamicLibraryImplERKNS_5utils10StringViewIcEEi [il2cpp::os::LibraryLoader::LoadDynamicLibraryImpl(il2cpp::utils::StringView<char> const&, int)] (http://localhost:3000/Build/Builds.wasm:wasm-function[41587]:0xd962a3)
    at __ZN6il2cpp2os13LibraryLoader22LoadDynamicLibraryImplERKNS_5utils10StringViewIcEE [il2cpp::os::LibraryLoader::LoadDynamicLibraryImpl(il2cpp::utils::StringView<char> const&)] (http://localhost:3000/Build/Builds.wasm:wasm-function[41586]:0xd961ee)
    at __ZN6il2cpp2os13LibraryLoader18LoadDynamicLibraryENS_5utils10StringViewIcEEi [il2cpp::os::LibraryLoader::LoadDynamicLibrary(il2cpp::utils::StringView<char>, int)] (http://localhost:3000/Build/Builds.wasm:wasm-function[41582]:0xd961b1)
    at __ZN6il2cpp2os13LibraryLoader18LoadDynamicLibraryENS_5utils10StringViewIcEE [il2cpp::os::LibraryLoader::LoadDynamicLibrary(il2cpp::utils::StringView<char>)] (http://localhost:3000/Build/Builds.wasm:wasm-function[41581]:0xd961a2)
    at __ZN6il2cpp2vm14PlatformInvoke7ResolveERK16PInvokeArguments [il2cpp::vm::PlatformInvoke::Resolve(PInvokeArguments const&)] (http://localhost:3000/Build/Builds.wasm:wasm-function[43821]:0xddc439)
    at __Z22il2cpp_codegen_resolveRK16PInvokeArguments [il2cpp_codegen_resolve(PInvokeArguments const&)] (http://localhost:3000/Build/Builds.wasm:wasm-function[44954]:0xe0167a)
    at __Z30il2cpp_codegen_resolve_pinvokeIPFiP51DATA_BLOB_t824EDD5F86832012A5E4D57F64815A06A5DB2449PDsS1_lP85CRYPTPROTECT_PROMPTSTRUCT_t74E199A5A5CE77436EB5087EEF2FAF1E88818163_marshaled_pinvokeiS1_ELm12ELm17EET_RAT0__KcRAT1__S8_20Il2CppCallConvention13Il2CppCharSetib [int (*il2cpp_codegen_resolve_pinvoke<int (*)(DATA_BLOB_t824EDD5F86832012A5E4D57F64815A06A5DB2449*, char16_t*, DATA_BLOB_t824EDD5F86832012A5E4D57F64815A06A5DB2449*, long, CRYPTPROTECT_PROMPTSTRUCT_t74E199A5A5CE77436EB5087EEF2FAF1E88818163_marshaled_pinvoke*, int, DATA_BLOB_t824EDD5F86832012A5E4D57F64815A06A5DB2449*), 12ul, 17ul>(char const (&) [12ul], char const (&) [17ul], Il2CppCallConvention, Il2CppCharSet, int, bool))(DATA_BLOB_t824EDD5F86832012A5E4D57F64815A06A5DB2449*, char16_t*, DATA_BLOB_t824EDD5F86832012A5E4D57F64815A06A5DB2449*, long, CRYPTPROTECT_PROMPTSTRUCT_t74E199A5A5CE77436EB5087EEF2FAF1E88818163_marshaled_pinvoke*, int, DATA_BLOB_t824EDD5F86832012A5E4D57F64815A06A5DB2449*)] (http://localhost:3000/Build/Builds.wasm:wasm-function[27848]:0xaa151d)
    at _UserCrypto_CryptProtectData_m35CB475CFC28355EB1579A94059F23605201705E (http://localhost:3000/Build/Builds.wasm:wasm-function[27846]:0xaa1425)
    at dynCall_iiiiiiiii (http://localhost:3000/Build/Builds.wasm:wasm-function[83544]:0x157233d)
    at Object.dynCall_iiiiiiiii (http://localhost:3000/Build/Builds.framework.js:27092:44)
    at invoke_iiiiiiiii (http://localhost:3000/Build/Builds.framework.js:17312:37)
    at _UserCrypto_Encrypt_mC46091927A279E4177694DE1DCA6D4F296687CFF (http://localhost:3000/Build/Builds.wasm:wasm-function[27845]:0xaa0d7d)
    at dynCall_iii (http://localhost:3000/Build/Builds.wasm:wasm-function[83505]:0x1571e1e)
    at Object.dynCall_iii (http://localhost:3000/Build/Builds.framework.js:26897:38)
    at invoke_iii (http://localhost:3000/Build/Builds.framework.js:16922:31)
    at _UserCrypto_get_IsUserCryptAvailable_m7FB6CC4F64076F9FFDBD5178664E28CBD9EC77B9 (http://localhost:3000/Build/Builds.wasm:wasm-function[27850]:0xaa15fb)
    at _CredentialProfileStoreChain_TryGetProfile_m115E1C55847B63C92C759EE337BC02D4436A45FF (http://localhost:3000/Build/Builds.wasm:wasm-function[33467]:0xbce1f9)
    at __ZN21InterfaceFuncInvoker2IP48Task_1_t42A068F8CEDED07EE9C45612BD13D4E4588B6525P52ByteU5BU5D_tDBBEB0E8362242FA7223000D978B0DD19D4B0726P54Dictionary_2_tDE3227CA5E7A32F5070BD24C69F42204A3ADE9D5E6InvokeEtP11Il2CppClassP12Il2CppObjectS3_S5_ [InterfaceFuncInvoker2<Task_1_t42A068F8CEDED07EE9C45612BD13D4E4588B6525*, ByteU5BU5D_tDBBEB0E8362242FA7223000D978B0DD19D4B0726*, Dictionary_2_tDE3227CA5E7A32F5070BD24C69F42204A3ADE9D5*>::Invoke(unsigned short, Il2CppClass*, Il2CppObject*, ByteU5BU5D_tDBBEB0E8362242FA7223000D978B0DD19D4B0726*, Dictionary_2_tDE3227CA5E7A32F5070BD24C69F42204A3ADE9D5*)] (http://localhost:3000/Build/Builds.wasm:wasm-function[28112]:0xaaa8b3)
    at _ProfileInternalConfiguration_Setup_m6D79F0188907415C288D3532747498F4FC09EA48 (http://localhost:3000/Build/Builds.wasm:wasm-function[32831]:0xba41da)
    at _ProfileInternalConfiguration__ctor_m9B419E3A67C3B3BF25C275AAD07445086F319BC9 (http://localhost:3000/Build/Builds.wasm:wasm-function[32830]:0xba4003)
    at _FallbackInternalConfigurationFactory_Reset_mA02AAAAD24F8EB9B505EB543D9736D16E261EBA0 (http://localhost:3000/Build/Builds.wasm:wasm-function[31811]:0xb5dc73)
    at _FallbackInternalConfigurationFactory__cctor_m0D712020F71D5ABCC8878850D16CF3491F5DEE49 (http://localhost:3000/Build/Builds.wasm:wasm-function[31810]:0xb5da87)
    at __Z66RuntimeInvoker_FalseVoid_t700C6383A2A510C2CF4DD86DABD5CA9FF70ADAC5PFvvEPK10MethodInfoPvPS4_ [RuntimeInvoker_FalseVoid_t700C6383A2A510C2CF4DD86DABD5CA9FF70ADAC5(void (*)(), MethodInfo const*, void*, void**)] (http://localhost:3000/Build/Builds.wasm:wasm-function[47269]:0xe414d3)
    at dynCall_iiiii (http://localhost:3000/Build/Builds.wasm:wasm-function[83524]:0x157203b)
    at Object.dynCall_iiiii (http://localhost:3000/Build/Builds.framework.js:26992:40)
    at invoke_iiiii (http://localhost:3000/Build/Builds.framework.js:17112:33)
    at __ZN6il2cpp2vm7Runtime6InvokeEPK10MethodInfoPvPS5_PP15Il2CppException [il2cpp::vm::Runtime::Invoke(MethodInfo const*, void*, void**, Il2CppException**)] (http://localhost:3000/Build/Builds.wasm:wasm-function[42570]:0xdb8971)
    at __ZN6il2cpp2vm7Runtime9ClassInitEP11Il2CppClass [il2cpp::vm::Runtime::ClassInit(Il2CppClass*)] (http://localhost:3000/Build/Builds.wasm:wasm-function[42573]:0xdb8b57)
    at __Z33il2cpp_codegen_runtime_class_initP11Il2CppClass [il2cpp_codegen_runtime_class_init(Il2CppClass*)] (http://localhost:3000/Build/Builds.wasm:wasm-function[44916]:0xe01282)
    at _ClientConfig_get_RetryMode_m160445D72F69CA1D77CE864155AC67975188747D (http://localhost:3000/Build/Builds.wasm:wasm-function[33256]:0xbc3b56)
    at __ZN21InterfaceFuncInvoker0IP12Il2CppObjectE6InvokeEtP11Il2CppClassS1_ [InterfaceFuncInvoker0<Il2CppObject*>::Invoke(unsigned short, Il2CppClass*, Il2CppObject*)] (http://localhost:3000/Build/Builds.wasm:wasm-function[27316]:0xa80826)
    at _AmazonServiceClient_BuildRuntimePipeline_mBD432FA9C1EF99F19C180AE782B79A1CF263EE62 (http://localhost:3000/Build/Builds.wasm:wasm-function[31088]:0xb3babe)
    at _AmazonServiceClient__ctor_mBF0730EE760A3209048451CB7B95CC3F796985AD (http://localhost:3000/Build/Builds.wasm:wasm-function[31086]:0xb3b7f5)
    at _AmazonS3Client__ctor_m441F9221229B36E9595E5DB0037E8E25A915F50B (http://localhost:3000/Build/Builds.wasm:wasm-function[27416]:0xa84466)
    at _AmazonCognitoIdentityClient__ctor_m9BCA5582B54BF239F97DA2A5DE547A5AB51E459B (http://localhost:3000/Build/Builds.wasm:wasm-function[31859]:0xb61f35)
    at _CognitoAWSCredentials__ctor_m67305AEA80A45CBFE9EFBA90D1DC65936D7EC7F5 (http://localhost:3000/Build/Builds.wasm:wasm-function[31978]:0xb69a2c)
    at _CognitoAWSCredentials__ctor_m412D51EE3B61F3EF3F413F2F7E5E4E0C93F78DDF (http://localhost:3000/Build/Builds.wasm:wasm-function[31977]:0xb699c9)
    at dynCall_viiii (http://localhost:3000/Build/Builds.wasm:wasm-function[83674]:0x157311a)
    at Object.dynCall_viiii (http://localhost:3000/Build/Builds.framework.js:27742:40)
    at invoke_viiii (http://localhost:3000/Build/Builds.framework.js:18612:26)
    at _AWSManager_Init_m5DC11E1EBD375409B74DA1017FAD63F80D8D947B (http://localhost:3000/Build/Builds.wasm:wasm-function[81964]:0x1527a3e)
    at _GameManager_Init_m54029F653587960FC4D4CE76F42E40572722AE59 (http://localhost:3000/Build/Builds.wasm:wasm-function[81974]:0x15282b0)
    at _ConfigurationSource_Invoke_mBAC172A6559EAB45BD378F7042F0035D9EB1F21E (http://localhost:3000/Build/Builds.wasm:wasm-function[28074]:0xaa8ecf)
    at _InvokableCall_Invoke_mC0E0B4D35F0795DCF2626DC15E5E92417430AAD7 (http://localhost:3000/Build/Builds.wasm:wasm-function[63337]:0x1134392)
    at _UnityEvent_Invoke_mDA46AA9786AD4C34211C6C6ADFB0963DFF430AF5 (http://localhost:3000/Build/Builds.wasm:wasm-function[77721]:0x14410d2)
`

Is awssdk compatible at all with Unity WebGL build? The docs are all over the place and it's impossible to find good references.
If it is, can we get a better guidance on Unity WebGl? 

Thank you, please let me know if other info are needed.

### Expected Behavior

awssdk services works on Unity WebGL build.

### Current Behavior

awssdk throws 

### Reproduction Steps

1. Create new Unity Project 2020.3.37f1;
2. Add required aws sdk (core, cognito, s3, securityToken) and dependency sdk (threading, task, compilerService);
3. Make a script to create `new AmazonS3Client(new CognitoAWSCredentials("key",RegionEndpoint.USEast1), RegionEndpoint.USEast1);`
4. Publish the build targetting webGL;
5. Start a server serving the build.
6. Observe the issue when webGL tries to create the AmazonS3Client class

### AWS .NET SDK and/or Package version used

AWSSDK.Core 3.7.103.4

### Targeted .NET Platform

netstandard 2.0

### Operating System and version

Windows 11

**Comment by ashishdhingra** [comment]
@M4dR0b Good afternoon. Could you please provide sample project and steps to reproduce the issue? AWS SDK for .NET has first level support for Blazor WebAssembly.

**Comment by tanvi-sutar** [comment]
Facing similar issues with unity webgl build.

**Comment by srcnalt** [comment]
Similar issue on Unity 2021 WebGL build. Using Core and Polly for audio synth. Works in editor however breaks in WebGL Builds. Will append more details.

**Comment by TuongCao-crypto** [comment]
I had same problem
awssdk netstandard 2.0

6e458229-9376-4e68-b740-e2fb94097578:10 ArgumentNullException: Value cannot be null.
Parameter name: stream
  at System.IO.StreamReader..ctor (System.IO.Stream stream, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks, System.Int32 bufferSize, System.Boolean leaveOpen) [0x00000] in <00000000000000000000000000000000>:0 
--- End of stack trace from previous location where exception was thrown ---

**Comment by TuongCao-crypto** [comment]
@ashishdhingra this issue happen on "S3Example"
