### ISSUE TITLE
Possible to get NullReferenceException in RetryPolicy

### ISSUE THREAD

**Issue by brianfeucht** [aws/aws-sdk-net#252]
Under certain conditions which I have not been able to isolate yet, it is possible to cause the RetryPolicy to throw a NullReferenceException if the exception type passed is not a AmazonServiceException.

Stacktrace:
```
System.AggregateException: One or more errors occurred. ---> System.NullReferenc
eException: Object reference not set to an instance of an object.
   at Amazon.Runtime.RetryPolicy.TryParseExceptionMessage(AmazonServiceException
 ase, DateTime& serverTime) in d:\Jenkins\jobs\build-sdkandtools-release\workspa
ce\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\RetryHandler\RetryPolicy.cs:l
ine 200
   at Amazon.Runtime.RetryPolicy.IsClockskew(IExecutionContext executionContext,
 Exception exception) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk
\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\RetryHandler\RetryPolicy.cs:line 14
1
   at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__0`1.MoveNext() in d:\
Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.
Runtime\Pipeline\RetryHandler\RetryHandler.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__0`1.MoveNext() in
d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amaz
on.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__0`1.MoveNext() in
d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amaz
on.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.<InvokeAsync>d__0`1.MoveNext()
 in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\
Amazon.S3\Internal\AmazonS3ExceptionHandler.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__0`1.MoveNext(
) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35
\Amazon.Runtime\Pipeline\Handlers\ErrorCallbackHandler.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__0`1.MoveNext() in d
:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazo
n.Runtime\Pipeline\Handlers\MetricsHandler.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)

```

**Comment by brianfeucht** [comment]
The cast at https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Pipeline/RetryHandler/RetryPolicy.cs#L120 makes it possible for the variable ase to be null.  A property of that object is then accessed later without checking for null first:
https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Pipeline/RetryHandler/RetryPolicy.cs#L200

**Comment by PavelSafronov** [comment]
Thanks for finding this issue. I'm going to patch it and release a fix as soon as possible.

**Comment by PavelSafronov** [comment]
We've released a patched version of the SDK that contains a fix for this issue.
