### ISSUE TITLE
ExpressionStatement is not correctly mapped to UpdateExpression

### ISSUE THREAD

**Issue by stgogm** [aws/aws-sdk-net#2528]
### Describe the bug

When updating an item using Document Model, the `ExpressionStatement` is not correctly mapped to `UpdateExpression`, causing an `Amazon.DynamoDBv2.AmazonDynamoDBException: Invalid UpdateExpression: The expression can not be empty;` exception to be thrown.

### Expected Behavior

The `UpdateItemAsync` method using Document Model should successfully update an item with a valid `ExpressionStatement`.

### Current Behavior

```
1106 [1] DEBUG CsAwsDynamoDB.Items (null) - Increment views...
Unhandled exception. Amazon.DynamoDBv2.AmazonDynamoDBException: Invalid UpdateExpression: The expression can not be empty;
 ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionStream(IRequestContext requestContext, IWebResponseData httpErrorResponse, HttpErrorResponseException exception, Stream responseStream)
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionAsync(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ExceptionHandler`1.HandleAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessExceptionAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Signer.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.DynamoDBv2.DocumentModel.Table.UpdateHelperAsync(Document doc, Key key, UpdateItemOperationConfig config, CancellationToken cancellationToken)
   at CsAwsDynamoDB.Items.IncrementViews() in /home/stgogm/Workspace/cs-aws-dynamodb/Items.cs:line 134
   at CsAwsDynamoDB.Items.Run() in /home/stgogm/Workspace/cs-aws-dynamodb/Items.cs:line 33
   at CsAwsDynamoDB.Program.Main(String[] args) in /home/stgogm/Workspace/cs-aws-dynamodb/Program.cs:line 10
   at CsAwsDynamoDB.Program.<Main>(String[] args)
   ```

### Reproduction Steps

```cs
var doc = new Document
{
  { "user_id", "kk3y6fqc" },
  { "timestamp", 1674674868 },
};

var config = new UpdateItemOperationConfig
{
  ReturnValues = ReturnValues.AllNewAttributes,
  ConditionalExpression = new Expression
  {
    ExpressionStatement = "ADD #v :i",
    ExpressionAttributeNames = {
      { "#v", "views" },
    },
    ExpressionAttributeValues = {
      { ":i", 1 },
    },
  },
};

await NotesTable.UpdateItemAsync(doc, config);
```

### Possible Solution

The `ExpressionStatement` value should be mapped to `UpdateExpression` on the request.

### AWS .NET SDK and/or Package version used

AWSSDK.DynamoDBv2 v3.7.101.30

### Targeted .NET Platform

.NET 6

### Operating System and version

Ubuntu

**Comment by ashishdhingra** [comment]
Hi @stgogm,

Good afternoon.

I'm unsure how you are able to execute the code and getting the mentioned error. While running the code below:
```C#
using Amazon;
using Amazon.DynamoDBv2;
using Amazon.DynamoDBv2.DocumentModel;
using Amazon.DynamoDBv2.Model;

var client = new AmazonDynamoDBClient(RegionEndpoint.USWest2);

Table table = Table.LoadTable(client, "Notes");

var doc = new Document
{
  { "user_id", "kk3y6fqc" },
  { "timestamp", 1674674868 },
};

var config = new UpdateItemOperationConfig
{
    ReturnValues = ReturnValues.AllNewAttributes,
    ConditionalExpression = new Expression
    {
        ExpressionStatement = "ADD #v :i",
        ExpressionAttributeNames =
        {
            { "#v" , "views" },
        },
        ExpressionAttributeValues =
        {
            { ":i", 1 }
        },
    }
};

var document = await table.UpdateItemAsync(doc, config);

Console.WriteLine(document);
```
exception `Amazon.DynamoDBv2.AmazonDynamoDBException: 'Invalid ConditionExpression: Syntax error; token: "ADD", near: "ADD #v"'` is thrown.

Upon checking the documentation for [DynamoDBv2: DocumentModel: UpdateItemOperationConfig](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/DynamoDBv2/TUpdateItemOperationConfig.html), it appears that the `ConditionalExpression` is `The expression that is evaluated before the update is performed. If the expression evaluates to false the update will fail and a ConditionalCheckFailedException exception will be thrown.`. Hence, `ExpressionStatement` for [Expression](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/DynamoDBv2/TExpression.html) should evaluate to `true`/`false`.

I understand you want to use scenario **ADD—updating numbers and sets** as mentioned at [Update expressions](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html#Expressions.UpdateExpressions.ADD), but this doesn't appear to be possible using the `DocumentModel`. (The example at [Example: CRUD operations using the AWS SDK for .NET document model](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ItemCRUDDotNetDocumentAPI.html) appears to demonstrate __UpdateBookPriceConditionally()__ method, but the expression statement `Price = :val` used in the example, is the conditional expression which updates the value only if `Price` value is `19`)

To use scenario **ADD—updating numbers and sets**, please refer example for **Updating an item** at [Working with items: .NET](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/LowLevelDotNetItemCRUD.html).

Thanks,
Ashish

**Comment by stgogm** [comment]
Thanks for your response @ashishdhingra! The query actually works with the other approach. I got confused over the expressions and the purpose of the `ConditionalExpression`.

Thanks again and have a great day!
