### ISSUE TITLE
Exception when updating a Schedule with copied properties

### ISSUE THREAD

**Issue by millele3** [aws/aws-sdk-net#2569]
### Describe the bug

I do not understand why there isn't a "Schedule" object, instead of a myriad of Request/Response objects containing schedule related properties.
Unfortunately, to enable/disable a schedule, it appears you have to overlay the entire schedule with a new UpdateScheduleRequest object.
So I call GetScheduleAsync, copy every property from the GetScheduleResponse object to the UpdateScheduleRequest object, and set the State to the ENABLED/DISABLED value as desired, and call UpdateScheduleAsync.

I get this error:
Amazon.Scheduler.Model.ValidationException: 1 validation error detected: Value '0' at 'flexibleTimeWindow.maximumWindowInMinutes' failed to satisfy constraint: Member must have value greater than or equal to 1

Even though the Mode is set to FlexibleTimeWindowMode.OFF

It appears this mapping is not acceptable:
UpdateScheduleRequest.FlexibleTimeWindow = GetScheduleResponse.FlexibleTimeWindow

Instead, I have to create a new FlexibleTimeWindow and set the properties individually. This is very cumbersome.

### Expected Behavior

Mapping a source schedule to an update schedule would update the schedule as expected

### Current Behavior

Amazon.Scheduler.Model.ValidationException: 1 validation error detected: Value '0' at 'flexibleTimeWindow.maximumWindowInMinutes' failed to satisfy constraint: Member must have value greater than or equal to 1
 ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionStream(IRequestContext requestContext, IWebResponseData httpErrorResponse, HttpErrorResponseException exception, Stream responseStream)
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionAsync(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ExceptionHandler`1.HandleAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessExceptionAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Signer.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at IssueDemonstration.Services.AwsSchedulerService.ChangeScheduleStateAsync(String scheduleGroupName, String scheduleName, Boolean scheduleEnabled) in C:\AsiCode\Temp\IssueDemonstration\IssueDemonstration\Services\AwsSchedulerService.cs:line 65
   at Program.<Main>$(String[] args) in C:\AsiCode\Temp\IssueDemonstration\IssueDemonstration\Program.cs:line 112

### Reproduction Steps

...
            // Get the schedule
            var schedule = await _awsScheduler.GetScheduleAsync(_options.ScheduleGroup, scheduleName);
...
            // Map GetScheduleResponse to UpdateScheduleRequest
        var updateScheduleRequest = new UpdateScheduleRequest
        {
            Description = schedule.Description,
            GroupName = schedule.GroupName,
            KmsKeyArn = schedule.KmsKeyArn,
            FlexibleTimeWindow = schedule.FlexibleTimeWindow, // THIS IS THE PROBLEM
            Name = schedule.Name,
            ScheduleExpression = schedule.ScheduleExpression,
            ScheduleExpressionTimezone = schedule.ScheduleExpressionTimezone,
            StartDate = schedule.StartDate ?? default,
            Target = schedule.Target
        };

            // Set enabled/disabled
            updateScheduleRequest.Schedule.State = enabled ? ScheduleState.ENABLED : ScheduleState.DISABLED;

...
            // Update the schedule
            var awsResponse = await _awsScheduler.UpdateScheduleAsync(updateScheduleRequest);

// EXCEPTION OCCURS

### Possible Solution

Minimally, fix the validation so each child object property doesn't need to be manually assigned.
Implement an Enable/Disable method like you have for Rules
A better fix would be to implement a common Schedule object that is used for Get/Create and Update operations.

### AWS .NET SDK and/or Package version used

AWSSDK.Scheduler 3.7.101.42

### Targeted .NET Platform

.NET 6

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
Issue is reproducible using the below modified code:
```C#
using Amazon.Scheduler.Model;
using Amazon.Scheduler;

string scheduleGroup = "default";
string scheduleName = "testschedule";
bool enabled = false;

var _awsScheduler = new AmazonSchedulerClient();
var schedule = await _awsScheduler.GetScheduleAsync(new GetScheduleRequest() { GroupName = scheduleGroup, Name = scheduleName });

// Map GetScheduleResponse to UpdateScheduleRequest
var updateScheduleRequest = new UpdateScheduleRequest
{
    Description = schedule.Description,
    GroupName = schedule.GroupName,
    KmsKeyArn = schedule.KmsKeyArn,
    FlexibleTimeWindow = schedule.FlexibleTimeWindow, // THIS IS THE PROBLEM
    Name = schedule.Name,
    ScheduleExpression = schedule.ScheduleExpression,
    ScheduleExpressionTimezone = schedule.ScheduleExpressionTimezone,
    StartDate = schedule.StartDate,
    Target = schedule.Target
};

// Set enabled/disabled
updateScheduleRequest.State = enabled ? ScheduleState.ENABLED : ScheduleState.DISABLED;

// Update the schedule
var awsResponse = await _awsScheduler.UpdateScheduleAsync(updateScheduleRequest);
```

The [FlexibleTimeWindow.MaximumWindowInMinutes](https://docs.aws.amazon.com/scheduler/latest/APIReference/API_FlexibleTimeWindow.html) is not required, at least for `FLEXIBLE` mode. However, the way we expose backing Nullable fields in AWS SDK for .NET with non-nullable properties, the issue occurs where marshaller considers [GetValueOrDefault()](https://github.com/aws/aws-sdk-net/blob/9ae9a8a1e5c24d27b6e057791a7c10826093efda/sdk/src/Services/Scheduler/Generated/Model/FlexibleTimeWindow.cs#L49) value which is invalid value `0`.

This is a breaking change in the SDK as is the case with other similar issues reported in the past.
CC @normj

**Comment by ashishdhingra** [comment]
The change has been released as part of [AWSSDK.Scheduler version 3.7.101.84](https://www.nuget.org/packages/AWSSDK.Scheduler/3.7.101.84) which changes `FlexibleTimeWindow.MaximumWindowInMinutes` as nullable type.
