### ISSUE TITLE
Exception thrown: 'System.DllNotFoundException' in AWSSDK.Core.dll: 'Unable to load shared library 'Crypt32.dll' or one of its dependencies.

### ISSUE THREAD

**Issue by khteh** [aws/aws-sdk-net#2603]
### Describe the bug

`<PackageReference Include="AWSSDK.DynamoDBv2" Version="3.7.103.3" />`
`new AmazonDynamoDBClient(_awsConfig.AccessKey, _awsConfig.SecretKey, Amazon.RegionEndpoint.GetBySystemName(_awsConfig.Region));` throws the following exception:
```
Exception has occurred: CLR/System.DllNotFoundException
Exception thrown: 'System.DllNotFoundException' in AWSSDK.Core.dll: 'Unable to load shared library 'Crypt32.dll' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/usr/lib/dotnet/shared/Microsoft.NETCore.App/7.0.5/Crypt32.dll.so: cannot open shared object file: No such file or directory
/usr/src/kyberlife/MerckPriceAvailability/src/MerckPriceAvailability/bin/Debug/net7.0/Crypt32.dll.so: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/7.0.5/libCrypt32.dll.so: cannot open shared object file: No such file or directory
/usr/src/kyberlife/MerckPriceAvailability/src/MerckPriceAvailability/bin/Debug/net7.0/libCrypt32.dll.so: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/7.0.5/Crypt32.dll: cannot open shared object file: No such file or directory
/usr/src/kyberlife/MerckPriceAvailability/src/MerckPriceAvailability/bin/Debug/net7.0/Crypt32.dll: cannot open shared object file: No such file or directory
/usr/lib/dotnet/shared/Microsoft.NETCore.App/7.0.5/libCrypt32.dll: cannot open shared object file: No such file or directory
/usr/src/kyberlife/MerckPriceAvailability/src/MerckPriceAvailability/bin/Debug/net7.0/libCrypt32.dll: cannot open shared object file: No such file or directory'
   at Amazon.Runtime.Internal.Settings.UserCrypto.CryptProtectData(DATA_BLOB& pDataIn, String szDataDescr, DATA_BLOB& pOptionalEntropy, IntPtr pvReserved, CRYPTPROTECT_PROMPTSTRUCT& pPromptStruct, CryptProtectFlags dwFlags, DATA_BLOB& pDataOut)
   at Amazon.Runtime.Internal.Settings.UserCrypto.Encrypt(String unencrypted)
```

### Expected Behavior

No exception

### Current Behavior

Exception

### Reproduction Steps

`<PackageReference Include="AWSSDK.DynamoDBv2" Version="3.7.103.3" />`
`new AmazonDynamoDBClient(_awsConfig.AccessKey, _awsConfig.SecretKey, Amazon.RegionEndpoint.GetBySystemName(_awsConfig.Region));`

### AWS .NET SDK and/or Package version used

3.7.103.3

### Targeted .NET Platform

.Net Core 7.0.105

### Operating System and version

Ubuntu 23.04

**Comment by ashishdhingra** [comment]
Hi @khteh,

Good afternoon.

Thanks for reporting the issue. Unfortunately, I'm unable to reproduce the issue. Could you please share the following:
- How is `_awsConfig` in the example code shared by you populated?
- What is the application type?
- what is the execution environment for your application?
- If possible, please share the sample code solution and steps to reproduce the issue.

Also refer similar open issue https://github.com/aws/aws-sdk-net/issues/1931, is your use case similar? Kindly note that `Crypt32.dll` is used in [UserCrypto](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Internal/Settings/UserCrypto.cs#L177) class, this is the Windows specific assembly.

Thanks,
Ashish

**Comment by khteh** [comment]
> * How is `_awsConfig` in the example code shared by you populated?
services.Configure<AWSConfig>(context.Configuration.GetSection(nameof(AWSConfig)));

> * What is the application type?
BackgroudService

> * what is the execution environment for your application?
Run it from local VSCode. `"DOTNET_ENVIRONMENT": "Development",`

> * If possible, please share the sample code solution and steps to reproduce the issue.
No. Private repo

> Also refer similar open issue #1931 and [#507 (comment)](https://github.com/aws/aws-sdk-net/issues/507#issuecomment-265607037), is your use case similar? Kindly note that `Crypt32.dll` is used in [UserCrypto](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Internal/Settings/UserCrypto.cs#L177) class, this is the Windows specific assembly.
I don't use `UserCrypto` class

**Comment by normj** [comment]
Hi @khteh 

In the code path of just creating a service client the only call to the `UserCrypto.Encrypt` is here which is a test encrypt to see if UserCrypto available. https://github.com/aws/aws-sdk-net/blob/2b806bfd8f67270ac96c2fedbef015f0c434bbaa/sdk/src/Core/Amazon.Runtime/Internal/Settings/UserCrypto.cs#L203

The catch block should be catching the `DllNotFoundException` which is the behavior I'm seeing when I try and replicate your issue.

The only other way to be calling the `Encrypt` API is if your code was saving an AWS profile into the `NetSDKCredentialsFile` which would have to be done in your code. It isn't something just done under the covers.

I want to confirm you are seeing this exception right after instantiate the `AmazonDynamoDBClient`? You aren't doing anything extra with saving profiles. Are you doing anything extra with compilation like using Native AOT?

**Comment by khteh** [comment]
![image](https://github.com/aws/aws-sdk-net/assets/3871483/dadd09f0-a4c8-413f-94d7-0532ec68893b)
Nothing extra.

**Comment by ashishdhingra** [comment]
> ![image](https://user-images.githubusercontent.com/3871483/243053058-dadd09f0-a4c8-413f-94d7-0532ec68893b.png) Nothing extra.

@khteh Unfortunately, I'm still unable to reproduce the issue locally using Visual Studio code referencing latest `AWSSDK.DynamoDBv2` package. Are you having some IDE debugger settings that is causing excepetion to be thrown?

**Comment by monty241** [comment]
There are multiple issues over the years, each time describing this issue. I do not want to open yet another one since we are moving away from CloudWatch, but instead only confirm that the problem can still occur on this code on Amazon Linux 2023 with net 8.0 and AWSSDK.CloudWatch 3.7.304 nuget package:

```
            RegionEndpoint regionEndpoint = RegionEndpoint.GetBySystemName(regionEndPointSystemName);
            AmazonCloudWatchConfig clientConfig = new AmazonCloudWatchConfig() { RegionEndpoint = regionEndpoint };
            var x = new AmazonCloudWatchClient(cloudWatchAccessKeyId, cloudWatchSecretKey, clientConfig);
```

Region name, key id en secret key are all set to a non-null value.

A first chance exception handler register the DllNotFoundException with:

```
Unable to load shared library 'Crypt32.dll' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/usr/local/hidden/Crypt32.dll.so: cannot open shared object file: No such file or directory
/usr/local/hidden/libCrypt32.dll.so: cannot open shared object file: No such file or directory
/usr/local/hidden/Crypt32.dll: cannot open shared object file: No such file or directory
/usr/local/hidden/libCrypt32.dll: cannot open shared object file: No such file or directory.
```

Last part stack trace:

```
at Amazon.Runtime.Internal.Settings.UserCrypto.CryptProtectData(DATA_BLOB& pDataIn, String szDataDescr, DATA_BLOB& pOptionalEntropy, IntPtr pvReserved, CRYPTPROTECT_PROMPTSTRUCT& pPromptStruct, CryptProtectFlags dwFlags, DATA_BLOB& pDataOut)
at Amazon.Runtime.Internal.Settings.UserCrypto.Encrypt(String unencrypted)                                                                                                  
at Amazon.Runtime.Internal.Settings.UserCrypto.get_IsUserCryptAvailable()                                                                                                   at Amazon.Runtime.CredentialManagement.CredentialProfileStoreChain.TryGetProfile(String profileName, CredentialProfile& profile)
at Amazon.Runtime.Internal.ProfileInternalConfiguration.Setup(ICredentialProfileSource source, String profileName)                                                          
at Amazon.Runtime.Internal.ProfileInternalConfiguration..ctor(ICredentialProfileSource source)                                                                              
at Amazon.Runtime.Internal.FallbackInternalConfigurationFactory.Reset()                                                                                                     
at Amazon.Runtime.Internal.FallbackInternalConfigurationFactory..cctor()                                                                                                    
at Amazon.Runtime.Internal.FallbackInternalConfigurationFactory.get_RetryMode()                                                                                             
at Amazon.Runtime.ClientConfig.get_RetryMode()                                                                                                                              
at Amazon.Runtime.AmazonServiceClient.BuildRuntimePipeline()                                                                                                                
at Amazon.Runtime.AmazonServiceClient..ctor(AWSCredentials credentials, ClientConfig config)                                                                                
at Amazon.Runtime.AmazonServiceClient..ctor(String awsAccessKeyId, String awsSecretAccessKey, ClientConfig config)
at Amazon.CloudWatch.AmazonCloudWatchClient..ctor(String awsAccessKeyId, String awsSecretAccessKey, AmazonCloudWatchConfig clientConfig)
at hidden.GetAmazonCloudWatchClient(GlobalState owner, ExecutionOptions executionOptions, String platformGroupName) in hidden.cs:line 4474
```

It might be that the logging still works. It seems that `get_IsUserCryptAvailable` just tries to use the method and ignorers the DllNotFoundException.

**Comment by dscpinheiro** [comment]
Do you still see the warning when using the latest version of the `AWSSDK.CloudWatch` package (which is `3.7.304.21` as of today)? We fixed this about a month ago (https://github.com/aws/aws-sdk-net/blob/main/changelogs/SDK.CHANGELOG.2024.md#377980-2024-04-26-1821-utc), and the SDK won't try to load that assembly outside of Windows anymore: https://github.com/aws/aws-sdk-net/blob/22a1ec96f18a31b72c4fe1bc79f8a37f2690c7a1/sdk/src/Core/Amazon.Runtime/Internal/Settings/UserCrypto.cs#L203-L212

---

If you don't mind sharing, I'm also curious to what you're moving to instead of CloudWatch.

**Comment by monty241** [comment]
Test after upgrade. No longer any errors from first chance exception! Seems fixed on net 8 with AWSSDK.CloudWatch 3.7.304.21.
