### ISSUE TITLE
QueryAsync does not appear to allow numeric range values

### ISSUE THREAD

**Issue by BryanCrotaz** [aws/aws-sdk-net#2612]
### Describe the bug

throws exception

```
public async Task<IEnumerable<TModel>> LoadFromIndexWithRange<TIndexKey>(string indexName, QueryOperator op, IEnumerable<long> rangeValues, TIndexKey indexValue)
	{
		if (indexValue == null)
		{
			return new TModel[0];
		}
		return (await dynamoContext
			.QueryAsync<TModel>(
			  indexValue,
			  op,
			  rangeValues.Select(v => (object)v),
			  new DynamoDBOperationConfig
			  {
				  TableNamePrefix = tableNamePrefix,
				  IndexName = indexName,
				  IsEmptyStringValueEnabled = true
			  }
			)
			.GetRemainingAsync()
		);
	}
```

```
System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Int64'.
   at Amazon.DynamoDBv2.Converter`1.TryTo(Object value, Primitive& p)
   at Amazon.DynamoDBv2.Converter.TryToEntry(Object value, DynamoDBEntry& entry)
   at Amazon.DynamoDBv2.Converter.ToEntry(Object value)
   at Amazon.DynamoDBv2.DynamoDBEntryConversion.ConvertToEntry(Type inputType, Object value)
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.ToDynamoDBEntry(SimplePropertyStorage propertyStorage, Object value, DynamoDBFlatConfig flatConfig, Boolean canReturnScalarInsteadOfList)
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.ConvertConditionValues(Object[] conditionValues, PropertyStorage conditionProperty, DynamoDBFlatConfig flatConfig, Boolean canReturnScalarInsteadOfList)
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.ComposeQueryFilterHelper(DynamoDBFlatConfig currentConfig, Document hashKey, IEnumerable`1 conditions, ItemStorageConfig storageConfig, List`1& indexNames)
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.ComposeQueryFilter(DynamoDBFlatConfig currentConfig, Object hashKeyValue, IEnumerable`1 conditions, ItemStorageConfig storageConfig, List`1& indexNames)
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.ConvertQueryByValue[T](Object hashKeyValue, IEnumerable`1 conditions, DynamoDBOperationConfig operationConfig, ItemStorageConfig storageConfig)
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.ConvertQueryByValue[T](Object hashKeyValue, QueryOperator op, IEnumerable`1 values, DynamoDBOperationConfig operationConfig)
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.QueryAsync[T](Object hashKeyValue, QueryOperator op, IEnumerable`1 values, DynamoDBOperationConfig operationConfig)
   at DynamoRepository`2.LoadFromIndexWithRange[TIndexKey](String indexName, QueryOperator op, IEnumerable`1 rangeValues, TIndexKey indexValue)
   at DisplaySure.Controllers.AgentController.Register(String organisationId, String machineId, String platform, String key, String name)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
```

### Expected Behavior

Expect to be able to have a numeric range

### Current Behavior

Fails with cannot cast error

### Reproduction Steps

See above

### AWS .NET SDK and/or Package version used

AWSSDK.DynamoDBv2 3.7.103.8

### Targeted .NET Platform

.Net 6

### Operating System and version

AWS Lambda

**Comment by BryanCrotaz** [comment]
Closed as bug was in my code
