### ISSUE TITLE
Exception type for protocol violation

### ISSUE THREAD

**Issue by SteveHudson** [aws/aws-sdk-net#275]
We have been working with Amazon support for several weeks on an issue where some of our customers get protocol violations uploading to S3.

I would like to log (in our existing logs) the information that support says they need.  My issue is that the protocol violation throws a AmazonServiceException instead of a AmazonS3Exception - so I don't have the id2 that support wants.

Is it possible that this exception could be changed to an AmazonS3Exception so I can log the Id2?

Here is a stack of our customer's error:

Inner exception level: 0

.ToString
DFS.Core.Objects.DFSApplicationException: An exception occurred attaching a viewable file. ---> DFS.VaultAPI.DFSVaultException: An error has occurred within the Vault DFS Module.  Please review the error log for additional details. ---> DFS.Core.Objects.DFSApplicationException: Upload Failed for file C:\Users\suzanne.iannarino\Desktop\American Univ\Revu\A-1-101 4.pdf (Begin GetObjectMetadataRequest(Key='E455C4B8-77D8-4E74-8DBD-82F6DFECEEA1/212/185/212 185 72 202 93 189 212 108 158 149 114 237 92 51 186 180 205 227 66 12.pdf') ---> **Amazon.Runtime.AmazonServiceException:** A WebException with status ServerProtocolViolation was thrown. ---> System.Net.WebException: **The server committed a protocol violation.** Section=ResponseStatusLine
   at System.Net.HttpWebRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RedirectHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.WebExceptionHandler.HandleException(IExecutionContext executionContext, WebException exception)
   at Amazon.Runtime.Internal.ExceptionHandler`1.Handle(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Signer.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3KmsHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointResolver.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3PostMarshallHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Marshaller.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3PreMarshallHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.AmazonServiceClient.Invoke[TRequest,TResponse](TRequest request, IMarshaller`2 marshaller, ResponseUnmarshaller unmarshaller)
   at Amazon.S3.AmazonS3Client.GetObjectMetadata(GetObjectMetadataRequest request)
   at DFS.Remote.Client.AmazonS3.Uploads.UploadS3File(TransferUtilityUploadRequest Request, TransferUtility Utility, KeyExistsActions ReplaceAction)
   --- End of inner exception stack trace ---
   at DFS.Remote.Client.AmazonS3.Uploads.UploadS3File(TransferUtilityUploadRequest Request, TransferUtility Utility, KeyExistsActions ReplaceAction)
   at DFS.Remote.Client.AmazonS3.Uploads.Upload(String LibraryId, TransferUtilityUploadRequest Request, KeyExistsActions ReplaceAction)
   at DFS.Remote.Client.AmazonS3.Uploads.Upload(LibraryDetails Library, String SourceFilename, String KeyName, KeyExistsActions ReplaceAction)
   at DFS.VaultAPI.Request.SendFileToVaultSpecificStorageDevice(DFSPrincipal Principal, String SourceFilename, String StorageDeviceId, String LibraryId, String CompanyId, String OwnerId, KeyExistsActions ReplaceAction, String& VaultEntryId)
   --- End of inner exception stack trace ---
   at DFS.VaultAPI.Common.HandleException(Exception vobjException)
   at DFS.VaultAPI.Request.SendFileToVaultSpecificStorageDevice(DFSPrincipal Principal, String SourceFilename, String StorageDeviceId, String LibraryId, String CompanyId, String OwnerId, KeyExistsActions ReplaceAction, String& VaultEntryId)
   at DFS.UITools.FolderDocumentsControl.CreateFormat(String vstrName, String vstrOwnerId, String vstrFilePath)
   at DFS.UITools.FolderDocumentsControl.cmniSelectExistingFileAsViewable(Object sender, ItemClickEventArgs e)
   --- End of inner exception stack trace ---

**Comment by jimfl** [comment]
Changing the exception in this case isn't going to provide any information because the id2 is in the response headers, and the HttpWebRequest has failed to parse the response.

You could enable logging per the instructions here

https://blogs.aws.amazon.com/net/post/TxZLWAOFZJQWRP/Logging-with-the-AWS-SDK-for-NET

but I suspect that you will have the same difficulty with the stage at which the exception is being thrown.

If you have a controlled repro case (a specific bucket and object), you could try enabling  unsafe header parsing. You might then get a response or a different exception which can be parsed and have the id2 in it. You can potentially combine this with logging as well.

To enable unsafe header parsing, you can add this setting to your web/app config:

    <system.net>
        <settings>
            <httpWebRequest useUnsafeHeaderParsing="true" />
        </settings>
    </system.net>

**Comment by SteveHudson** [comment]
Thank-you for your suggestions.  We have already tried logging at a couple of the clients and it has not resolved the issue.  We have also already turned on unsafe header parsing in the .exe.config and that has not solved the problem either.

I suppose you should close this discussion, because the exception type change does not make sense.  We will continue to work with support on problem.
