### ISSUE TITLE
Get-S3Object fails in user data script if credentials file is not on server

### ISSUE THREAD

**Issue by jrossfandango** [aws/aws-sdk-net#287]
I get this error if I call Get-S3Object within a user data script:

Path cannot be the empty string or all whitespace.

This is on a server that has an IAM role which has access to the S3 bucket that I am reading. I think it is related to this code being invoked by the EC2Config service which runs as Local System:

https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/AWSCredentials.cs#L484-L486

Local system does not have a personal folder, so the GetFolderPath call returns null or empty.

Here is the stack trace:

Parameter name: path
   at System.IO.Directory.GetParent(String path)
   at Amazon.Runtime.StoredProfileAWSCredentials.DetermineCredentialsFilePath(String profilesLocation)
   at Amazon.Runtime.StoredProfileAWSCredentials.IsProfileKnown(String profileName, String profilesLocation)
   at Amazon.PowerShell.Common.ICredentialsArgumentsMethods.TryGetCredentials(IAWSCredentialsArguments self, PSHost psHost, AWSPSCredentials& credentials)
   at Amazon.PowerShell.Common.ServiceCmdlet.ProcessRecord()
   at Amazon.PowerShell.Cmdlets.S3.GetS3ObjectCmdlet.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()

**Comment by jrossfandango** [comment]
The workaround is to bake this into an image:

[Environment]::SetEnvironmentVariable("HOME", "C:\Users\Administrator", "Machine")
New-Item -ItemType File -Force -Path "C:\Users\Administrator\.aws\credentials"

Then, when you bring up an instance of the baked image Get-S3Object can be invoked.

**Comment by steveataws** [comment]
Thanks for reporting this; we're working on a fix now and will update the ticket once released.

**Comment by mikepugh** [comment]
I've run into this issue as well with Read-S3Object cmdlet. The commands are executing from a custom powershell script executing via cloudformation (cfn-init) commands.

**Comment by steveataws** [comment]
A fix for this has now been released to Nuget and GitHub.

An updated Windows Installer containing the SDK and PowerShell tools is at http://sdk-for-net.amazonwebservices.com/latest/AWSToolsAndSDKForNet.msi, or the PowerShell tools can be updated from the PowerShell gallery at https://www.powershellgallery.com/packages/AWSPowerShell/.
