### ISSUE TITLE
AmazonPollyClient and AmazonS3Client constructor throwing exception

### ISSUE THREAD

**Issue by allmomoro088** [aws/aws-sdk-net#3026]
### Describe the bug

Executing the following code throws an exception on `var client = new AmazonPollyClient(credentials: c, region: RegionEndpoint.USEast1);`, I also tested with S3 and the same error happened.

`var text = "Hi, I'm finally playing here.";

var c = new BasicAWSCredentials("AKEY", "ASECRET");

var s3 = new AmazonS3Client(c, RegionEndpoint.USEast1);

var client = new AmazonPollyClient(credentials: c, region: RegionEndpoint.USEast1);

var r = new SynthesizeSpeechRequest()
{
    Engine = Engine.Neural,
    OutputFormat = OutputFormat.Mp3,
    SampleRate = "24000",
    VoiceId = VoiceId.Joanna,
    LanguageCode = LanguageCode.EnUS,
    Text = text,
    TextType = TextType.Text
};

var response = client.SynthesizeSpeechAsync(r);`

### Expected Behavior

Go through the entire code and acquire the response of SynthesizedSpeech.

### Current Behavior

Throwing exception on:
`var client = new AmazonPollyClient(credentials: c, region: RegionEndpoint.USEast1);`

### Reproduction Steps

Just paste the code provided above, use the latest SDKs available on nuget (AWSSDK.Core 3.7.200.15, AWSSDK.Polly 3.7.202.7 and AWSSDK.S3 3.7.201.13) and run the code with actual credentials.

### AWS .NET SDK and/or Package version used

AWSSDK.Core 3.7.200.15
AWSSDK.Polly 3.7.202.7
AWSSDK.S3 3.7.201.13

### Targeted .NET Platform

.Net 6.0 or .Net Framework 4.8

### Operating System and version

Windows 10, 22H2 (OS BUILD 19045.3324)

**Comment by ashishdhingra** [comment]
@allmomoro088 Thanks for opening the issue. Could you please share the exact error thrown? Also, could you please enable verbose logging using below code (works well when using console application) and share the detailed verbose logs:
```C#
Amazon.AWSConfigs.LoggingConfig.LogResponses = Amazon.ResponseLoggingOption.Always;
Amazon.AWSConfigs.LoggingConfig.LogTo = Amazon.LoggingOptions.SystemDiagnostics;
Amazon.AWSConfigs.AddTraceListener("Amazon", new System.Diagnostics.ConsoleTraceListener());
```

I just tested below S3 code using latest version of `AWSSDK.S3` and it works fine. So most likely it's the issue with your environment, may be credentials or IAM policy.
```C#
using (AmazonS3Client client = new AmazonS3Client(RegionEndpoint.USEast1))
{
    var listObjectsV2Response = await client.ListObjectsV2Async(new ListObjectsV2Request() { BucketName = "<<some-bucket>>" });
}
```

Thanks,
Ashish

**Comment by allmomoro088** [comment]
Hi @ashishdhingra 
Just ran the following code:
```
try
{
    Amazon.AWSConfigs.LoggingConfig.LogResponses = Amazon.ResponseLoggingOption.Always;
    Amazon.AWSConfigs.LoggingConfig.LogTo = Amazon.LoggingOptions.SystemDiagnostics;
    Amazon.AWSConfigs.AddTraceListener("Amazon", new System.Diagnostics.ConsoleTraceListener());

    var text = "Hi, I'm finally playing here.";

    var c = new BasicAWSCredentials("A", "B");

    var client = new AmazonPollyClient(credentials: c, region: RegionEndpoint.USEast1);

    var r = new SynthesizeSpeechRequest()
    {
        Engine = Engine.Neural,
        OutputFormat = OutputFormat.Mp3,
        SampleRate = "24000",
        VoiceId = VoiceId.Joanna,
        LanguageCode = LanguageCode.EnUS,
        Text = text,
        TextType = TextType.Text
    };

    var response = client.SynthesizeSpeechAsync(r);

    Console.WriteLine(response);
}
catch(Exception ex)
{
    Console.WriteLine(ex.Message);
    Console.WriteLine(ex.StackTrace);
    Console.WriteLine(ex.InnerException.Message);
    Console.WriteLine(ex.InnerException.StackTrace);
}
Console.Read();
```
Amazon Information: 0 : The environment variable AWS_ENABLE_ENDPOINT_DISCOVERY was not set with a value.
Amazon Information: 1 : The environment variable AWS_MAX_ATTEMPTS was not set with a value.
Amazon Information: 2 : The environment variable AWS_RETRY_MODE was not set with a value.
Amazon Information: 3 : The environment variable AWS_EC2_METADATA_SERVICE_ENDPOINT was not set with a value.
Amazon Information: 4 : The environment variable AWS_EC2_METADATA_SERVICE_ENDPOINT_MODE was not set with a value.
Amazon Information: 5 : The environment variable AWS_USE_DUALSTACK_ENDPOINT was not set with a value.
Amazon Information: 6 : The environment variable AWS_USE_FIPS_ENDPOINT was not set with a value.
Amazon Information: 7 : The environment variable AWS_IGNORE_CONFIGURED_ENDPOINT_URLS was not set with a value.
The type initializer for 'Amazon.Runtime.Internal.FallbackInternalConfigurationFactory' threw an exception.
   at Amazon.Runtime.ClientConfig.get_RetryMode()
   at Amazon.Runtime.AmazonServiceClient.BuildRuntimePipeline()
   at AWSPollyTest.Program.Main(String[] args) in E:\DEV\.NET\AWSPollyTest\AWSPollyTest\Program.cs:line 23
Invalid region endpoint provided
   at Amazon.Internal.RegionEndpointProviderV3.GetNonstandardRegionEndpoint(String regionName)
   at Amazon.Internal.RegionEndpointProviderV3.GetRegionEndpoint(String regionName)
   at Amazon.RegionEndpoint.GetEndpoint(String systemName, String displayName)
   at Amazon.Runtime.CredentialManagement.SharedCredentialsFile.TryGetProfile(String profileName, Boolean doRefresh, Boolean isSsoSession, Boolean isServicesSection, CredentialProfile& profile)
   at Amazon.Runtime.CredentialManagement.CredentialProfileStoreChain.TryGetProfile(String profileName, CredentialProfile& profile)
   at Amazon.Runtime.Internal.ProfileInternalConfiguration.Setup(ICredentialProfileSource source, String profileName)
   at Amazon.Runtime.Internal.FallbackInternalConfigurationFactory.Reset()
   at Amazon.Runtime.Internal.FallbackInternalConfigurationFactory..cctor()

**Comment by ashishdhingra** [comment]
> 
Hi @ashishdhingra
Just ran the following code:

try
{
    Amazon.AWSConfigs.LoggingConfig.LogResponses = Amazon.ResponseLoggingOption.Always;
    Amazon.AWSConfigs.LoggingConfig.LogTo = Amazon.LoggingOptions.SystemDiagnostics;
    Amazon.AWSConfigs.AddTraceListener("Amazon", new System.Diagnostics.ConsoleTraceListener());

    var text = "Hi, I'm finally playing here.";

    var c = new BasicAWSCredentials("A", "B");

    var client = new AmazonPollyClient(credentials: c, region: RegionEndpoint.USEast1);

    var r = new SynthesizeSpeechRequest()
    {
        Engine = Engine.Neural,
        OutputFormat = OutputFormat.Mp3,
        SampleRate = "24000",
        VoiceId = VoiceId.Joanna,
        LanguageCode = LanguageCode.EnUS,
        Text = text,
        TextType = TextType.Text
    };

    var response = client.SynthesizeSpeechAsync(r);

    Console.WriteLine(response);
}
catch(Exception ex)
{
    Console.WriteLine(ex.Message);
    Console.WriteLine(ex.StackTrace);
    Console.WriteLine(ex.InnerException.Message);
    Console.WriteLine(ex.InnerException.StackTrace);
}
Console.Read();
Amazon Information: 0 : The environment variable AWS_ENABLE_ENDPOINT_DISCOVERY was not set with a value.
Amazon Information: 1 : The environment variable AWS_MAX_ATTEMPTS was not set with a value.
Amazon Information: 2 : The environment variable AWS_RETRY_MODE was not set with a value.
Amazon Information: 3 : The environment variable AWS_EC2_METADATA_SERVICE_ENDPOINT was not set with a value.
Amazon Information: 4 : The environment variable AWS_EC2_METADATA_SERVICE_ENDPOINT_MODE was not set with a value.
Amazon Information: 5 : The environment variable AWS_USE_DUALSTACK_ENDPOINT was not set with a value.
Amazon Information: 6 : The environment variable AWS_USE_FIPS_ENDPOINT was not set with a value.
Amazon Information: 7 : The environment variable AWS_IGNORE_CONFIGURED_ENDPOINT_URLS was not set with a value.
The type initializer for 'Amazon.Runtime.Internal.FallbackInternalConfigurationFactory' threw an exception.
at Amazon.Runtime.ClientConfig.get_RetryMode()
at Amazon.Runtime.AmazonServiceClient.BuildRuntimePipeline()
at AWSPollyTest.Program.Main(String[] args) in E:\DEV.NET\AWSPollyTest\AWSPollyTest\Program.cs:line 23
Invalid region endpoint provided
at Amazon.Internal.RegionEndpointProviderV3.GetNonstandardRegionEndpoint(String regionName)
at Amazon.Internal.RegionEndpointProviderV3.GetRegionEndpoint(String regionName)
at Amazon.RegionEndpoint.GetEndpoint(String systemName, String displayName)
at Amazon.Runtime.CredentialManagement.SharedCredentialsFile.TryGetProfile(String profileName, Boolean doRefresh, Boolean isSsoSession, Boolean isServicesSection, CredentialProfile& profile)
at Amazon.Runtime.CredentialManagement.CredentialProfileStoreChain.TryGetProfile(String profileName, CredentialProfile& profile)
at Amazon.Runtime.Internal.ProfileInternalConfiguration.Setup(ICredentialProfileSource source, String profileName)
at Amazon.Runtime.Internal.FallbackInternalConfigurationFactory.Reset()
at Amazon.Runtime.Internal.FallbackInternalConfigurationFactory..cctor()

@allmomoro088 Could you please check your shared `credentials` file, normally under `%USERPROFILE%/.aws` and if it contains a profile (may be `default`) with invalid or blank region? If yes, kindly set it to valid region or remove `region` key all together.

Thanks,
Ashish

**Comment by allmomoro088** [comment]
@ashishdhingra ,
Thank you that worked, my credentials file had default profile without region defined. However that leads me to think, since I'll be shipping a game the possibility of creating a profile is remote and it will need access to services such as S3 and Polly, how can that be done?
Also, have that been a recent change? I ask that because I haven't changed anything in my development environment since my last development and and other softwares I developed has stopped working as well.

**Comment by ashishdhingra** [comment]
> @ashishdhingra , Thank you that worked, my credentials file had default profile without region defined. However that leads me to think, since I'll be shipping a game the possibility of creating a profile is remote and it will need access to services such as S3 and Polly, how can that be done? Also, have that been a recent change? I ask that because I haven't changed anything in my development environment since my last development and and other softwares I developed has stopped working as well.

@allmomoro088 This has not been a recent change. May be you used AWS CLI `aws configure` without specifying `region` value and it created the profile with missing region value.

Converting this issue into discussion since it is not a bug.
