### ISSUE TITLE
Amazon.AWSConfigs - Exception

### ISSUE THREAD

**Issue by xmark** [aws/aws-sdk-net#310]
Hi all, Im losing my mind trying to figure out this error I get on a testing server for a website Im trying to deploy.

ERROR Exception thrown: The type initializer for 'Amazon.AWSConfigs' threw an exception. -    at Amazon.Runtime.ClientConfig.GetDefaultRegionEndpoint() in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\ClientConfig.bcl.cs:line 42
   at Amazon.Runtime.ClientConfig..ctor() in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\ClientConfig.bcl.cs:line 38
   at Amazon.S3.AmazonS3Config..ctor() in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.S3\AmazonS3Config.cs:line 34

There is no more information on this error.

The other environments do NOT have an <aws> config section in their web.config files, so I actually also dont know how this magically works on those environments.

Any help on this would be appreciated.

**Comment by xmark** [comment]
This is my code for how I init the AmazonS3Config class:
`Amazon.S3.AmazonS3Config s3Config = new Amazon.S3.AmazonS3Config()
            {
                ServiceURL = "http://s3.amazqaswdasdasdasdasdonaws.com"
            };`

**Comment by xmark** [comment]
Ok fixed it, my issue was that I had a section definition:
`<section name="aws" type="Amazon.AWSSection, AWSSDK.Core" />`
But no section in the actual config file.

The reason why it worked in the 'other' environment is that this section definition was removed by a transformation...
