### ISSUE TITLE
Timestream SSL_ERROR_ZERO_RETURN

### ISSUE THREAD

**Issue by sarnrich** [aws/aws-sdk-net#3107]
### Describe the bug

When ingesting data to timestream with the following config I get this error over and over. 

```bash
Other Exception:  System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_ZERO_RETURN.
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Signer.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at outputs.TimestreamClientSingleMeasure.WriteRecords(List`1 records) in /source/outputs/TimestreamClientSingleMeasure.cs
```

### Expected Behavior

No or meaningful error which I can try to fix or workaround.

### Current Behavior

After letting the ingest process run for a while, then stop it and then run another ingest process the problem seems to be gone. After a short break without ingest and restarting ingestions it comes back. Somehow it looks like a coldstart, ingest scaling effect on AWS Timestream side.

### Reproduction Steps

I can not reproduce the error with a example running on my machine. It happens from a kubernetes cluster running a node js baseimage which calls a single file dotnet binary which does the ingest. Beforehand the runtime container was alpine and musl based but even switching to debian like shown produces the error.

```Dockerfile
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-executable
...
RUN dotnet restore -r linux-x64 \
  && dotnet publish -c Release -o /build -r linux-x64 --self-contained true --no-restore ingest.csproj /property:PublishSingleFile=true

FROM node:18-slim

RUN npm install --global npm@10.1.0

# Install dependencies and copy the code
RUN apt-get update
RUN apt-get install -y libicu72 curl unzip
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip
RUN ./aws/install
...
COPY --from=build-executable /build/ingest /application/bin/
# Mount volume and expose port
VOLUME ["/application"]
EXPOSE 3445
RUN cd src
CMD ["npm", "run", "start"]

```
```c#
public void Connect()
  {
    Console.WriteLine("Connecting to AWS TimeStream.");
    Console.WriteLine("using mode: single measure records");
    Console.WriteLine("using region:  " + _region);
    Console.WriteLine("using database:  " + _database);
    Console.WriteLine("using table:  " + _table);
    Console.WriteLine("using _accesskey: " + _accessKey);
    try
    {
      WriteProfile("default", _accessKey, _secretKey);

      // Recommended Timestream write client SDK configuration:
      // - Set SDK retry count to 10
      // - Set RequestTimeout to 20 seconds
      var writeClientConfig = new AmazonTimestreamWriteConfig
      {
        Timeout = TimeSpan.FromSeconds(20),
        RegionEndpoint = RegionEndpoint.GetBySystemName(_region),
        MaxErrorRetry = 10,
        MaxConnectionsPerServer = 5000
      };

      var writeClient = new AmazonTimestreamWriteClient(writeClientConfig);
      _writeClient = writeClient;
    }
    catch (Exception ex)
    {
      Console.WriteLine("Error connecting aws timestream service.", ex.Message);
    }
  }
  
  ...
  
   private async void WriteRecords(List<Record> records)
  {
    var writeRecordsRequest = new WriteRecordsRequest { DatabaseName = _database, TableName = _table, Records = records };
    try
    {
      await _writeClient.WriteRecordsAsync(writeRecordsRequest);
    }
    catch (RejectedRecordsException e)
    {
      Console.WriteLine("AWS Timestream Rejected Records Exception: " + e);
      PrintRejectedRecordsException(e);
    }
    catch (AmazonTimestreamWriteException e)
    {
      Console.WriteLine("AWS Timestream Write Exception: " + e);
    }
    catch (NullReferenceException e)
    {
      var innerException = e.InnerException;
      Console.WriteLine("NullReferenceExeption: " + e.Message);
      Console.WriteLine("Stack Trace: " + e.StackTrace);
      while (innerException != null)
      {
        Console.WriteLine("Inner Exception Message: " + innerException.Message);
        Console.WriteLine("Inner Exception Stack Trace: " + innerException.StackTrace);
        innerException = innerException.InnerException;
      }
    }
    catch (Exception e)
    {
      Console.WriteLine("Other Exception: " + e);
    }
  }

  private void WriteProfile(string profileName, string accesKey, string secretKey)
  {
    var options = new CredentialProfileOptions { AccessKey = accesKey, SecretKey = secretKey };
    var profile = new CredentialProfile(profileName, options);
    var sharedFile = new SharedCredentialsFile();
    sharedFile.RegisterProfile(profile);
  }
...
```

### AWS .NET SDK and/or Package version used

<PackageReference Include="AWSSDK.Core" Version="3.7.300" />
<PackageReference Include="AWSSDK.TimestreamWrite" Version="3.7.300" />
<TargetFramework>net6.0</TargetFramework>

### Targeted .NET Platform

.NET6.0

### Operating System and version

alpine 3.18 or debian 12

**Comment by ashishdhingra** [comment]
@sarnrich Good morning. Thanks for opening the issue. Could you please confirm if the error `SSL_ERROR_ZERO_RETURN` occurs intermittently? There was a similar [issue](https://github.com/aws/aws-sdk-net/issues/1556) reported for S3 and retry logic added for intermittent `SSL_ERROR_ZERO_RETURN` issue in `AWSSDK.Core 3.7.0.17`. So in your case, do you see retry and successful execution of your code?

**Comment by sarnrich** [comment]
update: It still happens totally randomly and mostly while starting ingesting after a certain break. I played around with base images moving from musl based alpine builds to debian linux-x64 builds. Ingesting cross regions and inner region. No matter what I do I cannot reproduce the problem rependently, but see it randomly happen either at the beginning of ingesting or also in between.
