### ISSUE TITLE
Error in DynamoDb Client After upgrading to ASP.NET Core 8

### ISSUE THREAD

**Issue by aaronolds** [aws/aws-sdk-net#3112]
### Describe the bug

Message":"Value cannot be null. (Parameter 'path1')

at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2)
   at Amazon.Internal.RegionEndpointProviderV3.GetEndpointJsonSourceStream()
   at Amazon.Internal.RegionEndpointProviderV3..ctor()
   at Amazon.RegionEndpoint.get_RegionEndpointProvider()
   at Amazon.RegionEndpoint.get_InternedRegionEndpoint()
   at Amazon.RegionEndpoint.GetEndpointForService(String serviceName, GetEndpointForServiceOptions options)
   at Amazon.Runtime.Internal.Auth.AWS4Signer.DetermineSigningRegion(IClientConfig clientConfig, String serviceName, RegionEndpoint alternateEndpoint, IRequest request)
   at Amazon.Runtime.Internal.Auth.AWS4Signer.SignRequest(IRequest request, IClientConfig clientConfig, RequestMetrics metrics, String awsAccessKeyId, String awsSecretAccessKey)
   at Amazon.Runtime.Internal.Auth.AWS4Signer.Sign(IRequest request, IClientConfig clientConfig, RequestMetrics metrics, String awsAccessKeyId, String awsSecretAccessKey)
   at Amazon.Runtime.Internal.Auth.AWS4Signer.Sign(IRequest request, IClientConfig clientConfig, RequestMetrics metrics, ImmutableCredentials credentials)
   at Amazon.Runtime.Internal.Auth.AbstractAWSSigner.SignAsync(IRequest request, IClientConfig clientConfig, RequestMetrics metrics, ImmutableCredentials credentials, CancellationToken token)
   at Amazon.Runtime.Internal.Signer.SignRequestAsync(IRequestContext requestContext)
   at Amazon.Runtime.Internal.Signer.PreInvokeAsync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Signer.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
     at TorchLake.Infrastructure.StateStore.Aws.AwsDynamoDbStateStoreClient._SaveStateAsync[TValue](String storeName, String key, TValue value, IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken)
   at TorchLake.Infrastructure.StateStore.Aws.AwsDynamoDbStateStoreClient.SaveStateAsync[TValue](String storeName, String key, TValue value, StateOptions stateOptions, IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken)

This exception is exactly the same as [this issue](https://github.com/aws/aws-sdk-net/issues/3110).  The only difference is 3110 is a Kinesis client and this is a DynamoDb client.

### Expected Behavior

Validate that path1 is not null before it tries to combine with path2

### Current Behavior

It isn't correctly validating path1.

### Reproduction Steps

Use a test console application docker build it and deploy it to EKS.  This ONLY happens on EKS.  I have a Windows and a Mac development machine that I run locally and this doesn't happen locally.

### Possible Solution

Validate that the code works correctly in Linux, specifically in a docker container running in EKS

### AWS .NET SDK and/or Package version used

ASP.NET 8.0.100
AWSSDK.DynamoDBv2 3.7.300.7"

### Targeted .NET Platform

.NET 8

### Operating System and version

AmazonLinux

**Comment by dscpinheiro** [comment]
Thanks for reporting this, we'll keep the investigation on #3110 (since it's the same problem).
