### ISSUE TITLE
AWS .Net S3 SDK throwing error "The provided token is expired" after running for more than 5-6 hours in ECS Fargate

### ISSUE THREAD

**Issue by sgsmittal226** [aws/aws-sdk-net#3141]
### Describe the bug

We are using following code that is running on ECS to get document from S3. but it starts throwing error .

I have also checked that we are also getting enviornment variable "AWS_CONTAINER_CREDENTIALS_RELATIVE_URI"
```
Error occured: The provided token has expired. while trying to get object with key advance-analytics/319/DOCUMENT/standard/bulk!843610.1.json from bucket xyz-jjjs, stacktrace:    at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionStream(IRequestContext requestContext, IWebResponseData httpErrorResponse, HttpErrorResponseException exception, Stream responseStream)
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionAsync(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ExceptionHandler`1.HandleAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessExceptionAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Signer.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)"
```   

```C#
using (var s3Client = new AmazonS3Client(new AmazonS3Config
                {
                    Timeout = TimeSpan.FromSeconds(360),
                    RetryMode = RequestRetryMode.Standard,
                    MaxErrorRetry = 5,
                    LogResponse = true,
                    ThrottleRetries = false,
                    DisableLogging = false
                }))
                {
                    GetObjectResponse file = await s3Client.GetObjectAsync(bucketName, key);

                    using var reader = new StreamReader(file.ResponseStream);
                    var contents = await reader.ReadToEndAsync();

                    return JsonUtil.Deserialize<T>(contents);
                }
```

### Expected Behavior

it should be working fine without throwing token error

### Current Behavior

We are using following code that is running on ECS to get document from S3. but it starts throwing error .

I have also checked that we are also getting enviornment variable "AWS_CONTAINER_CREDENTIALS_RELATIVE_URI"
```
Error occured: The provided token has expired. while trying to get object with key advance-analytics/319/DOCUMENT/standard/bulk!843610.1.json from bucket xyz-jjjs, stacktrace:    at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionStream(IRequestContext requestContext, IWebResponseData httpErrorResponse, HttpErrorResponseException exception, Stream responseStream)
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionAsync(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ExceptionHandler`1.HandleAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessExceptionAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Signer.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)"
```   

```C#
using (var s3Client = new AmazonS3Client(new AmazonS3Config
                {
                    Timeout = TimeSpan.FromSeconds(360),
                    RetryMode = RequestRetryMode.Standard,
                    MaxErrorRetry = 5,
                    LogResponse = true,
                    ThrottleRetries = false,
                    DisableLogging = false
                }))
                {
                    GetObjectResponse file = await s3Client.GetObjectAsync(bucketName, key);

                    using var reader = new StreamReader(file.ResponseStream);
                    var contents = await reader.ReadToEndAsync();

                    return JsonUtil.Deserialize<T>(contents);
                }
```

### Reproduction Steps

Run C# .Net Core console app as docker image as ECS task in Fargate. keep it running for atleast 10 hours

### AWS .NET SDK and/or Package version used
AWSSDK.S3, Version=3.3.0.0

### Targeted .NET Platform
.Net Core 3.1

### Operating System and version
Amazon Linux

**Comment by sgsmittal226** [comment]
@ashishdhingra thanks for responding.

we do have retry logic and we are also instantiating new client every time just to eliminate this issue but i will add this tracing you suggested to check the log

**Comment by sgsmittal226** [comment]
@ashishdhingra in most of the log. it is showing.

EnvironmentVariablesAWSCredentials 5874|2024-01-12T12:04:14.083Z|INFO|Credentials found using environment variables.

so does that mean it is not picking the credential from ECSTaskCredential ?
is that might be because i do see in enviornment variable AWS_SESSION_TOKEN getting passed automatically ?

**Comment by dscpinheiro** [comment]
Is there anything else on your ECS environment retrieving credentials? For example, assuming a role using the CLI: `aws sts assume-role --role-arn some-role --role-session-name some-session-name`

The SDK follows a credential resolution process (defined here: https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/creds-assign.html), and if the `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, and `AWS_SESSION_TOKEN` environment variables are set, they'll be used (skipping the ECS Task credentials).
