### ISSUE TITLE
On MAUI .Net 8 Android DynamoDB Operation is not supported on this platform

### ISSUE THREAD

**Issue by genifycom** [aws/aws-sdk-net#3149]
### Describe the bug

On Android, an attempt to use context.QueryAsync retuns an exception "Operation is not supported on this platform". On Windows, the same code works fine.

### Expected Behavior

DynamoDB should be available via the AWSSDK on any platform.

### Current Behavior

Same code works on Windows but not on Android

### Reproduction Steps

Add the following code to a MAUI .NET 8 project. In Windows, this works. In Android (tried several versions) this gives "Operation is not supported on this platform" on the QueryAsync line.
```
AmazonDynamoDBClient m_awsDb = new(aws_access_key, aws_secret_key, aws_region);
DynamoDBContext context = new DynamoDBContext(m_awsDb);
var pk = id;//"ITEM#56a4914b-2f99-4d58-ccfb-4b5a4c9ced1a";

string sort_key_starts_with = "ITEM#";
List<object> queryVal = new List<object>();
 queryVal.Add(sort_key_starts_with);

var myQuery = context.QueryAsync<MyObject>(pk, QueryOperator.BeginsWith, queryVal);
  var queryResult = await myQuery.GetRemainingAsync();
  return queryResult;
}
catch (AmazonDynamoDBException e) { Debug.WriteLine(e.Message); }
catch (AmazonServiceException e) { Debug.WriteLine(e.Message); }
catch (Exception e) { Debug.WriteLine(e.Message); }
```

### Possible Solution

Maybe missing Nuget packages for Android?

### AWS .NET SDK and/or Package version used

<PackageReference Include="AWSSDK.DynamoDBv2" Version="3.7.300.31" />

### Targeted .NET Platform

.NET 8

### Operating System and version

Windows 11, Android 13

**Comment by ashishdhingra** [comment]
@genifycom Thanks for reporting the issue. Instead of catching the exception, could you please share the stack trace when the exception is thrown? Also try enabling the verbose logging using the code below and shared the detailed logs:
```C#
Amazon.AWSConfigs.LoggingConfig.LogResponses = Amazon.ResponseLoggingOption.Always;
Amazon.AWSConfigs.LoggingConfig.LogTo = Amazon.LoggingOptions.Console;
Amazon.AWSConfigs.AddTraceListener("Amazon", new System.Diagnostics.ConsoleTraceListener());
```

Thanks,
Ashish

**Comment by genifycom** [comment]
Stack Trace included. Thanks.

System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Net.Http.HttpClientHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption)
   at Amazon.Runtime.HttpWebRequestMessage.GetResponse() in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_netstandard\HttpRequestMessageFactory.cs:line 495
   at Amazon.Runtime.Internal.HttpHandler`1[[System.Net.Http.HttpContent, System.Net.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].InvokeSync(IExecutionContext executionContext) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:line 87
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 57
   at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\Unmarshaller.cs:line 48
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 57
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 81
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 57
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 45
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 57
   at Amazon.Runtime.Internal.Signer.InvokeSync(IExecutionContext executionContext) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\Signer.cs:line 41
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 57
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeSync(IExecutionContext executionContext) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\EndpointDiscoveryHandler.cs:line 54
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 57
   at Amazon.Runtime.Internal.ChecksumHandler.InvokeSync(IExecutionContext executionContext) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\ChecksumHandler.cs:line 37
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 57
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeSync(IExecutionContext executionContext) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CredentialsRetriever.cs:line 72
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 57
   at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\RetryHandler\RetryHandler.cs:line 87
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 57
   at Amazon.Runtime.Internal.CompressionHandler.InvokeSync(IExecutionContext executionContext) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CompressionHandler.cs:line 39
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 57
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 45
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 57
   at Amazon.Runtime.Internal.BaseEndpointResolver.InvokeSync(IExecutionContext executionContext) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\BaseEndpointResolver.cs:line 33
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 57
   at Amazon.Runtime.Internal.Marshaller.InvokeSync(IExecutionContext executionContext) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\Marshaller.cs:line 39
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 57
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 45
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 57
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\ErrorCallbackHandler.cs:line 44
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 57
   at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\MetricsHandler.cs:line 40
   at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\RuntimePipeline.cs:line 135
   at Amazon.Runtime.AmazonServiceClient.Invoke[DescribeTableResponse](AmazonWebServiceRequest request, InvokeOptionsBase options) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\AmazonServiceClient.cs:line 224
   at Amazon.DynamoDBv2.AmazonDynamoDBClient.DescribeTable(DescribeTableRequest request) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Services\DynamoDBv2\Generated\_netstandard\AmazonDynamoDBClient.cs:line 2639
   at Amazon.DynamoDBv2.DocumentModel.Table.DescribeTable(String tableName) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Services\DynamoDBv2\Custom\DocumentModel\Table.cs:line 365
   at Amazon.Runtime.Internal.Util.Cache`2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Amazon.DynamoDBv2.Model.TableDescription, AWSSDK.DynamoDBv2, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604]].GetValueHelper(String key, Boolean& isStaleItem, Func`2 creator) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Internal\Util\SdkCache.cs:line 428
   at Amazon.Runtime.Internal.Util.Cache`2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Amazon.DynamoDBv2.Model.TableDescription, AWSSDK.DynamoDBv2, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604]].GetValue(String key, Func`2 creator, Boolean& isStaleItem) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Internal\Util\SdkCache.cs:line 315
   at Amazon.DynamoDBv2.DocumentModel.Table.LoadTableInfo(ICache`2 tableDescriptionCache) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Services\DynamoDBv2\Custom\DocumentModel\Table.cs:line 165
   at Amazon.DynamoDBv2.DocumentModel.Table.LoadTable(IAmazonDynamoDB ddbClient, TableConfig config) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Services\DynamoDBv2\Custom\DocumentModel\Table.cs:line 443
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.GetUnconfiguredTable(String tableName, Boolean disableFetchingTableMetadata) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Services\DynamoDBv2\Custom\DataModel\ContextInternal.cs:line 193
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.GetTargetTable(ItemStorageConfig storageConfig, DynamoDBFlatConfig flatConfig, DynamoDBConsumer consumer) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Services\DynamoDBv2\Custom\DataModel\ContextInternal.cs:line 141
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.ConvertQueryHelper[StrataAdmin](DynamoDBFlatConfig currentConfig, ItemStorageConfig storageConfig, QueryFilter filter, List`1 indexNames) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Services\DynamoDBv2\Custom\DataModel\ContextInternal.cs:line 1205
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.ConvertQueryByValue[StrataAdmin](Object hashKeyValue, IEnumerable`1 conditions, DynamoDBOperationConfig operationConfig, ItemStorageConfig storageConfig) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Services\DynamoDBv2\Custom\DataModel\ContextInternal.cs:line 1201
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.ConvertQueryByValue[StrataAdmin](Object hashKeyValue, QueryOperator op, IEnumerable`1 values, DynamoDBOperationConfig operationConfig) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Services\DynamoDBv2\Custom\DataModel\ContextInternal.cs:line 1189
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.QueryAsync[StrataAdmin](Object hashKeyValue, QueryOperator op, IEnumerable`1 values, DynamoDBOperationConfig operationConfig) in C:\codebuild\tmp\output\src2657205430\src\aws-sdk-net\sdk\src\Services\DynamoDBv2\Custom\DataModel\_async\Context.Async.cs:line 423
   at DataAccess.Repository.GetStrataBuildings(String id) in C:\Dev\StrataCommunication\StrataCommunication\StrataDataAccess\StrataRepository.cs:line 118

**Comment by normj** [comment]
@genifycom It looks like the error is happening when the DynamoDB high level library is doing its extra call to get the DDB table metadata. That is unfortunately a sync call which I can see Maui not allowing to avoid blocking UI for sync network calls. We put out a blog post last fall on how to remove the sync describe table call. Would it be possible to incorporate the suggestion in this post into your application?

https://aws.amazon.com/blogs/developer/improved-dynamodb-initialization-patterns-for-the-aws-sdk-for-net/

**Comment by genifycom** [comment]
Thank you Norm, that work fine.
