### ISSUE TITLE
ThirdParty.Json.LitJson.JsonMapper crashes on linux. Using nuget  AWSSDK - Amazon DynamoDB 3.2.2-beta nuget package.

### ISSUE THREAD

**Issue by bilal-fazlani** [aws/aws-sdk-net#315]
I am using [DynamoDb Nuget package](https://www.nuget.org/packages/AWSSDK.DynamoDBv2/3.2.2-beta) and when I try to read data, it throws following exception

On windows it seems to be working fine. I am using the .Net Core version.
```
 An unhandled exception was thrown by the application.
ThirdParty.Json.LitJson.JsonException: The type Amazon.Runtime.InstanceProfileAWSCredentials+SecurityInfo doesn't have the property 'Code'
   at ThirdParty.Json.LitJson.JsonMapper.ReadValue(Type inst_type, JsonReader reader)
   at ThirdParty.Json.LitJson.JsonMapper.ToObject[T](String json)
   at Amazon.Runtime.InstanceProfileAWSCredentials.GetServiceInfo()
   at Amazon.Runtime.InstanceProfileAWSCredentials.GetRefreshState()
   at Amazon.Runtime.InstanceProfileAWSCredentials.GenerateNewCredentials()
   at Amazon.Runtime.RefreshingAWSCredentials.GetCredentials()
   at Amazon.Runtime.Internal.Util.SdkCache.CacheKey.Create(AmazonServiceClient client, Object cacheType)
   at Amazon.Runtime.Internal.Util.SdkCache.GetCache[TKey,TValue](AmazonServiceClient client, Object cacheIdentifier, IEqualityComparer`1 keyComparer)
   at Amazon.DynamoDBv2.DocumentModel.Table..ctor(IAmazonDynamoDB ddbClient, String tableName, DynamoDBConsumer consumer, DynamoDBEntryConversion conversion)
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.GetTable(String tableName, DynamoDBFlatConfig flatConfig)
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.GetTargetTable(ItemStorageConfig storageConfig, DynamoDBFlatConfig flatConfig)
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.LoadHelper[T](Key key, DynamoDBFlatConfig flatConfig, ItemStorageConfig storageConfig, Boolean isAsync)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Notifications.Messaging.Recommendations.DynamoReader`1.<GetAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Notifications.Messaging.Recommendations.RecommendationService.<GetRecommendedJobs>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Notifications.Messaging.Recommendations.Controllers.RecommendationsController.<Get>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Mvc.Controllers.ControllerActionExecutor.<CastToObject>d__8`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker.<InvokeActionAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeActionFilterAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeAsync>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler.<RouteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.AspNet.Mvc.Routing.InnerAttributeRoute.<RouteAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.AspNet.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.<>c__DisplayClass32_0.<<Start>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.AspNet.Server.Kestrel.Http.Frame.<RequestProcessingAsync>d__79.MoveNext()
```

**Comment by normj** [comment]
Thanks for letting us know. I believe I know what the issue is and I will get a fix out soon.

**Comment by bryanroscoe** [comment]
I am also getting basically the same error when attempting to use an IAM Role in a docker container on ECS optimized linux image using .Net Core.

```
"System.AggregateException: One or more errors occurred. ---> ThirdParty.Json.LitJson.JsonException: The type Amazon.Runtime.InstanceProfileAWSCredentials+SecurityInfo doesn't have the property 'Code'
   at ThirdParty.Json.LitJson.JsonMapper.ReadValue(Type inst_type, JsonReader reader)
   at ThirdParty.Json.LitJson.JsonMapper.ToObject[T](String json)
   at Amazon.Runtime.InstanceProfileAWSCredentials.GetServiceInfo()
   at Amazon.Runtime.InstanceProfileAWSCredentials.GetRefreshState()
   at Amazon.Runtime.InstanceProfileAWSCredentials.GenerateNewCredentials()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by bilal-fazlani** [comment]
Is there a workaround i can use until it is fixed ?

**Comment by normj** [comment]
I have the fix but I decided to merge in the latest changes from the master branch which is taking longer than I expected because of the the recent merge of Unity support into master. If the merge looks like it will take much longer then I'll hold off on the master merge and put out a patch fix for just this issue.

**Comment by bilal-fazlani** [comment]
Thank you !

**Comment by bryanroscoe** [comment]
Thanks! Will you be updating the nuget package anytime soon?

**Comment by normj** [comment]
Merging in master was taking too long and not something I want to rush. I backed off for now to get a patch out to unblock you. 3.2.2.1 was just released to NuGet.

**Comment by bilal-fazlani** [comment]
Thank you very much for your quick response and resolution. I just
downloaded.

**Comment by bryanroscoe** [comment]
Thanks! Downloading now.
