### ISSUE TITLE
DDb Indexer Property during SerializeToDocument causes TargetParameterCountException

### ISSUE THREAD

**Issue by taesookim0412** [aws/aws-sdk-net#3166]
### Describe the bug

Attempting to save/serialize a DynamoDB class with SaveAsync / SaveHelper causes the reflection to attempt to call GetValue with limited parameters when there is an indexer property and save fails / throws an exception.

### Expected Behavior

I would like if there is some workaround that is also fast and/or acknowledgement that this is an issue that is already ignored because I want an indexer property with my serialized class.

### Current Behavior

SaveAsync fails:
```
System.Reflection.TargetParameterCountException
  HResult=0x8002000E
  Message=Parameter count mismatch.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.TryGetValue(Object instance, MemberInfo member, Object& value)
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.PopulateItemStorage(Object toStore, ItemStorage storage, DynamoDBFlatConfig flatConfig, Boolean keysOnly, Boolean ignoreNullValues)
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.SerializeToDocument(Object value, Type type, DynamoDBFlatConfig flatConfig)
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.ToDynamoDBEntry(SimplePropertyStorage propertyStorage, Object value, DynamoDBFlatConfig flatConfig, Boolean canReturnScalarInsteadOfList)
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.PopulateItemStorage(Object toStore, ItemStorage storage, DynamoDBFlatConfig flatConfig, Boolean keysOnly, Boolean ignoreNullValues)
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.SerializeToDocument(Object value, Type type, DynamoDBFlatConfig flatConfig)
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.ToDynamoDBEntry(SimplePropertyStorage propertyStorage, Object value, DynamoDBFlatConfig flatConfig, Boolean canReturnScalarInsteadOfList)
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.PopulateItemStorage(Object toStore, ItemStorage storage, DynamoDBFlatConfig flatConfig, Boolean keysOnly, Boolean ignoreNullValues)
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.<SaveHelperAsync>d__42.MoveNext()
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.<SaveHelperAsync>d__41`1.MoveNext()
```
Problem area:
```
        private static bool TryGetValue(object instance, MemberInfo member, out object value)
        {
            FieldInfo fieldInfo = member as FieldInfo;
            PropertyInfo propertyInfo = member as PropertyInfo;
            if (fieldInfo != null)
            {
                value = fieldInfo.GetValue(instance);
                return true;
            }

            if (propertyInfo != null)
            {
                value = propertyInfo.GetValue(instance, null);
                return true;
            }

            value = null;
            return false;
        }
```
The exact area is probably here:
```
            if (propertyInfo != null)
            {
                value = propertyInfo.GetValue(instance, null);
                return true;
            }
```

### Reproduction Steps

1. Create a class with DynamoDBTable annotation
2. A nested property has an indexer property
3. Create indexer 
for example 
```
        public T this[int index]
        {
            get
            {
                return Items[index];
            }
            set
            {
                Items[index] = value;
            }
        }
```

The use was like this 
```
[DynamoDBTable("A")]
public class A {
    public B B {get;set;}
    public A() {}
}
public class B:C {

    public B() {}
}
public class C {
    public D<E> {get; set;}
    public C() {}
}

public class D<T> {
    public T[] Items {get;set;}
        public T this[int index]
        {
            get
            {
                return Items[index];
            }
            set
            {
                Items[index] = value;
            }
        }
}
```
Sorry if it's kind of confusing but I think this was the case it was used in although I think it would happen in any case with an indexer.
4. Attempt to save with DynamoDBContext.SaveAsync

### Possible Solution

No workarounds for having both get and set on the indexer.

References:
Maybe only a read-only indexer
https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/indexers/

Good answer on SO:
https://stackoverflow.com/questions/46855438/c-sharp-parameter-count-mismatch-converting-list-to-datatable

```
If this line is throwing the exception

values[i] = Props[i].GetValue(item, null); 
...then it means you have a property that requires a parameter. In c#, the only type of property that takes a parameter is an [indexer](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/indexers/using-indexers). My guess is you should just exclude the indexer from the loop.

See [this question](https://stackoverflow.com/questions/4746188/propertyinfo-is-the-property-an-indexer) which tells you how to detect an indexer.

You can probably fix this by changing one line. Change this...
```

Questionable solution:
```
private static bool TryGetValue(object instance, MemberInfo member, out object value)
{
    FieldInfo fieldInfo = member as FieldInfo;
    PropertyInfo propertyInfo = member as PropertyInfo;

    if (fieldInfo != null)
    {
        value = fieldInfo.GetValue(instance);
        return true;
    }

    if (propertyInfo != null)
    {
        // Check if the property is an indexer and skip it
        if (propertyInfo.GetIndexParameters().Length > 0)
        {
            value = null;
            return false;
        }

        value = propertyInfo.GetValue(instance, null);
        return true;
    }

    value = null;
    return false;
}
```

### AWS .NET SDK and/or Package version used

AWSSDK.DynamoDBv2 3.7.104.1

### Targeted .NET Platform

.NET 6

### Operating System and version

Windows 10

**Comment by tnurmi82** [comment]
I'm observing this same issue. I have slightly newer version `3.7.301.7` of AWSSDK.DynamoDBv2 but it behaves the same.

**Comment by tnurmi82** [comment]
In my case I was trying to save `List<MyClass> items` in one SaveAsync call, like `await ddbContext.SaveAsync(items)`.
It helped to just save each item individually:
`foreach (var item in items)
{
  await Program.DynamoDBContext.SaveAsync(car);
}`

Good enough for me at this point.

**Comment by ashishdhingra** [comment]
@tnurmi82 Good afternoon. Could you please let us know if you are still blocked and/or have a workaround? Or if this is still an issue?

Thanks,
Ashish

**Comment by tnurmi82** [comment]
@ashishdhingra I'm good, thanks!

**Comment by ashishdhingra** [comment]
@taesookim0412 Good afternoon. Could you please confirm if this is still an issue with the latest version of `AWSSDK.DynamoDBv2` and if the workaround suggested by @tnurmi82 works?
