### ISSUE TITLE
Amazon.BedrockRuntime.Model.ValidationException: "claude-3-sonnet-20240229" is not supported on this API

### ISSUE THREAD

**Issue by luntanwang** [aws/aws-sdk-net#3217]
### Describe the bug

```
public async Task<string> AwsClaudeAiCompletion(string questionid = "")
{
    string claudeModelId = "anthropic.claude-3-sonnet-20240229-v1:0";
    AmazonBedrockRuntimeClient client = new(RegionEndpoint.USEast1);
    InvokeModelResponse response = await client.InvokeModelAsync(new InvokeModelRequest()
    {
        ModelId = claudeModelId,
        Body = AWSSDKUtils.GenerateMemoryStreamFromString(RequestJson),
        ContentType = "application/json",
        Accept = "application/json"
    });
    return await response.Body.ReadStringAsync();
}
```

Amazon.BedrockRuntime.Model.ValidationException: "claude-3-sonnet-20240229" is not supported on this API. Please use the Messages API instead.(short issue description)

### Expected Behavior

no exception

### Current Behavior

```
Amazon.BedrockRuntime.Model.ValidationException: "claude-3-sonnet-20240229" is not supported on this API. Please use the Messages API instead.
 ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.ProcessHttpResponseMessage(HttpResponseMessage responseMessage)
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionStream(IRequestContext requestContext, IWebResponseData httpErrorResponse, HttpErrorResponseException exception, Stream responseStream)
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionAsync(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ExceptionHandler`1.HandleAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessExceptionAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Signer.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
```

### Reproduction Steps

```
public async Task<string> AwsClaudeAiCompletion(string questionid = "")
{
    string claudeModelId = "anthropic.claude-3-sonnet-20240229-v1:0";
    AmazonBedrockRuntimeClient client = new(RegionEndpoint.USEast1);
    InvokeModelResponse response = await client.InvokeModelAsync(new InvokeModelRequest()
    {
        ModelId = claudeModelId,
        Body = AWSSDKUtils.GenerateMemoryStreamFromString(RequestJson),
        ContentType = "application/json",
        Accept = "application/json"
    });
    return await response.Body.ReadStringAsync();
}
```

### AWS .NET SDK and/or Package version used

AWSSDK.BedrockRuntime  3.7.301.43

### Targeted .NET Platform

.Net6

### Operating System and version

Ubuntu

**Comment by dscpinheiro** [comment]
Were you using the [text completions API](https://docs.anthropic.com/claude/docs/upgrading-from-the-text-completions-api)? It looks like it's in the legacy mode for Claude 3, so you'll need to update your input to use the messages API instead.

For example, I get the exception with the first prompt but the second one works as expected:
```
// Before
{
    "prompt": "Human:\n\n What is quantum mechanics? \n\n Assistant:\n\n",
    "temperature": 0.5,
    "top_p": 0.9,
    "max_tokens_to_sample": 512
}

// After
{
    "anthropic_version": "bedrock-2023-05-31",
    "max_tokens": 512,
    "messages": [
        {
            "role": "user",
            "content": [
                {
                    "type": "text",
                    "text": "What is quantum mechanics?"
                }
            ]
        }
    ],
    "temperature": 0.5,
    "top_p": 0.9
}
```

**Comment by luntanwang** [comment]
@dscpinheiro hello bro,  i used AWSSDK.BedrockRuntime SDK in. net6 to call the interface.
![image](https://github.com/aws/aws-sdk-net/assets/8469467/e013ec26-668f-4f3d-8052-5846c504fdaf)

**Comment by dscpinheiro** [comment]
You can use `Claude 3 Sonnet` with that version of the `AWSSDK.BedrockRuntime` package, but you’ll need to address the breaking changes introduced in the Claude API. That’s something the SDK won’t be able to do for you, see the Anthropic documentation in my previous comment.

Please let us know if you have any questions.
