### ISSUE TITLE
Incorrect behaviour of S3 client with minio and Gitlab ci

### ISSUE THREAD

**Issue by denbrazh** [aws/aws-sdk-net#3237]
### Describe the bug

We are using AWS S3 Client for gitlab CI tests using docker runner. During the test, the Testcontainers.Minio container is raised using DIND. If we try to configure AWS s3 client using ServiceURL = "http://docker:{someport}" then when we try to create a bucket named, for example, "test-bucket" the s3 client will send an http request like "test-bucket.docker:{someport}" instead of "docker:{someport}/test-bucket". This causes the request to break and the bucket is not created

### Expected Behavior

s3 client should create link like "http://docker:{someport}/test-bucket"

### Current Behavior

 Failed Test1 [56 s]
  Error Message:
   System.Net.Http.HttpRequestException : Name or service not known (test-bucket.docker:32769)
  ----> System.Net.Sockets.SocketException : Name or service not known
  Stack Trace:
     at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)

### Reproduction Steps

1) Gitlab CI/CD with docker runner 
2) yaml like this 
```yaml
stages:
  - test

unit-test-job:  
  services:
    - docker:dind
  variables:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_TLS_CERTDIR: ''
      DOCKER_DRIVER: overlay2
  tags:
    - **{docker runner}**
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - echo "Running some tests"
    - cd **{Project}**
    - dotnet restore
    - dotnet test
```

3.  Create NUnit test like this
```csharp
using Amazon.S3;
using Amazon.S3.Model;
using Testcontainers.Minio;
[Test]
    public async Task Test1()
    {
        var minioContainer = new MinioBuilder()
            .Build();
        await minioContainer.StartAsync();
        var accessKey = minioContainer.GetAccessKey(); 
        var pass = minioContainer.GetSecretKey();
        var url = minioContainer.GetConnectionString();  //gonna be like "http://docker:32769/"
        var amazonS3Client = new AmazonS3Client(
            accessKey, 
            pass,
            new AmazonS3Config { ServiceURL = url});
        var putBucketRequest = new PutBucketRequest
        {
            BucketName = bucketAmazon,
        };
        var s = await amazonS3Client.PutBucketAsync(putBucketRequest);
     }
```
If we run the code locally, the test passes successfully because the ConnectionString is "http://127.0.0.1:{some port}", but when we run it in Gitlab using dind, we get an error in the logs System.Net.Http.Http.HttpRequestException : Name or service not known (test-bucket.docker:32769).

### AWS .NET SDK and/or Package version used

AWSSDK.Core 3.7.303
AWSSDK.S3 3.7.307.1

### Targeted .NET Platform

.NET 8

### Operating System and version

Gitlab ubuntu runner

**Comment by normj** [comment]
On the `AmazonS3Config` you create can you try setting the `ForcePathStyle` property to `true`?

**Comment by denbrazh** [comment]
Yes, it helps!
