### ISSUE TITLE
Incorrect behavior when deleting a message that's already been moved to the DLQ

### ISSUE THREAD

**Issue by ardove** [aws/aws-sdk-net#3238]
### Describe the bug

To reproduce this issue, you'll need the following
* One queue to act as the dead letter queue - call it "AdoveVisibilityTimeoutTestDlq"
* One queue with the visibility timeout set to 5 seconds + a redrive policy configured to the dead letter queue and set to 1 maximum receive - call it "AdoveVisibilityTimeoutTest"

Then, you'll take the following steps
* Send a message to the AdoveVisibilityTimeoutTest queue via the AWS console 
* Receive the message once to move it to the DLQ and save the receipt handle
* Wait for 10 seconds
* Delete the message using the saved receipt handle
* Continue deleting the message until the error below pops up

There's sample code for this in the repro steps.

### Expected Behavior

The DeleteMessageAsync method probably needs to succeed for some period of time to deal with race conditions around moving items to the DLQ and programmatic deletion, but the exception at the end should really be corrected. I'd suggest raising the ReceiptHandleIsInvalid error code instead of QueueDoesNotExist. https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_DeleteMessage.html

### Current Behavior

The DeleteMessageAsync method considers the delete successful for about an hour. Then it raises an exception indicating that "The specified queue does not exist."

```
Starting delete loop...
Delete succeeded ET=0:01:09.9959369 ReceiptHandle=AQEBwpbOjN4qpDJd4ATkAUroQ+afG2mXciJJvIDO1zYrrWsGK3qXdmw6nLhWlFV7LCF3iGAR/Ov8IxZLrod7rdnxcXgZ4a4q9pBi3XkeJbWgIXPS/MboMM3e9uakrnLpXOs5Pee9W8aRhqIlQ66DbM6fR6Nw/oASY6fOmv0IkRwAiye5FtPpWodMs7ve2e4Trhfsl7NU5S81FqPz1GfUQHcL8qCVsi7OjrbBI4t1Q17c2NqYpREutWg62MU0XNSsVvdIoOIPNQbCZIR1WDcWNlNFT3Sf5uYEMXEQj5Mi2JDuyL+OzZcjG7HE4G0rOasjiHJHAfrwEwOOf/mJCC6SVszAIVGQVRRn+Rx9q3CeFyytFf8fTtmCaxdrByTfbBmeL7EXmZN6pthY44xb3HfnU8q5qw==
...
Delete succeeded ET=1:02:28.7236989 ReceiptHandle=AQEBwpbOjN4qpDJd4ATkAUroQ+afG2mXciJJvIDO1zYrrWsGK3qXdmw6nLhWlFV7LCF3iGAR/Ov8IxZLrod7rdnxcXgZ4a4q9pBi3XkeJbWgIXPS/MboMM3e9uakrnLpXOs5Pee9W8aRhqIlQ66DbM6fR6Nw/oASY6fOmv0IkRwAiye5FtPpWodMs7ve2e4Trhfsl7NU5S81FqPz1GfUQHcL8qCVsi7OjrbBI4t1Q17c2NqYpREutWg62MU0XNSsVvdIoOIPNQbCZIR1WDcWNlNFT3Sf5uYEMXEQj5Mi2JDuyL+OzZcjG7HE4G0rOasjiHJHAfrwEwOOf/mJCC6SVszAIVGQVRRn+Rx9q3CeFyytFf8fTtmCaxdrByTfbBmeL7EXmZN6pthY44xb3HfnU8q5qw==
Delete succeeded ET=1:02:33.8205223 ReceiptHandle=AQEBwpbOjN4qpDJd4ATkAUroQ+afG2mXciJJvIDO1zYrrWsGK3qXdmw6nLhWlFV7LCF3iGAR/Ov8IxZLrod7rdnxcXgZ4a4q9pBi3XkeJbWgIXPS/MboMM3e9uakrnLpXOs5Pee9W8aRhqIlQ66DbM6fR6Nw/oASY6fOmv0IkRwAiye5FtPpWodMs7ve2e4Trhfsl7NU5S81FqPz1GfUQHcL8qCVsi7OjrbBI4t1Q17c2NqYpREutWg62MU0XNSsVvdIoOIPNQbCZIR1WDcWNlNFT3Sf5uYEMXEQj5Mi2JDuyL+OzZcjG7HE4G0rOasjiHJHAfrwEwOOf/mJCC6SVszAIVGQVRRn+Rx9q3CeFyytFf8fTtmCaxdrByTfbBmeL7EXmZN6pthY44xb3HfnU8q5qw==
Delete succeeded ET=1:02:38.9154121 ReceiptHandle=AQEBwpbOjN4qpDJd4ATkAUroQ+afG2mXciJJvIDO1zYrrWsGK3qXdmw6nLhWlFV7LCF3iGAR/Ov8IxZLrod7rdnxcXgZ4a4q9pBi3XkeJbWgIXPS/MboMM3e9uakrnLpXOs5Pee9W8aRhqIlQ66DbM6fR6Nw/oASY6fOmv0IkRwAiye5FtPpWodMs7ve2e4Trhfsl7NU5S81FqPz1GfUQHcL8qCVsi7OjrbBI4t1Q17c2NqYpREutWg62MU0XNSsVvdIoOIPNQbCZIR1WDcWNlNFT3Sf5uYEMXEQj5Mi2JDuyL+OzZcjG7HE4G0rOasjiHJHAfrwEwOOf/mJCC6SVszAIVGQVRRn+Rx9q3CeFyytFf8fTtmCaxdrByTfbBmeL7EXmZN6pthY44xb3HfnU8q5qw==
Exception during delete ET=1:02:44.1324334 Message=Amazon.SQS.Model.QueueDoesNotExistException: The specified queue does not exist.
 ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.ProcessHttpResponseMessage(HttpResponseMessage responseMessage)
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.SQS.Internal.ValidationResponseHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionStream(IRequestContext requestContext, IWebResponseData httpErrorResponse, HttpErrorResponseException exception, Stream responseStream)
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionAsync(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ExceptionHandler`1.HandleAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessExceptionAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Signer.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Program.<Main>$(String[] args) in C:\dev\scratch\SqsMessageTester\SqsMessageTester\Program.cs:line 36

C:\dev\scratch\SqsMessageTester\SqsMessageTester\bin\Debug\net8.0\SqsMessageTester.exe (process 10920) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .
```

### Reproduction Steps
```
using System.Diagnostics;
using Amazon;
using Amazon.Runtime;
using Amazon.Runtime.CredentialManagement;
using Amazon.SQS;
using Amazon.SQS.Model;

var credChain = new CredentialProfileStoreChain();
if (!credChain.TryGetAWSCredentials("CuSqsSnsTestingPowerUser-358692710224", out AWSCredentials creds))
{
    Console.WriteLine("Failed to load AWS creds! Press enter to exit...");
    Console.Read();
    return 1;
}

var sqs = new AmazonSQSClient(creds, RegionEndpoint.USEast1);

const string queueUrl = "https://sqs.us-east-1.amazonaws.com/358692710224/AdoveVisibilityTimeoutTest";
await sqs.SendMessageAsync(queueUrl, "hello world!");

await Task.Delay(TimeSpan.FromSeconds(30));

ReceiveMessageResponse response = await sqs.ReceiveMessageAsync(queueUrl);

await Task.Delay(TimeSpan.FromSeconds(30));

var msg = response.Messages.First();

var timer = Stopwatch.StartNew();

Console.WriteLine("Starting delete loop...");

bool continueLoop = true;
while (continueLoop)
{
    try
    {
        await sqs.DeleteMessageAsync(new DeleteMessageRequest(queueUrl, msg.ReceiptHandle));
        Console.WriteLine($"Delete succeeded ET={timer.Elapsed:g} ReceiptHandle={msg.ReceiptHandle}");

        await Task.Delay(TimeSpan.FromMinutes(1));

    }
    catch (AmazonSQSException ex)
    {
        Console.WriteLine($"Exception during delete ET={timer.Elapsed:g} Message={ex}");
        continueLoop = false;
    }
}


return 0;
```

### AWS .NET SDK and/or Package version used

AWSSDK.SQS 3.7.300.62
.NET 8.0

Note, this actually repro'd in a production application running .NET Framework 4.8 running version 3.7.200.2 of the AWSSDK.SQS package. The sample code is the relevant repro. 

### Targeted .NET Platform

.NET 8, .NET Framework 4.8

### Operating System and version

Windows 11 Enterprise, Windows Server 2016

**Comment by ashishdhingra** [comment]
@ardove Good afternoon. Thanks for reporting the issue. Is it possible to elaborate steps to create queue in AWS console (may be specify properties that need to be setup for each queue separately). Somehow, when I execute your code, it is stuck in infinite loop. May be SQS setup for this issue has an issue.

Thanks,
Ashish
