### ISSUE TITLE
AmazonBedrockAgentRuntimeClient.RetrieveAndGenerateAsync throws an exception

### ISSUE THREAD

**Issue by JulesMBooth** [aws/aws-sdk-net#3278]
### Describe the bug

The code sample below which calls AmazonBedrockAgentRuntimeClient.AmazonBedrockAgentRuntimeClient.RetrieveAndGenerateAsync returns an Internal Server Error

### Expected Behavior

Returns RetrieveAndGenerateResponse

### Current Behavior

Returns error

Amazon.BedrockAgentRuntime.AmazonBedrockAgentRuntimeException: The service returned an error with Error Code InternalFailure and HTTP Body: {} ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (500) Internal Server Error. ---> System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.HttpRequest.<GetResponseAsync>d__19.MoveNext() in C:\codebuild\tmp\output\src3252655653\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_bcl\HttpWebRequestFactory.cs:line 338
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpRequest.<GetResponseAsync>d__19.MoveNext() in C:\codebuild\tmp\output\src3252655653\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_bcl\HttpWebRequestFactory.cs:line 359
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.HttpHandler`1.<InvokeAsync>d__9`1.MoveNext() in C:\codebuild\tmp\output\src3252655653\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:line 185
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.Unmarshaller.<InvokeAsync>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5`1.MoveNext()
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionStream(IRequestContext requestContext, IWebResponseData httpErrorResponse, HttpErrorResponseException exception, Stream responseStream) in C:\codebuild\tmp\output\src3252655653\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\HttpErrorResponseExceptionHandler.cs:line 163
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.<HandleExceptionAsync>d__2.MoveNext() in C:\codebuild\tmp\output\src3252655653\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\HttpErrorResponseExceptionHandler.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.ExceptionHandler`1.<HandleAsync>d__6.MoveNext() in C:\codebuild\tmp\output\src3252655653\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ExceptionHandler.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.ErrorHandler.<ProcessExceptionAsync>d__8.MoveNext() in C:\codebuild\tmp\output\src3252655653\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 243
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5`1.MoveNext() in C:\codebuild\tmp\output\src3252655653\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.Signer.<InvokeAsync>d__1`1.MoveNext() in C:\codebuild\tmp\output\src3252655653\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\Signer.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.<InvokeAsync>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.<InvokeAsync>d__2`1.MoveNext() in C:\codebuild\tmp\output\src3252655653\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\EndpointDiscoveryHandler.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7`1.MoveNext() in C:\codebuild\tmp\output\src3252655653\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CredentialsRetriever.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext() in C:\codebuild\tmp\output\src3252655653\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\RetryHandler\RetryHandler.cs:line 146
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5`1.MoveNext() in C:\codebuild\tmp\output\src3252655653\src\aws-sdk-net\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\ErrorCallbackHandler.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApp1.Program.<InvokeBedrockKnowledgeBaseAsync>d__3.MoveNext()

### Reproduction Steps

``` 
public static async Task<string> InvokeBedrockKnowledgeBaseAsync(string knowledgeBaseId, string sessionId, string prompt)
{
    var result = "";
    try
    {
        var client = new AmazonBedrockAgentRuntimeClient(RegionEndpoint.USEast1);

        Console.WriteLine($"Calling bedrock with Knowledge Base Id: {knowledgeBaseId} and Session Id: {sessionId} with prompt: {prompt}.");

        RetrieveAndGenerateResponse response = await client.RetrieveAndGenerateAsync(new RetrieveAndGenerateRequest
        {
            Input = new RetrieveAndGenerateInput
            {
                Text = prompt
            },
            RetrieveAndGenerateConfiguration = new RetrieveAndGenerateConfiguration
            {
                KnowledgeBaseConfiguration = new KnowledgeBaseRetrieveAndGenerateConfiguration
                {
                    KnowledgeBaseId = knowledgeBaseId,
                    ModelArn = "arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-v2"
                }
            },
            SessionId = sessionId

        });

        if (response.HttpStatusCode == System.Net.HttpStatusCode.OK)
        {
            result = response.Output.Text;
        }
        else
        {
            Console.WriteLine("InvokeModelAsync failed with status code " + response.HttpStatusCode);
        }
    }
    catch (Exception ex)
    {
        result = ex.ToString(); ;
    }

    return result;
}
```

### Additional Information/Context

I am able to invoke an Agent attached to the same Knowledge Base with the following code; 

```
public static async Task<string> InvokeBedrockAgentAsync(string agentId, string agentAliasId, string sessionId, string prompt)
 {
      var result = "";
      try
      {
          AmazonBedrockAgentRuntimeClient client = new AmazonBedrockAgentRuntimeClient(RegionEndpoint.USEast1);

          Console.WriteLine($"Calling bedrock with Agent Id: {agentId}, Agent Alias Id {agentAliasId} and Session Id: {sessionId} with prompt: {prompt}.");

          // list agents
          InvokeAgentResponse response = await client.InvokeAgentAsync(new InvokeAgentRequest()
          {
              AgentId = agentId,
              AgentAliasId = agentAliasId,
              SessionId = sessionId,
              InputText = prompt
          });

          if (response.HttpStatusCode == System.Net.HttpStatusCode.OK)
          {
              MemoryStream output = new MemoryStream();
              foreach (PayloadPart item in response.Completion)
              {
                  item.Bytes.CopyTo(output);
              }
              result = Encoding.UTF8.GetString(output.ToArray());
          }
          else
          {
              Console.WriteLine("InvokeModelAsync failed with status code " + response.HttpStatusCode);
          }
      }
      catch (Exception ex)
      {
          result = ex.ToString(); ;
      }

      return result;
}
```

### AWS .NET SDK and/or Package version used

AWSSDK.BedrockAgentRuntime 3.7.303.8
AWSSDK.BedrockRuntime 3.7.301.60
AWSSDK.Core 3.7.303.11

### Targeted .NET Platform

.Net Framework 4.8.1 .Net 6 & .Net 8

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
@JulesMBooth Good morning. Thanks for opening the issue. Could you please enable verbose logging using code below and share the detailed logs:
```C#
Amazon.AWSConfigs.LoggingConfig.LogResponses = Amazon.ResponseLoggingOption.Always;
Amazon.AWSConfigs.LoggingConfig.LogTo = Amazon.LoggingOptions.Console;
Amazon.AWSConfigs.AddTraceListener("Amazon", new System.Diagnostics.ConsoleTraceListener());
```

Thanks,
Ashish

**Comment by JulesMBooth** [comment]
Hi, 

I noticed when attempting the request by CLI that I had missed a parameter in the RetrieveAndGenerateConfiguration object: "Type" I set that to "KNOWLEDGE_BASE". Having examined the error response to that I realised I could only pass in a Session Id once I had got a response. So my code now looks like:

```
....
    Console.WriteLine("Please enter the Knowledge Base Id");

    string? kbId = Console.ReadLine();

    Console.WriteLine("Please enter your first prompt, after this type exit to stop prompting bedrock.");

    var input = Console.ReadLine();

    var sessionId = "";
    while (input?.ToUpperInvariant() != "EXIT")
    {    
        var response = await InvokeBedrockRetrieveAndGenerateKnowledgeBaseAsync(kbId, input, sessionId);

        if (response != null)
        {
            Console.WriteLine(response.Output.Text);

            sessionId = response.SessionId;
        }
        else
        {
            Console.WriteLine("Error Occurred");
        }

        Console.WriteLine("Please write your next prompt or type exit to leave.");
        input = Console.ReadLine();
    }
.....
  public static async Task<RetrieveAndGenerateResponse> InvokeBedrockRetrieveAndGenerateKnowledgeBaseAsync(string knowledgeBaseId, string prompt, string sessionId = "")
  {
      RetrieveAndGenerateResponse? result = null;
      try
      {
          AmazonBedrockAgentRuntimeClient client = new(RegionEndpoint.USEast1);

          Console.WriteLine($"Calling bedrock with Knowledge Base Id: {knowledgeBaseId}, prompt: {prompt} and {(String.IsNullOrWhiteSpace(sessionId) ? "No session Id" : $"Session Id: {sessionId}")}.");

          var request = new RetrieveAndGenerateRequest
          {
              Input = new RetrieveAndGenerateInput
              {
                  Text = prompt
              },
              RetrieveAndGenerateConfiguration = new RetrieveAndGenerateConfiguration
              {
                  Type = "KNOWLEDGE_BASE",
                  KnowledgeBaseConfiguration = new KnowledgeBaseRetrieveAndGenerateConfiguration
                  {
                      KnowledgeBaseId = knowledgeBaseId,
                      ModelArn = "arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-v2",
                  }
              },
          };

          if (!String.IsNullOrWhiteSpace(sessionId))
              request.SessionId = sessionId;

          RetrieveAndGenerateResponse response = await client.RetrieveAndGenerateAsync(request);
          
          if (response.HttpStatusCode == System.Net.HttpStatusCode.OK)
          {
              result = response;
          }
          else
          {
              Console.WriteLine("InvokeModelAsync failed with status code " + response.HttpStatusCode);
          }
      }
      catch (Exception ex)
      {
          Console.WriteLine(ex.ToString());
      }

      return result;
  }
```

And this works as expected. Not clear from the .Net docs how RetrieveAndGenerateConfiguration should be set however so that could be improved.  

I also found that I coudn't get requests to work on the CLI I have attached output. 
[BedrockCLI.txt](https://github.com/aws/aws-sdk-net/files/14945628/BedrockCLI.txt)

**Comment by ashishdhingra** [comment]
@JulesMBooth Thanks for the update and glad that it works for you now. AWS CLI appears to be failing with error `Could not connect to the endpoint URL.`. Unsure about the root cause of the error.

Regarding documentation:
- Agents for Amazon Bedrock Runtime [RetrieveAndGenerateConfiguration](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_RetrieveAndGenerateConfiguration.html) API reference does specify valid values (currently only `KNOWLEDGE_BASE`) for `type` property.
- The AWS .NET SDK API reference for [RetrieveAndGenerateConfiguration](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/BedrockAgentRuntime/TRetrieveAndGenerateConfiguration.html) does not appear to specify list of valid values. This would be the case with any property, not just this property.
  - This is also the case with Java SDK API reference [here](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/bedrockagentruntime/model/RetrieveAndGenerateConfiguration.html).
  - The API reference for SDK(s) are generated from the models shared by service team, for AWS .NET SDK it's [here](https://github.com/aws/aws-sdk-net/blob/bd2a8f6a5eb3c52d1a1c6a4b23cf96071752260e/generator/ServiceModels/bedrock-agent-runtime/bedrock-agent-runtime-2023-07-26.docs.json#L603). These are same across all SDK(s).
  - I would advise you to submit the feedback request by clicking [link](https://docs.aws.amazon.com/forms/aws-doc-feedback?service_name=NET-Ref-V3&file_name=TRetrieveAndGenerateConfiguration). It would be routed through appropriate channels.

Thanks,
Ashish
