### ISSUE TITLE
Unable to use S3 Path Style Access S3 URL 

### ISSUE THREAD

**Issue by Edstub207** [aws/aws-sdk-net#3342]
### Describe the bug

We are using Minio which has S3 Functionality, by default the URL is minio.blah.randomurl.com/bucketname/, however, when we provide that URL the AWS S3 SDK falls over, it looks like other libraries (Java for example) allow you to use this bucket formatting with things like withPathStyleAccessEnabled but I can't see that on the AWS .net API__

### Expected Behavior

Able to use either bucketname.minio.blah.randomurl.com/ or minio.blah.randomurl.com/bucketname/ as a URL for S3 Storage with the AWS API 

### Current Behavior

1: Prefixes the bucket name into the ServiceURL which doesn't resolve DNS as it doesn't exist 

2: No bucket name is provided and an exception is thrown because a bucketname is a required field 
```
System.ArgumentException: BucketName is a required property and must be set before making this call. (Parameter 'GetObjectRequest.BucketName')
   at Amazon.S3.Model.Internal.MarshallTransformations.GetObjectRequestMarshaller.Marshall(GetObjectRequest getObjectRequest)
   at Amazon.Runtime.Internal.Marshaller.PreInvoke(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Marshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
```

### Reproduction Steps

Have the following confiig line for an AWS Store (Customized to your relevant Minio URL) 
awsOptions.DefaultClientConfig.ServiceURL = "minio.blah.randomurl.com/bucketname/";

### AWS .NET SDK and/or Package version used

AWSSDK.S3 3.7.309.2

### Targeted .NET Platform

Net 8

### Operating System and version

Docker Container Built on Windows running on Linux

**Comment by ashishdhingra** [comment]
@Edstub207 Good morning. Thanks for opening the issue. Are you unable to use [AmazonS3Config.ForcePathStyle](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/S3/TS3Config.html) in AWS .NET SDK? Please confirm.

Kindly note that we do not support using AWS .NET SDK with 3rd party AWS simulated services. SDK might work for certain scenarios, however, there are always some edge cases.

Thanks,
Ashish

**Comment by Edstub207** [comment]
@ashishdhingra thanks for the reply, an ex-colleague pointed me towards some reference code which I missed when looking into this and that's solved my problem!
