### ISSUE TITLE
SQS poll exception: System.InvalidOperationException: Collection was modified

### ISSUE THREAD

**Issue by peterkiss1** [aws/aws-sdk-net#3394]
### Describe the bug

Exception thrown on SQS ReceiveMessageAsync() call when there are 2 clients in the same application polling the same queue.
The application starts multiple .NET hosted services, 2 of them containing an SQS client and polling messages from the same queue continuously (max. wait time is 20 seconds). This setup worked just fine but after upgrading from .NET 8.0.6 to .NET 8.0.7 and AWSSDK.SQS 3.7.301.18 to 3.7.301.30 the issue started.

### Expected Behavior

This exception should not be thrown, no shared state or invalid enumeration should happen within receiving the messages.

### Current Behavior

Exception is thrown:

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at Amazon.SQS.Model.Internal.MarshallTransformations.ReceiveMessageRequestMarshaller.Marshall(ReceiveMessageRequest publicRequest)
   at Amazon.Runtime.Internal.Marshaller.PreInvoke(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Marshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at CompanyName.ApplicationIntegration.Queues.Amazon.SQS.Buffered.BufferedSqsQueue`1.GetBatchAsync(CancellationToken cancellationToken)
   at CompanyName.Extensions.Commands.CommandProcessor`1.ProcessAsync(CancellationToken cancellationToken)
   at CompanyName.AppName.Api.Hosting.CommandProcessorBackgroundService.CallbackAsync(HostedServiceConfiguration value, CancellationToken cancellationToken) in /src/Api/Hosting/CommandProcessorBackgroundService.cs:line 20
   at CompanyName.Extensions.Hosting.Continuous.ContinuousHostedService`2.CallbackAsync(CancellationToken stoppingToken)
```

When this error started to happen we also started to see "pipe is broken" errors in the logs. Zero messages were consumed from the queue while this error was ongoing, only container restart helped. After restart it still happened from time to time and it became more frequent when there was something to be processed, or more messages were available.

### Reproduction Steps

The below snippet might not be the best as the 2 poll task aren't awaited in the same time but running independently called from independent background services (code, logic is the same but 2 instance)

```
while (true)
{
    var tasks = new Task[2];
	
	for (int i = 0; i < tasks.Length; i++)
	{
	    tasks[i] = sqsClient.ReceiveMessageAsync(new ReceiveMessageRequest
		{
			QueueUrl = "insert your queue url",
			MaxNumberOfMessages = 10,
			WaitTimeSeconds = 20
		});
	}
	
	await Task.WhenAll(tasks);
}
˙˙˙˙

If required i will extract a more complete example.

### Possible Solution

Did not find any solution or workaround, only to run 1 instance if the consumer in the same application.

### Additional Information/Context

As mentioned this started to happen after the version upgrades, no additional code change happened around our solution.

### AWS .NET SDK and/or Package version used

AWSSDK.SQS 3.7.301.30

### Targeted .NET Platform

 .NET 8.0.7

### Operating System and version

Debian

**Comment by peterkiss1** [comment]
Happened again with only 1 consumer running in the app:
SocketException trace:
```
"System.IO.IOException: Unable to write data to the transport connection: Broken pipe.
 ---> System.Net.Sockets.SocketException (32): Broken pipe
 --- End of inner exception stack trace ---
 at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
 at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
 at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
 at Amazon.SQS.Internal.ValidationResponseHandler.InvokeAsync[T](IExecutionContext executionContext)
 at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
 at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
 at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
 at Amazon.Runtime.Internal.Signer.InvokeAsync[T](IExecutionContext executionContext)
 at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
 at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
 at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
 at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
 at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
 at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
 at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
 at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
 at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
 at Company.ApplicationIntegration.Queues.Amazon.SQS.Buffered.BufferedSqsQueue`1.GetBatchAsync(CancellationToken cancellationToken)
 at Company.Extensions.Commands.CommandProcessor`1.ProcessAsync(CancellationToken cancellationToken)
 at Company.AppName.Api.Hosting.CommandProcessorBackgroundService.CallbackAsync(HostedServiceConfiguration value, CancellationToken cancellationToken) in /src/Api/Hosting/CommandProcessorBackgroundService.cs:line 20
 at Company.Extensions.Hosting.Continuous.ContinuousHostedService`2.CallbackAsync(CancellationToken stoppingToken)"
```

**Comment by peterkiss1** [comment]
Found a related one: https://github.com/aws/aws-sdk-net/issues/1858

**Comment by dscpinheiro** [comment]
That message is the same, but it's a different API (`SendMessageBatch` vs `ReceiveMessage`) so I don't believe it's the same problem.

Do you see the error when using `.NET 8.0.6` and `AWSSDK.SQS 3.7.301.30`? Looking at our changelog, I don't see any functional changes between the two versions of the SQS package (the versions bumps were to pick `AWSSDK.Core` updates) so I want to confirm it's not an issue with the .NET runtime.

If you still see the error, please share a more concrete example if possible (I tried running your example from two local console apps but did not see the exception).

**Comment by dscpinheiro** [comment]
Got it. If you could share the more concrete example you mentioned that'll help us troubleshoot.

For the record, `MessageSystemAttributeNames` was added in version `3.7.301.0` of SQS (so it already existed in the working version you had - `3.7.301.18`): https://github.com/aws/aws-sdk-net/blob/main/changelogs/SDK.CHANGELOG.2024.md#378060-2024-05-08-1820-utc

**Comment by normj** [comment]
Just double checking but you aren't reusing instances of `ReceiveMessageRequest` across invocations of `ReceiveMessage`?

**Comment by peterkiss1** [comment]
`ReceiveMessageRequest` is not shared, however some part of it shared as it is coming from the queue specific config:

```
        private ReceiveMessageRequest BuildRequest(int maxNumberOfMessages, int? waitTimeSeconds = null)
        {
            return new ReceiveMessageRequest
            {
                QueueUrl = _configuration.QueueUrl,
                WaitTimeSeconds = waitTimeSeconds ?? _configuration.WaitTimeSeconds,
                VisibilityTimeout = _configuration.VisibilityTimeout,
                MaxNumberOfMessages = maxNumberOfMessages,
                MessageAttributeNames = _configuration.MessageAttributeNames
            };
        }
```

And remember, we are failing now (literally in this very moment) when there is only 1 consumer in the app.

**Comment by peterkiss1** [comment]
New trace as we have another update for us in the apps: https://github.com/newrelic/newrelic-dotnet-agent/pull/2620/files

This looks pretty related.

**Comment by peterkiss1** [comment]
After removing this latest and greatest New Relic agent it looks like the issue is completely gone. Will open a bug ticket in their repo and also will reach out in private.
