### ISSUE TITLE
Failure on retry after 500/502 error during multipart upload

### ISSUE THREAD

**Issue by evanverneyfink** [aws/aws-sdk-net#372]
We're running into an issue where a 500 or 502 error on the upload of one of the parts in a multipart upload causes the following exception to be thrown:

```
System.NotSupportedException: The stream does not support concurrent IO read or write operations.
   at System.Net.ConnectStream.InternalWrite(Boolean async, Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.ConnectStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at Amazon.Runtime.Internal.HttpRequest.WriteToRequestBody(Stream requestContent, Stream contentStream, IDictionary`2 contentHeaders, IRequestContext requestContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_bcl\HttpWebRequestFactory.cs:line 164
   at Amazon.Runtime.Internal.HttpHandler`1.WriteContentToRequestBody(TRequestContent requestContent, IHttpRequest`1 httpRequest, IRequestContext requestContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:line 383
   at Amazon.Runtime.Internal.HttpHandler`1.<InvokeAsync>d__9`1.MoveNext() in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:line 144
--- End of stack trace from previous location where exception was thrown ---
   at Amazon.Runtime.Internal.HttpHandler`1.<InvokeAsync>d__9`1.MoveNext() in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:line 155
   ...
```

I believe this is occurring on an attempt to retry the part, although I'm not 100% sure on this.

Please note that the 502 Bad Gateway error seems to be an issue with the proxy we're using, and we are working to fix this, but we see the same behavior with 500 errors returned by Amazon.

**Comment by PavelSafronov** [comment]
Can you provide the full stack trace, your code, and which versions of the various SDK packages you are using?

**Comment by evanverneyfink** [comment]
SDK version:
AWSSDK.Core = 3.1.6
AWSSDK.S3 = 3.1.6.2

Relevant snippets of our code:

```
private TransferUtilityConfig TransferConfig => new TransferUtilityConfig
{
    MinSizeBeforePartUpload = Settings.MultiPartThreshold, // currently set to 100 MB
    ConcurrentServiceRequests = Settings.MultiPartConcurrentCalls // currently set to 10
}

public void Execute()
{
    // ... some logging and tracking code

    var request = CreateUploadRequest(FileInfo.FileSize, BucketName, ObjectKey);

    using (var transferUtil = new TransferUtility(Client, TransferConfig))
        transferUtil.Upload(request);

    // ... more logging, validation, etc
}

private TransferUtilityUploadRequest CreateUploadRequest(string filePath, string bucketName, string objectKey)
{
    var uploadRequest = new TransferUtilityUploadRequest
    {
        BucketName = bucketName,
        Key = objectKey,
        FilePath = filePath,
        PartSize = Settings.MultiPartBytesPerPart, // currently set to 10 MB
        AutoCloseStream = false,
        AutoResetStreamPosition = true,
        CannedACL = S3CannedACL.PublicRead
    };

    uploadRequest.UploadProgressEvent += UpdateProgress;

    return uploadRequest;
}
```

Full stack trace:

```
System.NotSupportedException: The stream does not support concurrent IO read or write operations.
at System.Net.ConnectStream.InternalWrite(Boolean async, Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
at System.Net.ConnectStream.Write(Byte[] buffer, Int32 offset, Int32 size)
at Amazon.Runtime.Internal.HttpRequest.WriteToRequestBody(Stream requestContent, Stream contentStream, IDictionary`2 contentHeaders, IRequestContext requestContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_bcl\HttpWebRequestFactory.cs:line 164
at Amazon.Runtime.Internal.HttpHandler`1.WriteContentToRequestBody(TRequestContent requestContent, IHttpRequest`1 httpRequest, IRequestContext requestContext) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:line 383
at Amazon.Runtime.Internal.HttpHandler`1.<InvokeAsync>d__9`1.MoveNext() in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:line 144
--- End of stack trace from previous location where exception was thrown ---
at Amazon.Runtime.Internal.HttpHandler`1.<InvokeAsync>d__9`1.MoveNext() in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:line 155
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Amazon.Runtime.Internal.RedirectHandler.<InvokeAsync>d__1`1.MoveNext() in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\RedirectHandler.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Amazon.Runtime.Internal.Unmarshaller.<InvokeAsync>d__3`1.MoveNext() in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\Unmarshaller.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Amazon.S3.Internal.AmazonS3ResponseHandler.<InvokeAsync>d__1`1.MoveNext() in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Services\S3\Custom\Internal\AmazonS3ResponseHandler.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5`1.MoveNext() in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext() in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7`1.MoveNext() in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CredentialsRetriever.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext() in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\RetryHandler\RetryHandler.cs:line 129
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext() in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext() in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Amazon.S3.Internal.AmazonS3ExceptionHandler.<InvokeAsync>d__1`1.MoveNext() in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Services\S3\Custom\Internal\AmazonS3ExceptionHandler.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5`1.MoveNext() in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\ErrorCallbackHandler.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1`1.MoveNext() in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\MetricsHandler.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Amazon.S3.Transfer.Internal.MultipartUploadCommand.<UploadPartAsync>d__24.MoveNext() in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Services\S3\Custom\_bcl+pcl\Transfer\Internal\_async\MultipartUploadCommand.async.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Amazon.S3.Transfer.Internal.BaseCommand.<WhenAllOrFirstExceptionAsync>d__5`1.MoveNext() in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Services\S3\Custom\_bcl+pcl\Transfer\Internal\_async\BaseCommand.async.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at Amazon.S3.Transfer.Internal.MultipartUploadCommand.<ExecuteAsync>d__23.MoveNext() in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Services\S3\Custom\_bcl+pcl\Transfer\Internal\_async\MultipartUploadCommand.async.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
at Amazon.S3.Transfer.TransferUtility.Upload(TransferUtilityUploadRequest request) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Services\S3\Custom\_bcl+pcl\Transfer\_bcl45\TransferUtility.sync.bcl45.cs:line 284
at Triskel.Fims.Repository.S3.Utility.Uploads.S3Upload.Execute()
```

Looking at the code as I've posted it now, I'm wondering if the issue has to do with the following settings:

```
        AutoCloseStream = false,
        AutoResetStreamPosition = true,
```

I inherited some of this code from another developer, so I don't really know what their reasoning behind it was. Could this be the root of the problem?

**Comment by PavelSafronov** [comment]
Since you are not operating on streams but rather on files, there is no need to set either *AutoCloseStream* or *AutoResetStreamPosition*. Everything else about your code seems reasonable.

**Comment by evanverneyfink** [comment]
I believe you're saying these values will be ignored when providing a file path and not a stream for upload. Is that correct? In which case, doesn't this constitute a legitimate bug?

**Comment by trailway** [comment]
I have been struggling with this for a while:

https://forums.aws.amazon.com/thread.jspa?threadID=161083&tstart=0

**Comment by evanverneyfink** [comment]
Can someone please indicate if this is being considered as a bug and/or is currently under active investigation? If not, we'll be looking to escalate through other channels if possible, as this is causing us issues in our production environment.

**Comment by PavelSafronov** [comment]
Have you tried not setting AutoCloseStream or AutoResetStreamPosition properties? If so, have you observed these same errors?

**Comment by sdcarpenter** [comment]
We just hit this as well, and were not setting these properties.

**Comment by normj** [comment]
Has anybody that is experience this problem tried @PavelSafronov suggestion of not setting AutoCloseStream or AutoResetStreamPosition properties?

**Comment by costleya** [comment]
Closing due to inactivity,
