### ISSUE TITLE
Exception when using 4.5 client with config.UseHttp=true while running Fiddler.

### ISSUE THREAD

**Issue by vgribok** [aws/aws-sdk-net#43]
Using AWS SDK for .NET 4.5, I wanted to see how AWS requests and responses look on the wire. To do that I set config.UserHttp=true to run in clear HTTP instead of SSL, and ran Fiddler. This produced an exception below. If Fiddler is stopped or exited, or if HTTPS is used, the problem does not occur. NET 3.5 client does not have this problem either - its traffic shows in Fiddler just fine.

Exception is thrown in AmazonWebServiceClient class, method:
private async Task<T> InvokeConfiguredRequest<T>(WebRequestState state, CancellationToken cancellationToken) where T : AmazonWebServiceResponse.
at
responseMessage = await httpClient.SendAsync(requestMessage, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
line.

Similar problem reported at http://social.msdn.microsoft.com/Forums/vstudio/en-US/6a745a51-8a7b-4a5c-9f07-be02cc01278c/httpwebrequest-in-c-do-not-work-with-net-45?prof=required. .

Exceptions chain:

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Amazon.Runtime.AmazonWebServiceClient.<InvokeConfiguredRequest>d__b`1.MoveNext() in c:\!Projects\Fabric.WebServices\aws-sdk-net\AWSSDK_DotNet45\Amazon.Runtime\AmazonWebServiceClient.cs:line 143

Inner exception:
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)

The innermost exception is:
   at System.DomainNameHelper.IdnEquivalent(String hostname)
   at System.Uri.get_IdnHost()
   at System.Net.HttpWebRequest.GetSafeHostAndPort(Uri sourceUri, Boolean addDefaultPort, Boolean forcePunycode)
   at System.Net.HttpWebRequest.GenerateProxyRequestLine(Int32 headersSize)
   at System.Net.HttpWebRequest.SerializeHeaders()
   at System.Net.HttpWebRequest.EndSubmitRequest()
   at System.Net.HttpWebRequest.SetRequestSubmitDone(ConnectStream submitStream)
   at System.Net.Connection.CompleteConnection(Boolean async, HttpWebRequest request)

**Comment by gokarnm** [comment]
Closing this issue, as it's not reproducible and OP is not working on this anymore.
