### ISSUE TITLE
Can region be given in credentials or config file in the .aws folder?

### ISSUE THREAD

**Issue by gardient** [aws/aws-sdk-net#478]
I'm trying to initialize `new AmazonCloudWatchLogsClient()` and using the credentials file (`%userprofile%/.aws/credentials`) with the default profile.

The credentials file has both `aws_access_key_id`, `aws_secret_access_key` and `region` set (region is `eu-west-1` in case I'm somehow formatting them incorrectly)

The problem is that it keeps giving me an AmazonClientException with the message "No RegionEndpoint or ServiceURL configured"

I also tried adding the region to the `%userprofile%/.aws/config` file same problem.

If i hard code it in the code, it works.

Did i misunderstand the docs or is this a bug?

You can find my code [here](https://github.com/gardient/CloudWatchLogDownloader/blob/master/CloudWatchLogDownloader/Program.cs#L20)

**Comment by gardient** [comment]
stack trace:

```
   at Amazon.Runtime.ClientConfig.Validate() in v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\ClientConfig.cs:line 417
   at Amazon.Runtime.AmazonServiceClient..ctor(AWSCredentials credentials, ClientConfig config) in v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\AmazonServiceClient.cs:line 151
   at Amazon.CloudWatchLogs.AmazonCloudWatchLogsClient..ctor() in v3-stage-release\AWSDotNetPublic\sdk\src\Services\CloudWatchLogs\Generated\_bcl45\AmazonCloudWatchLogsClient.cs:line 98
   at CloudWatchLogDownloader.Program.Main(String[] args) in CloudWatchLogDownloader\CloudWatchLogDownloader\Program.cs:line 20
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by Singh400** [comment]
According to the example [**here**](http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config.html), yes.

>
```
<configuration>
  <appSettings>
    <add key="AWSRegion" value="us-west-2"/>
  </appSettings>
</configuration>
```

**Comment by gardient** [comment]
Those are from the app/web.config files. the one i'm talking about are the file `%userprofile%/.aws/credentials` and `%userprofile%/.aws/config`. something like 

```
[default]
aws_access_key_id=<access_key_id>
aws_secret_access_key=<secret_access_key>
region=<region>
```

I'm asking because it takes the `aws_access_key_id` and `aws_secret_access_key` from there the same as the aws-cli but doesn't seem to recognize the `region` in either of those.

Also yes I'm aware that that's for the aws-cli but i think some consistency across the board doesn't hurt. And I just find it confusing that it takes both the key in your example and the environment variable AWS_REGION, but not the region specified in the `%userprofile%/.aws/credentials` or `%userprofile%/.aws/config` files.

**Comment by normj** [comment]
I agree it would be good for the .NET SDK to be the same as other SDK and pull the region out of the credentials file. The logic in the .NET SDK has a separate fallback mechanism for finding credentials versus region so when it is looking for a region it doesn't have the scope of a profile.

Not saying we won't do it because of that, just that it will take us a bit to get the time to rework that logic.

**Comment by gardient** [comment]
That would be awesome! any chance you can give me an ETA? not that i can't live without this but still.

**Comment by normj** [comment]
I'm not sure when we will get to this feature request, but I'll post back here when we make progress.

**Comment by PavelSafronov** [comment]
This is supported in the latest version of the SDK. You can read about this feature in the [Configuring AWS Credentials section](http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-creds.html#using-a-credentials-file) of the [Developer Guide](http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/welcome.html).
