### ISSUE TITLE
AWS SDK 2.0 isn't FIPS compliant anymore

### ISSUE THREAD

**Issue by nseyen** [aws/aws-sdk-net#48]
Hi,

Our application is deployed to a FIPS compliant environment.
When we upgrade from AWS SDK 1.5.39 to the latest version (2.0.2.3) of the AWS SDK, we get exceptions (our code remains the same).

Are you going to make the AWS SDK 2.x FIPS compliant?

Thanks in advance!
Kind regards,
Niels

Our code:

        public void Upload(CloudRequest request)
        {
            using (var utility = new TransferUtility(CreateClient(request)))
            {
                utility.Upload(request.FilePath, request.Bucket, request.Key);
            }
        }

        private AmazonS3Client CreateClient(CloudRequestBase request)
        {
            return new AmazonS3Client(request.AccessKey, request.SecretKey, RegionEndpoint.GetBySystemName(request.Region));
        }

The exception:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
   at System.Security.Cryptography.MD5CryptoServiceProvider..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle._InvokeConstructor(IRuntimeMethodInfo method, Object[] args, SignatureStruct& signature, RuntimeType declaringType)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
   at Amazon.Runtime.Internal.Util.HashingWrapper.Init(String algorithmName) in c:\Jenkins\workspace\release-v2-sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Internal\Util\HashingWrapper.bcl.cs:line 35
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipVisibilityChecks, Boolean skipCheckThis, Boolean fillCache)
   at System.Activator.CreateInstance[T]()
   at Amazon.Runtime.Internal.Util.HashStream`1..ctor(Stream baseStream, Byte[] expectedHash, Int64 expectedLength) in c:\Jenkins\workspace\release-v2-sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Internal\Util\HashStream.cs:line 347
   at Amazon.S3.Model.Internal.MarshallTransformations.PutObjectRequestMarshaller.Marshall(PutObjectRequest putObjectRequest) in c:\Jenkins\workspace\release-v2-sdk\src\AWSSDK_DotNet35\Amazon.S3\Model\Internal\MarshallTransformations\PutObjectRequestMarshaller.cs:line 94
   at Amazon.Runtime.AmazonWebServiceClient.Invoke[T,R](R request, AsyncCallback callback, Object state, Boolean synchronized, IMarshaller`2 marshaller, ResponseUnmarshaller unmarshaller, AbstractAWSSigner signer) in c:\Jenkins\workspace\release-v2-sdk\src\AWSSDK_DotNet35\Amazon.Runtime\AmazonWebServiceClient.cs:line 73
   at Amazon.S3.AmazonS3Client.PutObject(PutObjectRequest putObjectRequest) in c:\Jenkins\workspace\release-v2-sdk\src\AWSSDK_DotNet35\Amazon.S3\AmazonS3Client.cs:line 349

**Comment by PavelSafronov** [comment]
The latest version of the .NET SDK (2.3.33) is now FIPS compliant.
