### ISSUE TITLE
EC2InstanceMetadata.GetItems task canceled

### ISSUE THREAD

**Issue by aggieben** [aws/aws-sdk-net#482]
I'm trying to get the temporary security credentials associated with an instance profile like this:

```
var credentialMetadata = EC2InstanceMetadata.IAMSecurityCredentials["profile aws-elasticbeanstalk-ec2-role"];
```

From my logs, it looks like the request probably timed out (a trace right before the above line indicated 10 seconds prior to the exception), but I don't understand why.  If I use `curl` to retrieve the metadata I get a response  in something like 4 ms.  The exception backtrace is below.

I'm using .NET Core in a docker container.

```
System.AggregateException: AsyncHelpers.Run method threw an exception. (A task was canceled.) ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<GetContentAsync>d__32`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.Util.AsyncHelpers.<>c__DisplayClass1_0`1.<<RunSync>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.Util.AsyncHelpers.ExclusiveSynchronizationContext.BeginMessageLoop()
   at Amazon.Runtime.Internal.Util.AsyncHelpers.RunSync[T](Func`1 task)
   at Amazon.Util.AWSSDKUtils.DownloadStringContent(Uri uri, TimeSpan timeout)
   at Amazon.Util.EC2InstanceMetadata.GetItems(String relativeOrAbsolutePath, Int32 tries, Boolean slurp)
   at Amazon.Util.EC2InstanceMetadata.get_IAMSecurityCredentials()
   at Saddleback.IdentityServer.Web.Startup.ConfigureCloudWatchLogging(IHostingEnvironment hostEnv, ILoggerFactory loggerFactory, IOptions`1 options)
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<GetContentAsync>d__32`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.Util.AsyncHelpers.<>c__DisplayClass1_0`1.<<RunSync>b__0>d.MoveNext()<---
```

**Comment by PavelSafronov** [comment]
Can you post the curl command that succeeds?

If  you are attempting to retrieve the role named "aws-elasticbeanstalk-ec2-role", can you try removing "profile " as below?
```
var credentialMetadata = EC2InstanceMetadata.IAMSecurityCredentials["aws-elasticbeanstalk-ec2-role"];
```

**Comment by aggieben** [comment]
@PavelSafronov that was a typo.  The code does actually look like what you suggested.  Here's my curl command:

```
root@5ede573b431d# time curl http://169.254.169.254/latest/meta-data/iam/security-credentials/aws-elasticbeanstalk-ec2-role
{
  "Code" : "Success",
  "LastUpdated" : "2016-11-01T18:23:42Z",
  "Type" : "AWS-HMAC",
  "AccessKeyId" : "<access key id>",
  "SecretAccessKey" : "<access key>",
  "Token" : "<base64-encoded token>",
  "Expiration" : "2016-11-02T00:51:00Z"
}
real    0m0.022s
user    0m0.008s
sys     0m0.008s
```

The secrets are redacted obviously, but this is the result (from inside a docker container).

**Comment by PavelSafronov** [comment]
Are you able to retrieve any other properties on the `EC2InstanceMetadata` object?

If you are retrieving this data to use as credentials for SDK calls, consider using `InstanceProfileAWSCredentials` instead, as that class handles automatic refreshing of the credentials when they expire.

**Comment by aggieben** [comment]
Perfect, this is just what I needed.  Thank you.

**Comment by PavelSafronov** [comment]
Does `InstanceProfileAWSCredentials` work for you? Are you no longer receiving task canceled exceptions?

**Comment by aggieben** [comment]
@PavelSafronov yes, it's working for me.  Thanks.
