### ISSUE TITLE
Amazon.Runtime.AmazonUnmarshallingException occured with .NET AWSSDK.SimpleNotificationService v3.1.0.0

### ISSUE THREAD

**Issue by Lionel1204** [aws/aws-sdk-net#487]
Hi,
We'v used .Net AWSSDK of SNS v3.1.0.0
And we have sent notifications to SNS topic:
`using (var snsclient = SnsClientFactory.GetClient())
            {
                foreach (var msg in messages)
                {
                        // Publish message
                        snsclient.Publish(new PublishRequest
                                            {
                                                Subject = msg.Item1,
                                                Message = msg.Item2,
                                                TopicArn = topicARN
                                            }
                                        );
                }
            }`

Then we got an AmazonUnmarshallingException occasionlly:

`{"ClassName":"Amazon.Runtime.AmazonUnmarshallingException","Message":"Error unmarshalling response back from AWS.","Data":null,"InnerException":{"ClassName":"System.Xml.XmlException","Message":"Root element is missing.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at System.Xml.XmlTextReaderImpl.Throw(Exception e)\r\n   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()\r\n   at Amazon.Runtime.Internal.Transform.XmlUnmarshallerContext.Read() in d:\\Jenkins\\jobs\\v3-release-build\\workspace\\AWSDotNetPublic\\sdk\\src\\Core\\Amazon.Runtime\\Internal\\Transform\\UnmarshallerContext.cs:line 368\r\n   at Amazon.Runtime.Internal.Transform.ErrorResponseUnmarshaller.Unmarshall(XmlUnmarshallerContext context) in d:\\Jenkins\\jobs\\v3-release-build\\workspace\\AWSDotNetPublic\\sdk\\src\\Core\\Amazon.Runtime\\Internal\\Transform\\ErrorResponseUnmarshaller.cs:line 36\r\n   at Amazon.SimpleNotificationService.Model.Internal.MarshallTransformations.PublishResponseUnmarshaller.UnmarshallException(XmlUnmarshallerContext context, Exception innerException, HttpStatusCode statusCode) in d:\\Jenkins\\jobs\\v3-release-build\\workspace\\AWSDotNetPublic\\sdk\\src\\Services\\SimpleNotificationService\\Generated\\Model\\Internal\\MarshallTransformations\\PublishResponseUnmarshaller.cs:line 106\r\n   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception) in d:\\Jenkins\\jobs\\v3-release-build\\workspace\\AWSDotNetPublic\\sdk\\src\\Core\\Amazon.Runtime\\Pipeline\\ErrorHandler\\HttpErrorResponseExceptionHandler.cs:line 78","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nThrow\nSystem.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Xml.XmlTextReaderImpl\nVoid Throw(System.Exception)","HResult":-2146232000,"Source":"System.Xml","WatsonBuckets":null,"res":"Xml_MissingRoot","args":[""],"lineNumber":0,"linePosition":0,"sourceUri":"","version":"2.0"},"HelpURL":null,"StackTraceString":"   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception) in d:\\Jenkins\\jobs\\v3-release-build\\workspace\\AWSDotNetPublic\\sdk\\src\\Core\\Amazon.Runtime\\Pipeline\\ErrorHandler\\HttpErrorResponseExceptionHandler.cs:line 113\r\n   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception) in d:\\Jenkins\\jobs\\v3-release-build\\workspace\\AWSDotNetPublic\\sdk\\src\\Core\\Amazon.Runtime\\Pipeline\\ErrorHandler\\ErrorHandler.cs:line 202\r\n   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext) in d:\\Jenkins\\jobs\\v3-release-build\\workspace\\AWSDotNetPublic\\sdk\\src\\Core\\Amazon.Runtime\\Pipeline\\ErrorHandler\\ErrorHandler.cs:line 76\r\n   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in d:\\Jenkins\\jobs\\v3-release-build\\workspace\\AWSDotNetPublic\\sdk\\src\\Core\\Amazon.Runtime\\Pipeline\\Handlers\\CallbackHandler.cs:line 46\r\n   at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext) in d:\\Jenkins\\jobs\\v3-release-build\\workspace\\AWSDotNetPublic\\sdk\\src\\Core\\Amazon.Runtime\\Pipeline\\RetryHandler\\RetryHandler.cs:line 88\r\n   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in d:\\Jenkins\\jobs\\v3-release-build\\workspace\\AWSDotNetPublic\\sdk\\src\\Core\\Amazon.Runtime\\Pipeline\\Handlers\\CallbackHandler.cs:line 46\r\n   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in d:\\Jenkins\\jobs\\v3-release-build\\workspace\\AWSDotNetPublic\\sdk\\src\\Core\\Amazon.Runtime\\Pipeline\\Handlers\\CallbackHandler.cs:line 46\r\n   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext) in d:\\Jenkins\\jobs\\v3-release-build\\workspace\\AWSDotNetPublic\\sdk\\src\\Core\\Amazon.Runtime\\Pipeline\\Handlers\\ErrorCallbackHandler.cs:line 44\r\n   at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext) in d:\\Jenkins\\jobs\\v3-release-build\\workspace\\AWSDotNetPublic\\sdk\\src\\Core\\Amazon.Runtime\\Pipeline\\Handlers\\MetricsHandler.cs:line 40\r\n   at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext) in d:\\Jenkins\\jobs\\v3-release-build\\workspace\\AWSDotNetPublic\\sdk\\src\\Core\\Amazon.Runtime\\Pipeline\\RuntimePipeline.cs:line 136\r\n   at Amazon.Runtime.AmazonServiceClient.Invoke[TRequest,TResponse](TRequest request, IMarshaller`2 marshaller, ResponseUnmarshaller unmarshaller) in d:\\Jenkins\\jobs\\v3-release-build\\workspace\\AWSDotNetPublic\\sdk\\src\\Core\\Amazon.Runtime\\AmazonServiceClient.cs:line 117\r\n   at Amazon.SimpleNotificationService.AmazonSimpleNotificationServiceClient.Publish(PublishRequest request) in d:\\Jenkins\\jobs\\v3-release-build\\workspace\\AWSDotNetPublic\\sdk\\src\\Services\\SimpleNotificationService\\Generated\\_bcl45\\AmazonSimpleNotificationServiceClient.cs:line 2127\r\n   at Raas.Assets.Data.SNSManager.PostToTopic(String topicARN, TupleList`2 messages)`

I would appreciate if you would tell me how to resolve this problem in a simple way, Thanks a lot!

**Comment by sstevenkang** [comment]
Seems like the service returned a malformed XML payload; or, at least the SDK thinks so.  When you say this happens occasionally, does this happen at random or does it happen consistently when publishing a certain subject, message and arn combination?  Also, could you can share the REST request/response traffic when this exception is raised?

**Comment by gokarnm** [comment]
Closing this due to lack of activity, feel free to reopen with the information that was requested.

**Comment by Singh400** [comment]
Hi,

We are seeing these exceptions with increasing frequency on our platform. It used to happen maybe once every six months or so. Today it has happened six times. Our abstraction is using a fan-out pattern. All messages are published onto a SNS topic. Various SQS queues are subscribed to the respective topics. These exceptions are happening across different types of messages.

```
Amazon.Runtime.AmazonUnmarshallingException: Error unmarshalling response back from AWS.  ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at Amazon.Runtime.Internal.Transform.XmlUnmarshallerContext.Read()
   at Amazon.Runtime.Internal.Transform.ErrorResponseUnmarshaller.Unmarshall(XmlUnmarshallerContext context)
   at Amazon.SimpleNotificationService.Model.Internal.MarshallTransformations.PublishResponseUnmarshaller.UnmarshallException(XmlUnmarshallerContext context, Exception innerException, HttpStatusCode statusCode)
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.AmazonServiceClient.Invoke[TRequest,TResponse](TRequest request, IMarshaller`2 marshaller, ResponseUnmarshaller unmarshaller)
   at Amazon.SimpleNotificationService.AmazonSimpleNotificationServiceClient.Publish(PublishRequest request)
```

If there is any further information required, please let us know.

Cheers,
Indy
