### ISSUE TITLE
is there UWP and WP8.1 support on xamarin.forms (PCL)?

### ISSUE THREAD

**Issue by EmilAlipiev** [aws/aws-sdk-net#506]
I am trying to implement Cognito Identity and it worked fine for Android but when I change platform to UWP. I get the error message as below.

it seems like PCL version doesnt support UWP. Can you please confirm it? is there any plan to support it or we should implement in native and access with dependency injection only.

thank you for your effort
```

System.NotImplementedException was unhandled by user code
  HResult=-2147467263
  Message=This functionality is not implemented in the portable version of this assembly. You should reference the AWSSDK.Core NuGet package from your main application project in order to reference the platform-specific implementation.
  Source=AWSSDK.Core
  StackTrace:
       at Amazon.Util.Internal.PlatformServices.ApplicationSettings.GetValue(String key, ApplicationSettingsMode mode)
       at Amazon.CognitoIdentity.CognitoAWSCredentials.GetCachedIdentityId()
       at Amazon.CognitoIdentity.CognitoAWSCredentials..ctor(String accountId, String identityPoolId, String unAuthRoleArn, String authRoleArn, IAmazonCognitoIdentity cibClient, IAmazonSecurityTokenService stsClient)
       at Amazon.CognitoIdentity.CognitoAWSCredentials..ctor(String accountId, String identityPoolId, String unAuthRoleArn, String authRoleArn, RegionEndpoint region)
       at Amazon.CognitoIdentity.CognitoAWSCredentials..ctor(String identityPoolId, RegionEndpoint region)
```

**Comment by Tapperi** [comment]
Same issue here. Did you find any solution or workaround on this? Just starting with xamarin.forms, pcl and s3, and documentation sayt this should also work with uwp?

**Comment by EmilAlipiev** [comment]
No Sorry, i didnt find . please let me know if you find something. It looks like there isnt much support for aws. Looks like Amazon doesnt care much about xamarin.

**Comment by sstevenkang** [comment]
Hi guys.  We are aware of this issue and have a fix in review.

**Comment by sstevenkang** [comment]
https://github.com/aws/aws-sdk-net/commit/af26c3b986e11bab65aa93fbf611e36440888671 has been committed which should resolve this problem.  Updating it to the latest nuget packages would resolve the problem. Feel free to reopen the issue if the issue persists.
