### ISSUE TITLE
Getting exception "A connection with the server could not be established"

### ISSUE THREAD

**Issue by chethanra** [aws/aws-sdk-net#526]
Hi,

I am getting following exception in few machine and same work fine in remaining machines. It throws this exception while fetching/saving (ex: SaveAsync(...)) data into dynamodb using dynamo db context.

Exception:
```
ex           {System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: **A connection with the server could not be established**
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at Amazon.Runtime.HttpWebRequestMessage.GetResponse() in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_mobile\HttpRequestMessageFactory.cs:line 368
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:line 85
   at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\Unmarshaller.cs:line 50
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 81
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 46
   at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\RetryHandler\RetryHandler.cs:line 88
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 46
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 46
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\ErrorCallbackHandler.cs:line 44
   at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\MetricsHandler.cs:line 40
   at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\RuntimePipeline.cs:line 136
   at Amazon.Runtime.AmazonServiceClient.Invoke[TRequest,TResponse](TRequest request, IMarshaller`2 marshaller, ResponseUnmarshaller unmarshaller) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\AmazonServiceClient.cs:line 192
   at Amazon.DynamoDBv2.AmazonDynamoDBClient.DescribeTable(DescribeTableRequest request) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Generated\_mobile\AmazonDynamoDBClient.cs:line 1186
   at Amazon.DynamoDBv2.DocumentModel.Table.DescribeTable(String tableName) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DocumentModel\Table.cs:line 302
   at Amazon.Runtime.Internal.Util.Cache`2.GetValueHelper(TKey key, Boolean& isStaleItem, Func`2 creator) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\Util\SdkCache.cs:line 424
   at Amazon.DynamoDBv2.DocumentModel.Table.LoadTableInfo() in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DocumentModel\Table.cs:line 130
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.GetTable(String tableName, DynamoDBFlatConfig flatConfig) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DataModel\ContextInternal.cs:line 119
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.GetTargetTable(ItemStorageConfig storageConfig, DynamoDBFlatConfig flatConfig) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DataModel\ContextInternal.cs:line 109
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.ConvertScan[T](IEnumerable`1 conditions, DynamoDBOperationConfig operationConfig) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DataModel\ContextInternal.cs:line 962
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.ScanAsync[T](IEnumerable`1 conditions, DynamoDBOperationConfig operationConfig) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DataModel\_async\Context.Async.cs:line 306
   at xxx.yyy.zzz.Repositories.Repository.<xxx-yyy-zzz-Contract-Repositories-IRepository-GetUser>d__5.MoveNext() in D:\xxxx\Source\xxxservice\xxx-yyy-zzz\Repositories\UserRepository.cs:line 94}                System.Exception {System.Net.Http.HttpRequestException}
+                             Data       {System.Collections.ListDictionaryInternal}          System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
                                HResult -2147012867       int
                                HelpLink               null         string
+                             InnerException {System.Net.Http.WinHttpException: A connection with the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()}       System.Exception {System.Net.Http.WinHttpException}
                                Message              "**An error occurred while sending the request.**" string
                                Source  "AWSSDK.Core"               string
                                StackTrace          "   at Amazon.Runtime.HttpWebRequestMessage.GetResponse() in E:\\JenkinsWorkspaces\\v3-stage-release\\AWSDotNetPublic\\sdk\\src\\Core\\Amazon.Runtime\\Pipeline\\HttpHandler\\_mobile\\HttpRequestMessageFactory.cs:line 368\r\n   at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext) in E:\\JenkinsWorkspaces\\v3-stage-release\\AWSDotNetPublic\\sdk\\src\\Core\\Amazon.Runtime\\Pipeline\\HttpHandler\\HttpHandler.cs:line 85\r\n   at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext) in E:\\JenkinsWorkspaces\\v3-stage-release\\AWSDotNetPublic\\sdk\\src\\Core\\Amazon.Runtime\\Pipeline\\Handlers\\Unmarshaller.cs:line 50\r\n   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext) in E:\\JenkinsWorkspaces\\v3-stage-release\\AWSDotNetPublic\\sdk\\src\\Core\\Amazon.Runtime\\Pipeline\\ErrorHandler\\ErrorHandler.cs:line 81\r\n   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in E:\\JenkinsWorkspaces\\v3-stage-release\\AWSDotNetPublic\\sdk\\src\\Core\\Amazon.Runtime\\Pipeline\\Handlers\\CallbackHandler.cs:line 46\r\n   at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext) in E:\\JenkinsWorkspaces\\v3-stage-release\\AWSDotNetPublic\\sdk\\src\\Core\\Amazon.Runtime\\Pipeline\\RetryHandler\\RetryHandler.cs:line 88\r\n   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in E:\\JenkinsWorkspaces\\v3-stage-release\\AWSDotNetPublic\\sdk\\src\\Core\\Amazon.Runtime\\Pipeline\\Handlers\\CallbackHandler.cs:line 46\r\n   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in E:\\JenkinsWorkspaces\\v3-stage-release\\AWSDotNetPublic\\sdk\\src\\Core\\Amazon.Runtime\\Pipeline\\Handlers\\CallbackHandler.cs:line 46\r\n   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext) in E:\\JenkinsWorkspaces\\v3-stage-release\\AWSDotNetPublic\\sdk\\src\\Core\\Amazon.Runtime\\Pipeline\\Handlers\\ErrorCallbackHandler.cs:line 44\r\n   at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext) in E:\\JenkinsWorkspaces\\v3-stage-release\\AWSDotNetPublic\\sdk\\src\\Core\\Amazon.Runtime\\Pipeline\\Handlers\\MetricsHandler.cs:line 40\r\n   at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext) in E:\\JenkinsWorkspaces\\v3-stage-release\\AWSDotNetPublic\\sdk\\src\\Core\\Amazon.Runtime\\Pipeline\\RuntimePipeline.cs:line 136\r\n   at Amazon.Runtime.AmazonServiceClient.Invoke[TRequest,TResponse](TRequest request, IMarshaller`2 marshaller, ResponseUnmarshaller unmarshaller) in E:\\JenkinsWorkspaces\\v3-stage-release\\AWSDotNetPublic\\sdk\\src\\Core\\Amazon.Runtime\\AmazonServiceClient.cs:line 192\r\n   at Amazon.DynamoDBv2.AmazonDynamoDBClient.DescribeTable(DescribeTableRequest request) in E:\\JenkinsWorkspaces\\v3-stage-release\\AWSDotNetPublic\\sdk\\src\\Services\\DynamoDBv2\\Generated\\_mobile\\AmazonDynamoDBClient.cs:line 1186\r\n   at Amazon.DynamoDBv2.DocumentModel.Table.DescribeTable(String tableName) in E:\\JenkinsWorkspaces\\v3-stage-release\\AWSDotNetPublic\\sdk\\src\\Services\\DynamoDBv2\\Custom\\DocumentModel\\Table.cs:line 302\r\n   at Amazon.Runtime.Internal.Util.Cache`2.GetValueHelper(TKey key, Boolean& isStaleItem, Func`2 creator) in E:\\JenkinsWorkspaces\\v3-stage-release\\AWSDotNetPublic\\sdk\\src\\Core\\Amazon.Runtime\\Internal\\Util\\SdkCache.cs:line 424\r\n   at Amazon.DynamoDBv2.DocumentModel.Table.LoadTableInfo() in E:\\JenkinsWorkspaces\\v3-stage-release\\AWSDotNetPublic\\sdk\\src\\Services\\DynamoDBv2\\Custom\\DocumentModel\\Table.cs:line 130\r\n   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.GetTable(String tableName, DynamoDBFlatConfig flatConfig) in E:\\JenkinsWorkspaces\\v3-stage-release\\AWSDotNetPublic\\sdk\\src\\Services\\DynamoDBv2\\Custom\\DataModel\\ContextInternal.cs:line 119\r\n   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.GetTargetTable(ItemStorageConfig storageConfig, DynamoDBFlatConfig flatConfig) in E:\\JenkinsWorkspaces\\v3-stage-release\\AWSDotNetPublic\\sdk\\src\\Services\\DynamoDBv2\\Custom\\DataModel\\ContextInternal.cs:line 109\r\n   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.ConvertScan[T](IEnumerable`1 conditions, DynamoDBOperationConfig operationConfig) in E:\\JenkinsWorkspaces\\v3-stage-release\\AWSDotNetPublic\\sdk\\src\\Services\\DynamoDBv2\\Custom\\DataModel\\ContextInternal.cs:line 962\r\n   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.ScanAsync[T](IEnumerable`1 conditions, DynamoDBOperationConfig operationConfig) in E:\\JenkinsWorkspaces\\v3-stage-release\\AWSDotNetPublic\\sdk\\src\\Services\\DynamoDBv2\\Custom\\DataModel\\_async\\Context.Async.cs:line 306\r\n   at xxx.yyy.zzz.Repositories.UserRepository.<xxx-yyy-zzz-Contract-Repositories-IRepository-GetUser>d__5.MoveNext() in D:\\xxxx\\Source\\xxxservice\\xxx-yyy-zzz\\Repositories\\Repository.cs:line 94"                string
+                             TargetSite           {Amazon.Runtime.Internal.Transform.IWebResponseData GetResponse()}                System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}
```

Thanks,
Chethan

**Comment by PavelSafronov** [comment]
The exception `System.Net.Http.WinHttpException: **A connection with the server could not be established**` can be caused by any number of factors. You'll need to verify that the machines on which this is happening are connected to the internet and are not going through a proxy that may be blocking these requests.

**Comment by normj** [comment]
Closing for lack of activity. Feel free to open with more information.
