### ISSUE TITLE
Sporadic ConnectFailure to Amazon S3

### ISSUE THREAD

**Issue by dyardyGIT** [aws/aws-sdk-net#527]
We have set up an Amazon S3 bucket to manage images/files. Our web application running on IIS 7.x at different times has to use Amazon S3 API/SDK to pull a document from the bucket. It works most of the time however sporadically (a few times a day) our requests for documents fail.

The following is the exception message:

```
System.Exception: An error occurred here with the message 'Amazon.Runtime.AmazonServiceException: A WebException with status ConnectFailure was thrown. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 52.218.144.25:443
at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
--- End of inner exception stack trace ---
at System.Net.HttpWebRequest.GetResponse()
at Amazon.Runtime.Internal.HttpRequest.GetResponse()
at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext)
at Amazon.Runtime.Internal.RedirectHandler.InvokeSync(IExecutionContext executionContext)
at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext)
at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeSync(IExecutionContext executionContext)
at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
...
```
We have increased RAM/CPU but we continue to get sporadic failures. We have increased the retries and timeouts (10minutes) but are still seeing these exceptions/failures.

Have others seen this issue/resolution?

thx

**Comment by sstevenkang** [comment]
Hi there. Do you think you can provide more information, like doing some http traffic monitoring and extracting the specific [request id](http://docs.aws.amazon.com/AmazonS3/latest/dev/troubleshooting.html)? We need more information to help you.

**Comment by sstevenkang** [comment]
Closing due to inactivity.  Please feel free to reopen it with requested information.
