### ISSUE TITLE
appSettings.json on ASPNET.CORE in linux does not work

### ISSUE THREAD

**Issue by lucacasali** [aws/aws-sdk-net#536]
On Linux this version :
    "AWSSDK.Extensions.NETCore.Setup": "3.3.0.2",
    "AWSSDK.S3": "3.3.0.2",
Is not working.

If you configure a simple aspnet core web site with an appSetting.json with
appSettings.json

```
"AWS": {
    "Region": "eu-west-1",
    "AWSAccessKey": "*****",
    "AWSSecretKey": "*****"
  }
}
```

```
public Startup(IHostingEnvironment env)
{
    Console.WriteLine($" Startup --> {env.ContentRootPath}");
    Configuration = new ConfigurationBuilder()
        .SetBasePath(env.ContentRootPath)
        .AddJsonFile("./Configuration/appSettings.json")
        .AddJsonFile($"./Configuration/appSettings_{env.EnvironmentName}.json")
        .AddEnvironmentVariables()
        .Build();

    var opt = Configuration.GetAWSOptions();

    **var s = opt.CreateServiceClient<IAmazonS3>();**
}
```
If you try to get **IAmazonS3** 

```
> Unhandled Exception: Amazon.Runtime.AmazonServiceException: Unable to find credentials
> 
> Exception 1 of 3:
> System.ArgumentException: App.config does not contain credentials information. Either add the AWSAccessKey and AWSSecretKey properties or the AWSProfileName property.
>    at Amazon.Runtime.StoredProfileAWSCredentials..ctor(String profileName, String profilesLocation) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\AWSCredentials.cs:line 679
>    at Amazon.Runtime.FallbackCredentialsFactory.<>c.<Reset>b__6_0() in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\AWSCredentials.cs:line 2105
>    at Amazon.Runtime.FallbackCredentialsFactory.GetCredentials(Boolean fallbackToAnonymous) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\AWSCredentials.cs:line 2150
> 
> Exception 2 of 3:
> System.InvalidOperationException: The environment variables AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY/AWS_SESSION_TOKEN were not set with AWS credentials.
>    at Amazon.Runtime.EnvironmentVariablesAWSCredentials.FetchAWSCredentials() in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\AWSCredentials.cs:line 856
>    at Amazon.Runtime.FallbackCredentialsFactory.<>c.<Reset>b__6_1() in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\AWSCredentials.cs:line 2106
>    at Amazon.Runtime.FallbackCredentialsFactory.GetCredentials(Boolean fallbackToAnonymous) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\AWSCredentials.cs:line 2150
> 
> Exception 3 of 3:
> System.AggregateException: AsyncHelpers.Run method threw an exception. (An error occurred while sending the request.) ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Couldn't connect to server
>    at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
>    at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
>    --- End of inner exception stack trace ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at System.Net.Http.HttpClient.<GetContentAsync>d__32`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Amazon.Runtime.Internal.Util.AsyncHelpers.<>c__DisplayClass1_0`1.<<RunSync>b__0>d.MoveNext() in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\Util\_mobile\AsyncHelpers.cs:line 78
>    --- End of inner exception stack trace ---
>    at Amazon.Runtime.Internal.Util.AsyncHelpers.ExclusiveSynchronizationContext.BeginMessageLoop() in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\Util\_mobile\AsyncHelpers.cs:line 138
>    at Amazon.Runtime.Internal.Util.AsyncHelpers.RunSync[T](Func`1 task) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\Util\_mobile\AsyncHelpers.cs:line 86
>    at Amazon.Util.AWSSDKUtils.DownloadStringContent(Uri uri, TimeSpan timeout) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Util\AWSSDKUtils.cs:line 873
>    at Amazon.Runtime.URIBasedRefreshingCredentialHelper.GetContents(Uri uri) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\AWSCredentials.cs:line 1190
>    at Amazon.Runtime.InstanceProfileAWSCredentials.<GetAvailableRoles>d__10.MoveNext()
>    at Amazon.Runtime.InstanceProfileAWSCredentials.GetFirstRole() in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\AWSCredentials.cs:line 1422
>    at Amazon.Runtime.FallbackCredentialsFactory.ECSEC2CredentialsWrapper() in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\AWSCredentials.cs:line 2129
>    at Amazon.Runtime.FallbackCredentialsFactory.GetCredentials(Boolean fallbackToAnonymous) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\AWSCredentials.cs:line 2150
> ---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Couldn't connect to server
>    at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
>    at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
>    --- End of inner exception stack trace ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at System.Net.Http.HttpClient.<GetContentAsync>d__32`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Amazon.Runtime.Internal.Util.AsyncHelpers.<>c__DisplayClass1_0`1.<<RunSync>b__0>d.MoveNext() in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\Util\_mobile\AsyncHelpers.cs:line 78<---
> 
> 
> 
>    at Amazon.Runtime.FallbackCredentialsFactory.GetCredentials(Boolean fallbackToAnonymous) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\AWSCredentials.cs:line 2141
>    at Amazon.Extensions.NETCore.Setup.ClientFactory.CreateCredentials(AWSOptions options)
>    at Amazon.Extensions.NETCore.Setup.ClientFactory.CreateServiceClient(Type serviceInterfaceType, AWSOptions options)
>    at Amazon.Extensions.NETCore.Setup.AWSOptions.CreateServiceClient[T]()
>    at Technogym.MywellnessCloud.Fuse.Startup..ctor(IHostingEnvironment env) in /home/mwcloud/test/fuse_aws/src/fuse.mywellness.com/Startup.cs:line 52
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
>    at Microsoft.AspNetCore.Hosting.Internal.StartupLoader.LoadMethods(IServiceProvider hostingServiceProvider, Type startupType, String environmentName)
>    at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c__DisplayClass1_0.<UseStartup>b__1(IServiceProvider sp)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureStartup()
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
>    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
>    at Technogym.MywellnessCloud.Fuse.Program.Main(String[] args) in /home/mwcloud/test/fuse_aws/src/fuse.mywellness.com/Program.cs:line 20
> 
```

**Comment by lucacasali** [comment]
Also upgrading  "AWSSDK.S3": "3.3.5.2" it is not working. On windows the same code works

**Comment by ralsu091** [comment]
See issue https://github.com/aws/aws-sdk-net/issues/499

**Comment by sstevenkang** [comment]
@lucacasali, did #499 help diagnose the problem?  If not, could you provide more information regarding your environment and setup?

**Comment by sstevenkang** [comment]
Closing this due to inactivity.  Issue #655 seems unrelated to this topic.

**Comment by SrinathUpadhya** [comment]
i want to write to aws cloudwatch from my application (ASP.NET Core 2.0) using serilogger framework.
 //var renderer = new MyCustomRenderer();
                // options for the sink, specifying the log group name
                //CloudWatchSinkOptions options = new CloudWatchSinkOptions { LogGroupName = logGroupName, LogEventRenderer = MyCustomRenderer };

                // setup AWS CloudWatch client
                AWSCredentials credentials = new BasicAWSCredentials("", "");
                var str = credentials.GetCredentials();
                IAmazonCloudWatchLogs client = new AmazonCloudWatchLogsClient(credentials, RegionEndpoint.APNortheast1);

                var logger = new LoggerConfiguration()
                    .ReadFrom.Configuration(Configuration)
                    .WriteTo.AmazonCloudWatch(new CloudWatchSinkOptions
                    {
                        LogGroupName = "MyLogGroupName",
                        MinimumLogEventLevel = LogEventLevel.Information
                    }, new AmazonCloudWatchLogsClient(credentials, RegionEndpoint.APNortheast1))
                    .CreateLogger();

What credentials i need to pass here in order to write logs to awscloud watch. 
And sharing credentials is also not recommended. is there any other approcah?
