### ISSUE TITLE
The type initializer for 'Amazon.AWSConfigsS3' threw an exception.

### ISSUE THREAD

**Issue by lionsguard** [aws/aws-sdk-net#538]
I am getting the following exception with the associated stack trace when attempting to create a pre-signed url. This is within an NUnit test project.

When I disable/comment out the config section for requiring SignatureVersion4 the URL is generated but since I am encrypting the data in the bucket using the KMS I am required to use sig version 4.

**Exception:**
```
System.TypeInitializationException was unhandled by user code
  HResult=-2146233036
  Message=The type initializer for 'Amazon.AWSConfigsS3' threw an exception.
  Source=AWSSDK.S3
  TypeName=Amazon.AWSConfigsS3
  StackTrace:
       at Amazon.AWSConfigsS3.get_UseSignatureVersion4()
       at Amazon.S3.AmazonS3Client.CreateSigner() in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Services\S3\Generated\_bcl45\AmazonS3Client.cs:line 209
       at Amazon.Runtime.AmazonServiceClient..ctor(AWSCredentials credentials, ClientConfig config) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\AmazonServiceClient.cs:line 154
       [REDACTED]
  InnerException: 
       HResult=-2146232828
       Message=Exception has been thrown by the target of an invocation.
       Source=mscorlib
       StackTrace:
            at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
            at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
            at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
            at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
            at System.Configuration.ConfigurationElement.ApplyInstanceAttributes(Object instance)
            at System.Configuration.ConfigurationElement.get_Properties()
            at System.Configuration.ConfigurationElement.DeserializeElement(XmlReader reader, Boolean serializeCollectionKey)
            at Amazon.V4ClientSectionRoot..ctor(XElement section) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Services\S3\Custom\AWSConfigs.S3.cs:line 162
            at Amazon.AWSConfigsS3..cctor() in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Services\S3\Custom\AWSConfigs.S3.cs:line 75
       InnerException: 
            HResult=-2146233069
            Message=No parameterless constructor defined for this object.
            Source=mscorlib
            StackTrace:
                 at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
                 at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
                 at System.Activator.CreateInstance(Type type, Boolean nonPublic)
                 at System.Configuration.TypeUtil.CreateInstanceWithReflectionPermission(Type type)
                 at System.Configuration.ConfigurationElement.CreateElement(Type type)
                 at System.Configuration.ConfigurationElement.get_Item(ConfigurationProperty prop)
                 at Amazon.V4ClientSectionRoot.get_S3() in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Services\S3\Custom\AWSConfigs.S3.cs:line 167
            InnerException: 
```

**App.config:**
```
<configSections>
    <section name="aws" type="Amazon.AWSSection, AWSSDK.Core"/>
  </configSections>
<aws profileName="test-service" profilesLocation="C:\aws\credentials" region="us-east-1">
    <s3 useSignatureVersion4="true"/>
    <logging logTo="Log4Net"/>
  </aws>
```

**Code:**
```
using (var client = new AmazonS3Client())
{
    var request = new GetPreSignedUrlRequest
    {
        BucketName = bucket,
        Key = objectKey,
        Expires = DateTime.Now.AddMinutes(20)
    };

    return client.GetPreSignedURL(request);
}
```
* bucket and objectKey come out of the config

**Comment by lionsguard** [comment]
If I use the appSettings node, everything works as expected.

**Comment by PavelSafronov** [comment]
Thanks for reporting this.

**Comment by PavelSafronov** [comment]
We've pushed out a code change that fixes this issue. Resolving.
