### ISSUE TITLE
Today version cause default initial of service to fail

### ISSUE THREAD

**Issue by Thaina** [aws/aws-sdk-net#584]
I have got a problem with AWSSDK Lambda and Cognito. Lambda 3.3.2.7 specifically

Just call this

```C#
var lambda = new AmazonLambdaClient();
```

And it throw this

```
One or more errors occurred. (The type initializer for 'LambdaHandler' threw an exception.): AggregateException
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
at lambda_method(Closure , Stream , Stream , ContextInfo )

at LambdaHandler.<myHandler>d__21.MoveNext() in /opt/atlassian/pipelines/agent/build/Program.cs:line 146
The type initializer for 'Amazon.Runtime.FallbackCredentialsFactory' threw an exception.: TypeInitializationException
at Amazon.Lambda.AmazonLambdaClient..ctor()
at LambdaHandler.Config.Create() in /opt/atlassian/pipelines/agent/build/Data/Config.cs:line 18
at LambdaHandler..cctor() in /opt/atlassian/pipelines/agent/build/Program.cs:line 33
The encrypted store is not available on this platform.: AmazonClientException
at Amazon.Util.Internal.SettingsManager.EnsureAvailable()
at Amazon.Runtime.CredentialManagement.NetSDKCredentialsFile..ctor()
at Amazon.Runtime.FallbackCredentialsFactory..cctor()
```

Same as Cognito

**Comment by vellozzi** [comment]
The fix for this issue is released in AWSSDK.Core 3.3.10 at https://www.nuget.org/packages/AWSSDK.Core/. Please let us know if you have any further problems.
