### ISSUE TITLE
NoApplicableSKUsException: This extension is not installable on any currently installed products.

### ISSUE THREAD

**Issue by devocity-us** [aws/aws-sdk-net#608]
Hello,
   I attempted to search for an existing issue related to mine but I was not able too. I have **Visual Studio _2017_ & _2015_ Enterprise** installed currently and attempted to install the [VS 2017 AWS Toolkit Preview](https://aws.amazon.com/blogs/developer/preview-of-the-aws-toolkit-for-visual-studio-2017/). A few seconds after starting [AWSToolkitPackage.VS2017.vsix](https://sdk-for-net.amazonwebservices.com/preview/AWSToolkitPackage.VS2017.vsix) the installed failed with the following **NoApplicableSKUsException**: This extension is not installable on any currently installed products.

I opened the log and found two sections that were interesting. I'm not sure if this was a decision and I didn't read something, by design, or a mistake; about half way into the log under the **Supported Products** section it only lists 1 supported product 
> Microsoft.VisualStudio.Community Version : [15.0,)

The fact that the log states that it only supports VS 2017 Community explains why it did not attempt to install using my instance of Visual Studio 2017 Enterprise.

Further down under the heading **Searching for applicable products...** the install actually found another version of Visual Studio I have installed yet still failed.
- 4/2/2017 3:14:01 PM - Searching for applicable products...
- 4/2/2017 3:14:02 PM - **_Found installed product - Microsoft Visual Studio Enterprise 2015_**
- 4/2/2017 3:14:02 PM - Found installed product - Microsoft Visual Studio Professional 2015
- 4/2/2017 3:14:02 PM - Found installed product - Microsoft Visual Studio Community 2015
- 4/2/2017 3:14:02 PM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
- 4/2/2017 3:14:02 PM - Found installed product - Global Location
- 4/2/2017 3:14:02 PM - Found installed product - ssms

Please advise if this is how it is to be until officially release or if this is an issue.

# VSIX Installer.log:

> 4/2/2017 3:14:01 PM - Microsoft VSIX Installer
4/2/2017 3:14:01 PM - -------------------------------------------
4/2/2017 3:14:01 PM - Initializing Install...
4/2/2017 3:14:01 PM - Extension Details...
4/2/2017 3:14:01 PM - 	Identifier         : 12ed248b-6d4a-47eb-be9e-8eabea0ff119
4/2/2017 3:14:01 PM - 	Name              : AWS Toolkit for Visual Studio 2017
4/2/2017 3:14:01 PM - 	Author             : Amazon Web Services LLC
4/2/2017 3:14:01 PM - 	Version            : 1.12.0.1
4/2/2017 3:14:01 PM - 	Description      : The AWS Toolkit for Visual Studio is an extension for Microsoft Visual Studio that makes it easier for developers to develop, debug, and deploy .NET applications using Amazon Web Services. With the AWS Toolkit for Visual Studio, you'll be able to get started faster and be more productive when building AWS applications.
4/2/2017 3:14:01 PM - 	Locale             : en-US
4/2/2017 3:14:01 PM - 	MoreInfoURL        : http://aws.amazon.com/sdkfornet
4/2/2017 3:14:01 PM - 	InstalledByMSI     : False
4/2/2017 3:14:01 PM - 	SupportedFrameworkVersionRange : [4.6,)
4/2/2017 3:14:01 PM - 
4/2/2017 3:14:01 PM - 	SignatureState     : ValidSignature
4/2/2017 3:14:01 PM - 	SignedBy           : Amazon.com, Inc.
4/2/2017 3:14:01 PM - 	Certificate Info   : 
4/2/2017 3:14:01 PM - 		-------------------------------------------------------
4/2/2017 3:14:01 PM - 		[Subject]       : CN="Amazon.com, Inc.", OU=Amazon Web Services, O="Amazon.com, Inc.", L=Seattle, S=Washington, C=US
4/2/2017 3:14:01 PM - 		[Issuer]        : CN=Symantec Class 3 SHA256 Code Signing CA, OU=Symantec Trust Network, O=Symantec Corporation, C=US
4/2/2017 3:14:01 PM - 		[Serial Number] : 221F14F6E28EA1ABD010EA24DA1BBA0B
4/2/2017 3:14:01 PM - 		[Not Before]    : 6/21/2016 8:00:00 PM
4/2/2017 3:14:01 PM - 		[Not After]     : 6/18/2017 7:59:59 PM
4/2/2017 3:14:01 PM - 		[Thumbprint]    : 695BF9422F01FFEEC9187B1FD688185A1B299CAE
4/2/2017 3:14:01 PM - 
4/2/2017 3:14:01 PM - 	Supported Products : 
4/2/2017 3:14:01 PM - 		Microsoft.VisualStudio.Community
4/2/2017 3:14:01 PM - 			Version : [15.0,)
4/2/2017 3:14:01 PM - 
4/2/2017 3:14:01 PM - 	References         : 
4/2/2017 3:14:01 PM - 		-------------------------------------------------------
4/2/2017 3:14:01 PM - 		Identifier   : Microsoft.VisualStudio.MPF.11.0
4/2/2017 3:14:01 PM - 		Name         : Visual Studio MPF 11.0
4/2/2017 3:14:01 PM - 		Version      : [11.0]
4/2/2017 3:14:01 PM - 		MoreInfoURL  : 
4/2/2017 3:14:01 PM - 		Nested       : No
4/2/2017 3:14:01 PM - 
4/2/2017 3:14:01 PM - Signature Details...
4/2/2017 3:14:01 PM - 	Extension is signed with a valid signature.
4/2/2017 3:14:01 PM - 
4/2/2017 3:14:01 PM - Searching for applicable products...
4/2/2017 3:14:02 PM - Found installed product - Microsoft Visual Studio Enterprise 2015
4/2/2017 3:14:02 PM - Found installed product - Microsoft Visual Studio Professional 2015
4/2/2017 3:14:02 PM - Found installed product - Microsoft Visual Studio Community 2015
4/2/2017 3:14:02 PM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
4/2/2017 3:14:02 PM - Found installed product - Global Location
4/2/2017 3:14:02 PM - Found installed product - ssms
4/2/2017 3:14:02 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

Thanks,
Patrick

**Comment by steveataws** [comment]
I can't yet explain why the preview isn't installing for you in your VS2017 Enterprise edition install, but a couple of notes -

1. The 2017 preview vsix file is for VS2017 editions only - it does not install into earlier versions of Visual Studio. To install the toolkit into your 205 Enterprise edition you'll need to download our regular Windows Installer file from https://sdk-for-net.amazonwebservices.com/latest/AWSToolsAndSDKForNet.msi.

2. The manifest file that describes a VSIX plugin lists the lowest supported SKU for an edition - which is why you are seeing 'Community'. I have the same VSIX file as you installed in my Professional level edition. Given the changes in VS2017 it's quite possible we missed some other setting or didn't quite get our version range corrct so will investigate further and see what I can find and report back.

**Comment by steveataws** [comment]
I've not been able to set up a system with 2015 and 2017 Enterprise editions yet, but on a fresh system with just 2017 Enterprise the preview vsix package we are currently shipping installed without any issue. When I ran the vsix installer, it correctly noted I had 2017 Enterprise and all went well from there.

I'm wondering if perhaps this is a dependency issue, although we declare our package to only depend on the host shell (or core editor as it's referred to in the vsix integration docs). When you installed 2017 Enterprise, can you tell us what features you selected for installation?

**Comment by gokarnm** [comment]
Closing this for lack of activity, feel free to reopen with more information.
