### ISSUE TITLE
Intermittent issue with upload - The request was aborted: Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by rsrini83** [aws/aws-sdk-net#614]
Hi,

Recently we are facing upload failure(frequent) with the below exception,

```
An unhandled exception was caught at the service layer. System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> Amazon.Runtime.AmazonServiceException: A WebException with status SecureChannelFailure was thrown. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure 
 channel.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
```

We are running our application in EC2 Instances (10 instances in parallel), same region as S3 bucket. 

We didn't hit this issue when EC2 instances and S3 buckets are in same AWS account. We are seeing this issue when EC2 instances are in one AWS account and S3 buckets are in another account. I'm not sure this makes any difference. But would like to call it out. 

Any suggestions to fix this issue.

--Srinu

**Comment by gokarnm** [comment]
Hi Srinu, the accounts should not make a difference. Are you accessing the same bucket in both cases? What is the region for the bucket? How frequently do you see this error?

Could you enable `System.Diagnostics` logging for `System.Net` ? The instructions to enable this logging is present [here](http://stackoverflow.com/questions/12317771/the-request-was-aborted-could-not-create-ssl-tls-secure-channel/12327881). This would give detailed logging for the .NET System.Net library.
The log should have more details about the failure, here is an [example](https://blogs.msdn.microsoft.com/asiatech/2009/04/08/using-system-net-trace-to-troubleshooting-ssl-problem-in-net-2-0-application/).

**Comment by gokarnm** [comment]
Are you still facing this issue?

**Comment by rsrini83** [comment]
HI Goakarnm,

Some how i missed your first response. Here are the details requested,
Are you accessing the same bucket in both cases? 
Srinu>> No. Each instance uploads to different bucket.
What is the region for the bucket?
Srinu>> Bucket and Instance are in same region. (US-EAST-1)
How frequently do you see this error?
Srinu>> Initially we have seen very rarely, however it gradually increased and 3 out of 10 instnaces faced this issue with multiple upload failures.
Will try with enabling System.Diagnositics and let you  know the result in next couple of days.


--Srinu

**Comment by megnap** [comment]
Hi,
I am facing the same issue.  S3 region: **us-west-2** 
A WebException with status SecureChannelFailure was thrown. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---

**Comment by sstevenkang** [comment]
@megnap  could you provide us with a detailed log following the steps @gokarnm gave above?

**Comment by sstevenkang** [comment]
Closing due to inactivity.
