### ISSUE TITLE
Copying encrypted RDS DB snapshot fails using IAM roles

### ISSUE THREAD

**Issue by mwhouser** [aws/aws-sdk-net#635]
When attempting to copy an Encrypted RDS DB snapshot using IAM roles, the SDK fails to generate the pre-signed URL correctly.

The copy succeeds when:

* the source DB snapshot is NOT encrypted, or
* the credentials used are access key/secret (IAM user)

But when the source DB snapshot is encrypted AND an IAM role is being used, the copy fails.

The IAM role can be attained by:

* IAM roles for EC2 instances
* Using `sts:AssumeRole`

The results (failure) is the same.

## Expected Behavior

Using `Amazon.RDS.AmazonRDSClient.CopyDBSnapshot` with a client that's authenticated using IAM roles for EC2 instances, the copy should succeed:

```c#
var request = new Amazon.RDS.Model.CopyDBSnapshotRequest()
{
    SourceDBSnapshotIdentifier = "arn:aws:rds:us-east-1:123456789012:snapshot:snapshot-id",
    SourceRegion = "us-east-1",
    TargetDBSnapshotIdentifier = "target-snapshot-id",
    KmsKeyId = kmsKeyGuid,
};
var response = client.CopyDBSnapshot(request);
```

## Current Behavior

An exception is thrown with message: PreSignedUrl could not be authenticated

```
Amazon.RDS.AmazonRDSException: PreSignedUrl could not be authenticated. ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpRequest.GetResponse() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_bcl\HttpWebRequestFactory.cs:line 106
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpRequest.GetResponse() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_bcl\HttpWebRequestFactory.cs:line 114
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:line 85
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
   at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\Unmarshaller.cs:line 48
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 72
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\HttpErrorResponseExceptionHandler.cs:line 114
   at Amazon.Runtime.Internal.ExceptionHandler`1.Handle(IExecutionContext executionContext, Exception exception) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ExceptionHandler.cs:line 38
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 204
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 78
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 45
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
   at Amazon.Runtime.Internal.Signer.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\Signer.cs:line 38
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CredentialsRetriever.cs:line 72
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
   at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\RetryHandler\RetryHandler.cs:line 84
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 45
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
   at Amazon.Runtime.Internal.EndpointResolver.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\EndpointResolver.cs:line 34
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
   at Amazon.Runtime.Internal.Marshaller.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\Marshaller.cs:line 37
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
   at Amazon.RDS.Internal.PreSignedUrlRequestHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Services\RDS\Custom\Internal\PreSignedUrlRequestHandler.cs:line 56
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 45
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\ErrorCallbackHandler.cs:line 44
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 55
   at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\MetricsHandler.cs:line 40
   at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\RuntimePipeline.cs:line 135
   at Amazon.Runtime.AmazonServiceClient.Invoke[TRequest,TResponse](TRequest request, IMarshaller`2 marshaller, ResponseUnmarshaller unmarshaller) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\AmazonServiceClient.cs:line 192
   at Amazon.RDS.AmazonRDSClient.CopyDBSnapshot(CopyDBSnapshotRequest request) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Services\RDS\Generated\_bcl45\AmazonRDSClient.cs:line 929
   at CopyEncryptedRdsSnapshots.Program.ExecuteCopy(String targetId, IAmazonRDS client) in C:\Users\matt\documents\visual studio 2017\Projects\CopyEncryptedRdsSnapshots2\CopyEncryptedRdsSnapshots2\Program.cs:line 58
   at CopyEncryptedRdsSnapshots.Program.Main(String[] args) in C:\Users\matt\documents\visual studio 2017\Projects\CopyEncryptedRdsSnapshots2\CopyEncryptedRdsSnapshots2\Program.cs:line 31
```

## Steps to Reproduce (for bugs)

Sample Program:

```c#
namespace CopyEncryptedRdsSnapshots
{
    class Program
    {
        static void Main(string[] args)
        {

            // Copy by IAM EC2 role
            {
                var client = new Amazon.RDS.AmazonRDSClient(Amazon.RegionEndpoint.USWest2);
                try
                {
                    ExecuteCopy("target-snapshot-id", client);

                    Console.WriteLine("Copy by IAM role successful.");
                }
                catch (Exception e)
                {
                    Console.WriteLine("Copy by IAM role failed: {0}", e);
                }

            }

            Console.WriteLine("Press Enter to continue...");
            Console.ReadLine();
        }

        static void ExecuteCopy(string targetId, Amazon.RDS.IAmazonRDS client)
        {
            var request = new Amazon.RDS.Model.CopyDBSnapshotRequest()
            {
                SourceDBSnapshotIdentifier = "arn:aws:rds:us-east-1:123456789012:snapshot:snapshot-id",
                SourceRegion = "us-east-1",

                TargetDBSnapshotIdentifier = targetId,
                KmsKeyId = "<kms-key-id>",
            };

            var response = client.CopyDBSnapshot(request);
        }
    }
}
```

## Context

This is blocking the copying of encrypted DB snapshots using IAM roles.

## Your Environment

* AWSSDK.Core version used:  3.3.13.2
* AWSSDK.RDS version used: 3.3.10 
* Operating System and version: Windows 2012 Server, Windows 2016 Server
* Visual Studio version: Visual Studio 2013, 2017
* Targeted .NET platform: 4.5, 4.6.1

**Comment by PavelSafronov** [comment]
Can you verify that the IAM role you are assuming has the correct permissions? If you provide the role permission to all RDS resources, does the copy succeed?

**Comment by PavelSafronov** [comment]
Can you also specify how the encrypted DB snapshot is/can be created? I'm having issues reproducing this because the encrypted snapshots I'm creating don't have ARNs and I thus can't make the `CopyDBSnapshot` call to reproduce the error you are seeing.

**Comment by mwhouser** [comment]
The IAM policy that's attached to my IAM role is the following:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "kms:CreateGrant",
                "kms:DescribeKey",
                "kms:ListAliases"
            ],
            "Effect": "Allow",
            "Resource": "*"
        },
        {
            "Action": [
                "rds:CopyDBSnapshot",
                "rds:DeleteDBSnapshot",
                "rds:DescribeDBSnapshots",
                "rds:ListTagsForResource"
            ],
            "Effect": "Allow",
            "Resource": "*"
        }
    ]
}
```

It is identical to the policy attached to my IAM user, which works correctly.

I have also attached the "AdministratorAccess" managed policy to my role, and it did not make things better.

**Comment by mwhouser** [comment]
For me, any DB snapshot has the same error:

* Auto-generated DB snapshots by my RDS instance, or
* Manually created DB snapshots by my RDS instance.

In my specific case, I did this:

1. I started with a non-encrypted RDS instance (MySQL).
2. I created a manual DB snapshot from my instance (will be unencrypted as well)
3. I copied the snapshot (in the same region) using the AWS Management Console, this time encrypting the snapshot during the copy. I tried using both the "aws/rds" KMS key, but also a custom KMS key.
4. My ARNs are shown in the AWS Management Console snapshot details. However, they are always the following format: `arn:aws:rds:<region name>:<account #>:snapshot:<snapshot-id>` so you could probably just construct your own from your other known information.

**Comment by PavelSafronov** [comment]
OK, was finally able to reproduce this. The key was to start with MySQL DB, then the created snapshots had ARNs and I was able to work with them.
It looks like this is not specific to AssumeRole credentials and reproduces with any session credentials, for instance [STS.GetSessionToken](http://docs.aws.amazon.com/STS/latest/APIReference/API_GetSessionToken.html).

**Comment by vellozzi** [comment]
We've identified the issue and will release the fix as soon as we can.  
The issue is that RDS treats the X-Amz-Security-Token parameter in the PreSignedUrl as case-sensitive.  The .NET SDK is generating the PreSignedUrl with x-amz-security-token though.
