### ISSUE TITLE
File uploaded to S3 with space can't be downloaded with GetObjectAsync

### ISSUE THREAD

**Issue by tamhinsf** [aws/aws-sdk-net#640]
AWSSDK.S3/3.3.5.15 in a .NETCoreApp,Version=v1.1 CLI app on OS X.

Create an S3 bucket, attach an SNS notification on the bucket for PUT events
Configure SNS to dump the notification into SQS.
Upload to S3 a file with a space in its name ("this image.jpg") to an S3 bucket.
Process the SQS message that has embedded JSON with the S3 file (key) name in it.

Use this snippet of code to download the S3 object.

```
 var response = await s3Client.GetObjectAsync(myClass.S3.Bucket.Name,
                          myClass.S3.Object.Key);
```

(works fine if file is named "thisimage.jpg" but not "this image.jpg")

When the uploaded file is "this image.jpg", the key is returned as "this+image.jpg" in the S3 -> SNS -> SQS notification JSON.  However, in the S3 web UI, the key is "this image.jpg".   Furthermore, the S3 web UI lists the URL to the file as https://region/bucket/this+image.jpg

Upon calling GetObjectASync, this exception gets thrown.  Here's the dump:
```
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.<InvokeAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CloudtrailToAzure.Program.<GetAndUploadAttachment>d__20.MoveNext() in <path to my code removed>
```

Am I doing something wrong?

**Comment by PavelSafronov** [comment]
What was the actual exception that was thrown? The stack trace you have listed does not contain that information.

Initial read suggests that this is an issue in the S3 -> SNS -> SQS data flow, and not specifically a .NET SDK issue. You would need to identify where the + is being injected into the key name (SNS or SQS?) and follow up with that service team, through their respective forums: [SNS forum](https://forums.aws.amazon.com/forum.jspa?forumID=72) or [SQS forum](https://forums.aws.amazon.com/forum.jspa?forumID=12). This repo is for mainly for reporting issues and bugs with the .NET SDK, and from the current information it sounds like this would be an issue with any SDK, so I'm inclined to close this issue.

**Comment by tamhinsf** [comment]
I think you're right that this is a service issue versus one with the SDK.  

For what it's worth, here's the full exception thrown immediately after calling GetObjectAsync using the key provided by the JSON notification (which inserts a "+" wherever a space is in the filename).  Looks like my cut-and-paste was cut off. 

> Exception Amazon.S3.AmazonS3Exception: The specified key does not exist. ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amaz
on.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.<GetResponseAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.HttpHandler`1.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.RedirectHandler.<InvokeAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.Unmarshaller.<InvokeAsync>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.<InvokeAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5`1.MoveNext()
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.<InvokeAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CloudtrailToAzure.Program.<GetAndUploadAttachment>d__20.MoveNext() in <path to my code removed>

Reproducing:

Immediately after uploading "this image.jpg" into the S3 section of the AWS Console, I see these file properties.   Note I've obscured a couple of fields - but you can see the difference between the key (file name) and the link - which has introduced a "+" (https://region/bucket/key)

![s3console](http://i63.tinypic.com/j0uste.png)

If you run this snippet of code, the key returned is "this image.jpg" (different than the JSON notification provided by the S3 bucket).  The file can be successfully downloaded by GetObjectAsync.  

~~~~        

static async Task BrowseBucket()
{
            var s3Client = new AmazonS3Client(accessKey,secretKey,Amazon.RegionEndpoint.USWest1);
            ListObjectsRequest request = new ListObjectsRequest();
            request.BucketName = "obscured-bucket-name";
            ListObjectsResponse response = await s3Client.ListObjectsAsync(request);
            foreach(var v in response.S3Objects)
            {
                Console.WriteLine("The key is " + v.Key + " ");
                var getObjectResponse = await s3Client.GetObjectAsync(request.BucketName,
                        v.Key);
            }
}

~~~~       

Can you point me in the right direction of the S3 team? 
Is there another method to call to work around this issue?

**Comment by PavelSafronov** [comment]
I tried configuring SNS, SQS, and Lambda notifications for a bucket, and all three receive incorrect (space replaced by plus) keys, so it looks like this is an S3 issue.
The [S3 forum](https://forums.aws.amazon.com/forum.jspa?forumID=24) is a good starting point. I'm also going to contact the team internally about this.

As this is not an issue with the .NET SDK, I'm going to close the issue, but feel free to add more information here if you feel it is relevant. I'll also update the issue if I learn anything.

**Comment by tamhinsf** [comment]
Fair enough.  Thanks for taking the issue up internally.  I'll just have to filter key names (file names) prior to calling GetObjectAsync and hope I don't clobber anything else.   Thanks.

**Comment by PavelSafronov** [comment]
I tried uploading a file named `this im + age blah.txt` and the key in the event ended up being `this+im+%2B+age+blah.txt`. It looks like S3 is url-encoding the keys before sending them, so perhaps you could run something like `WebUtility.UrlDecode(eventKey)` to get the "correct" key. But right now that's just a theory on my part.
