### ISSUE TITLE
Load credentials from .NET SDK when running IIS locally

### ISSUE THREAD

**Issue by mr-olson** [aws/aws-sdk-net#673]
## Expected Behavior
When configuring a local development machine with full IIS, and running the AppPool under my user account and "Load User Profile" set to true, I expect the SDK to pick up credentials from the .NET credential store in C:\Users\<username>\AppData\Local\AWSToolkit .

## Current Behavior
Without a workaround, I get the stack trace in https://stackoverflow.com/questions/29558015/amazon-runtime-amazonserviceexception-unable-to-find-credentials

## Possible Solution
Try .NET credential store when only a profile name is supplied in config

## Steps to Reproduce (for bugs)
1. Create an AWS profile in Visual Studio
2. Create simple web application that references the profile via AWSProfileName in Web.Config or appsettings.json
3. Test access to AWS resource(s) such as S3 buckets
4. Install full IIS
5. Configure web site in IIS
6. Set app pool up with your own credentials, set the "Load User Profile" option true
7. Open test website, get stack trace referenced above in current behavior

## Context
This would be nice to have so that developers don't need to have unencrypted credentials lying around on their machines and risk disclosure or checking them into source control accidentally.

**Comment by sstevenkang** [comment]
Could you provide more information?  Which platform are you targeting 4.5 or .net core?  Also, could you share what your web.config looks like?

**Comment by vellozzi** [comment]
What version of the AWSSDK.Core nuget package are you using?  I can't see how that stack trace would be produced with the latest version of AWSSDK.Core.  Are you using an older version?  Could you upgrade to the latest?

**Comment by mr-olson** [comment]
I'm using .NET 4.5 in a simple MVC project just to prove out the concept of using the VS credential store, just trying to list contents of an S3 bucket.

I confirmed that the IIS app pool is using my identity by removing all other permissions from the .aws/credentials file and hard-coding its path in the Web.config temporarily via the AWSProfilesLocation key.

I also confirmed the IIS Express hosting option does work as expected with only an AWSProfileName key set. In the VS debugger, the credentials associated are type "Amazon.Runtime.AssumeRoleAWSCredentialsOptions".

Relevant portion of Web.config:
  <appSettings>
    <add key="AWSProfileName" value="NAMED_PROFILE_IN_.NET_Credential_Store" />
    <add key="AWSRegion" value="us-west-2" />
  </appSettings>

Upgraded to 3.3.14.1 for AWSSDK.Core, might have been behind, but the current stack trace is only mildly changed:

Exception Details: Amazon.Runtime.AmazonServiceException: Unable to find credentials

Exception 1 of 4:
System.InvalidOperationException: The app.config/web.config files for the application did not contain credential information
  at Amazon.Runtime.AppConfigAWSCredentials..ctor() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Credentials\_bcl\AppConfigAWSCredentials.cs:line 69
  at Amazon.Runtime.FallbackCredentialsFactory.<>c.<Reset>b__8_0() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Credentials\FallbackCredentialsFactory.cs:line 48
  at Amazon.Runtime.FallbackCredentialsFactory.GetCredentials(Boolean fallbackToAnonymous) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Credentials\FallbackCredentialsFactory.cs:line 113

Exception 2 of 4:
Amazon.Runtime.AmazonClientException: Unable to find a default profile in CredentialProfileStoreChain.
  at Amazon.Runtime.FallbackCredentialsFactory.GetAWSCredentials(ICredentialProfileSource source, String defaultProfileName) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Credentials\FallbackCredentialsFactory.cs:line 69
  at Amazon.Runtime.FallbackCredentialsFactory.GetCredentials(Boolean fallbackToAnonymous) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Credentials\FallbackCredentialsFactory.cs:line 113

Exception 3 of 4:
System.InvalidOperationException: The environment variables AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY/AWS_SESSION_TOKEN were not set with AWS credentials.
  at Amazon.Runtime.EnvironmentVariablesAWSCredentials.FetchCredentials() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Credentials\_bcl+coreclr\EnvironmentVariablesAWSCredentials.cs:line 80
  at Amazon.Runtime.FallbackCredentialsFactory.<>c.<Reset>b__8_2() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Credentials\FallbackCredentialsFactory.cs:line 53
  at Amazon.Runtime.FallbackCredentialsFactory.GetCredentials(Boolean fallbackToAnonymous) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Credentials\FallbackCredentialsFactory.cs:line 113

Exception 4 of 4:
Amazon.Runtime.AmazonServiceException: Unable to reach credentials server
  at Amazon.Runtime.URIBasedRefreshingCredentialHelper.GetContents(Uri uri) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Credentials\URIBasedRefreshingCredentialHelper.cs:line 36
  at Amazon.Runtime.InstanceProfileAWSCredentials.<GetAvailableRoles>d__10.MoveNext() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Credentials\InstanceProfileAWSCredentials.cs:line 0
  at Amazon.Runtime.InstanceProfileAWSCredentials.GetFirstRole() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Credentials\InstanceProfileAWSCredentials.cs:line 204
  at Amazon.Runtime.FallbackCredentialsFactory.ECSEC2CredentialsWrapper() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Credentials\FallbackCredentialsFactory.cs:line 92
  at Amazon.Runtime.FallbackCredentialsFactory.GetCredentials(Boolean fallbackToAnonymous) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Credentials\FallbackCredentialsFactory.cs:line 113

**Comment by vellozzi** [comment]
It's possible that there's an error in the credentials file or, of course, maybe there's some other bug.
-Did you write the credentials file programmatically, or with Visual Studio?
-Are you intentionally using assume role credentials?
-If you're creating assume role credentials please send the code that you used to do that.

Try to run this code first thing in your application.  This should give us more information.
```
CredentialProfile profile;
var netSdkCredsFile = new NetSDKCredentialsFile();
if (netSdkCredsFile.TryGetProfile("NAMED_PROFILE_IN_.NET_Credential_Store", out profile))
    AWSCredentialsFactory.GetAWSCredentials(profile, netSdkCredsFile, true)
else
    throw new Exception("Not finding profile");
```
In the meantime I'll improve the logging in the FallbackCredentialsFactory to make these things easier to diagnose in the future.

**Comment by mr-olson** [comment]
It's not a credentials file per se, it's the .NET SDK credential store that I'm trying to use.

Yes, intentionally using an assume role role profile, but it works fine outside of IIS context.

Running in IIS locally, your code throws the exception. Running in IIS Express, it successfully retrieves the profile. The IIS AppPool is set up under my account, and is configured to load the user profile (in case that matters at all). Anonymous auth to the site uses the app pool identity.

The code below is a workaround for VS 2017 AWS toolkit not yet being able to create assumed role profiles directly as previous versions were.

```
            var netSDKFile = new NetSDKCredentialsFile();

            // If we haven't already created an assume role profile, do so:
            if (!netSDKFile.TryGetProfile(assumeRoleProfileName, out assumeRoleProfile)) {
                CredentialProfile basicProfile;
                // Update the profile with the roleARN (limitation of current VS toolkit, in AWS we'd use instance role)
                if (netSDKFile.TryGetProfile(profileName, out basicProfile)) {
                    CredentialProfileOptions opts = new CredentialProfileOptions
                    {
                        RoleArn = roleARN,
                        SourceProfile = profileName
                    };
                    assumeRoleProfile = new CredentialProfile(assumeRoleProfileName, opts);
                    assumeRoleProfile.Region = RegionEndpoint.USWest2;
                    netSDKFile.RegisterProfile(assumeRoleProfile);
                    AWSCredentials creds;
                    AWSCredentialsFactory.TryGetAWSCredentials(basicProfile, netSDKFile, out creds);
                }
            }
```

**Comment by vellozzi** [comment]
What's the exception thrown by the code I sent when you run it in IIS locally?
The FallbackCredentialsFactory may mask the real problem.  So it will help to see the exception, if any, from the snippet I sent.

**Comment by mr-olson** [comment]
Your code does not throw an exception, the TryGetProfile() call just returns false & doesn't populate the profile out param.

The exception I included earlier happens on S3 client instance creation:

`
IAmazonS3 s3Client = new AmazonS3Client();
`

**Comment by vellozzi** [comment]
You wouldn't use the UserCrypto class directly under normal circumstances, but try running
`Amazon.Runtime.Internal.Settings.UserCrypto.Encrypt("foo");`
and see if that throws an exception.

**Comment by mr-olson** [comment]
`
var x = Amazon.Runtime.Internal.Settings.UserCrypto.Encrypt("foo");
`

That succeeds, or at least doesn’t throw an exception and x has a nice long hexadecimal string afterward.

The encrypted text is different when running in debug mode against local IIS than IIS Express, but both strings still decrypt to the original “foo” under either hosting approach.

**Comment by vellozzi** [comment]
Hm.  That's a good thing.  But not what I expected.
Here are a couple things to try:
1. Try to read in a basic profile and create AWSCredentials from it.  That may point to an issue with assume role profiles.
2. Back up your .NET Credentials file, delete it.  In your code write the basic and assume role profiles.  Then read the assume role profile and try to create AWSCredentials from it immediately after.  Try this in local IIS first; make sure the file is both written and read with local IIS, and not mixed with code running in IIS Express.
It looks like you're testing out the basic profile with this:
```
AWSCredentials creds;
AWSCredentialsFactory.TryGetAWSCredentials(basicProfile, netSDKFile, out creds);
```
But try running that for assume role profile too.  Also verify it returns true, and creds is populated.

**Comment by vellozzi** [comment]
Closing due to inactivity.

**Comment by Proladge** [comment]
hi there, @mr-olson could you please reach me out on proladge@gmail.com in case you were able to get it resolved for you

**Comment by Proladge** [comment]
Here is the answer
https://github.com/aws/aws-sdk-net/issues/1139
