### ISSUE TITLE
Trouble connecting to AWS Explorer through Visual Studio 2017

### ISSUE THREAD

**Issue by toddhughes1** [aws/aws-sdk-net#708]
I'm trying to connect to AWS (Amazon Web Services) using Visual Studio 2017. However, in the AWS Explorer in Visual Studio, it says "Failed to connect to AWS".

- I created an account in the AWS IAM Management Console.
- I assigned this account AdministratorAccess and created access keys.
- I installed the AWS SDK for .NET for Visual Studio 2017.
- In the Visual Studio AWS Explorer, I selected and created a New Account Profile.
- The AWS Explorer shows "Failed to connect to AWS". (The Region list is still disabled.)
- It seems like a rather simple process, but it's not working for me.

As a credential test, I set up the AWS CLI (Command Line Interface). Then I ran aws configure using the same Access key ID and Secret access key. I was able to access AWS--e.g. aws iam list-users and aws lambda list-functions. (I have some test lambda functions in my account already, and they showed up.)

Edit:
- Without changing anything, suddenly this started working in Visual Studio. I was able to access my AWS resources and upload lambda function. Then....I came in the next day, and it wasn't accessible again.

What am I missing? Let me know if you need any more info.

**Comment by steveataws** [comment]
This suggests an issue with the credentials. Given that the toolkit can read from two credential store files (it's own private and encrypted file at %userprofile%\AppData\Local\AWSToolkit\RegisteredAccounts.json and the plain-text credential file used by the CLI %userprofile%\.aws\credentials), if the account was registered in both places with the same profile name it's possible they could be conflicting.

Since the toolkit can read from the CLI's credential file, and that set of credentials seem to work ok, delete the toolkit's private credential file (the one in %userprofile%\AppData\Local\AWSToolkit). Make sure to restart the IDE to get everything back in sync.

Let us know if they gets you up and running in the IDE.

**Comment by toddhughes1** [comment]
I deleted the file you suggested and restarted the IDE, but it did not work for me. Like I mentioned before, AWS Explorer in VS will work (connect) for me for a while. Then, I might do something in my environment, such as logout/in or restart my machine, and it doesn't work anymore. Now I'm stuck again.

**Comment by toddhughes1** [comment]
I found a workaround. However, I have no idea why this works. If I open VS (with or without a project open), none of the suggestions work, even though I can connect through the AWS CLI. And as I mentioned before, if I click to edit the profile in VS, the credentials are there, but the regions list is empty.

But then, when I launch Fiddler, suddenly AWS Explorer is able to connect in VS. Weird.

**Comment by normj** [comment]
I don't think there is anything we can do as it seems like a network issue on your side. My guess is there is some sort of cert validation issue going on and by having fiddler on that disables certificate validation. You might get more information checking out the toolkit's log file at C:\Users\<user-id>\AppData\Local\AWSToolkit\logs\visualstudio

**Comment by maxotek** [comment]
My profile was already saved and it worked fine even last night. Since, this morning I am getting the "**Failed to connect to AWS**" error in AWS Explorer.

I looked into the logs at C:\Users<user-id>\AppData\Local\AWSToolkit\logs\visualstudio and found this:-

```
2018-02-07 11:34:05,912 [1] INFO  Amazon.AWSToolkit.S3FileFetcher - Probing for hosted file 'ServiceEndPoints.xml' at url prefix 'https://d3rrggjwfhwld2.cloudfront.net/'
2018-02-07 11:34:06,099 [1] ERROR Amazon.AWSToolkit.S3FileFetcher - Failed to find config file ServiceEndPoints.xml from cloudfront.
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.GetResponse()
   at Amazon.AWSToolkit.S3FileFetcher.OpenFileStream(String filename, CacheMode cacheMode)
2018-02-07 11:34:07,045 [1] ERROR Amazon.AWSToolkit.S3FileFetcher - Error getting ServiceEndPoints.xml.
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.GetResponse()
   at Amazon.AWSToolkit.S3FileFetcher.OpenFileStream(String filename, CacheMode cacheMode)
2018-02-07 11:34:07,045 [1] ERROR Amazon.AWSToolkit.S3FileFetcher - Error getting ServiceEndPoints.xml.
System.ArgumentNullException: Value cannot be null.
Parameter name: stream
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
   at System.IO.StreamReader..ctor(Stream stream)
   at Amazon.AWSToolkit.S3FileFetcher.GetFileContent(String filename, CacheMode cacheMode)
```

Looking in through Fiddler, this is the Raw request:-

GET https://d3rrggjwfhwld2.cloudfront.net/ServiceEndPoints.xml HTTP/1.1
Host: d3rrggjwfhwld2.cloudfront.net

I don't see any authentication related headers being sent. Are they even needed for this call?

I also see a similar request for this URL:-

GET https://aws-vs-toolkit.s3.amazonaws.com/ServiceEndPoints.xml HTTP/1.1
Host: aws-vs-toolkit.s3.amazonaws.com

It ends with the same 403 error. Perhaps this is the fallback URL when cloudfront fails.

Here's the log from yesterday when everything worked just fine:-

```
2018-02-06 12:38:57,569 [5] INFO  Amazon.AWSToolkit.S3FileFetcher - Probing for hosted file 'ServiceEndPoints.xml' at url prefix 'https://d3rrggjwfhwld2.cloudfront.net/'
2018-02-06 12:39:07,253 [1] INFO  Amazon.AWSToolkit.Utility - ...resolved for C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\qusg2mug.1af\SDK\AWSSDK.Core.dll
2018-02-06 12:39:07,257 [1] INFO  Amazon.AWSToolkit.Utility - ...resolved for C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\qusg2mug.1af\SDK\AWSSDK.Core.dll
2018-02-06 12:39:07,342 [1] INFO  Amazon.AWSToolkit.Utility - ...resolved for C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\qusg2mug.1af\SDK\AWSSDK.Core.dll
2018-02-06 12:39:07,346 [1] INFO  Amazon.AWSToolkit.Utility - ...resolved for C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\qusg2mug.1af\SDK\AWSSDK.Core.dll
2018-02-06 12:39:41,594 [1] INFO  Amazon.AWSToolkit.VisualStudio.AWSToolkitPackage - Received __VSSPROPID4.VSSPROPID_ShellInitialized property change, new value True
2018-02-06 12:43:57,835 [87] INFO  Amazon.AWSToolkit.MobileAnalytics.AMAServiceCallHandler - Reponse from AMAClient.PutEvents(request) meta data: Amazon.Runtime.ResponseMetadata, response HttpStatusCode: Amazon.Runtime.ResponseMetadata
2018-02-06 14:21:37,790 [1] INFO  Amazon.AWSToolkit.MobileAnalytics.SimpleMobileAnalytics - Queuing analytics event in local queue with timestamp: 02/06/2018 08:51:37
2018-02-06 14:21:37,790 [1] INFO  Amazon.AWSToolkit.MobileAnalytics.SimpleMobileAnalytics - Main session was stopped. Attemping to force final analytics service call attempt. Note: Permission to collect analytics will be checked.
2018-02-06 14:21:39,916 [125] INFO  Amazon.AWSToolkit.MobileAnalytics.AMAServiceCallHandler - Reponse from AMAClient.PutEvents(request) meta data: Amazon.Runtime.ResponseMetadata, response HttpStatusCode: Amazon.Runtime.ResponseMetadata
2018-02-06 14:21:42,696 [72] INFO  Amazon.AWSToolkit.MobileAnalytics.AMAServiceCallHandler - Reponse from AMAClient.PutEvents(request) meta data: Amazon.Runtime.ResponseMetadata, response HttpStatusCode: Amazon.Runtime.ResponseMetadata
2018-02-06 14:30:46,693 [1] INFO  Amazon.AWSToolkit.MobileAnalytics.SimpleMobileAnalytics - Queuing analytics event in local queue with timestamp: 02/06/2018 09:00:46
2018-02-06 14:30:46,702 [1] INFO  Amazon.AWSToolkit.MobileAnalytics.SimpleMobileAnalytics - Main session was stopped. Attemping to force final analytics service call attempt. Note: Permission to collect analytics will be checked.
2018-02-06 14:30:48,588 [134] INFO  Amazon.AWSToolkit.MobileAnalytics.AMAServiceCallHandler - Reponse from AMAClient.PutEvents(request) meta data: Amazon.Runtime.ResponseMetadata, response HttpStatusCode: Amazon.Runtime.ResponseMetadata
```

I have tried creating new credentials in IAM and connecting from a different system. All end with the same error.

**Comment by veer3383** [comment]
@maxotek  Even i am facing the exact same issue since today morning, it was working fine yesterday.

**Comment by maxotek** [comment]
@veer3383 Perhaps its a bad patch on the server. I don't recall AWS toolkit updating today even though it is set to auto-update. I also tried re-installing the VS Extension on one of the systems.

**Comment by bjj951** [comment]
I'm facing the same 'Failed to connect to AWS' problem after restarting my machine today.
[log.txt](https://github.com/aws/aws-sdk-net/files/1702117/log.txt)

**Comment by normj** [comment]
I'm looking into the issue now

**Comment by bjj951** [comment]
@normj Hi Norm, not sure if you have changed anything as yet, but it is now working for me OK. cheers

**Comment by normj** [comment]
I believe the problem is fixed now. You might need to restart Visual Studio to clear out the error state.

**Comment by maxotek** [comment]
Yup seems to be fine now.

**Comment by normj** [comment]
Thanks for confirming it was fixed. Sorry about that.

**Comment by normj** [comment]
For those that are curious of the root cause of this issue. The toolkit downloads a file from S3 via CloudFront that provides all of the service endpoints and regions the toolkit will support. We have been working on some new automation on this file so we can keep the file up to date faster. When the new automation pushed a new version there was a bug in the automation to not make the file public. This caused the toolkit to get a permission denied while attempting to download the file. Although we had monitoring to make sure the CloudFront Origin was available we did not have monitoring on the individual files in the bucket which is are biggest lessen learned and we will be addressing that quickly.

Again we are sorry for the inconvenience and strive to do better.

**Comment by itsurkan** [comment]
I had the same issue, I was because in .aws contained credentials folder, but I should be credentials file!
