### ISSUE TITLE
Cannot Install AWS Tools for 2017

### ISSUE THREAD

**Issue by stuart-mck** [aws/aws-sdk-net#750]
I'm trying to install the AWS toolkit for VS 2017, but the installer is failing with an error saying it cannot find VS 2017

## Expected Behavior
The installer should recognise my installation of Visual Studio 2017 and install  the software

## Current Behavior
The VSIX installer fails during the installation with the error message
"This extension is not installable on any currently installed products."

Extract from log:

16/09/2017 6:03:00 PM - Searching for applicable products...
16/09/2017 6:03:01 PM - Found installed product - Microsoft Visual Studio Ultimate 2012
16/09/2017 6:03:01 PM - Found installed product - Microsoft Visual Studio Premium 2012 
16/09/2017 6:03:01 PM - Found installed product - Microsoft Visual Studio Professional 2012
16/09/2017 6:03:01 PM - Found installed product - Microsoft Visual Studio 2012 Shell (Integrated)
16/09/2017 6:03:01 PM - Found installed product - Microsoft Visual Studio Express 2012 for Windows Phone
16/09/2017 6:03:01 PM - Found installed product - Microsoft Visual Studio Ultimate 2013
16/09/2017 6:03:01 PM - Found installed product - Microsoft Visual Studio Premium 2013 
16/09/2017 6:03:01 PM - Found installed product - Microsoft Visual Studio Professional 2013
16/09/2017 6:03:01 PM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
16/09/2017 6:03:01 PM - Found installed product - Microsoft Visual Studio Enterprise 2015
16/09/2017 6:03:01 PM - Found installed product - Microsoft Visual Studio Professional 2015
16/09/2017 6:03:01 PM - Found installed product - Microsoft Visual Studio Community 2015
16/09/2017 6:03:01 PM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
16/09/2017 6:03:01 PM - Found installed product - Global Location
16/09/2017 6:03:01 PM - Found installed product - ssms
16/09/2017 6:03:01 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

## Possible Solution
?? presumably an expected record / directory / file etc is missing - what does the installer look for to determine the installed versions?

## Steps to Reproduce (for bugs)
Run the installer (AWSToolkitPackage.vsix)

## Context
Working on AWS project - need the VS tools to assist with development

## Your Environment
I have a few versions of VS installed - VS 2017 version is 15.3.4 enterprise. I did have some issues installing VS 2017  - a couple of failed installations / computer crashes during the install phase - maybe a directory or ? is missing that the installer requires?

## .NET Core Info
.netcore 2.0
PS C:\> dotnet --info
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by steveataws** [comment]
Is your install of VS2017 behaving normally otherwise, after your previous setup failures? Is it possible to run a repair on it anyway to get to a known good install state where the setup runs without any issues? And, if you look under C:\Program Files (x86)\Microsoft Visual Studio\2017 how many edition folders do you see?

Looking at the logs you posted, I would expect to see it find the instance during probing - our vsix is specifically set to install only into VS2017, so if Microsoft's vs_installer.exe doesn't find a relevant 2017 instance then it will bail with the message you see. I'm wondering therefore if your prior install issues have left the instance in an odd state that their installer isn't detecting it is present, or an older version of vs_installer.exe is being picked up, and if a repair might clean things up. 

My system has 2013-2017 Professional editions installed and I see these log entries when I download our latest vsix and run it by double-clicking the vsix file:

9/21/2017 9:41:54 AM - Searching for applicable products...
9/21/2017 9:41:54 AM - Found installed product - Microsoft Visual Studio Professional 2013
9/21/2017 9:41:54 AM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
9/21/2017 9:41:54 AM - Found installed product - Microsoft Visual Studio Professional 2015
9/21/2017 9:41:54 AM - Found installed product - Microsoft Visual Studio Community 2015
9/21/2017 9:41:54 AM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
9/21/2017 9:41:54 AM - Found installed product - Global Location
9/21/2017 9:41:54 AM - Found installed product - Visual Studio Professional 2017

**Comment by normj** [comment]
Closing for lack of activity

**Comment by mcoles-thortech** [comment]
Similar problem here. Visual Studio 2017 Enterprise installed. AWS Tools 2017 fails to install with the message "The installation was unable to install the extension to all the selected products.... This extension is not installable on any currently installed products."

My version of VS is 15.6 Enterprise.
