### ISSUE TITLE
Operation is not supported on this platform. on lambda

### ISSUE THREAD

**Issue by odyth** [aws/aws-sdk-net#781]
I get "Operation is not supported on this platform" when trying to get an object from S3 using lambda.  I am using the latest versions of AWSSDK for lambda. Below are all the packages that are in my lambda project.  I am using AWS Toolkit version 1.12.2.0 to deploy my code to lambda and using Visual Studio 2017 Enterprise version 15.3.5.

<ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="1.0.0" />
    <PackageReference Include="Amazon.Lambda.DynamoDBEvents" Version="1.0.1" />
    <PackageReference Include="Amazon.Lambda.KinesisEvents" Version="1.0.1" />
    <PackageReference Include="Amazon.Lambda.S3Events" Version="1.0.1" />
    <PackageReference Include="Amazon.Lambda.Serialization.Json" Version="1.1.0" />
    <PackageReference Include="AWSSDK.KeyManagementService" Version="3.3.3.3" />
    <PackageReference Include="AWSSDK.S3" Version="3.3.11.3" />
    <PackageReference Include="AWSSDK.SimpleNotificationService" Version="3.3.0.23" />
    <PackageReference Include="Elasticsearch.Net.Aws" Version="2.3.7" />
    <PackageReference Include="NEST" Version="5.5.0" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.1" />  
  </ItemGroup>

I get the following error when trying to get an object from S3.  See stack trace below.  My code is really straight forward and my code never makes it to the hello world log statement.

```
public async Task HandleAsync(S3Event evnt, ILambdaContext context)
{
    var bucketName = evnt.Records[0].S3.Bucket.Name;
    var key = evnt.Records[0].S3.Object.Key;
    var s3Client = new AmazonS3Client();
    context.Logger.LogLine("I made it here");

    using (var response = await s3Client.GetObjectAsync(bucketName, key)) //throws exception here
    {
        context.Logger.LogLine("hello world"); //never makes it here
    }
}
```

One or more errors occurred. (Operation is not supported on this platform.): AggregateException
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at lambda_method(Closure , Stream , Stream , ContextInfo )

at System.Runtime.InteropServices.OSPlatform.get_Windows()
at Amazon.Runtime.ClientConfig.get_HttpClientCacheSize()
at Amazon.Runtime.HttpRequestMessageFactory.CreateConfigUniqueString(IClientConfig clientConfig)
at Amazon.Runtime.HttpRequestMessageFactory.CreateHttpRequest(Uri requestUri)
at Amazon.Runtime.Internal.HttpHandler`1.CreateWebRequest(IRequestContext requestContext)
at Amazon.Runtime.Internal.HttpHandler`1.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Amazon.Runtime.Internal.RedirectHandler.<InvokeAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Amazon.Runtime.Internal.Unmarshaller.<InvokeAsync>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Amazon.S3.Internal.AmazonS3ResponseHandler.<InvokeAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Amazon.S3.Internal.AmazonS3ExceptionHandler.<InvokeAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at MyNameSpace.Handler.<HandleAsync>d__7.MoveNext()

**Comment by normj** [comment]
I don't see the list of packages? Can you share your csproj file? The error usually happens when you include dependency that depend on .NET Core 1.1.

**Comment by odyth** [comment]
Still working through this, but seems my issue is I have a class library that references some packages that need NETStandard 1.6.1.  Visual Studio used to downgrade the package and give me a little warning "warning NU1605: Detected package downgrade: NETStandard.Library from 1.6.1 to 1.6.0. Reference the package directly from the project to select a different version."  They now changed NU1605 to be an error, which you can undo.  I did that thinking I would get the old behavior, but something else is happening now as it causes lambda to choke with my above error.  The package that seems to do it is MySql.Data 8.0.8-dmr.  I'll just have to find a replacement for that while I wait for lambda to support newer versions of .net core.

**Comment by mariowood** [comment]
I came across this issue yesterday and the fix for me was to downgrade AWSSDK.S3 from 3.3.14 to 3.3.10, hopefully this is helpful to someone.
