### ISSUE TITLE
Unable to install Toolkit - due to inability to access Certificate  

### ISSUE THREAD

**Issue by ahrensd** [aws/aws-sdk-net#790]
Can't install the toolkit. 
I'm behind a corporate firewall and have to use a separate Admin credentials which has no internet access, is there a offline installer? (Windows 10 system)

Have attempted the installed on another system (Windows 7) with Admin rights and access to the internet. It worked fine. The problem appears to be with authenticating the certificate. Anyway around this?

Both have updated Visual Studio 2017 Enterprise.

Tail of the log file:-
`8/11/2017 9:33:22 AM - Certificate is invalid: AWSToolkitPackage.vsix
8/11/2017 9:34:02 AM - Skipping Install of '12ed248b-6d4a-47eb-be9e-8eabea0ff119,version=1.12.2.1' since downloading it failed.
8/11/2017 9:34:02 AM - Skipping cache of package '12ed248b-6d4a-47eb-be9e-8eabea0ff119,version=1.12.2.1' since the package or a parent package had a vital failure.
8/11/2017 9:34:02 AM - Skipping cache of package 'Component.12ed248b-6d4a-47eb-be9e-8eabea0ff119,version=1.12.2.1' since the package or a parent package had a vital failure.
8/11/2017 9:34:45 AM - Install Error : Microsoft.VisualStudio.Setup.PackageFailureException: Package '12ed248b-6d4a-47eb-be9e-8eabea0ff119' failed to download
   at Microsoft.VisualStudio.Setup.InstallOperation.Run(CancellationToken token)
   at Microsoft.VisualStudio.Setup.Engine.RunOperation(InstallOperation installOperation, CancellationToken token, ExecuteAction action, ITelemetryOperation telemetryOperation)
   at Microsoft.VisualStudio.Setup.Engine.RunCoreOperation(InstallOperation coreOperation, ExecuteAction action, ITelemetryOperation telemetryOperation, CancellationToken token)
   at Microsoft.VisualStudio.Setup.Engine.Install(Product product, String destination, CancellationToken token)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)`

Have determined that the problem is with the certificate, so include the snippet of log near the beginning of the log file:-
`8/11/2017 9:31:40 AM - Signature Details...
8/11/2017 9:31:40 AM - 	Extension is signed with an invalid certificate
8/11/2017 9:31:40 AM - 		(PartialChain)      : A certificate chain could not be built to a trusted root authority.
8/11/2017 9:31:40 AM - 		(RevocationStatusUnknown): The revocation function was unable to check revocation for the certificate.
8/11/2017 9:31:40 AM - 		(OfflineRevocation) : The revocation function was unable to check revocation because the revocation server was offline.` 

Would be good if you had the option to override the certificate check?

**Comment by normj** [comment]
The certificate check is out of our control and just part of the Visual Studio extension install system. You would need to open an issue with the Visual Studio team for a work around.
