### ISSUE TITLE
RuntimeInformation.IsOSPlatform(OSPlatform.Windows) throws System.PlatformNotSupportedException on AWS Lambda

### ISSUE THREAD

**Issue by kekedk** [aws/aws-sdk-net#791]
@normj  Added breaking check https://github.com/aws/aws-sdk-net/commit/a4d2348b25865195e43e9448ec5655bc473d5dcc

```
Unknown error responding to request: PlatformNotSupportedException:
System.PlatformNotSupportedException: Operation is not supported on this platform.
at System.Runtime.InteropServices.OSPlatform.get_Windows()
at Amazon.Runtime.ClientConfig.get_HttpClientCacheSize()
at Amazon.Runtime.HttpRequestMessageFactory.CreateConfigUniqueString(IClientConfig clientConfig)
at Amazon.Runtime.HttpRequestMessageFactory.CreateHttpRequest(Uri requestUri)
at Amazon.Runtime.Internal.HttpHandler`1.CreateWebRequest(IRequestContext requestContext)
at Amazon.Runtime.Internal.HttpHandler`1.<InvokeAsync>d__9`1.MoveNext()
```

[Code Line Link](https://github.com/aws/aws-sdk-net/blob/5c86b5115c3675e7c6eca57198e3a5d27aeebf11/sdk/src/Core/Amazon.Runtime/ClientConfig.cs#L524)

**Comment by normj** [comment]
This error usually happen when one of your dependencies requires .NET Core 1.1. Would you be able to add your project file to the issue?

**Comment by kekedk** [comment]
<PackageReference Include="Amazon.Lambda.AspNetCoreServer" Version="0.10.2-preview1" />
    <PackageReference Include="Amazon.Lambda.Logging.AspNetCore" Version="1.1.0" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.3.3" />
    <PackageReference Include="AWSSDK.SQS" Version="3.3.2.7" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.Routing" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="1.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="1.1.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="1.1.2" />
    <PackageReference Include="Serilog" Version="2.5.0" />
    <PackageReference Include="Serilog.Enrichers.Memory" Version="1.0.4" />
    <PackageReference Include="Serilog.Enrichers.Process" Version="2.0.1" />
    <PackageReference Include="Serilog.Enrichers.Thread" Version="3.0.0" />
    <PackageReference Include="Serilog.Exceptions" Version="2.5.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="2.0.2" />
    <PackageReference Include="Serilog.Formatting.Compact" Version="1.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="1.0.0" />

**Comment by normj** [comment]
Your project file is pulling in .NET Core 1.1 dependencies like Microsoft.AspNetCore.Mvc version 1.1.3. If you use our tooling to deploy it should warn you when you pull in .NET Core 1.1 references. If you look at the *.deps.json file that is in your publish folder look for the NuGet packages that are causing NETStandard.Library 1.6.1 to be pulled in. You need it to be using version NETStandard.Library 1.6.0.

**Comment by sstevenkang** [comment]
Closing due to inactivity.  Please ping this thread or open a new one if you still have unresolved issues.
