### ISSUE TITLE
Error updating Cloudfront Distribution in Powershell

### ISSUE THREAD

**Issue by croomshine** [aws/aws-sdk-net#825]
## Expected Behavior

After supplying all the parameters for a Cloudfront distribution, the update should succeed.

## Current Behavior

Receiving the following error.  I have included `-Header_Item @() -Header_Quantity 0` as parameters in the command.
```
Amazon Error: 12 : An exception of type HttpErrorResponseException was handled in ErrorHandler., Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpRequest.GetResponse()
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
Amazon Error: 13 : Received error response: [<?xml version="1.0"?>
<ErrorResponse xmlns="http://cloudfront.amazonaws.com/doc/2017-03-25/"><Error><Type>Sender</Type><Code>InvalidArgument</Code><Message>The parameter Header settings is required.</Message></Error><RequestId>341907af-f0bd-11e7-b0e0-4b2adee934b3</RequestId></ErrorResponse>], Amazon.CloudFront.Model.InvalidArgumentException: The parameter Header settings is required. ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpRequest.GetResponse()
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
   --- End of inner exception stack trace ---
Amazon Error: 14 : InvalidArgumentException making request UpdateDistributionRequest to https://cloudfront.amazonaws.com/. Attempt 1., Amazon.CloudFront.Model.InvalidArgumentException: The parameter Header settings is required. ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpRequest.GetResponse()
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext)
```

## Possible Solution

Unsure.  The error indicates I am missing a parameter, but looking through the documentation I am unsure what parameter is required.

## Steps to Reproduce (for bugs)

Run `Update-CFDistribution`

## Context

I am unable to update current CF distributions through the API.

## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

```
AWS Tools for Windows PowerShell
Version 3.3.210.0
Copyright 2012-2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Amazon Web Services SDK for .NET
Core Runtime Version 3.3.21.4
Copyright 2009-2015 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Release notes: https://aws.amazon.com/releasenotes/PowerShell

This software includes third party software subject to the following copyrights:
- Logging from log4net, Apache License
[http://logging.apache.org/log4net/license.html]
```

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by croomshine** [comment]
I've been able to resolve this issue.  The CacheBehavior object I was creating did not have all the default properties set.
