### ISSUE TITLE
ReceiveFailure intermittent errors since v2.0 with Mono

### ISSUE THREAD

**Issue by DanielLaberge** [aws/aws-sdk-net#83]
Hello, we're using Mono v3.4.0 (master/6d0ffb3) on Ubuntu 12.04.4 (x64) running on EC2.

**Since updating to v2.0.11 from 1.5.48 we've been getting unexplainable intermittent errors when using the following APIs: S3.PutObject, S3.GetObject and SQS.ReceiveMessage.** 

We are not able to reproduce any of the following problems when running the same app in Windows. 

We're forced to rollback to 1.5.48 for now, which works fine in mono.

```c#
var request = new PutObjectRequest
{
    BucketName = bucketName,
    FilePath = zipFilePath,
    Key = s3Key,
    ServerSideEncryptionMethod = ServerSideEncryptionMethod.AES256,
    StorageClass = S3StorageClass.ReducedRedundancy
};

S3Client.PutObject(request);
```
The full exception:
```
Error System.Net.WebException: Error getting response stream (ReadDone2): ReceiveFailure ---> System.Exception:    at System.Net.WebConnection.HandleError(WebExceptionStatus st, System.Exception e, System.String where)
   at System.Net.WebConnection.ReadDone(IAsyncResult result)
  at System.Net.WebConnection.HandleError (WebExceptionStatus st, System.Exception e, System.String where) [0x0003a] in /opt/mono3/mono/mcs/class/System/System.Net/WebConnection.cs:488
  --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) [0x00065] in /opt/mono3/mono/mcs/class/System/System.Net/HttpWebRequest.cs:986
  at System.Threading.Tasks.TaskFactory`1[TResult].InnerInvoke (System.Threading.Tasks.TaskCompletionSource`1 tcs, System.Func`2 endMethod, IAsyncResult l) [0x00000] in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /opt/mono3/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:62
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <filename unknown>:0
  at System.Net.Http.HttpClientHandler+<SendAsync>c__async0.MoveNext () [0x00245] in /opt/mono3/mono/mcs/class/System.Net.Http/System.Net.Http/HttpClientHandler.cs:319
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /opt/mono3/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:62
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <filename unknown>:0
  at System.Net.Http.HttpClient+<SendAsyncWorker>c__async0.MoveNext () [0x000a9] in /opt/mono3/mono/mcs/class/System.Net.Http/System.Net.Http/HttpClient.cs:273
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /opt/mono3/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:62
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <filename unknown>:0
  at Amazon.Runtime.AmazonWebServiceClient+<InvokeConfiguredRequest>d__3`1[Amazon.S3.Model.PutObjectResponse].MoveNext () [0x00000] in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /opt/mono3/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:62
  at Amazon.S3.AmazonS3Client.PutObject (Amazon.S3.Model.PutObjectRequest request) [0x00000] in <filename unknown>:0
```

We're also seeing the following exception when downloading files with S3Client.GetObject() and when calling SQSClient.ReceiveMessage() :

```
System.IO.IOException: IO exception during Write. ---> System.NullReferenceException: Object reference not set to an instance of an object
  at Mono.Security.Protocol.Tls.SslStreamBase.InternalBeginWrite (Mono.Security.Protocol.Tls.InternalAsyncResult asyncResult) [0x00031] in /opt/mono3/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/SslStreamBase.cs:780
  --- End of inner exception stack trace ---
  at Mono.Security.Protocol.Tls.SslStreamBase.InternalBeginWrite (Mono.Security.Protocol.Tls.InternalAsyncResult asyncResult) [0x00089] in /opt/mono3/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/SslStreamBase.cs:793
  at Mono.Security.Protocol.Tls.SslStreamBase.BeginWrite (System.Byte[] buffer, Int32 offset, Int32 count, System.AsyncCallback callback, System.Object state) [0x000a3] in /opt/mono3/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/SslStreamBase.cs:862
  at System.Net.WebConnection.BeginWrite (System.Net.HttpWebRequest request, System.Byte[] buffer, Int32 offset, Int32 size, System.AsyncCallback cb, System.Object state) [0x0005f] in /opt/mono3/mono/mcs/class/System/System.Net/WebConnection.cs:1048         
```
**Even worse: This exception cannot be caught by our try...catch blocks, so our program exits due to the unhandled exception** 

This tells me this might due to some async code? We're not using any in our app but the AWS SDK does...

Please note that more APIs might be affected, we can't tell because we're only using these three and they're all failing.

Hopefully this post will help fellow programmers find a solution to this hair-pulling problem: Rollback to 1.5.48.

**Comment by jaredbroad** [comment]
Have you tested later versions @DanielLaberge? I've got memory leaks and wondering if its a AWS-Mono bug. I also had the same exceptions but later versions seem to work ok with try-catches.

**Comment by DanielLaberge** [comment]
I haven't tried it yet, even though I was tempted to recently. From what
you're saying, there are still problems with it so I might stick to 1.x
yet...

**Comment by jaredbroad** [comment]
Are you still on x.48 or have you updated to the latest x.61 version?

Thanks,
JB

On Sat, Feb 28, 2015 at 3:19 PM, DanielLaberge <notifications@github.com>
wrote:

> I haven't tried it yet, even though I was tempted to recently. From what
> you're saying, there are still problems with it so I might stick to 1.x
> yet...
> On Feb 28, 2015 11:16 AM, "Jared" <notifications@github.com> wrote:
>
> > Have you tested later versions @DanielLaberge
> > <https://github.com/DanielLaberge>? I've got memory leaks and wondering
> > if its a AWS-Mono bug. I also had the same exceptions but later versions
> > seem to work ok with try-catches.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/aws/aws-sdk-net/issues/83#issuecomment-76532489>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aws/aws-sdk-net/issues/83#issuecomment-76538234>.
>



-- 
Jared Broad

www.quantconnect.com
Phone-USA: +1 917 310 1082
*Democratizing Finance, Empowering Individuals*
Facebook <http://www.facebook.com/QuantConnect> | Twitter
<https://twitter.com/#!/QuantConnect> | LinkedIn
<http://www.linkedin.com/company/quantconnect> | Skype: jaredbroad

**Comment by gokarnm** [comment]
Closing due to lack of activity.
