### ISSUE TITLE
Intermitent Bad Request for StartWithSrpAuthAsync

### ISSUE THREAD

**Issue by pramodpaudel377** [aws/aws-sdk-net#834]
While logging sometimes there is an error - "Invalid Input Given" due to Bad Request while using StartWithSrpAuthAsync. this is not happening every time and is an intermittent issue. 
 
## Expected Behavior
While creating a BigInteger it should check and make sure it is a valid number and should able to authenticate SRP auth request. 

## Current Behavior
Right now while generating BigInteger with random value here - 
```
 internal static Tuple<BigInteger, BigInteger> CreateAaTuple()
        {
            BigInteger a, A;
            do
            {
                a = new BigInteger(16, new Random());
                A = g.ModPow(a, N);
            } while (A.Mod(N).Equals(BigInteger.Zero));

            return Tuple.Create<BigInteger, BigInteger>(A, a);
        }
```
sometimes its generating valid value which is not valid for AWS Cognito SRP auth. and should be identified early

## Steps to Reproduce (for bugs)
using this Auth-request I am able to reproduce the issue - 

            InitiateAuthRequest initiateAuthRequest = new InitiateAuthRequest()
            {
                AuthFlow = AuthFlowType.USER_SRP_AUTH,
                ClientId = <AWS-CLIENT-ID>,
                AuthParameters = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    { CognitoConstants.ChlgParamUsername, username },
                    { CognitoConstants.ChlgParamSrpA, "b8feb74c204ff5" }
                    //
                }
            };

            InitiateAuthResponse initiateResponse = await 
           provider.InitiateAuthAsync(initiateAuthRequest).ConfigureAwait(false);

## Context
I am trying to authenticate the user using StartWithSrpAuthAsync it works fine 95 % but fails sometimes with Bad Request error and ended up showing Invalid Input Given error. 

## Your Environment

* AWSSDK.Core version used: 3.3.18.2
* Operating System and version: Win 10 64 bit
* Visual Studio version: VS 2017

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by gokarnm** [comment]
@pramodpaudel377, thanks for reporting this, we'll look into it.

**Comment by sstevenkang** [comment]
Hi, I am a little confused by your report.  Could you distinguish which portion of the report is your theory/diagnosis and which is the observed behavior?  Why do you think `CreateAaTuple()` is generating an invalid value?  

To help you diagnose this, could you capture the request IDs?  Also, if you could capture the HTTP request and response via Fiddler or some other traffic monitoring tool, that would be helpful.

**Comment by pramodpaudel377** [comment]
this is a random issue, and can't be reproduced as desired by the system. So fiddler log is not possible, but I'll give it a try if I can manage to capture some. but I am getting "Invalid Input Given" sometimes. 

So I tried passing a value in ChlgParamSrpA (ie - b8feb74c204ff5 ) which is not following this pattern - **^[0-9a-fA-F]+$** and CreateAaTuple is the only function whose output is used to set ChlgParamSrpA value. 

So I am sure CreateAaTuple, sometimes not generating the desired output. Since this works most of the time with same Inputs from Users.

**Comment by sstevenkang** [comment]
I get that this is intermittent. The string `b8feb74c204ff5` follows the pattern `^[0-9a-fA-F]+$`--did you mean to say that the service returns invalid input despite following the regex pattern? 

In your application's `catch` block, could you log the [requestid](https://github.com/aws/aws-sdk-net/blob/ce0046225e12b70369c37c890bcdc2b70aa68e31/sdk/src/Core/Amazon.Runtime/Internal/ErrorResponse.cs#L59) and share that with us?

**Comment by pramodpaudel377** [comment]
I am sorry, Yes I meant it follows the pattern but will throw Invalid Input even when it follows the pattern. 

Here is the stack trace I find in elmah - 

`Amazon.CognitoIdentityProvider.Model.InvalidParameterException: Invalid input given ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.HttpRequest.<GetResponseAsync>d__16.MoveNext() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_bcl\HttpWebRequestFactory.cs:line 230
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpRequest.<GetResponseAsync>d__16.MoveNext() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_bcl\HttpWebRequestFactory.cs:line 247
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.HttpHandler`1.<InvokeAsync>d__9`1.MoveNext() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:line 175
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.Unmarshaller.<InvokeAsync>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5`1.MoveNext()
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\HttpErrorResponseExceptionHandler.cs:line 114
   at Amazon.Runtime.Internal.ExceptionHandler`1.Handle(IExecutionContext executionContext, Exception exception) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ExceptionHandler.cs:line 38
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 204
   at Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5`1.MoveNext() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7`1.MoveNext() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CredentialsRetriever.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\RetryHandler\RetryHandler.cs:line 137
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5`1.MoveNext() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\ErrorCallbackHandler.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Extensions.CognitoAuthentication.CognitoUser.<StartWithSrpAuthAsync>d__77.MoveNext() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\extensions\src\AWSSDK.Extensions.CognitoAuthentication\CognitoUserAuthentication.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at iota.Services.UserService.<LoginAsync>d__6.MoveNext() in C:\Users\java\Documents\workspace\dev\iotfrontend\iota.Services\UserService.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at iota.Business.UserBusiness.<LoginAsync>d__4.MoveNext() in C:\Users\java\Documents\workspace\dev\iotfrontend\iota.Business\UserBusiness.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at iota.Controllers.UserController.<Login>d__5.MoveNext() in C:\Users\java\Documents\workspace\dev\iotfrontend\iota\Controllers\UserController.cs:line 60`

**Comment by pramodpaudel377** [comment]
I'll add the logging for requestID and will share with you once I'll get the issue again.

**Comment by pramodpaudel377** [comment]
Here is the request ID - f1526660-fd36-11e7-a701-9951c60f2a98

**Comment by sstevenkang** [comment]
I think that's all we need for now.  I'll get in touch with the service team to chase down what's going on here.

**Comment by behrooziAWS** [comment]
Could you provide a timestamp and region?  I agree it is likely an issue with the client as the javascript/ios/android implementations exhibited this behavior when there were client code bugs and now they work 100%.

**Comment by sstevenkang** [comment]
@behrooziAWS do you by any chance remember what those bugs were?  I can check our code to see the same bugs are present.

**Comment by pramodpaudel377** [comment]
Here is the timestamp of the request Id I shared earlier - Date: Fri, 19 Jan 2018 16:36:47 GMT, Region is us-east-1

**Comment by pramodpaudel377** [comment]
hey Guys, any luck here. I am wondering if you need any more info on my side? Can you confirm if this is an issue with Client?

**Comment by sstevenkang** [comment]
We are looking into it.  Last correspondence with the service team indicate that it might be a client side issue after all.  We are reviewing how SRP_A is generated.

**Comment by normj** [comment]
Is anybody seeing this issue with the latest release of the library. Note the library was also renamed to [Amazon.Extensions.CognitoAuthentication](https://aws.amazon.com/blogs/developer/now-generally-available-amazon-cognitoauthentication-extension-library/)

**Comment by normj** [comment]
Closing for lack of activity
