### ISSUE TITLE
Amazon.Runtime.AmazonServiceException. Why?

### ISSUE THREAD

**Issue by Awr0ra** [aws/aws-sdk-net#847]
This issue occurred in the code:
```

           const string sqsAppKey = "AAAAAAAAAAAAAAAA";                       
            const string sqsSecretKey = "SSSSSSSSSSSSSSSSSSSSSSSSS";

            AWSCredentials credentials = new BasicAWSCredentials(sqsAppKey, sqsSecretKey);

            
            AmazonTranscribeServiceClient client = new AmazonTranscribeServiceClient(credentials, RegionEndpoint.USEast1);

            StartTranscriptionJobRequest req = new StartTranscriptionJobRequest();

            Media media = new Media();
            media.MediaFileUri = @"https://s3.us-east-1.amazonaws.com/temp-awr-store6/m140_16_33.mp3";

            req.TranscriptionJobName = "job2601";
            req.MediaSampleRateHertz = 44100;
            req.LanguageCode = "en-US";
            req.Media = media;
            req.MediaFormat = "mp3";

            StartTranscriptionJobResponse resp = client.StartTranscriptionJob(req); // <<<----- error here
```

The issues:

Amazon.Runtime.AmazonServiceException
  HResult=0x80131500
  Message=A WebException with status SendFailure was thrown.
  Source=AWSSDK.Core
  StackTrace:
   at Amazon.Runtime.Internal.WebExceptionHandler.HandleException(IExecutionContext executionContext, WebException exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.AmazonServiceClient.Invoke[TRequest,TResponse](TRequest request, IMarshaller`2 marshaller, ResponseUnmarshaller unmarshaller)
   at Amazon.TranscribeService.AmazonTranscribeServiceClient.StartTranscriptionJob(StartTranscriptionJobRequest request) in D:\aws-sdk-net-samples-master\awsSdkNet_2\sdk\src\Services\TranscribeService\Generated\_bcl45\AmazonTranscribeServiceClient.cs:line 367
   at AwsConsoleTranscribe.Program.Main(String[] args) in D:\aws-sdk-net-samples-master\awrAWStest\Transcribe\AwsConsoleTranscribe\AwsConsoleTranscribe\Program.cs:line 86

Inner Exception 1:
**WebException: The underlying connection was closed: An unexpected error occurred on a send.**

Inner Exception 2:
**IOException: Authentication failed because the remote party has closed the transport stream.**

**Comment by sstevenkang** [comment]
Which platform/framework are you trying to build for?  Could you provide more information?

**Comment by Awr0ra** [comment]
.Net Framework 4.5
AWSSDK.Core (version 3.3.0.0)
AWSSDK.TranscribeService (Assembly version 3.3.0.0)

**Comment by Awr0ra** [comment]
BUT in the same time Java-code is working well

```

        String sAccessKey = "AAAAAAAAAAAAAAAAAA";
        String sSecretKey = "SSSSSSSSSSSSSSSSSS";
        String sRegionName = "us-east-1";
        String sTranscriptionJobName = "j001";
        String sLanguageCode = "en-US";
        String sMediaFormat = "mp3";
        String sMediaUri = "https://s3.us-east-1.amazonaws.com/temp-awr-store6/m140_16_33.mp3";
        String endpoint = "https://transcribe.us-east-1.amazonaws.com/";
		
        AWSCredentials awsCredentials;
        awsCredentials = new BasicAWSCredentials(sAccessKey, sSecretKey);

        try{
            AmazonTranscribeClient client = (AmazonTranscribeClient) AmazonTranscribeClientBuilder.standard().withCredentials(
                    new AWSStaticCredentialsProvider(awsCredentials)).withEndpointConfiguration(
                    new AwsClientBuilder.EndpointConfiguration(endpoint,sRegionName)).build();	

            StartTranscriptionJobRequest reqStart = new StartTranscriptionJobRequest();

            reqStart.setLanguageCode(sLanguageCode);
            reqStart.setTranscriptionJobName(sTranscriptionJobName);
            reqStart.setMediaFormat(sMediaFormat);
            Media fileMp3 = new Media();
            fileMp3.setMediaFileUri(sMediaUri);
            reqStart.setMedia(fileMp3);
            reqStart.setMediaSampleRateHertz(44100);

            
            StartTranscriptionJobResult respStart = new StartTranscriptionJobResult();
            respStart = client.startTranscriptionJob(reqStart);					
        }
        catch (Exception ex) {
            System.out.println(" ---- Trans client error:  " + ex.getMessage() );
        }	
```
The difference is followed:
 **String endpoint = "https://transcribe.us-east-1.amazonaws.com/";**

**Comment by Awr0ra** [comment]
This problem is still relevant

**Comment by gokarnm** [comment]
Hi @Awr0ra , Amazon Transcribe is currently in preview. I'm assuming you've signed up for the preview, that's how it's working with Java SDK. Could you confirm that you signed up for the preview?

**Comment by ravindu** [comment]
Hi, I'm currently working on Amazon transcribe service using java. I'm also couldn't get StartTranscriptionJobResult. This is the error that i received.

**com.amazonaws.SdkClientException: Unable to execute HTTP request: Received fatal alert: handshake_failure**

Here  is the java code.

public class AmazonSTTService {

    public static void callTranscribeService(){
        
        AWSCredentials awsCredentials= new BasicAWSCredentials("XXXXXXXXXXXX", "YYYYYYYYYYYYYY");
        
        ClientConfiguration clientConfig = new ClientConfiguration();
        clientConfig.setConnectionTimeout(60000);
        clientConfig.setMaxConnections(100);
        clientConfig.setSocketTimeout(60000);
        
        AmazonTranscribe transcribeClient = AmazonTranscribeClientBuilder.standard().withCredentials(
                new AWSStaticCredentialsProvider(awsCredentials)).withEndpointConfiguration(
                new AwsClientBuilder.EndpointConfiguration("https://transcribe.us-east-1.amazonaws.com/","us-east-1")).withClientConfiguration(clientConfig).build();  
        StartTranscriptionJobRequest request=buildRequest();
        StartTranscriptionJobResult response= transcribeClient.startTranscriptionJob(request);
        System.out.println(response.getTranscriptionJob().getTranscriptionJobStatus());
    }

    private static StartTranscriptionJobRequest buildRequest() {
        StartTranscriptionJobRequest request=new StartTranscriptionJobRequest();
        request.setMediaSampleRateHertz(16000);
        request.setMediaFormat("wav");
        request.setLanguageCode("en-US");
        request.setTranscriptionJobName("JOB-001");
        Media media=new Media();
        media.setMediaFileUri("https://vui-stt-audio-stt-audio4103322782059301951.wav");
        request.setMedia(media);
        
        return request;
    }
}

Can you share a resource that i can refer how to call Transcribe service using aws java sdk?

**Comment by Awr0ra** [comment]
My opinion is
your problem is in media-file URL
`media.setMediaFileUri("https://vui-stt-audio-stt-audio4103322782059301951.wav");`
media file should be upload to S3 bucket before using in AmazonTranscribe
Plz see my Java code above
`String sMediaUri = "https://s3.us-east-1.amazonaws.com/temp-awr-store6/m140_16_33.mp3";`

**Comment by ravindu** [comment]
@Awr0ra  Thanks, yes that should be changed. Here is the correct url 
https://vui-stt-audio.s3.amazonaws.com/stt-audio7450403211019441053.wav

But issue remains same. I have signed up to the preview also. But still didn't get a response from Amazon. Some times that will the issue. Also this Amazon account which i'm using now don't have full permission as mentioned in https://docs.aws.amazon.com/transcribe/latest/dg/access-control-managing-permissions.html . 

Is that will be an issue?

**Comment by Awr0ra** [comment]
This Java-code has been created the Transcription job
plz try
```
static void StartTranscribeJob()
    {
        String sAccessKey = "AAAAAAAAAAAAAAAAAA";
        String sSecretKey = "XXXXXXXXXXXXXXX";
        String sRegionName = "us-east-1";
        String sTranscriptionJobName = "j0703";
        String sLanguageCode = "en-US";
        String sMediaFormat = "wav";
        String sMediaUri = "https://vui-stt-audio.s3.amazonaws.com/stt-audio7450403211019441053.wav";
        String sSessionToken ="";
        String endpoint = "https://transcribe.us-east-1.amazonaws.com/";

        AWSCredentials awsCredentials;
        awsCredentials = new BasicAWSCredentials(sAccessKey, sSecretKey);

        try{
            AmazonTranscribeClient client = (AmazonTranscribeClient) AmazonTranscribeClientBuilder.standard().withCredentials(
                    new AWSStaticCredentialsProvider(awsCredentials)).withEndpointConfiguration(
                    new AwsClientBuilder.EndpointConfiguration(endpoint,sRegionName)).build();

            System.out.println(" ---- StartTranscriptionJob start... " );

            StartTranscriptionJobRequest reqStart = new StartTranscriptionJobRequest();

            reqStart.setLanguageCode(sLanguageCode);
            reqStart.setTranscriptionJobName(sTranscriptionJobName);
            reqStart.setMediaFormat(sMediaFormat);
            Media fileMp3 = new Media();
            fileMp3.setMediaFileUri(sMediaUri);
            reqStart.setMedia(fileMp3);
            reqStart.setMediaSampleRateHertz(44100);

            System.out.println(" ---- req... " );

            StartTranscriptionJobResult respStart = new StartTranscriptionJobResult();
            respStart = client.startTranscriptionJob(reqStart);

            System.out.println("Get response:   " + respStart.toString());

            System.out.println(" ---- StartTranscriptionJob finish... " );

        }
        catch (Exception ex) {
            System.out.println(" ---- Trans client error:  " + ex.getMessage() );
        }
    }
```

**Comment by sstevenkang** [comment]
@Awr0ra  could you capture the full HTTP request and Response and share that with us?  Please remove any sensitive information like accesskey & secret key from the dump.

**Comment by sstevenkang** [comment]
@ravindu please reach out to the folks at https://github.com/aws/aws-sdk-java for java specific question.

**Comment by dilshantfl** [comment]
When calling the StartTranscribeJob, I am getting this error. However I am yet ot be invited into the transcribe service preview

`com.amazonaws.SdkClientException: Unable to execute HTTP request: Received fatal alert: handshake_failure
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1114)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1064)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
`

> 

Dear Amazon Transcribe Preview   Applicant,       You are receiving this email notification as we have received your   application for preview access. We will reach out to you with details and   next steps if you have been accepted.       Thank you for your interest,       Amazon Web Services
--

My code

```
public AmazonS3 getAmazonS3Client() {
        BasicAWSCredentials awsCreds = this.getAwsCredentials();

        AmazonS3 s3 = AmazonS3ClientBuilder.standard().withCredentials(new AWSStaticCredentialsProvider(awsCreds))
                .withRegion(Regions.valueOf(awsRegion)).build();
        return s3;
    }

AmazonS3 s3 = awsSpeechCredentialsProvider.getAmazonS3Client();
        String fileName = "amazon-transcribe-" + UUID.randomUUID().toString() + ".wav";
        if (!s3.doesBucketExist(awsS3Bucket)) {
            s3.createBucket(awsS3Bucket);
        }
        s3.putObject(awsS3Bucket, fileName, file);
        return new AbstractMap.SimpleEntry<String, String>(fileName, s3.getUrl(awsS3Bucket, fileName).toExternalForm());

public AmazonTranscribe getAmazonTranscribeClient() {
        BasicAWSCredentials awsCreds = this.getAwsCredentials();

        AmazonTranscribe transcribe = AmazonTranscribeClientBuilder.standard()
                .withCredentials(new AWSStaticCredentialsProvider(awsCreds)).withRegion(Regions.valueOf(awsRegion))
                .build();
        return transcribe;
    }

AmazonTranscribe amazonTranscribe = awsSpeechCredentialsProvider.getAmazonTranscribeClient();

        StartTranscriptionJobRequest startTranscriptionJobRequest = new StartTranscriptionJobRequest();
        startTranscriptionJobRequest.setLanguageCode(language);
        Media media = new Media();
        media.setMediaFileUri(fileUri);
        startTranscriptionJobRequest.setMedia(media);
        startTranscriptionJobRequest.setMediaFormat("wav");
        startTranscriptionJobRequest.setTranscriptionJobName(fileName + "-job");

        amazonTranscribe.startTranscriptionJob(startTranscriptionJobRequest);
```

**Comment by Awr0ra** [comment]
@sstevenkang 
I dont know what you mean
>  could you capture the full HTTP request and Response and share that with us?

my .net code is in 1st message

**Comment by sstevenkang** [comment]
i am asking if you could capture the content of the HTTP request/response using traffic monitoring tool like Fiddler.

**Comment by normj** [comment]
Closing for lack of activity
