### ISSUE TITLE
Web.config must have absolute path for ProfilesLocation

### ISSUE THREAD

**Issue by GenZodd** [aws/aws-sdk-net#848]
## Expected Behavior
When the config value is used in a web.config or app.config `<add key="AWSProfilesLocation" value="\aws-credentials" />`  the path is resolve to the application path. 

## Current Behavior
The path is not found as it appears nothing is done to resolve the path and it is taken as an absolute path. 

## Possible Solution
At runtime resolve, the absolute path is the provided path is in a relative format. 

## Context
It forces all developers to create a "known" path that will exist on all their machines. it does not allow for an ignored file in the application root to be updated with their profile data. They need to create the credentials file, add their keys and the move that to the absolute path defined in the config. 

## Your Environment
* AWSSDK.Core version used: 3.3
* Operating System and version: Windows 10 
* Visual Studio version: 2017
* Targeted .NET platform: 4.6.2

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by sstevenkang** [comment]
Did you mean to set the value to `.\aws-credentials` instead of `\aws-credentials` ?

**Comment by GenZodd** [comment]
I tried that syntax as well. I also tried ~\credentials. I tried every combination I could think if. It is always not found. I also dug around the source code and found nothing in the source code of the SDK that tries to see if that path it is provided is relative or absolute. It appears to just use whatever path it is given as if it is absolute.

**Comment by sstevenkang** [comment]
I can't repro this.  Are you setting `AWSProfileName` correctly?  If you could create a repro project that would help us narrow this down.

**Comment by GenZodd** [comment]
Maybe it is the AssumeProfile part that is getting in the way? I will work on a simple project that has this issues. For now here are my configs.

      <add key="AWSProfileName" value="assume-role-cd" />
      <add key="AWSProfilesLocation" value=".\credentials" />
       <add key="AWSRegion" value="us-east-1"/>

Error I get:

    <br>Exception 1 of 4:
            <br>System.InvalidOperationException: The app.config/web.config files for the application did not contain credential information
            <br> &nbsp;&nbsp;at Amazon.Runtime.AppConfigAWSCredentials..ctor() in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Credentials\_bcl\AppConfigAWSCredentials.cs:line 69
            <br> &nbsp;&nbsp;at Amazon.Runtime.FallbackCredentialsFactory.&lt;&gt;c.&lt;Reset&gt;b__9_0() in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Credentials\FallbackCredentialsFactory.cs:line 50
            <br> &nbsp;&nbsp;at Amazon.Runtime.FallbackCredentialsFactory.GetCredentials(Boolean fallbackToAnonymous) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Credentials\FallbackCredentialsFactory.cs:line 115

**Comment by normj** [comment]
Closing for lack of activity

**Comment by ReinerRunge** [comment]
So is there a way to specify a profiles location that is in the same directory as the `appsettings.json` file? or do we always have to specify an absolute path?
