### ISSUE TITLE
Exception in ErrorHandler.ProcessException()

### ISSUE THREAD

**Issue by xakep139** [aws/aws-sdk-net#858]
If ErrorHandler get an exception of type `System.Exception` there will be a `System.ArgumentNullException` with message:
```
Value cannot be null.
Parameter name: key
```

Here's the stacktrace:
```
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 200
   at Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5`1.MoveNext() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7`1.MoveNext() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CredentialsRetriever.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\RetryHandler\RetryHandler.cs:line 153
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.<InvokeAsync>d__1`1.MoveNext() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Services\S3\Custom\Internal\AmazonS3ExceptionHandler.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5`1.MoveNext() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\ErrorCallbackHandler.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DemoS3.Program.<WritingAnObject>d__2.MoveNext() in C:\Users\n.balabaev\Documents\Visual Studio 2017\Projects\DemoS3\Program.cs:line 43
```
## Expected Behavior

Get original exception from ErrorHandler

## Possible Solution

Fix loop logic in ErrorHandler.ProcessException() if exception has type `System.Exception`

## Steps to Reproduce (for bugs)

I've created a repro https://github.com/xakep139/DemoS3. If you replace `Exception` with any of it subclass (here https://github.com/xakep139/DemoS3/blob/master/BrokenStream.cs#L14), the exception thrown at `ErrorHandler.ProcessException()` (https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Pipeline/ErrorHandler/ErrorHandler.cs#L187) will be correct.

## Your Environment

* AWSSDK.Core version used: 3.3.21.6
* Service assembly and version used: AWSSDK.S3 version 3.3.17
* Operating System and version: Windows 10 Enterprise 1709 (16299.192)
* Visual Studio version: Microsoft Visual Studio Professional 2017 Version 15.5.5
* Targeted .NET platform: .NET Core 2.0

## .NET Core Info

* .NET Core version used for development: 2.0.5
* .NET Core version installed in the environment where application runs: 2.0.5
* Output of `dotnet --info`: 
```
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```
* Contents of project.json/project.csproj: https://github.com/xakep139/DemoS3/blob/master/DemoS3.csproj

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by xakep139** [comment]
@ashishdhingra do you have any estimations when this issue will be picked up for fixing?

**Comment by ashishdhingra** [comment]
Reproducible using code below:
**BrokenStream.cs**
```C#
namespace ConsoleTest
{
    public class BrokenStream : Stream
    {
        public override void Flush()
        {
        }

        public override int Read(byte[] buffer, int offset, int count)
        {
            throw new Exception("Oooops!");
        }

        public override long Seek(long offset, SeekOrigin origin)
        {
            throw new NotSupportedException();
        }

        public override void SetLength(long value)
        {
            throw new NotSupportedException();
        }

        public override void Write(byte[] buffer, int offset, int count)
        {
            throw new NotSupportedException();
        }

        public override bool CanRead => true;
        public override bool CanSeek => false;
        public override bool CanWrite => false;
        public override long Length => 123;
        public override long Position { get; set; }
    }
}
```
**Program.cs**
```C#
using Amazon.Runtime;
using Amazon.S3.Model;
using Amazon.S3;
using ConsoleTest;

const string BucketName = "somebucket";

using (var client = new AmazonS3Client())
{
    using (var myBrokenStream = new BrokenStream())
    {
        await WritingAnObject(client, myBrokenStream);
    }
}

static async Task WritingAnObject(IAmazonS3 client, Stream inputStream)
{
    try
    {
        var request = new PutObjectRequest
        {
            InputStream = inputStream,
            BucketName = BucketName,
            CannedACL = S3CannedACL.PublicRead,
            Key = "1/temp.txt"
        };

        await client.PutObjectAsync(request);
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex);
    }
}
```

**Comment by ashishdhingra** [comment]
Fix has been released in [AWSSDK.Core 3.7.400.1](https://www.nuget.org/packages/AWSSDK.Core/3.7.400.1)
