### ISSUE TITLE
Visual Studio 2017 (15.5.6) Crash on Start-Up

### ISSUE THREAD

**Issue by dem1urge** [aws/aws-sdk-net#864]
## Expected Behavior
Visual Studio 2017 (15.5.6) should start up completely (and not crash.  heh.).

## Current Behavior
Visual Studio 2017 loads and looks like it is going to complete at first but crashes with the Exit Program or Debug options.  If Debug is chosen, it, of course, crashes again.  Here is the event from the event log:
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Amazon.AWSToolkit.ECS.Nodes.RootViewModel.BuildClient(Amazon.Runtime.AWSCredentials)
   at Amazon.AWSToolkit.Navigator.Node.ServiceRootViewModel..ctor(Amazon.AWSToolkit.Navigator.Node.IMetaNode, Amazon.AWSToolkit.Navigator.Node.IViewModel, System.String)
   at Amazon.AWSToolkit.ECS.Nodes.RootViewModel..ctor(Amazon.AWSToolkit.Account.AccountViewModel)
   at Amazon.AWSToolkit.ECS.Nodes.RootViewMetaNode.CreateServiceRootModel(Amazon.AWSToolkit.Account.AccountViewModel)
   at Amazon.AWSToolkit.Account.AccountViewModel.CreateServiceChildren()
   at Amazon.AWSToolkit.Navigator.NavigatorControl.updateActiveRegion()
   at Amazon.AWSToolkit.Navigator.NavigatorControl.onRegionChanged(System.Object, System.Windows.Controls.SelectionChangedEventArgs)
   at System.Windows.Controls.SelectionChangedEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs)
   at System.Windows.Controls.ComboBox.OnSelectionChanged(System.Windows.Controls.SelectionChangedEventArgs)
   at System.Windows.Controls.Primitives.Selector.InvokeSelectionChanged(System.Collections.Generic.List`1<ItemInfo>, System.Collections.Generic.List`1<ItemInfo>)
   at System.Windows.Controls.Primitives.Selector+SelectionChanger.End()
   at System.Windows.Controls.Primitives.Selector+SelectionChanger.SelectJustThisItem(ItemInfo, Boolean)
   at System.Windows.Controls.Primitives.Selector.OnSelectedItemChanged(System.Windows.DependencyObject, System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.FrameworkElement.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.UpdateEffectiveValue(System.Windows.EntryIndex, System.Windows.DependencyProperty, System.Windows.PropertyMetadata, System.Windows.EffectiveValueEntry, System.Windows.EffectiveValueEntry ByRef, Boolean, Boolean, System.Windows.OperationType)
   at System.Windows.DependencyObject.SetValueCommon(System.Windows.DependencyProperty, System.Object, System.Windows.PropertyMetadata, Boolean, Boolean, System.Windows.OperationType, Boolean)
   at Amazon.AWSToolkit.Navigator.NavigatorControl.setInitialRegionSelection()
   at Amazon.AWSToolkit.Navigator.NavigatorControl._ctlAccounts_PropertyChanged(System.Object, System.ComponentModel.PropertyChangedEventArgs)
   at Amazon.AWSToolkit.CommonUI.Components.RegisteredProfilesPicker._ctlCombo_SelectionChanged(System.Object, System.Windows.Controls.SelectionChangedEventArgs)
   at System.Windows.Controls.SelectionChangedEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs)
   at System.Windows.Controls.ComboBox.OnSelectionChanged(System.Windows.Controls.SelectionChangedEventArgs)
   at System.Windows.Controls.Primitives.Selector.InvokeSelectionChanged(System.Collections.Generic.List`1<ItemInfo>, System.Collections.Generic.List`1<ItemInfo>)
   at System.Windows.Controls.Primitives.Selector+SelectionChanger.End()
   at System.Windows.Controls.Primitives.Selector+SelectionChanger.SelectJustThisItem(ItemInfo, Boolean)
   at System.Windows.Controls.Primitives.Selector.OnSelectedItemChanged(System.Windows.DependencyObject, System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.FrameworkElement.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.UpdateEffectiveValue(System.Windows.EntryIndex, System.Windows.DependencyProperty, System.Windows.PropertyMetadata, System.Windows.EffectiveValueEntry, System.Windows.EffectiveValueEntry ByRef, Boolean, Boolean, System.Windows.OperationType)
   at System.Windows.DependencyObject.SetValueCommon(System.Windows.DependencyProperty, System.Object, System.Windows.PropertyMetadata, Boolean, Boolean, System.Windows.OperationType, Boolean)
   at Amazon.AWSToolkit.CommonUI.Components.RegisteredProfilesPicker.set_SelectedAccount(Amazon.AWSToolkit.Account.AccountViewModel)
   at Amazon.AWSToolkit.Navigator.NavigatorControl.Initialize(Amazon.AWSToolkit.Navigator.Node.AWSViewModel)
   at Amazon.AWSToolkit.ToolkitFactory+<>c__DisplayClass8_0.<InitializeToolkit>b__1()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

## Possible Solution
Revert to 1.14.0.1?  This one DOES work in our VS2017.5.5.6 IDE.  We have already done this, in house, because someone had the habit of saving the VSIX files so we were able to get our shop up and running again.  We have also advised our Devs to disable automatic updates for a while.

## Steps to Reproduce (for bugs)
Start VS2017.  Crash.

## Context
Was trying to start up VS2017.  It was affecting our entire Dev Team.  Once they shutdown VS2017, for say, lunch, they came back to a broken VS2017 upon startup.
## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: Windows 10 Enterprise, 10.0.16299
* Visual Studio version: 2017, 15.5.6
Here's a dump of the info from VS2017:
Microsoft Visual Studio Professional 2017 
Version 15.5.6
VisualStudio.15.Release/15.5.6+27130.2027
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Professional

Visual Basic 2017   00369-60000-00001-AA466
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA466
Microsoft Visual C# 2017

Visual C++ 2017   00369-60000-00001-AA466
Microsoft Visual C++ 2017

Visual F# 4.1   00369-60000-00001-AA466
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio Package   8.10.01106.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.31127.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2012   4.0.20601.0
For additional information, visit https://www.asp.net/

ASP.NET Web Frameworks and Tools 2017   5.2.51007.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.31106.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.3.2000.1
Microsoft Azure Data Lake Tools for Visual Studio

Azure Data Lake Tools for Visual Studio   2.3.2000.1
Microsoft Azure Data Lake Tools for Visual Studio

BusinessObjectEditor   1.0
Information about my package

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

ConvertToDevExtremeCommand Extension   1.0
ConvertToDevExtremeCommand Visual Studio Extension Detailed Info

Cookiecutter   3.0.17320.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

CreateLayoutWizard   1.0
Create layout wizard.

DevExpress.DeploymentTool   1.0
A useful tool for deploying DevExpress assemblies.

DevExpress.ExpressApp.Design.DynamicPackage   1.0
DevExpress VSIX Package

DevExpress.ExpressApp.DesignPackage   1.0
DevExpress VSIX Package

DevExpress.Win.LayoutAssistant Extension   1.0
DevExpress.Win.LayoutAssistant Visual Studio Extension Detailed Info

DevExtreme.Design   17.1.5
DevExtreme Visual Studio integration package

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

GitClientVSPackage Extension   1.0
GitClientVSPackage Visual Studio Extension Detailed Info

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Microsoft Azure HDInsight Azure Node   2.3.2000.1
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.3.2000.1
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   2.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.3.2000.1
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.51120.3

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Node.js Tools   1.4.11025.7
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   4.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Python   3.0.17320.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Django support   3.0.17320.1
Provides templates and integration for the Django web framework.

Python - IronPython support   3.0.17320.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   3.0.17320.1
Profiling support for Python projects.

R Tools for Visual Studio   1.3.31108.1213
Provides project system, R Interactive window, plotting, and more for the R programming language.

SQL Server Data Tools   15.1.61710.120
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TSVN   1.9
Control TortoiseSVN from within Visual Studio

TypeScript Tools   15.5.11025.1
TypeScript Tools for Microsoft Visual Studio

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Universal Windows Apps   15.0.27130.2020
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualSVN   6.0.4
Integration with Subversion version control. For more information about VisualSVN, see the VisualSVN website at http://www.visualsvn.com
Copyright © 2017 VisualSVN Software Ltd. All rights reserved.

WebJobs Tools v1.0.0   15.0.40108.0
WebJobs Tools v1.0.0

XtraReports package   1.0
XtraReports package

These are sans AWS Tools of course.

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by normj** [comment]
We believe we have resolved the issue. Very sorry for crashing Visual Studio which is the worst thing an extension can do.

**Comment by steveataws** [comment]
As @normj notes, we think we found the root cause in the control file but can you confirm what region your AWS Explorer was set to (either last time you used the toolkit or if you happened to catch sight on the startup that crashed)?

**Comment by dem1urge** [comment]
us-gov-west-1 is the region.  Thanks for the quick response, y'all. 👍

**Comment by steveataws** [comment]
Thanks for confirming; the changes we made to the control file were for that region so it looks like we're good to go.

**Comment by dem1urge** [comment]
Fix confirmed.  Thanks guys! 😊
