### ISSUE TITLE
Visual Studio Crashes with AWS Toolkit and SAML credentials

### ISSUE THREAD

**Issue by dabalakov** [aws/aws-sdk-net#878]
I'm trying to setup developers with visual studio and AWS Toolkit along with AWS SAML credentials. For some developers after installing the toolkit and storing the profiles visual studio 2017 crashes during startup.

## Expected Behavior
I expect visual studio to load and allow us to open projects. Then once the AWS SAM project is loaded we should be able to use the the publish to lambda and deploy using the stored SAML credentials.

## Current Behavior
Currently visual studio crashes a short time after load and the AWS toolkit shows the following log entries

```
2018-02-19 16:57:48,280 [1] DEBUG Amazon.AWSToolkit.VisualStudio.AWSToolkitPackage - Creating SAWSToolkitShellProvider service
2018-02-19 16:57:48,318 [8] INFO  Amazon.AWSToolkit.ToolkitFactory - Starting default probe for plugins in folder 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\by0nsasm.txy\Plugins'
2018-02-19 16:57:48,318 [1] INFO  Amazon.AWSToolkit.MobileAnalytics.SimpleMobileAnalytics - Queuing analytics event in local queue with timestamp: 02/20/2018 00:57:48
2018-02-19 16:57:48,396 [8] INFO  Amazon.AWSToolkit.Utility - ...resolved for C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\by0nsasm.txy\SDK\AWSSDK.CloudFormation.dll
2018-02-19 16:57:48,404 [8] INFO  Amazon.AWSToolkit.ToolkitFactory - Loaded plugin CloudFormation from AWSToolkit.CloudFormation, Version=1.14.1.3, Culture=neutral, PublicKeyToken=8339e7e97bb08995
2018-02-19 16:57:48,422 [8] INFO  Amazon.AWSToolkit.Utility - ...resolved for C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\by0nsasm.txy\SDK\AWSSDK.CloudFront.dll
2018-02-19 16:57:48,430 [8] INFO  Amazon.AWSToolkit.ToolkitFactory - Loaded plugin CloudFront from AWSToolkit.CloudFront, Version=1.14.1.3, Culture=neutral, PublicKeyToken=8339e7e97bb08995
2018-02-19 16:57:48,445 [8] INFO  Amazon.AWSToolkit.Utility - ...resolved for C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\by0nsasm.txy\SDK\AWSSDK.IdentityManagement.dll
2018-02-19 16:57:48,467 [8] INFO  Amazon.AWSToolkit.Utility - ...resolved for C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\by0nsasm.txy\SDK\AWSSDK.CodeCommit.dll
2018-02-19 16:57:48,475 [8] INFO  Amazon.AWSToolkit.ToolkitFactory - Loaded plugin CodeCommit from AWSToolkit.CodeCommit, Version=1.14.1.3, Culture=neutral, PublicKeyToken=8339e7e97bb08995
2018-02-19 16:57:48,494 [8] INFO  Amazon.AWSToolkit.ToolkitFactory - Loaded plugin DynamoDB from AWSToolkit.DynamoDB, Version=1.14.1.3, Culture=neutral, PublicKeyToken=8339e7e97bb08995
2018-02-19 16:57:48,514 [8] INFO  Amazon.AWSToolkit.Utility - ...resolved for C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\by0nsasm.txy\SDK\AWSSDK.EC2.dll
2018-02-19 16:57:48,547 [8] INFO  Amazon.AWSToolkit.ToolkitFactory - Loaded plugin EC2 from AWSToolkit.EC2, Version=1.14.1.3, Culture=neutral, PublicKeyToken=8339e7e97bb08995
2018-02-19 16:57:48,574 [8] INFO  Amazon.AWSToolkit.Utility - ...resolved for C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\by0nsasm.txy\SDK\AWSSDK.ECS.dll
2018-02-19 16:57:48,586 [8] INFO  Amazon.AWSToolkit.Utility - ...resolved for C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\by0nsasm.txy\SDK\AWSSDK.ECR.dll
2018-02-19 16:57:48,596 [8] INFO  Amazon.AWSToolkit.Utility - ...resolved for C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\by0nsasm.txy\SDK\AWSSDK.CloudWatchLogs.dll
2018-02-19 16:57:48,608 [8] INFO  Amazon.AWSToolkit.Utility - ...resolved for C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\by0nsasm.txy\SDK\AWSSDK.CloudWatchEvents.dll
2018-02-19 16:57:48,621 [8] INFO  Amazon.AWSToolkit.Utility - ...resolved for C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\by0nsasm.txy\SDK\AWSSDK.S3.dll
2018-02-19 16:57:48,638 [8] INFO  Amazon.AWSToolkit.ToolkitFactory - Loaded plugin ECS from AWSToolkit.ECS, Version=1.14.1.3, Culture=neutral, PublicKeyToken=8339e7e97bb08995
2018-02-19 16:57:48,663 [8] INFO  Amazon.AWSToolkit.Utility - ...resolved for C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\by0nsasm.txy\SDK\AWSSDK.ElasticBeanstalk.dll
2018-02-19 16:57:48,674 [8] INFO  Amazon.AWSToolkit.Utility - ...resolved for C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\by0nsasm.txy\SDK\AWSSDK.RDS.dll
2018-02-19 16:57:48,681 [8] INFO  Amazon.AWSToolkit.ToolkitFactory - Loaded plugin Beanstalk from AWSToolkit.ElasticBeanstalk, Version=1.14.1.3, Culture=neutral, PublicKeyToken=8339e7e97bb08995
2018-02-19 16:57:48,695 [8] INFO  Amazon.AWSToolkit.ToolkitFactory - Loaded plugin IdentityManagement from AWSToolkit.IdentityManagement, Version=1.14.1.3, Culture=neutral, PublicKeyToken=8339e7e97bb08995
2018-02-19 16:57:48,714 [8] INFO  Amazon.AWSToolkit.Utility - ...resolved for C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\by0nsasm.txy\SDK\AWSSDK.Lambda.dll
2018-02-19 16:57:48,740 [8] INFO  Amazon.AWSToolkit.ToolkitFactory - Loaded plugin Lambda from AWSToolkit.Lambda, Version=1.14.1.3, Culture=neutral, PublicKeyToken=8339e7e97bb08995
2018-02-19 16:57:48,767 [8] INFO  Amazon.AWSToolkit.ToolkitFactory - Loaded plugin RDS from AWSToolkit.RDS, Version=1.14.1.3, Culture=neutral, PublicKeyToken=8339e7e97bb08995
2018-02-19 16:57:48,784 [8] INFO  Amazon.AWSToolkit.ToolkitFactory - Loaded plugin S3 from AWSToolkit.S3, Version=1.14.1.3, Culture=neutral, PublicKeyToken=8339e7e97bb08995
2018-02-19 16:57:48,807 [8] INFO  Amazon.AWSToolkit.Utility - ...resolved for C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\by0nsasm.txy\SDK\AWSSDK.SimpleDB.dll
2018-02-19 16:57:48,814 [8] INFO  Amazon.AWSToolkit.ToolkitFactory - Loaded plugin SimpleDB from AWSToolkit.SimpleDB, Version=1.14.1.3, Culture=neutral, PublicKeyToken=8339e7e97bb08995
2018-02-19 16:57:48,831 [8] INFO  Amazon.AWSToolkit.Utility - ...resolved for C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\by0nsasm.txy\SDK\AWSSDK.SimpleNotificationService.dll
2018-02-19 16:57:48,839 [8] INFO  Amazon.AWSToolkit.ToolkitFactory - Loaded plugin SNS from AWSToolkit.SNS, Version=1.14.1.3, Culture=neutral, PublicKeyToken=8339e7e97bb08995
2018-02-19 16:57:48,855 [8] INFO  Amazon.AWSToolkit.Utility - ...resolved for C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\by0nsasm.txy\SDK\AWSSDK.SQS.dll
2018-02-19 16:57:48,867 [8] INFO  Amazon.AWSToolkit.ToolkitFactory - Loaded plugin SQS from AWSToolkit.SQS, Version=1.14.1.3, Culture=neutral, PublicKeyToken=8339e7e97bb08995
2018-02-19 16:57:48,993 [8] INFO  Amazon.AWSToolkit.S3FileFetcher - Null/empty hosted files location override
2018-02-19 16:57:48,994 [8] INFO  Amazon.AWSToolkit.S3FileFetcher - Null/empty hosted files location override
2018-02-19 16:57:48,994 [8] INFO  Amazon.AWSToolkit.S3FileFetcher - Probing for hosted file 'ServiceEndPoints.xml' at url prefix 'https://d3rrggjwfhwld2.cloudfront.net/'
2018-02-19 16:57:49,126 [1] INFO  Amazon.AWSToolkit.VisualStudio.AWSToolkitPackage - Received __VSSPROPID4.VSSPROPID_ShellInitialized property change, new value True
2018-02-19 16:57:49,345 [1] FATAL Amazon.AWSToolkit.ToolkitFactory - Unhandled exception
System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<System.Collections.Generic.IList`1<System.String>> Amazon.Runtime.SharedInterfaces.ICoreAmazonS3.GetAllObjectKeysAsync(System.String, System.String, System.Collections.Generic.IDictionary`2<System.String,System.Object>)'.
   at Amazon.AWSToolkit.S3.Nodes.S3RootViewModel.BuildClient(AWSCredentials awsCredentials)
   at Amazon.AWSToolkit.Navigator.Node.ServiceRootViewModel..ctor(IMetaNode metaNode, IViewModel parent, String name)
   at Amazon.AWSToolkit.S3.Nodes.S3RootViewModel..ctor(AccountViewModel accountViewModel)
   at Amazon.AWSToolkit.S3.Nodes.S3RootViewMetaNode.CreateServiceRootModel(AccountViewModel account)
   at Amazon.AWSToolkit.Account.AccountViewModel.CreateServiceChildren()
   at Amazon.AWSToolkit.Navigator.NavigatorControl.updateActiveRegion()
   at Amazon.AWSToolkit.Navigator.NavigatorControl.onRegionChanged(Object sender, SelectionChangedEventArgs e)
   at System.Windows.Controls.SelectionChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.ComboBox.OnSelectionChanged(SelectionChangedEventArgs e)
   at System.Windows.Controls.Primitives.Selector.InvokeSelectionChanged(List`1 unselectedInfos, List`1 selectedInfos)
   at System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
   at System.Windows.Controls.Primitives.Selector.SelectionChanger.SelectJustThisItem(ItemInfo info, Boolean assumeInItemsCollection)
   at System.Windows.Controls.Primitives.Selector.OnSelectedItemChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at Amazon.AWSToolkit.Navigator.NavigatorControl.setInitialRegionSelection()
   at Amazon.AWSToolkit.Navigator.NavigatorControl._ctlAccounts_PropertyChanged(Object sender, PropertyChangedEventArgs e)
   at Amazon.AWSToolkit.CommonUI.Components.RegisteredProfilesPicker._ctlCombo_SelectionChanged(Object sender, SelectionChangedEventArgs e)
   at System.Windows.Controls.SelectionChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.ComboBox.OnSelectionChanged(SelectionChangedEventArgs e)
   at System.Windows.Controls.Primitives.Selector.InvokeSelectionChanged(List`1 unselectedInfos, List`1 selectedInfos)
   at System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
   at System.Windows.Controls.Primitives.Selector.SelectionChanger.SelectJustThisItem(ItemInfo info, Boolean assumeInItemsCollection)
   at System.Windows.Controls.Primitives.Selector.OnSelectedItemChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at Amazon.AWSToolkit.CommonUI.Components.RegisteredProfilesPicker.set_SelectedAccount(AccountViewModel value)
   at Amazon.AWSToolkit.Navigator.NavigatorControl.Initialize(AWSViewModel viewModel)
   at Amazon.AWSToolkit.ToolkitFactory.<>c__DisplayClass8_0.<InitializeToolkit>b__1()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

## Steps to Reproduce (for bugs)

- Install AWS toolkit for Visual Studio 2017
- Store SAML based Profile using the following (https://docs.aws.amazon.com/powershell/latest/userguide/saml-pst.html)
- Open Visual Studio 2017 and it should crash before letting you load a project
- To Resolve: remove the stored credentials using the following command:
Get-AWSCredentials -ListProfileDetail | forEach { Remove-AWSCredentialProfile $_.profileName }

## Context
We're trying to develop AWS SAM applications within Visual Studio and publish to an account.

## Your Environment
- Visual Studio 2017: 15.5.6
- AWS Toolkit for Visual Studio 2017: 1.14.13

**Comment by steveataws** [comment]
Thanks for letting us know. 

We can certainly fix the crash however please note that at this time the toolkit does not support the SAML credential profiles that are created and can be used with our PowerShell tools. We have a backlog item to extend credential support in the toolkit this year to include these kinds of profiles but I don't have an ETA for release that I can share yet. So, once the crash is fixed, these profiles won't actually appear in the explorer for you to select.

**Comment by dabalakov** [comment]
Thanks Steve,
Some of the developers in our Company do have this setup working with SAML credentials so I was hoping there was better resolution than just removing the ability to use SAML credentials. I haven't been able to identify what version / steps get it working for some developers vs not working for others.

**Comment by dabalakov** [comment]
One of our developers are also reporting that without storing SAML credentials, visual studio loads, but they can't use the "Publish to Lambda" feature. The logs shows the same Fatal error with the GetAllObjectKeysAsync method missing.

**Comment by steveataws** [comment]
Is your setup somehow writing credentials to the shared (ini) format credential file? That's the only way I can think of that the VS toolkit would appear to be working with credentials obtained from a federated provider.

**Comment by dabalakov** [comment]
you mean the credentials file at c:\users\username\.aws\credentials? No there wasn't a .aws folder in both situations, working and not working. 

FYI, Also visual studio reports that the performance of AWSToolkit is slow on startup which looks to be this bug. https://github.com/aws/aws-sdk-net/issues/768. It has the same missing method error too. Could this be related?

**Comment by dabalakov** [comment]
Another note, we removed the SAML credentials and visual studio loads fine without them. But when we enter access key and credentials into the AWS Toolkit startup page and click save. We get the same fatal error. It seems to me that this error doesn't have to do with SAML credentials but with some underlying dependency that is failing.  While SAML credentials aren't officially supported, as long as the extension isn't crashing on this missing method error, SAML credentials do work. Let me know if you need any specific details to help diagnosing this. 
![image](https://user-images.githubusercontent.com/33964103/36453087-b351daa2-164b-11e8-9de6-7bac3443d646.png)

**Comment by steveataws** [comment]
Ok, so you're using the VS toolkit's own accounts file (%userprofile%/appdata/local/awstoolkit/registeredaccounts.json), and you've used the Set-AWSSamlEndpoint and Set-AWSSamlRoleProfile cmdlets to add one or more profiles to this file, and then when you start VS you get a crash (even though the profile wasn't selected as active in the explorer at any time). Is that a correct summary?

I'm not sure what the missing method error is all about; you have the latest version which has all the service related info for the explorer loading in a non-UI thread that normj did for the referenced issue. I'll worry about the crash first, then we can take a further look at that problem.

**Comment by steveataws** [comment]
Is that snapshot from a run without the saml credential profile? If so then it looks like the toolkit is (correctly for now) filtering out profiles it cannot use. Where does the crash occur, after that missing method message?

**Comment by dabalakov** [comment]
Correct we're using the VS Toolkits accounts file (registeraccounts.json). using Set-AWSSamlEndpoint and Set-AWSSamlRoleProfile add entries to these files. Once at least 1 is added, VS crashes upon startup even though nothing was selected. 

While having 0 entires in the file, opening VS Studio doesn't cause a crash, however when specifying IAM credentials (access key + secret) in the "getting started" page, then hitting "save and close" presents us with the error (as seen in the screenshot). 

VS crashes only when there are SAML entries in the (registeraccounts.json) file, however it also doesn't connect successfully with regular credentials and has a similar error message ("missing method: GetAllObjectKeysAsync")

**Comment by normj** [comment]
I have seen this error before when some other extension loads the .NET 3.5 version of the AWS SDK for .NET. The most common culprit is having our AWS PowerShell CmdLet installed and then the VS PowerShell extension installed.

**Comment by steveataws** [comment]
@dabalakov, apologies it's taken me a while to cycle back to this.

I've now resurrected my PowerShell saml testing setup and having run the Set-AWSSamlEndpoint and Set-AWSSamlRoleProfile cmdlets to update registeredaccounts.json with saml-based credential profiles I'm not seeing a crash when starting any of VS2013/2015/2017. The explorer window filters out the profiles, as I'd expect.

Can you try temporarily removing our AWSPowerShell module and see if VS then starts to operate normally, to rule-in-or-out the scenario posted by Norm previously?

**Comment by rmandadapu** [comment]
My problem is different in this case.. I followed this link to setup SAML profile. https://docs.aws.amazon.com/powershell/latest/userguide/saml-pst.html

and have configured this successfully, and then I ran my code in VS and I got this error here..

Exception 1 of 4: System.InvalidOperationException: **The profile [SAMLMikeProfile] is a SAML role profile that specifies a user identity. This type of profile is not allowed here. Please use a SAML role profile without an explicit user identity, or a different type of profile**. at Amazon.Runtime.CredentialManagement.AWSCredentialsFactory.GetAWSCredentials(String profileName, ICredentialProfileSource profileSource, CredentialProfileOptions options, RegionEndpoint stsRegion, Boolean nonCallbackOnly) at Amazon.Runtime.CredentialManagement.AWSCredentialsFactory.GetAWSCredentials(CredentialProfile profile, ICredentialProfileSource profileSource, Boolean nonCallbackOnly) at Amazon.Runtime.AppConfigAWSCredentials..ctor() at Amazon.Runtime.FallbackCredentialsFactory.<>c.<Reset>b__9_0() at Amazon.Runtime.FallbackCredentialsFactory.GetCredentials(Boolean fallbackToAnonymous) 
Exception 2 of 4: System.IO.InvalidDataException: Credential profile [default] is not valid. Please ensure the profile contains a valid combination of properties. at Amazon.Runtime.CredentialManagement.AWSCredentialsFactory.ThrowOrReturnNull(String message, Exception innerException, Boolean doThrow) at Amazon.Runtime.CredentialManagement.AWSCredentialsFactory.ThrowInvalidOrReturnNull(String profileName, Boolean doThrow) at Amazon.Runtime.CredentialManagement.AWSCredentialsFactory.GetAWSCredentialsInternal(String profileName, Nullable`1 profileType, CredentialProfileOptions options, RegionEndpoint stsRegion, ICredentialProfileSource profileSource, Boolean throwIfInvalid) at Amazon.Runtime.CredentialManagement.AWSCredentialsFactory.GetAWSCredentials(String profileName, ICredentialProfileSource profileSource, CredentialProfileOptions options, RegionEndpoint stsRegion, Boolean nonCallbackOnly) at Amazon.Runtime.CredentialManagement.AWSCredentialsFactory.GetAWSCredentials(CredentialProfile profile, ICredentialProfileSource profileSource, Boolean nonCallbackOnly) at Amazon.Runtime.FallbackCredentialsFactory.GetAWSCredentials(ICredentialProfileSource source) at Amazon.Runtime.FallbackCredentialsFactory.<>c.<Reset>b__9_1() at Amazon.Runtime.FallbackCredentialsFactory.GetCredentials(Boolean fallbackToAnonymous)
Exception 3 of 4: System.InvalidOperationException: The environment variables AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY/AWS_SESSION_TOKEN were not set with AWS credentials. at Amazon.Runtime.EnvironmentVariablesAWSCredentials.FetchCredentials() at Amazon.Runtime.EnvironmentVariablesAWSCredentials..ctor() at Amazon.Runtime.FallbackCredentialsFactory.<>c.<Reset>b__9_2() at Amazon.Runtime.FallbackCredentialsFactory.GetCredentials(Boolean fallbackToAnonymous) 
Exception 4 of 4: Amazon.Runtime.AmazonServiceException: Unable to reach credentials server at Amazon.Runtime.URIBasedRefreshingCredentialHelper.GetContents(Uri uri) at Amazon.Runtime.InstanceProfileAWSCredentials.<GetAvailableRoles>d__10.MoveNext() at Amazon.Runtime.InstanceProfileAWSCredentials.GetFirstRole() at Amazon.Runtime.FallbackCredentialsFactory.ECSEC2CredentialsWrapper() at Amazon.Runtime.FallbackCredentialsFactory.GetCredentials(Boolean fallbackToAnonymous)


And now I'm able to fix the issue, in my case all of our developers using same saml role and when I created first saml profile for a visual studio I stored profile as  SAMLDEMOProfile and it worked in his case.

Later I tried the same thing and I stored profile this time as SAMLProfile and it gave me the above errors., I contacted aws support and they were saying they don't support beyond their limits./

So here again I removed everything and set up a profile as a SAMLDEMOProfile guess what it worked..


I really don't know why it worked and it didn't.. but what I understood is that Store as a name for the same role has to match I guess.

I tried to change in registeredaccounts.json but it didn't work.. It only worked when I stored profile as our developers using.

So hopefully aws will solve this issue and they should bring support on issues like this.
