### ISSUE TITLE
AmazonUnmarshallingException

### ISSUE THREAD

**Issue by francoisdutoit** [aws/aws-sdk-net#885]
Hi,
I'm trying to read a stream from my Kinesis Video Stream using.net - so far I have the below code...but getting an AmazonUnmarshallingException on my GetMedia Request....any ideas?

Thanks!

           var accessKeyID = "MyaccessKeyID";
            var secretKey = "MysecretKey";
            var credentials = new BasicAWSCredentials(accessKeyID, secretKey);

            var videoClient = new AmazonKinesisVideoClient(credentials, RegionEndpoint.USWest2);
            var streams = videoClient.ListStreams(new ListStreamsRequest());

            //var getDataEndpointRequest = new GetDataEndpointRequest();
            //getDataEndpointRequest.
            //var dataEndPoint = videoClient.GetDataEndpoint(getDataEndpointRequest);

            var amazonKinesisVideoMediaConfig = new AmazonKinesisVideoMediaConfig();
            amazonKinesisVideoMediaConfig.ServiceURL = "https://kinesisvideo.us-west-2.amazonaws.com";

            var videoMediaClient = new AmazonKinesisVideoMediaClient(credentials, 
           amazonKinesisVideoMediaConfig);
   
            var mediaRequest = new GetMediaRequest();
            mediaRequest.StreamARN = streams.StreamInfoList[1].StreamARN;
            mediaRequest.StreamName = streams.StreamInfoList[1].StreamName;

            var getMediaResponse = videoMediaClient.GetMedia(mediaRequest);

**Comment by francoisdutoit** [comment]
The exception details - 

Amazon.Runtime.AmazonUnmarshallingException was unhandled
  HResult=-2146233088
  Message=Error unmarshalling response back from AWS. Request ID: 0cb9d34b-1e4d-11e8-8b7d-930540e40c62, Response Body: <AccessDeniedException>
  <Message>Unable to determine service/operation name to be authorized</Message>
</AccessDeniedException>

  RequestId=0cb9d34b-1e4d-11e8-8b7d-930540e40c62
  ResponseBody=<AccessDeniedException>
  <Message>Unable to determine service/operation name to be authorized</Message>
</AccessDeniedException>

  Source=AWSSDK.Core
  StackTrace:
       at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
       at Amazon.Runtime.Internal.ExceptionHandler`1.Handle(IExecutionContext executionContext, Exception exception)
       at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
       at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
       at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
       at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
       at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
       at Amazon.Runtime.Internal.Signer.InvokeSync(IExecutionContext executionContext)
       at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
       at Amazon.Runtime.Internal.CredentialsRetriever.InvokeSync(IExecutionContext executionContext)
       at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
       at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext)
       at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
       at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
       at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
       at Amazon.Runtime.Internal.EndpointResolver.InvokeSync(IExecutionContext executionContext)
       at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
       at Amazon.Runtime.Internal.Marshaller.InvokeSync(IExecutionContext executionContext)
       at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
       at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
       at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
       at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext)
       at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
       at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext)
       at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext)
       at Amazon.Runtime.AmazonServiceClient.Invoke[TRequest,TResponse](TRequest request, IMarshaller`2 marshaller, ResponseUnmarshaller unmarshaller)
       at Amazon.KinesisVideoMedia.AmazonKinesisVideoMediaClient.GetMedia(GetMediaRequest request)
       at WinFormStreamer.Form1.Form1_Load(Object sender, EventArgs e) in D:\OneDrive\2018\NeighbourhoodWatch\Projects\WinFormStreamer\WinFormStreamer\Form1.cs:line 67
       at System.Windows.Forms.Form.OnLoad(EventArgs e)
       at System.Windows.Forms.Form.OnCreateControl()
       at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
       at System.Windows.Forms.Control.CreateControl()
       at System.Windows.Forms.Control.WmShowWindow(Message& m)
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
       at System.Windows.Forms.ContainerControl.WndProc(Message& m)
       at System.Windows.Forms.Form.WmShowWindow(Message& m)
       at System.Windows.Forms.Form.WndProc(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
       at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
  InnerException: 
       HResult=-2146232000
       LineNumber=0
       LinePosition=0
       Message=Root element is missing.
       Source=System.Xml
       SourceUri=""
       StackTrace:
            at System.Xml.XmlTextReaderImpl.Throw(Exception e)
            at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
            at System.Xml.XmlTextReaderImpl.Read()
            at Amazon.Runtime.Internal.Transform.XmlUnmarshallerContext.Read()
            at Amazon.Runtime.Internal.Transform.ErrorResponseUnmarshaller.Unmarshall(XmlUnmarshallerContext context)
            at Amazon.Runtime.Internal.Transform.JsonErrorResponseUnmarshaller.Unmarshall(JsonUnmarshallerContext context)
            at Amazon.KinesisVideoMedia.Model.Internal.MarshallTransformations.GetMediaResponseUnmarshaller.UnmarshallException(JsonUnmarshallerContext context, Exception innerException, HttpStatusCode statusCode)
            at Amazon.Runtime.Internal.Transform.JsonResponseUnmarshaller.UnmarshallException(UnmarshallerContext input, Exception innerException, HttpStatusCode statusCode)
            at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
       InnerException:

**Comment by francoisdutoit** [comment]
Managed to get it working.

**Comment by vellozzi** [comment]
@francoisdutoit - The message "Unable to determine service/operation name to be authorized" is an error message from the service.  That's probably what you fixed.
But thanks for bringing this up.  Because the SDK isn't unmarshalling it correctly and that needs to be fixed.

**Comment by francoisdutoit** [comment]
@vellozzi 

I am however getting an empty stream... :/
See issue : Kinesis Video - Empty Payload #889

I did note that the repose payload type says video/webm although my stream is video/h264.... Is that corrrect?
