### ISSUE TITLE
Unable to deploy Lambda function with VS2017

### ISSUE THREAD

**Issue by ianoble** [aws/aws-sdk-net#947]
I'm not able to deploy Lambda functions that worked fine before. Here is the error I get in the deploy dialog window, using the "Upload Lambda Function" wizard:

Executing publish command
Deleted previous publish folder
... invoking 'dotnet publish', working folder 'C:\Users\INoble\Documents\Visual Studio 2017\Projects\SharepointPOC\SharepointPOC\bin\Release\netcoreapp1.0\publish'
... publish: Microsoft (R) Build Engine version 15.7.177.53362 for .NET Core
... publish: Copyright (C) Microsoft Corporation. All rights reserved.
... publish:   Restore completed in 36.53 ms for C:\Users\INoble\Documents\Visual Studio 2017\Projects\SharepointPOC\SharepointPOC\SharepointPOC.csproj.
... publish:   Restore completed in 63.83 ms for C:\Users\INoble\Documents\Visual Studio 2017\Projects\SharepointPOC\SharepointPOC\SharepointPOC.csproj.
... publish:   SharepointPOC -> C:\Users\INoble\Documents\Visual Studio 2017\Projects\SharepointPOC\SharepointPOC\bin\Release\netcoreapp1.0\SharepointPOC.dll
... publish:   SharepointPOC -> C:\Users\INoble\Documents\Visual Studio 2017\Projects\SharepointPOC\SharepointPOC\bin\Release\netcoreapp1.0\publish\
Unknown error executing command: Value cannot be null.
Parameter name: stream
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
   at System.IO.StreamReader..ctor(Stream stream)
   at Amazon.Lambda.Tools.LambdaPackager.CalculateRuntimeHierarchy()
   at Amazon.Lambda.Tools.LambdaPackager.FlattenRuntimeFolder(IToolLogger logger, String publishLocation, JsonData depsJsonTargetNode)
   at Amazon.Lambda.Tools.LambdaPackager.CreateApplicationBundle(LambdaToolsDefaults defaults, IToolLogger logger, String workingDirectory, String projectLocation, String configuration, String targetFramework, String msbuildParameters, Boolean disableVersionCheck, String& publishLocation, String& zipArchivePath)
   at Amazon.Lambda.Tools.Commands.DeployFunctionCommand.<PerformActionAsync>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Common.DotNetCli.Tools.Commands.BaseCommand`1.<ExecuteAsync>d__10.MoveNext()

Visualize Studio 2017: v15.7.0

AWS Toolkit: v1.14.3.0

.Net Core 1.0

**Comment by gordonglas** [comment]
I'm getting the same exception.

**Comment by normj** [comment]
We published a new version of the toolkit today, version 1.14.3.2, that fixes the issue with .NET Core 1.0 Lambda functions.

**Comment by steveataws** [comment]
Resolving issue as fixed shipped as noted.
