### ISSUE TITLE
IOT Data Clients do not set RegionEndpoint information when initialized

### ISSUE THREAD

**Issue by joelhess** [aws/aws-sdk-net#976]
When instantiating an AmazonIotDataClient with a service URL, or a config object with the regionendpoint set, the AmazonIotDataClient.Config.RegionEndpoint is empty. This is causing an issue when integrating with AWS X-Ray (see https://github.com/aws/aws-xray-sdk-dotnet/issues/21) as the region info is empty, and results in an exception.

## Expected Behavior
The RegionEndpoint Property should be populated if only a ServiceUrl is provided.

## Current Behavior

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Amazon.XRay.Recorder.Handlers.AwsSdk.Internal.XRayPipelineHandler.ProcessEndRequest(IExecutionContext executionContext)
   at Amazon.XRay.Recorder.Handlers.AwsSdk.Internal.XRayPipelineHandler.<InvokeAsync>d__27`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Messaging.Core.Service.IoT.IoTService.<PublishMessage>d__2`1.MoveNext() in ...Messaging.Core\Service\IoT\IoTService.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

## Possible Solution
If a Service Url is provided, use [AWSSDKUtils.DeterminRegion(string)](https://docs.aws.amazon.com/sdkfornet1/latest/apidocs/html/M_Amazon_Util_AWSSDKUtils_DetermineRegion.htm) to populate the region.

## Steps to Reproduce (for bugs)
Create a project with XRay enabled using AWSSDKHandler.RegisterXRayForAllServices();
Create an IOT Client with AmazonIotDataClient(serviceUrl)
Publish a message to the IOT service.

## Context
We're trying to stand up a stack with IoT integration, and using xray for tracing our service requests

## Your Environment

* AWSSDK.Core version used: 
* AWSSDK.IoT version used: 3.3.10.1
* AWSSDK.IoTData version: 3.3.0.29
* AWSXRayRecorder.Core: 2.2.0-beta
* Service assembly and version used: 
* Operating System and version: Win10 v1709
* Visual Studio version: 15.7
* Targeted .NET platform: core 2.0

## .NET Core Info

* .NET Core version used for development: 2.1
* .NET Core version installed in the environment where application runs: 2.0
* Output of `dotnet --info`: 
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300\

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  1.1.5 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by sstevenkang** [comment]
RegionEndpoint is a set by the caller.  I agree with comment in the PR linked is correct that x-ray-sdk is the correct place to determine the region not in the .NET SDK.
