### ISSUE TITLE
Timeout error on upload end

### ISSUE THREAD

**Issue by maxima120** [aws/aws-sdk-net#979]
I am trying to implement proper retry strategy for Glacier operations. When I upload/archive I pull Ethernet off my PC and wait. The progress prints every 5 sec. I wait 20 sec then connect it back.

The progress goes back somewhat but it seems the upload recovers OK and finally it goes to 98-100% (this varies from test to test) and then it throws an `AmazonGlacierException`. This happens about **9 out of 10 tests**.

I create **client** like this:

`config = new AmazonGlacierConfig()
{
    RegionEndpoint = region,
    MaxErrorRetry = 4,
};`
`client = new AmazonGlacierClient(accessKeyId, secretAccessKey, config); `

**this happens in both - single and mult-part uploads:**

`InitiateMultipartUploadRequest + UploadMultipartPart

or

UploadArchive`

the **exception**:

`Amazon.Glacier.Model.RequestTimeoutException: Request timed out. ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (408) Request Timeout. ---> System.Net.WebException: The remote server returned an error: (408) Request Timeout.
   at System.Net.HttpWebRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpRequest.GetResponse()
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpHandler1.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ExceptionHandler1.Handle(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Signer.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointResolver.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Glacier.Internal.ProcessRequestHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Marshaller.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.AmazonServiceClient.Invoke[TRequest,TResponse](TRequest request, IMarshaller2 marshaller, ResponseUnmarshaller unmarshaller)
   at Amazon.Glacier.AmazonGlacierClient.UploadArchive(UploadArchiveRequest request)
   at AmazonGlacierAdapter.Actions.AmazonGlacierAdapterArchive.UploadArchiveSingle(AmazonGlacierClient client, String filename, String vaultName, String accountId) in zz\AmazonGlacierArchive.cs:line 501
   at zz.TryUpload(GlacierTask task, String accountId, String vaultName, AmazonGlacierClient client, FileInfo fileInfo) in zz\AmazonGlacierArchive.cs:line 442
   at zz.AmazonGlacierAdapterArchive.Upload(GlacierTask task) in zz\AmazonGlacierArchive.cs:line 392`

## Expected Behavior
I expect the upload to finish without exception

## Current Behavior
I receive exception

## Context
make Glacier operations more stable as about 30% of uploads/downloads fail with various exceptions

## Your Environment
W10 x64
AWSSDK.Core 3.3.0.0
VS 2015
.NET 4.5.2

**Comment by maxima120** [comment]
nobody had this issue ? I cant believe it..

**Comment by sstevenkang** [comment]
Could you provide request ids that is associated with this failure?

**Comment by maxima120** [comment]
this was happening for 2 solid weeks but then stopped. I guess it was some sort of Amazon server issue which was fixed. Cannot reproduce it since.
